from ..object import Armor

__all__ = ['ARMOR_PIECES']


ARMOR_PIECES = [
    Armor('leather_helmet', rarity='common', part='helmet',
          defense=5),
    Armor('leather_chestplate', rarity='common', part='chestplate',
          defense=15),
    Armor('leather_leggings', rarity='common', part='leggings',
          defense=10),
    Armor('leather_boots', rarity='common', part='boots',
          defense=5),

    Armor('golden_helmet', rarity='common', part='helmet',
          defense=10),
    Armor('golden_chestplate', rarity='common', part='chestplate',
          defense=25),
    Armor('golden_leggings', rarity='common', part='leggings',
          defense=15),
    Armor('golden_boots', rarity='common', part='boots',
          defense=5),

    Armor('chainmail_helmet', rarity='uncommon', part='helmet',
          defense=12),
    Armor('chainmail_chestplate', rarity='uncommon', part='chestplate',
          defense=30),
    Armor('chainmail_leggings', rarity='uncommon', part='leggings',
          defense=20),
    Armor('chainmail_boots', rarity='uncommon', part='boots',
          defense=7),

    Armor('iron_helmet', rarity='common', part='helmet',
          defense=10),
    Armor('iron_chestplate', rarity='common', part='chestplate',
          defense=30),
    Armor('iron_leggings', rarity='common', part='leggings',
          defense=25),
    Armor('iron_boots', rarity='common', part='boots',
          defense=10),

    Armor('diamond_helmet', rarity='uncommon', part='helmet',
          defense=15),
    Armor('diamond_chestplate', rarity='uncommon', part='chestplate',
          defense=40),
    Armor('diamond_leggings', rarity='uncommon', part='leggings',
          defense=30),
    Armor('diamond_boots', rarity='uncommon', part='boots',
          defense=15),

    Armor('farm_suit_helmet', rarity='common', part='helmet',
          defense=15),
    Armor('farm_suit_chestplate', rarity='common', part='chestplate',
          defense=40),
    Armor('farm_suit_leggings', rarity='common', part='leggings',
          defense=30),
    Armor('farm_suit_boots', rarity='common', part='boots',
          defense=15),

    Armor('farm_helmet', rarity='rare', part='helmet',
          health=20, defense=40),
    Armor('farm_chestplate', rarity='rare', part='chestplate',
          health=20, defense=75),
    Armor('farm_leggings', rarity='rare', part='leggings',
          health=20, defense=50),
    Armor('farm_boots', rarity='rare', part='boots',
          health=20, defense=35),

    Armor('pumpkin_helmet', rarity='common', part='helmet',
          health=8, defense=8),
    Armor('pumpkin_chestplate', rarity='common', part='chestplate',
          health=14, defense=14),
    Armor('pumpkin_leggings', rarity='common', part='leggings',
          health=10, defense=10),
    Armor('pumpkin_boots', rarity='common', part='boots',
          health=8, defense=8),

    Armor('farmer_boots', rarity='uncommon', part='boots',
          health=40, defense=20, speed=10),
    Armor('ranchers_boots', rarity='rare', part='boots',
          health=100, defense=70, speed=50),

    Armor('mushroom_helmet', rarity='common', part='helmet',
          health=20),
    Armor('mushroom_chestplate', rarity='common', part='chestplate',
          health=10, defense=10),
    Armor('mushroom_leggings', rarity='common', part='leggings',
          health=10, defense=5),
    Armor('mushroom_boots', rarity='common', part='boots',
          health=15),

    Armor('cactus_helmet', rarity='common', part='helmet',
          health=5, defense=10),
    Armor('cactus_chestplate', rarity='common', part='chestplate',
          health=15, defense=25),
    Armor('cactus_leggings', rarity='common', part='leggings',
          health=10, defense=20),
    Armor('cactus_boots', rarity='common', part='boots',
          health=5, defense=10),

    Armor('speedster_helmet', rarity='epic', part='helmet',
          defense=70, speed=15),
    Armor('speedster_chestplate', rarity='epic', part='chestplate',
          defense=120, speed=15),
    Armor('speedster_leggings', rarity='epic', part='leggings',
          defense=95, speed=15),
    Armor('speedster_boots', rarity='epic', part='boots',
          defense=65, speed=15),

    Armor('cow_head', rarity='common', part='helmet',
          health=15, defense=5),

    Armor('miners_outfit_helmet', rarity='uncommon', part='helmet',
          defense=15, mining_speed=25),
    Armor('miners_outfit_chestplate', rarity='uncommon', part='chestplate',
          defense=40, mining_speed=25),
    Armor('miners_outfit_leggings', rarity='uncommon', part='leggings',
          defense=30, mining_speed=25),
    Armor('miners_outfit_boots', rarity='uncommon', part='boots',
          defense=15, mining_speed=25),

    Armor('golem_hat', rarity='common', part='helmet'),

    Armor('golem_armor_helmet', rarity='rare', part='helmet',
          health=45, defense=45),
    Armor('golem_armor_chestplate', rarity='rare', part='chestplate',
          health=65, defense=90),
    Armor('golem_armor_leggings', rarity='rare', part='leggings',
          health=55, defense=75),
    Armor('golem_armor_boots', rarity='rare', part='boots',
          health=40, defense=40),

    Armor('hardened_diamond_helmet', rarity='rare', part='helmet',
          defense=60),
    Armor('hardened_diamond_chestplate', rarity='rare', part='chestplate',
          defense=120),
    Armor('hardened_diamond_leggings', rarity='rare', part='leggings',
          defense=95),
    Armor('hardened_diamond_boots', rarity='rare', part='boots',
          defense=55),

    Armor('perfect_helmet', rarity='rare', part='helmet',
          defense=110),
    Armor('perfect_chestplate', rarity='rare', part='chestplate',
          defense=160),
    Armor('perfect_leggings', rarity='rare', part='leggings',
          defense=140),
    Armor('perfect_boots', rarity='rare', part='boots',
          defense=500),

    Armor('emerald_helmet', rarity='epic', part='helmet',
          defense=50),
    Armor('emerald_chestplate', rarity='epic', part='chestplate',
          defense=100),
    Armor('emerald_leggings', rarity='epic', part='leggings',
          defense=75),
    Armor('emerald_boots', rarity='epic', part='boots',
          defense=45),

    Armor('frozen_blaze_helmet', rarity='epic', part='helmet',
          strength=40, defense=110, speed=2),
    Armor('frozen_blaze_chestplate', rarity='epic', part='chestplate',
          strength=40, defense=180, speed=2),
    Armor('frozen_blaze_leggings', rarity='epic', part='leggings',
          strength=40, defense=140, speed=2),
    Armor('frozen_blaze_boots', rarity='epic', part='boots',
          strength=40, defense=100, speed=2),

    Armor('mithril_coat', rarity='epic', part='chestplate',
          defense=125, speed=15),

    Armor('zombie_hat', rarity='common', part='helmet',
          defense=10),
    Armor('zombies_heart', rarity='rare', part='helmet',
          health=50),
    Armor('zombie_chestplate', rarity='epic', part='chestplate',
          health=200, defense=40),
    Armor('zombie_leggings', rarity='epic', part='leggings',
          health=160, defense=30),
    Armor('zombie_boots', rarity='epic', part='boots',
          health=120, defense=25),

    Armor('skeleton_hat', rarity='common', part='helmet',
          intelligence=10, speed=2),
    Armor('skeletons_helmet', rarity='rare', part='helmet',
          defense=75),

    Armor('spiders_boots', rarity='rare', part='boots',
          defense=45, intelligence=50, speed=5),
    Armor('spider_hat', rarity='common', part='helmet',
          crit_chance=2),

    Armor('creeper_hat', rarity='common', part='helmet',
          strength=5, crit_chance=5, crit_damage=5,
          health=5, defense=5, intelligence=5),
    Armor('creeper_pants', rarity='rare', part='leggings',
          health=200, defense=65),

    Armor('ghast_head', rarity='common', part='helmet',
          health=100),

    Armor('slime_hat', rarity='common', part='helmet',
          health=50),

    Armor('blaze_hat', rarity='common', part='helmet',
          strength=20),

    Armor('blaze_helmet', rarity='epic', part='helmet',
          strength=10, defense=50, speed=2),
    Armor('blaze_chestplate', rarity='epic', part='chestplate',
          strength=10, defense=150, speed=2),
    Armor('blaze_leggings', rarity='epic', part='leggings',
          strength=10, defense=110, speed=2),
    Armor('blaze_boots', rarity='epic', part='boots',
          strength=10, defense=70, speed=2),

    Armor('leaflet_helmet', rarity='common', part='helmet',
          health=20),
    Armor('leaflet_chestplate', rarity='common', part='chestplate',
          health=35),
    Armor('leaflet_leggings', rarity='common', part='leggings',
          health=30),
    Armor('leaflet_boots', rarity='common', part='boots',
          health=15),

    Armor('growth_helmet', rarity='rare', part='helmet',
          health=50, defense=30),
    Armor('growth_chestplate', rarity='rare', part='chestplate',
          health=100, defense=50),
    Armor('growth_leggings', rarity='rare', part='leggings',
          health=80, defense=40),
    Armor('growth_boots', rarity='rare', part='boots',
          health=50, defense=25),

    Armor('magma_cube_head', rarity='common', part='helmet',
          health=25, defense=25),

    Armor('armor_of_magma_helmet', rarity='epic', part='helmet',
          health=50, defense=15),
    Armor('armor_of_magma_chestplate', rarity='epic', part='chestplate',
          health=100, defense=30),
    Armor('armor_of_magma_leggings', rarity='epic', part='leggings',
          health=75, defense=25),
    Armor('armor_of_magma_boots', rarity='epic', part='boots',
          health=45, defense=15),

    Armor('cheap_tuxedo_jacket', rarity='epic', part='chestplate',
          crit_damage=50, intelligence=50),
    Armor('cheap_tuxedo_pants', rarity='epic', part='leggings',
          crit_damage=25, intelligence=25),
    Armor('cheap_tuxedo_oxfords', rarity='epic', part='boots',
          crit_damage=25, intelligence=25),

    Armor('fancy_tuxedo_jacket', rarity='legendary', part='chestplate',
          crit_damage=80, intelligence=150),
    Armor('fancy_tuxedo_pants', rarity='legendary', part='leggings',
          crit_damage=35, intelligence=75),
    Armor('fancy_tuxedo_oxfords', rarity='legendary', part='boots',
          crit_damage=35, intelligence=75),

    Armor('elegant_tuxedo_jacket', rarity='legendary', part='chestplate',
          crit_damage=100, intelligence=300),
    Armor('elegant_tuxedo_pants', rarity='legendary', part='leggings',
          crit_damage=50, intelligence=100),
    Armor('elegant_tuxedo_oxfords', rarity='legendary', part='boots',
          crit_damage=50, intelligence=100, speed=10),

    Armor('lapis_helmet', rarity='uncommon', part='helmet',
          defense=25),
    Armor('lapis_chestplate', rarity='uncommon', part='chestplate',
          defense=40),
    Armor('lapis_leggings', rarity='uncommon', part='leggings',
          defense=35),
    Armor('lapis_boots', rarity='uncommon', part='boots',
          defense=20),

    Armor('miner_helmet', rarity='uncommon', part='helmet',
          defense=45),
    Armor('miner_chestplate', rarity='uncommon', part='chestplate',
          defense=95),
    Armor('miner_leggings', rarity='uncommon', part='leggings',
          defense=70),
    Armor('miner_boots', rarity='uncommon', part='boots',
          defense=45),

    Armor('goblin_helmet', rarity='rare', part='helmet',
          defense=70, intelligence=-1, mining_speed=10),
    Armor('goblin_chestplate', rarity='rare', part='chestplate',
          defense=140, intelligence=-1, mining_speed=10),
    Armor('goblin_leggings', rarity='rare', part='leggings',
          defense=125, intelligence=-1, mining_speed=10),
    Armor('goblin_boots', rarity='rare', part='boots',
          defense=60, intelligence=-1, mining_speed=10),

    Armor('glacite_helmet', rarity='rare', part='helmet',
          defense=70, speed=10, mining_speed=10, true_defense=5),
    Armor('glacite_chestplate', rarity='rare', part='chestplate',
          defense=150, speed=15, mining_speed=10, true_defense=20),
    Armor('glacite_leggings', rarity='rare', part='leggings',
          defense=125, speed=15, mining_speed=10, true_defense=20),
    Armor('glacite_boots', rarity='rare', part='boots',
          defense=70, speed=10, mining_speed=10, true_defense=5),

    Armor('sorrow_helmet', rarity='legendary', part='helmet',
          magic_find=10, mining_speed=50, mining_fortune=20, true_defense=100),
    Armor('sorrow_chestplate', rarity='legendary', part='chestplate',
          magic_find=10, mining_speed=50, mining_fortune=20, true_defense=200),
    Armor('sorrow_leggings', rarity='legendary', part='leggings',
          magic_find=10, mining_speed=50, mining_fortune=20, true_defense=150),
    Armor('sorrow_boots', rarity='legendary', part='boots',
          magic_find=10, mining_speed=50, mining_fortune=20, true_defense=75),

    Armor('ender_helmet', rarity='epic', part='helmet',
          health=20, defense=35),
    Armor('ender_chestplate', rarity='epic', part='chestplate',
          health=30, defense=60),
    Armor('ender_leggings', rarity='epic', part='leggings',
          health=25, defense=50),
    Armor('ender_boots', rarity='epic', part='boots',
          health=15, defense=25),
    Armor('obsidian_chestplate', rarity='epic', part='chestplate',
          defense=250,
          combat_skill_req=14),
]