from ..object import *


__all__ = ['PETS']

PETS = [
    Pet('bee_pet', rarity='common', category='farming',
        speed=10, intelligence=50, strength=30),
    Pet('bee_pet', rarity='uncommon', category='farming',
        speed=10, intelligence=50, strength=30),
    Pet('bee_pet', rarity='rare', category='farming',
        speed=10, intelligence=50, strength=30),
    Pet('bee_pet', rarity='epic', category='farming',
        speed=10, intelligence=50, strength=30),
    Pet('bee_pet', rarity='legendary', category='farming',
        speed=10, intelligence=50, strength=30),

    Pet('chicken_pet', rarity='common', category='farming',
        health=200),
    Pet('chicken_pet', rarity='uncommon', category='farming',
        health=200),
    Pet('chicken_pet', rarity='rare', category='farming',
        health=200),
    Pet('chicken_pet', rarity='epic', category='farming',
        health=200),
    Pet('chicken_pet', rarity='legendary', category='farming',
        health=200),

    Pet('pig_pet', rarity='common', category='farming',
        speed=25),
    Pet('pig_pet', rarity='uncommon', category='farming',
        speed=25),
    Pet('pig_pet', rarity='rare', category='farming',
        speed=25),
    Pet('pig_pet', rarity='epic', category='farming',
        speed=25),
    Pet('pig_pet', rarity='legendary', category='farming',
        speed=25),

    Pet('bat_pet', rarity='common', category='mining',
        speed=5, intelligence=100),
    Pet('bat_pet', rarity='uncommon', category='mining',
        speed=5, intelligence=100),
    Pet('bat_pet', rarity='rare', category='mining',
        speed=5, intelligence=100),
    Pet('bat_pet', rarity='epic', category='mining',
        speed=5, intelligence=100),
    Pet('bat_pet', rarity='legendary', category='mining',
        speed=5, intelligence=100),

    Pet('endermite_pet', rarity='common', category='mining',
        intelligence=100),
    Pet('endermite_pet', rarity='uncommon', category='mining',
        intelligence=100),
    Pet('endermite_pet', rarity='rare', category='mining',
        intelligence=100),
    Pet('endermite_pet', rarity='epic', category='mining',
        intelligence=100),
    Pet('endermite_pet', rarity='legendary', category='mining',
        intelligence=100),

    Pet('silverfish_pet', rarity='common', category='mining',
        health=20, defense=100),
    Pet('silverfish_pet', rarity='uncommon', category='mining',
        health=20, defense=100),
    Pet('silverfish_pet', rarity='rare', category='mining',
        health=20, defense=100),
    Pet('silverfish_pet', rarity='epic', category='mining',
        health=20, defense=100),
    Pet('silverfish_pet', rarity='legendary', category='mining',
        health=20, defense=100),

    Pet('wither_skeleton_pet', rarity='epic', category='mining',
        defense=25, intelligence=25,
        strength=25, crit_chance=5, crit_damage=25),
    Pet('wither_skeleton_pet', rarity='legendary', category='mining',
        defense=25, intelligence=25,
        strength=25, crit_chance=5, crit_damage=25),

    Pet('mithril_golem_pet', rarity='common', category='mining',
        true_defense=50),
    Pet('mithril_golem_pet', rarity='uncommon', category='mining',
        true_defense=50),
    Pet('mithril_golem_pet', rarity='rare', category='mining',
        true_defense=50),
    Pet('mithril_golem_pet', rarity='epic', category='mining',
        true_defense=50),
    Pet('mithril_golem_pet', rarity='legendary', category='mining',
        true_defense=50),

    Pet('rabbit_pet', rarity='common', category='farming',
        health=100, speed=20),
    Pet('rabbit_pet', rarity='uncommon', category='farming',
        health=100, speed=20),
    Pet('rabbit_pet', rarity='rare', category='farming',
        health=100, speed=20),
    Pet('rabbit_pet', rarity='epic', category='farming',
        health=100, speed=20),
    Pet('rabbit_pet', rarity='legendary', category='farming',
        health=100, speed=20),

    Pet('hound_pet', rarity='epic', category='combat',
        strength=40, attack_speed=15, ferocity=5),
    Pet('hound_pet', rarity='legendary', category='combat',
        strength=40, attack_speed=15, ferocity=5),

    Pet('tarantula_pet', rarity='epic', category='combat',
        strength=10, crit_chance=10, crit_damage=30),
    Pet('tarantula_pet', rarity='legendary', category='combat',
        strength=10, crit_chance=10, crit_damage=30),

    Pet('magma_cube_pet', rarity='common', category='combat',
        health=50, defense=100 / 3, strength=20),
    Pet('magma_cube_pet', rarity='uncommon', category='combat',
        health=50, defense=100 / 3, strength=20),
    Pet('magma_cube_pet', rarity='rare', category='combat',
        health=50, defense=100 / 3, strength=20),

    Pet('enderman_pet', rarity='common', category='combat',
        crit_damage=75),
    Pet('enderman_pet', rarity='uncommon', category='combat',
        crit_damage=75),
    Pet('enderman_pet', rarity='rare', category='combat',
        crit_damage=75),
    Pet('enderman_pet', rarity='epic', category='combat',
        crit_damage=75),
    Pet('enderman_pet', rarity='legendary', category='combat',
        crit_damage=75),
    Pet('enderman_pet', rarity='mythic', category='combat',
        crit_damage=75),

    Pet('ghoul_pet', rarity='epic', category='combat',
        health=100, intelligence=70, ferocity=5),
    Pet('ghoul_pet', rarity='legendary', category='combat',
        health=100, intelligence=70, ferocity=5),

    Pet('blaze_pet', rarity='epic', category='combat',
        defense=30, intelligence=100),
    Pet('blaze_pet', rarity='legendary', category='combat',
        defense=30, intelligence=100),

    Pet('horse_pet', rarity='common', category='combat',
        speed=25, intelligence=50),
    Pet('horse_pet', rarity='uncommon', category='combat',
        speed=25, intelligence=50),
    Pet('horse_pet', rarity='rare', category='combat',
        speed=25, intelligence=50),
    Pet('horse_pet', rarity='epic', category='combat',
        speed=25, intelligence=50),
    Pet('horse_pet', rarity='legendary', category='combat',
        speed=25, intelligence=50),

    Pet('pigman_pet', rarity='epic', category='combat',
        defense=50, strength=50, ferocity=5),
    Pet('pigman_pet', rarity='legendary', category='combat',
        defense=50, strength=50, ferocity=5),

    Pet('skeleton_pet', rarity='common', category='combat',
        crit_chance=15, crit_damage=30),
    Pet('skeleton_pet', rarity='uncommon', category='combat',
        crit_chance=15, crit_damage=30),
    Pet('skeleton_pet', rarity='rare', category='combat',
        crit_chance=15, crit_damage=30),
    Pet('skeleton_pet', rarity='epic', category='combat',
        crit_chance=15, crit_damage=30),
    Pet('skeleton_pet', rarity='legendary', category='combat',
        crit_chance=15, crit_damage=30),

    Pet('spider_pet', rarity='common', category='combat',
        strength=10, crit_chance=10),
    Pet('spider_pet', rarity='uncommon', category='combat',
        strength=10, crit_chance=10),
    Pet('spider_pet', rarity='rare', category='combat',
        strength=10, crit_chance=10),
    Pet('spider_pet', rarity='epic', category='combat',
        strength=10, crit_chance=10),
    Pet('spider_pet', rarity='legendary', category='combat',
        strength=10, crit_chance=10),

    Pet('wolf_pet', rarity='common', category='combat',
        health=50, speed=20, true_defense=10, crit_damage=10),
    Pet('wolf_pet', rarity='uncommon', category='combat',
        health=50, speed=20, true_defense=10, crit_damage=10),
    Pet('wolf_pet', rarity='rare', category='combat',
        health=50, speed=20, true_defense=10, crit_damage=10),
    Pet('wolf_pet', rarity='epic', category='combat',
        health=50, speed=20, true_defense=10, crit_damage=10),
    Pet('wolf_pet', rarity='legendary', category='combat',
        health=50, speed=20, true_defense=10, crit_damage=10),

    Pet('zombie_pet', rarity='common', category='combat',
        health=100, crit_damage=30),
    Pet('zombie_pet', rarity='uncommon', category='combat',
        health=100, crit_damage=30),
    Pet('zombie_pet', rarity='rare', category='combat',
        health=100, crit_damage=30),
    Pet('zombie_pet', rarity='epic', category='combat',
        health=100, crit_damage=30),
    Pet('zombie_pet', rarity='legendary', category='combat',
        health=100, crit_damage=30),

    Pet('phoenix_pet', rarity='epic', category='combat',
        intelligence=50, strength=10),
    Pet('phoenix_pet', rarity='legendary', category='combat',
        intelligence=50, strength=10,
        abilities=['eternal_coins']),

    Pet('ocelot_pet', rarity='common', category='foraging',
        speed=50, ferocity=10),
    Pet('ocelot_pet', rarity='uncommon', category='foraging',
        speed=50, ferocity=10),
    Pet('ocelot_pet', rarity='rare', category='foraging',
        speed=50, ferocity=10),
    Pet('ocelot_pet', rarity='epic', category='foraging',
        speed=50, ferocity=10),
    Pet('ocelot_pet', rarity='legendary', category='foraging',
        speed=50, ferocity=10),

    Pet('guardian_pet', rarity='common', category='enchanting',
        defense=50, intelligence=100),
    Pet('guardian_pet', rarity='uncommon', category='enchanting',
        defense=50, intelligence=100),
    Pet('guardian_pet', rarity='rare', category='enchanting',
        defense=50, intelligence=100),
    Pet('guardian_pet', rarity='epic', category='enchanting',
        defense=50, intelligence=100),
    Pet('guardian_pet', rarity='legendary', category='enchanting',
        defense=50, intelligence=100),

    Pet('squid_pet', rarity='common', category='fishing',
        health=50, intelligence=50),
    Pet('squid_pet', rarity='uncommon', category='fishing',
        health=50, intelligence=50),
    Pet('squid_pet', rarity='rare', category='fishing',
        health=50, intelligence=50),
    Pet('squid_pet', rarity='epic', category='fishing',
        health=50, intelligence=50),
    Pet('squid_pet', rarity='legendary', category='fishing',
        health=50, intelligence=50),

    Pet('flying_fish_pet', rarity='rare', category='fishing',
        health=40, defense=40),
    Pet('flying_fish_pet', rarity='epic', category='fishing',
        health=40, defense=40),
    Pet('flying_fish_pet', rarity='legendary', category='fishing',
        health=40, defense=40),
]
