from ..object import Axe, Hoe, Pickaxe, Drill, FishingRod


__all__ = ['TOOLS']

TOOLS = [
    Axe('wooden_axe', rarity='common', tool_speed=2),
    Axe('stone_axe', rarity='common', tool_speed=4),
    Axe('golden_axe', rarity='common', tool_speed=12),
    Axe('iron_axe', rarity='common', tool_speed=6),
    Axe('diamond_axe', rarity='uncommon', tool_speed=8),

    Axe('rookie_axe', rarity='common', tool_speed=4,
        enchantments={'efficiency': 1}),
    Axe('promising_axe', rarity='uncommon', tool_speed=6),
    Axe('sweet_axe', rarity='uncommon', tool_speed=6),
    Axe('efficient_axe', rarity='uncommon', tool_speed=6),

    Axe('jungle_axe', rarity='uncommon', tool_speed=2,
        abilities=['jungle_axe']),
    Axe('treecapitator', rarity='epic', tool_speed=12,
        abilities=['treecapitator']),

    Hoe('wooden_hoe', rarity='common'),
    Hoe('golden_hoe', rarity='common'),
    Hoe('stone_hoe', rarity='common'),
    Hoe('iron_hoe', rarity='common'),
    Hoe('diamond_hoe', rarity='uncommon'),

    Hoe('rookie_hoe', rarity='common'),

    Pickaxe('wooden_pickaxe', rarity='common',
            breaking_power=1, mining_speed=70, damage=20),
    Pickaxe('golden_pickaxe', rarity='common',
            breaking_power=1, mining_speed=250, damage=15),
    Pickaxe('stone_pickaxe', rarity='common',
            breaking_power=2, mining_speed=110, damage=20),
    Pickaxe('iron_pickaxe', rarity='common',
            breaking_power=3, mining_speed=160, damage=25),
    Pickaxe('diamond_pickaxe', rarity='uncommon',
            breaking_power=4, mining_speed=230, damage=30),

    Pickaxe('rookie_pickaxe', rarity='common',
            breaking_power=2, mining_speed=180, damage=15,
            enchantments={'efficiency': 1}),
    Pickaxe('promising_pickaxe', rarity='uncommon',
            breaking_power=2, mining_speed=190, damage=20),

    Pickaxe('zombie_pickaxe', rarity='common',
            breaking_power=3, mining_speed=290),

    Pickaxe('stonk', rarity='epic',
            breaking_power=1, mining_speed=380,
            enchantments={'efficiency': 6}),

    Pickaxe('fractured_mithril_pickaxe', rarity='uncommon',
            breaking_power=5, mining_speed=200, damage=30),
    Pickaxe('bandaged_mithril_pickaxe', rarity='uncommon',
            breaking_power=5, mining_speed=250, damage=30),
    Pickaxe('mithril_pickaxe', rarity='uncommon',
            breaking_power=5, mining_speed=280, damage=40),
    Pickaxe('refined_mithril_pickaxe', rarity='rare',
            breaking_power=5, mining_speed=300, damage=50),
    Pickaxe('titanium_pickaxe', rarity='rare',
            breaking_power=6, mining_speed=310, damage=60),
    Pickaxe('refined_titanium_pickaxe', rarity='rare',
            breaking_power=6, mining_speed=400, damage=65),

    Drill('mithril_drill_226', rarity='rare',
          breaking_power=5, mining_speed=450, damage=65),
    Drill('mithril_drill_326', rarity='rare',
          breaking_power=6, mining_speed=600, damage=65),
    Drill('titanium_drill_355', rarity='epic',
          breaking_power=7, mining_speed=700, mining_fortune=15, damage=75),
    Drill('titanium_drill_455', rarity='epic',
          breaking_power=8, mining_speed=900, mining_fortune=15, damage=75),
    Drill('titanium_drill_555', rarity='epic',
          breaking_power=9, mining_speed=1_200, mining_fortune=15, damage=75),

    FishingRod('fishing_rod', rarity='common'),
    FishingRod('prismarine_rod', rarity='common',
               damage=15, strength=10, fishing_speed=10,
               fishing_skill_req=3),
    FishingRod('sponge_rod', rarity='common',
               damage=20, strength=15,
               fishing_speed=20,
               fishing_skill_req=5),
    FishingRod('speedster_rod', rarity='uncommon',
               damage=30, strength=15, fishing_speed=30,
               fishing_skill_req=6),

    FishingRod('farmers_rod', rarity='uncommon',
               damage=50, strength=20, fishing_speed=40,
               fishing_skill_req=8),
    FishingRod('challenging_rod', rarity='rare',
               damage=60, strength=60,
               fishing_speed=50, sea_creature_chance=2,
               fishing_skill_req=10),
    FishingRod('rod_of_champions', rarity='rare',
               damage=90, strength=80,
               fishing_speed=60, sea_creature_chance=4,
               fishing_skill_req=15),
    FishingRod('rod_of_legends', rarity='rare',
               damage=130, strength=120,
               fishing_speed=70, sea_creature_chance=6,
               fishing_skill_req=20),

    FishingRod('shredder', rarity='legendary',
               damage=120, ferocity=50, fishing_speed=75,
               fishing_skill_req=20),
]
