from ...object import *


COMBAT_MINIONS = [
    Minion('zombie_minion', tier=1, cooldown=26, slots=2),
    Minion('zombie_minion', tier=2, cooldown=26, slots=4),
    Minion('zombie_minion', tier=3, cooldown=24, slots=4),
    Minion('zombie_minion', tier=4, cooldown=24, slots=6),
    Minion('zombie_minion', tier=5, cooldown=22, slots=6),
    Minion('zombie_minion', tier=6, cooldown=22, slots=9),
    Minion('zombie_minion', tier=7, cooldown=20, slots=9),
    Minion('zombie_minion', tier=8, cooldown=20, slots=12),
    Minion('zombie_minion', tier=9, cooldown=17, slots=12),
    Minion('zombie_minion', tier=10, cooldown=17, slots=15),
    Minion('zombie_minion', tier=11, cooldown=13, slots=15),

    Minion('skeleton_minion', tier=1, cooldown=26, slots=2),
    Minion('skeleton_minion', tier=2, cooldown=26, slots=4),
    Minion('skeleton_minion', tier=3, cooldown=24, slots=4),
    Minion('skeleton_minion', tier=4, cooldown=24, slots=6),
    Minion('skeleton_minion', tier=5, cooldown=22, slots=6),
    Minion('skeleton_minion', tier=6, cooldown=22, slots=9),
    Minion('skeleton_minion', tier=7, cooldown=20, slots=9),
    Minion('skeleton_minion', tier=8, cooldown=20, slots=12),
    Minion('skeleton_minion', tier=9, cooldown=17, slots=12),
    Minion('skeleton_minion', tier=10, cooldown=17, slots=15),
    Minion('skeleton_minion', tier=11, cooldown=13, slots=15),

    Minion('spider_minion', tier=1, cooldown=26, slots=2),
    Minion('spider_minion', tier=2, cooldown=26, slots=4),
    Minion('spider_minion', tier=3, cooldown=24, slots=4),
    Minion('spider_minion', tier=4, cooldown=24, slots=6),
    Minion('spider_minion', tier=5, cooldown=22, slots=6),
    Minion('spider_minion', tier=6, cooldown=22, slots=9),
    Minion('spider_minion', tier=7, cooldown=20, slots=9),
    Minion('spider_minion', tier=8, cooldown=20, slots=12),
    Minion('spider_minion', tier=9, cooldown=17, slots=12),
    Minion('spider_minion', tier=10, cooldown=17, slots=15),
    Minion('spider_minion', tier=11, cooldown=13, slots=15),

    Minion('cave_spider_minion', tier=1, cooldown=26, slots=2),
    Minion('cave_spider_minion', tier=2, cooldown=26, slots=4),
    Minion('cave_spider_minion', tier=3, cooldown=24, slots=4),
    Minion('cave_spider_minion', tier=4, cooldown=24, slots=6),
    Minion('cave_spider_minion', tier=5, cooldown=22, slots=6),
    Minion('cave_spider_minion', tier=6, cooldown=22, slots=9),
    Minion('cave_spider_minion', tier=7, cooldown=20, slots=9),
    Minion('cave_spider_minion', tier=8, cooldown=20, slots=12),
    Minion('cave_spider_minion', tier=9, cooldown=17, slots=12),
    Minion('cave_spider_minion', tier=10, cooldown=17, slots=15),
    Minion('cave_spider_minion', tier=11, cooldown=13, slots=15),

    Minion('creeper_minion', tier=1, cooldown=27, slots=2),
    Minion('creeper_minion', tier=2, cooldown=27, slots=4),
    Minion('creeper_minion', tier=3, cooldown=25, slots=4),
    Minion('creeper_minion', tier=4, cooldown=25, slots=6),
    Minion('creeper_minion', tier=5, cooldown=23, slots=6),
    Minion('creeper_minion', tier=6, cooldown=23, slots=9),
    Minion('creeper_minion', tier=7, cooldown=21, slots=9),
    Minion('creeper_minion', tier=8, cooldown=21, slots=12),
    Minion('creeper_minion', tier=9, cooldown=18, slots=12),
    Minion('creeper_minion', tier=10, cooldown=18, slots=15),
    Minion('creeper_minion', tier=11, cooldown=14, slots=15),

    Minion('enderman_minion', tier=1, cooldown=32, slots=2),
    Minion('enderman_minion', tier=2, cooldown=32, slots=4),
    Minion('enderman_minion', tier=3, cooldown=30, slots=4),
    Minion('enderman_minion', tier=4, cooldown=30, slots=6),
    Minion('enderman_minion', tier=5, cooldown=28, slots=6),
    Minion('enderman_minion', tier=6, cooldown=28, slots=9),
    Minion('enderman_minion', tier=7, cooldown=25, slots=9),
    Minion('enderman_minion', tier=8, cooldown=25, slots=12),
    Minion('enderman_minion', tier=9, cooldown=22, slots=12),
    Minion('enderman_minion', tier=10, cooldown=22, slots=15),
    Minion('enderman_minion', tier=11, cooldown=18, slots=15),

    Minion('ghast_minion', tier=1, cooldown=50, slots=2),
    Minion('ghast_minion', tier=2, cooldown=50, slots=4),
    Minion('ghast_minion', tier=3, cooldown=47, slots=4),
    Minion('ghast_minion', tier=4, cooldown=47, slots=6),
    Minion('ghast_minion', tier=5, cooldown=44, slots=6),
    Minion('ghast_minion', tier=6, cooldown=44, slots=9),
    Minion('ghast_minion', tier=7, cooldown=41, slots=9),
    Minion('ghast_minion', tier=8, cooldown=41, slots=12),
    Minion('ghast_minion', tier=9, cooldown=38, slots=12),
    Minion('ghast_minion', tier=10, cooldown=38, slots=15),
    Minion('ghast_minion', tier=11, cooldown=32, slots=15),

    Minion('slime_minion', tier=1, cooldown=26, slots=2),
    Minion('slime_minion', tier=2, cooldown=26, slots=4),
    Minion('slime_minion', tier=3, cooldown=24, slots=4),
    Minion('slime_minion', tier=4, cooldown=24, slots=6),
    Minion('slime_minion', tier=5, cooldown=22, slots=6),
    Minion('slime_minion', tier=6, cooldown=22, slots=9),
    Minion('slime_minion', tier=7, cooldown=19, slots=9),
    Minion('slime_minion', tier=8, cooldown=19, slots=12),
    Minion('slime_minion', tier=9, cooldown=16, slots=12),
    Minion('slime_minion', tier=10, cooldown=16, slots=15),
    Minion('slime_minion', tier=11, cooldown=12, slots=15),

    Minion('blaze_minion', tier=1, cooldown=33, slots=2),
    Minion('blaze_minion', tier=2, cooldown=33, slots=4),
    Minion('blaze_minion', tier=3, cooldown=31, slots=4),
    Minion('blaze_minion', tier=4, cooldown=31, slots=6),
    Minion('blaze_minion', tier=5, cooldown=28.5, slots=6),
    Minion('blaze_minion', tier=6, cooldown=28.5, slots=9),
    Minion('blaze_minion', tier=7, cooldown=25, slots=9),
    Minion('blaze_minion', tier=8, cooldown=25, slots=12),
    Minion('blaze_minion', tier=9, cooldown=21, slots=12),
    Minion('blaze_minion', tier=10, cooldown=21, slots=15),
    Minion('blaze_minion', tier=11, cooldown=16.5, slots=15),

    Minion('magma_cube_minion', tier=1, cooldown=32, slots=2),
    Minion('magma_cube_minion', tier=2, cooldown=32, slots=4),
    Minion('magma_cube_minion', tier=3, cooldown=30, slots=4),
    Minion('magma_cube_minion', tier=4, cooldown=30, slots=6),
    Minion('magma_cube_minion', tier=5, cooldown=28, slots=6),
    Minion('magma_cube_minion', tier=6, cooldown=28, slots=9),
    Minion('magma_cube_minion', tier=7, cooldown=25, slots=9),
    Minion('magma_cube_minion', tier=8, cooldown=25, slots=12),
    Minion('magma_cube_minion', tier=9, cooldown=22, slots=12),
    Minion('magma_cube_minion', tier=10, cooldown=22, slots=15),
    Minion('magma_cube_minion', tier=11, cooldown=18, slots=15),
]
