from ...object import *


FORAGING_MINIONS = [
    Minion('oak_minion', tier=1, cooldown=48, slots=1),
    Minion('oak_minion', tier=2, cooldown=48, slots=3),
    Minion('oak_minion', tier=3, cooldown=45, slots=3),
    Minion('oak_minion', tier=4, cooldown=45, slots=6),
    Minion('oak_minion', tier=5, cooldown=42, slots=6),
    Minion('oak_minion', tier=6, cooldown=42, slots=9),
    Minion('oak_minion', tier=7, cooldown=38, slots=9),
    Minion('oak_minion', tier=8, cooldown=38, slots=12),
    Minion('oak_minion', tier=9, cooldown=33, slots=12),
    Minion('oak_minion', tier=10, cooldown=33, slots=15),
    Minion('oak_minion', tier=11, cooldown=27, slots=15),

    Minion('birch_minion', tier=1, cooldown=48, slots=1),
    Minion('birch_minion', tier=2, cooldown=48, slots=3),
    Minion('birch_minion', tier=3, cooldown=45, slots=3),
    Minion('birch_minion', tier=4, cooldown=45, slots=6),
    Minion('birch_minion', tier=5, cooldown=42, slots=6),
    Minion('birch_minion', tier=6, cooldown=42, slots=9),
    Minion('birch_minion', tier=7, cooldown=38, slots=9),
    Minion('birch_minion', tier=8, cooldown=38, slots=12),
    Minion('birch_minion', tier=9, cooldown=33, slots=12),
    Minion('birch_minion', tier=10, cooldown=33, slots=15),
    Minion('birch_minion', tier=11, cooldown=27, slots=15),

    Minion('spruce_minion', tier=1, cooldown=48, slots=1),
    Minion('spruce_minion', tier=2, cooldown=48, slots=3),
    Minion('spruce_minion', tier=3, cooldown=45, slots=3),
    Minion('spruce_minion', tier=4, cooldown=45, slots=6),
    Minion('spruce_minion', tier=5, cooldown=42, slots=6),
    Minion('spruce_minion', tier=6, cooldown=42, slots=9),
    Minion('spruce_minion', tier=7, cooldown=38, slots=9),
    Minion('spruce_minion', tier=8, cooldown=38, slots=12),
    Minion('spruce_minion', tier=9, cooldown=33, slots=12),
    Minion('spruce_minion', tier=10, cooldown=33, slots=15),
    Minion('spruce_minion', tier=11, cooldown=27, slots=15),

    Minion('dark_oak_minion', tier=1, cooldown=48, slots=1),
    Minion('dark_oak_minion', tier=2, cooldown=48, slots=3),
    Minion('dark_oak_minion', tier=3, cooldown=45, slots=3),
    Minion('dark_oak_minion', tier=4, cooldown=45, slots=6),
    Minion('dark_oak_minion', tier=5, cooldown=42, slots=6),
    Minion('dark_oak_minion', tier=6, cooldown=42, slots=9),
    Minion('dark_oak_minion', tier=7, cooldown=38, slots=9),
    Minion('dark_oak_minion', tier=8, cooldown=38, slots=12),
    Minion('dark_oak_minion', tier=9, cooldown=33, slots=12),
    Minion('dark_oak_minion', tier=10, cooldown=33, slots=15),
    Minion('dark_oak_minion', tier=11, cooldown=27, slots=15),

    Minion('acacia_minion', tier=1, cooldown=48, slots=1),
    Minion('acacia_minion', tier=2, cooldown=48, slots=3),
    Minion('acacia_minion', tier=3, cooldown=45, slots=3),
    Minion('acacia_minion', tier=4, cooldown=45, slots=6),
    Minion('acacia_minion', tier=5, cooldown=42, slots=6),
    Minion('acacia_minion', tier=6, cooldown=42, slots=9),
    Minion('acacia_minion', tier=7, cooldown=38, slots=9),
    Minion('acacia_minion', tier=8, cooldown=38, slots=12),
    Minion('acacia_minion', tier=9, cooldown=33, slots=12),
    Minion('acacia_minion', tier=10, cooldown=33, slots=15),
    Minion('acacia_minion', tier=11, cooldown=27, slots=15),

    Minion('jungle_minion', tier=1, cooldown=48, slots=1),
    Minion('jungle_minion', tier=2, cooldown=48, slots=3),
    Minion('jungle_minion', tier=3, cooldown=45, slots=3),
    Minion('jungle_minion', tier=4, cooldown=45, slots=6),
    Minion('jungle_minion', tier=5, cooldown=42, slots=6),
    Minion('jungle_minion', tier=6, cooldown=42, slots=9),
    Minion('jungle_minion', tier=7, cooldown=38, slots=9),
    Minion('jungle_minion', tier=8, cooldown=38, slots=12),
    Minion('jungle_minion', tier=9, cooldown=33, slots=12),
    Minion('jungle_minion', tier=10, cooldown=33, slots=15),
    Minion('jungle_minion', tier=11, cooldown=27, slots=15),
]
