from ...object import *


__all__ = ['COMBAT_ARMOR']

COMBAT_ARMOR = [
    Armor('zombie_hat', rarity='common', part='helmet',
          defense=10),
    Armor('zombies_heart', rarity='rare', part='helmet',
          health=50),
    Armor('zombie_chestplate', rarity='epic', part='chestplate',
          health=200, defense=40),
    Armor('zombie_leggings', rarity='epic', part='leggings',
          health=160, defense=30),
    Armor('zombie_boots', rarity='epic', part='boots',
          health=120, defense=25),

    Armor('skeleton_hat', rarity='common', part='helmet',
          intelligence=10, speed=2),
    Armor('skeletons_helmet', rarity='rare', part='helmet',
          defense=75),

    Armor('spiders_boots', rarity='rare', part='boots',
          defense=45, intelligence=50, speed=5),
    Armor('spider_hat', rarity='common', part='helmet',
          crit_chance=2),

    Armor('creeper_hat', rarity='common', part='helmet',
          strength=5, crit_chance=5, crit_damage=5,
          health=5, defense=5, intelligence=5),
    Armor('creeper_pants', rarity='rare', part='leggings',
          health=200, defense=65),

    Armor('ghast_head', rarity='common', part='helmet',
          health=100),

    Armor('slime_hat', rarity='common', part='helmet',
          health=50),

    Armor('blaze_hat', rarity='common', part='helmet',
          strength=20),

    Armor('blaze_helmet', rarity='epic', part='helmet',
          strength=10, defense=50, speed=2),
    Armor('blaze_chestplate', rarity='epic', part='chestplate',
          strength=10, defense=150, speed=2),
    Armor('blaze_leggings', rarity='epic', part='leggings',
          strength=10, defense=110, speed=2),
    Armor('blaze_boots', rarity='epic', part='boots',
          strength=10, defense=70, speed=2),

    Armor('magma_cube_head', rarity='common', part='helmet',
          health=25, defense=25),

    Armor('armor_of_magma_helmet', rarity='epic', part='helmet',
          health=50, defense=15),
    Armor('armor_of_magma_chestplate', rarity='epic', part='chestplate',
          health=100, defense=30),
    Armor('armor_of_magma_leggings', rarity='epic', part='leggings',
          health=75, defense=25),
    Armor('armor_of_magma_boots', rarity='epic', part='boots',
          health=45, defense=15),

    Armor('ender_helmet', rarity='epic', part='helmet',
          health=20, defense=35,
          combat_skill_req=12,
          abilities=['ender_armor']),
    Armor('ender_chestplate', rarity='epic', part='chestplate',
          health=30, defense=60,
          combat_skill_req=12,
          abilities=['ender_armor']),
    Armor('ender_leggings', rarity='epic', part='leggings',
          health=25, defense=50,
          combat_skill_req=12,
          abilities=['ender_armor']),
    Armor('ender_boots', rarity='epic', part='boots',
          health=15, defense=25,
          combat_skill_req=12,
          abilities=['ender_armor']),

    Armor('obsidian_chestplate', rarity='epic', part='chestplate',
          defense=250,
          combat_skill_req=14),

    Armor('protector_dragon_helmet', rarity='legendary', part='helmet',
          health=70, defense=135,
          combat_skill_req=16,
          abilities=['protective_blood']),
    Armor('protector_dragon_chestplate', rarity='legendary', part='chestplate',
          health=120, defense=185,
          combat_skill_req=16,
          abilities=['protective_blood']),
    Armor('protector_dragon_leggings', rarity='legendary', part='leggings',
          health=100, defense=165,
          combat_skill_req=16,
          abilities=['protective_blood']),
    Armor('protector_dragon_boots', rarity='legendary', part='boots',
          health=60, defense=115,
          combat_skill_req=16,
          abilities=['protective_blood']),

    Armor('old_dragon_helmet', rarity='legendary', part='helmet',
          health=110, defense=90,
          combat_skill_req=16,
          abilities=['old_blood']),
    Armor('old_dragon_chestplate', rarity='legendary', part='chestplate',
          health=160, defense=150,
          combat_skill_req=16,
          abilities=['old_blood']),
    Armor('old_dragon_leggings', rarity='legendary', part='leggings',
          health=130, defense=140,
          combat_skill_req=16,
          abilities=['old_blood']),
    Armor('old_dragon_boots', rarity='legendary', part='boots',
          health=80, defense=90,
          combat_skill_req=16,
          abilities=['old_blood']),

    Armor('unstable_dragon_helmet', rarity='legendary', part='helmet',
          crit_chance=5, crit_damage=15,
          health=70, defense=110, intelligence=25,
          combat_skill_req=16),
    Armor('unstable_dragon_chestplate', rarity='legendary', part='chestplate',
          crit_chance=5, crit_damage=15,
          health=120, defense=160,
          combat_skill_req=16),
    Armor('unstable_dragon_leggings', rarity='legendary', part='leggings',
          crit_chance=5, crit_damage=15,
          health=100, defense=140,
          combat_skill_req=16),
    Armor('unstable_dragon_boots', rarity='legendary', part='boots',
          crit_chance=5, crit_damage=15,
          health=60, defense=90,
          combat_skill_req=16),

    Armor('holy_dragon_helmet', rarity='legendary', part='helmet',
          health=110, defense=110,
          combat_skill_req=16,
          abilities=['holy_blood']),
    Armor('holy_dragon_chestplate', rarity='legendary', part='chestplate',
          health=180, defense=160,
          combat_skill_req=16,
          abilities=['holy_blood']),
    Armor('holy_dragon_leggings', rarity='legendary', part='leggings',
          health=155, defense=140,
          combat_skill_req=16,
          abilities=['holy_blood']),
    Armor('holy_dragon_boots', rarity='legendary', part='boots',
          health=100, defense=90,
          combat_skill_req=16,
          abilities=['holy_blood']),

    Armor('wise_dragon_helmet', rarity='legendary', part='helmet',
          health=70, defense=110, intelligence=125,
          combat_skill_req=16),
    Armor('wise_dragon_chestplate', rarity='legendary', part='chestplate',
          health=120, defense=160, intelligence=75,
          combat_skill_req=16),
    Armor('wise_dragon_leggings', rarity='legendary', part='leggings',
          health=100, defense=140, intelligence=75,
          combat_skill_req=16),
    Armor('wise_dragon_boots', rarity='legendary', part='boots',
          health=60, defense=90, intelligence=75,
          combat_skill_req=16),

    Armor('young_dragon_helmet', rarity='legendary', part='helmet',
          health=70, defense=110, speed=20,
          combat_skill_req=16,
          abilities=['young_blood']),
    Armor('young_dragon_chestplate', rarity='legendary', part='chestplate',
          health=120, defense=160, speed=20,
          combat_skill_req=16,
          abilities=['young_blood']),
    Armor('young_dragon_leggings', rarity='legendary', part='leggings',
          health=100, defense=140, speed=20,
          combat_skill_req=16,
          abilities=['young_blood']),
    Armor('young_dragon_boots', rarity='legendary', part='boots',
          health=60, defense=90, speed=20,
          combat_skill_req=16,
          abilities=['young_blood']),

    Armor('strong_dragon_helmet', rarity='legendary', part='helmet',
          strength=25, health=70, defense=110,
          combat_skill_req=16,
          abilities=['strong_blood']),
    Armor('strong_dragon_chestplate', rarity='legendary', part='chestplate',
          strength=25, health=120, defense=160,
          combat_skill_req=16,
          abilities=['strong_blood']),
    Armor('strong_dragon_leggings', rarity='legendary', part='leggings',
          strength=25, health=100, defense=140,
          combat_skill_req=16,
          abilities=['strong_blood']),
    Armor('strong_dragon_boots', rarity='legendary', part='boots',
          strength=25, health=60, defense=90,
          combat_skill_req=16,
          abilities=['strong_blood']),

    Armor('superior_dragon_helmet', rarity='legendary', part='helmet',
          strength=10, crit_chance=2, crit_damage=10,
          health=90, defense=130, intelligence=25, speed=3,
          combat_skill_req=20,
          abilities=['superior_blood']),
    Armor('superior_dragon_chestplate', rarity='legendary', part='chestplate',
          strength=10, crit_chance=2, crit_damage=10,
          health=150, defense=190, intelligence=25, speed=3,
          combat_skill_req=20,
          abilities=['superior_blood']),
    Armor('superior_dragon_leggings', rarity='legendary', part='leggings',
          strength=10, crit_chance=2, crit_damage=10,
          health=130, defense=170, intelligence=25, speed=3,
          combat_skill_req=20,
          abilities=['superior_blood']),
    Armor('superior_dragon_boots', rarity='legendary', part='boots',
          strength=10, crit_chance=2, crit_damage=10,
          health=80, defense=110, intelligence=25, speed=3,
          combat_skill_req=20,
          abilities=['superior_blood']),
]