from ...object import Armor


__all__ = ['DUNGEON_ARMOR']

DUNGEON_ARMOR = [
    Armor('rotten_helmet', rarity='rare', part='helmet',
          defense=15,
          stars=0, dungeon_skill_req=1),
    Armor('rotten_chestplate', rarity='rare', part='chestplate',
          health=140, defense=15,
          stars=0, dungeon_skill_req=1),
    Armor('rotten_leggings', rarity='rare', part='leggings',
          health=112, defense=15,
          stars=0, dungeon_skill_req=1),
    Armor('rotten_boots', rarity='rare', part='boots',
          defense=15,
          stars=0, dungeon_skill_req=1),

    Armor('rotten_helmet', rarity='epic', part='helmet',
          defense=22.5,
          stars=0, dungeon_skill_req=1),
    Armor('rotten_chestplate', rarity='epic', part='chestplate',
          health=210, defense=22.5,
          stars=0, dungeon_skill_req=1),
    Armor('rotten_leggings', rarity='epic', part='leggings',
          health=168, defense=22.5,
          stars=0, dungeon_skill_req=1),
    Armor('rotten_boots', rarity='epic', part='boots',
          defense=22.5,
          stars=0, dungeon_skill_req=1),

    Armor('heavy_helmet', rarity='rare', part='helmet',
          health=75, defense=77, speed=-5,
          stars=0, dungeon_skill_req=2),
    Armor('heavy_chestplate', rarity='rare', part='chestplate',
          health=75, defense=127, speed=-5,
          stars=0, dungeon_skill_req=2),
    Armor('heavy_leggings', rarity='rare', part='leggings',
          health=75, defense=107, speed=-5,
          stars=0, dungeon_skill_req=2),
    Armor('heavy_boots', rarity='rare', part='boots',
          health=75, defense=72, speed=-5,
          stars=0, dungeon_skill_req=2),

    Armor('heavy_helmet', rarity='epic', part='helmet',
          health=75, defense=125, speed=-5,
          stars=0, dungeon_skill_req=2),
    Armor('heavy_chestplate', rarity='epic', part='chestplate',
          health=75, defense=213, speed=-5,
          stars=0, dungeon_skill_req=2),
    Armor('heavy_leggings', rarity='epic', part='leggings',
          health=75, defense=179, speed=-5,
          stars=0, dungeon_skill_req=2),
    Armor('heavy_boots', rarity='epic', part='boots',
          health=75, defense=116, speed=-5,
          stars=0, dungeon_skill_req=2),

    Armor('skeleton_grunt_helmet', rarity='epic', part='helmet',
          crit_damage=15, health=14, defense=23,
          stars=0, dungeon_skill_req=1),
    Armor('skeleton_grunt_chestplate', rarity='epic', part='chestplate',
          crit_damage=15, health=23, defense=38,
          stars=0, dungeon_skill_req=1),
    Armor('skeleton_grunt_leggings', rarity='epic', part='leggings',
          crit_damage=15, health=22, defense=34,
          stars=0, dungeon_skill_req=1),
    Armor('skeleton_grunt_boots', rarity='epic', part='boots',
          crit_damage=15, health=13, defense=20,
          stars=0, dungeon_skill_req=1),

    Armor('skeleton_grunt_helmet', rarity='legendary', part='helmet',
          crit_damage=27, health=25, defense=41,
          stars=0, dungeon_skill_req=1),
    Armor('skeleton_grunt_chestplate', rarity='legendary', part='chestplate',
          crit_damage=27, health=42, defense=66,
          stars=0, dungeon_skill_req=1),
    Armor('skeleton_grunt_leggings', rarity='legendary', part='leggings',
          crit_damage=27, health=40, defense=62,
          stars=0, dungeon_skill_req=1),
    Armor('skeleton_grunt_boots', rarity='legendary', part='boots',
          crit_damage=27, health=21, defense=35,
          stars=0, dungeon_skill_req=1),

    Armor('skeleton_soldier_helmet', rarity='epic', part='helmet',
          crit_chance=2, crit_damage=17, health=16, defense=26,
          stars=0, dungeon_skill_req=9),
    Armor('skeleton_soldier_chestplate', rarity='epic', part='chestplate',
          crit_chance=2, crit_damage=17, health=25, defense=39,
          stars=0, dungeon_skill_req=9),
    Armor('skeleton_soldier_leggings', rarity='epic', part='leggings',
          crit_chance=2, crit_damage=17, health=24, defense=38,
          stars=0, dungeon_skill_req=9),
    Armor('skeleton_soldier_boots', rarity='epic', part='boots',
          crit_chance=2, crit_damage=17, health=14, defense=22,
          stars=0, dungeon_skill_req=9),

    Armor('skeleton_soldier_helmet', rarity='legendary', part='helmet',
          crit_chance=5, crit_damage=39, health=39, defense=63,
          stars=0, dungeon_skill_req=9),
    Armor('skeleton_soldier_chestplate', rarity='legendary', part='chestplate',
          crit_chance=5, crit_damage=41, health=66, defense=104,
          stars=0, dungeon_skill_req=9),
    Armor('skeleton_soldier_leggings', rarity='legendary', part='leggings',
          crit_chance=5, crit_damage=41, health=60, defense=95,
          stars=0, dungeon_skill_req=9),
    Armor('skeleton_soldier_boots', rarity='legendary', part='boots',
          crit_chance=5, crit_damage=41, health=35, defense=57,
          stars=0, dungeon_skill_req=9),

    Armor('skeleton_master_helmet', rarity='epic', part='helmet',
          crit_chance=2, crit_damage=23, health=17, defense=28,
          stars=0, dungeon_skill_req=12),
    Armor('skeleton_master_chestplate', rarity='epic', part='chestplate',
          crit_chance=2, crit_damage=23, health=29, defense=45,
          stars=0, dungeon_skill_req=12),
    Armor('skeleton_master_leggings', rarity='epic', part='leggings',
          crit_chance=2, crit_damage=23, health=23, defense=42,
          stars=0, dungeon_skill_req=12),
    Armor('skeleton_master_boots', rarity='epic', part='boots',
          crit_chance=2, crit_damage=23, health=15, defense=25,
          stars=0, dungeon_skill_req=12),

    Armor('skeleton_master_helmet', rarity='legendary', part='helmet',
          crit_chance=5, crit_damage=53, health=40, defense=63,
          stars=0, dungeon_skill_req=12),
    Armor('skeleton_master_chestplate', rarity='legendary', part='chestplate',
          crit_chance=5, crit_damage=53, health=66, defense=104,
          stars=0, dungeon_skill_req=12),
    Armor('skeleton_master_leggings', rarity='legendary', part='leggings',
          crit_chance=5, crit_damage=53, health=60, defense=95,
          stars=0, dungeon_skill_req=12),
    Armor('skeleton_master_boots', rarity='legendary', part='boots',
          crit_chance=5, crit_damage=53, health=35, defense=57,
          stars=0, dungeon_skill_req=12),

    Armor('skeleton_lord_helmet', rarity='epic', part='helmet',
          crit_chance=2, crit_damage=36, health=26, defense=53,
          stars=0, dungeon_skill_req=25),
    Armor('skeleton_lord_chestplate', rarity='epic', part='chestplate',
          crit_chance=2, crit_damage=36, health=44, defense=86,
          stars=0, dungeon_skill_req=25),
    Armor('skeleton_lord_leggings', rarity='epic', part='leggings',
          crit_chance=2, crit_damage=36, health=26, defense=79,
          stars=0, dungeon_skill_req=25),
    Armor('skeleton_lord_boots', rarity='epic', part='boots',
          crit_chance=2, crit_damage=36, health=23, defense=47,
          stars=0, dungeon_skill_req=25),

    Armor('skeleton_lord_helmet', rarity='legendary', part='helmet',
          crit_chance=3, crit_damage=54, health=39, defense=80,
          stars=0, dungeon_skill_req=25),
    Armor('skeleton_lord_chestplate', rarity='legendary', part='chestplate',
          crit_chance=3, crit_damage=54, health=66, defense=129,
          stars=0, dungeon_skill_req=25),
    Armor('skeleton_lord_leggings', rarity='legendary', part='leggings',
          crit_chance=3, crit_damage=54, health=39, defense=119,
          stars=0, dungeon_skill_req=25),
    Armor('skeleton_lord_boots', rarity='legendary', part='boots',
          crit_chance=3, crit_damage=54, health=35, defense=71,
          stars=0, dungeon_skill_req=25),

    Armor('zombie_soldier_helmet', rarity='epic', part='helmet',
          health=96, defense=58,
          stars=0, dungeon_skill_req=9),
    Armor('zombie_soldier_chestplate', rarity='epic', part='chestplate',
          health=118, defense=96,
          stars=0, dungeon_skill_req=9),
    Armor('zombie_soldier_leggings', rarity='epic', part='leggings',
          health=109, defense=86,
          stars=0, dungeon_skill_req=9),
    Armor('zombie_soldier_boots', rarity='epic', part='boots',
          health=92, defense=51,
          stars=0, dungeon_skill_req=9),

    Armor('zombie_soldier_helmet', rarity='legendary', part='helmet',
          health=132, defense=128,
          stars=0, dungeon_skill_req=9),
    Armor('zombie_soldier_chestplate', rarity='legendary', part='chestplate',
          health=188, defense=230,
          stars=0, dungeon_skill_req=9),
    Armor('zombie_soldier_leggings', rarity='legendary', part='leggings',
          health=165, defense=201,
          stars=0, dungeon_skill_req=9),
    Armor('zombie_soldier_boots', rarity='legendary', part='boots',
          health=120, defense=111,
          stars=0, dungeon_skill_req=9),

    Armor('zombie_commander_helmet', rarity='epic', part='helmet',
          health=114, defense=37,
          stars=0, dungeon_skill_req=18),
    Armor('zombie_commander_chestplate', rarity='epic', part='chestplate',
          health=134, defense=50,
          stars=0, dungeon_skill_req=18),
    Armor('zombie_commander_leggings', rarity='epic', part='leggings',
          health=126, defense=45,
          stars=0, dungeon_skill_req=18),
    Armor('zombie_commander_boots', rarity='epic', part='boots',
          health=107, defense=32,
          stars=0, dungeon_skill_req=18),

    Armor('zombie_commander_helmet', rarity='legendary', part='helmet',
          health=186, defense=78,
          stars=0, dungeon_skill_req=18),
    Armor('zombie_commander_chestplate', rarity='legendary', part='chestplate',
          health=243, defense=113,
          stars=0, dungeon_skill_req=18),
    Armor('zombie_commander_leggings', rarity='legendary', part='leggings',
          health=221, defense=98,
          stars=0, dungeon_skill_req=18),
    Armor('zombie_commander_boots', rarity='legendary', part='boots',
          health=164, defense=63,
          stars=0, dungeon_skill_req=18),

    Armor('zombie_knight_helmet', rarity='epic', part='helmet',
          strength=12, defense=64, speed=5,
          stars=0, dungeon_skill_req=24),
    Armor('zombie_knight_chestplate', rarity='epic', part='chestplate',
          strength=23, defense=115, speed=5,
          stars=0, dungeon_skill_req=24),
    Armor('zombie_knight_leggings', rarity='epic', part='leggings',
          strength=18, defense=101, speed=5,
          stars=0, dungeon_skill_req=24),
    Armor('zombie_knight_boots', rarity='epic', part='boots',
          strength=12, defense=55, speed=5,
          stars=0, dungeon_skill_req=24),

    Armor('zombie_knight_helmet', rarity='legendary', part='helmet',
          strength=26, defense=137, speed=11,
          stars=0, dungeon_skill_req=24),
    Armor('zombie_knight_chestplate', rarity='legendary', part='chestplate',
          strength=50, defense=242, speed=11,
          stars=0, dungeon_skill_req=24),
    Armor('zombie_knight_leggings', rarity='legendary', part='leggings',
          strength=38, defense=213, speed=11,
          stars=0, dungeon_skill_req=24),
    Armor('zombie_knight_boots', rarity='legendary', part='boots',
          strength=26, defense=117, speed=11,
          stars=0, dungeon_skill_req=24),

    Armor('skeletor_helmet', rarity='epic', part='helmet',
          health=17, defense=28,
          stars=0, dungeon_skill_req=15),
    Armor('skeletor_chestplate', rarity='epic', part='chestplate',
          health=29, defense=45,
          stars=0, dungeon_skill_req=15),
    Armor('skeletor_leggings', rarity='epic', part='leggings',
          health=26, defense=42,
          stars=0, dungeon_skill_req=15),
    Armor('skeletor_boots', rarity='epic', part='boots',
          health=15, defense=25,
          stars=0, dungeon_skill_req=15),

    Armor('skeletor_helmet', rarity='legendary', part='helmet',
          health=36, defense=59,
          stars=0, dungeon_skill_req=15),
    Armor('skeletor_chestplate', rarity='legendary', part='chestplate',
          health=60, defense=95,
          stars=0, dungeon_skill_req=15),
    Armor('skeletor_leggings', rarity='legendary', part='leggings',
          health=54, defense=87,
          stars=0, dungeon_skill_req=15),
    Armor('skeletor_boots', rarity='legendary', part='boots',
          health=32, defense=51,
          stars=0, dungeon_skill_req=15),

    Armor('zombie_lord_helmet', rarity='epic', part='helmet',
          strength=13, health=106, defense=47, intelligence=13,
          stars=0, dungeon_skill_req=25),
    Armor('zombie_lord_chestplate', rarity='epic', part='chestplate',
          strength=13, health=160, defense=73, intelligence=13,
          stars=0, dungeon_skill_req=25),
    Armor('zombie_lord_leggings', rarity='epic', part='leggings',
          strength=13, health=138, defense=62, intelligence=13,
          stars=0, dungeon_skill_req=25),
    Armor('zombie_lord_boots', rarity='epic', part='boots',
          strength=13, health=84, defense=36, intelligence=13,
          stars=0, dungeon_skill_req=25),

    Armor('zombie_lord_helmet', rarity='legendary', part='helmet',
          strength=20, health=159, defense=71, intelligence=20,
          stars=0, dungeon_skill_req=25),
    Armor('zombie_lord_chestplate', rarity='legendary', part='chestplate',
          strength=20, health=240, defense=110, intelligence=20,
          stars=0, dungeon_skill_req=25),
    Armor('zombie_lord_leggings', rarity='legendary', part='leggings',
          strength=20, health=207, defense=93, intelligence=20,
          stars=0, dungeon_skill_req=25),
    Armor('zombie_lord_boots', rarity='legendary', part='boots',
          strength=20, health=126, defense=54, intelligence=20,
          stars=0, dungeon_skill_req=25),

    Armor('super_heavy_helmet', rarity='epic', part='helmet',
          defense=85, speed=-10,
          stars=0, dungeon_skill_req=15),
    Armor('super_heavy_chestplate', rarity='epic', part='chestplate',
          defense=127, speed=-10,
          stars=0, dungeon_skill_req=15),
    Armor('super_heavy_leggings', rarity='epic', part='leggings',
          defense=113, speed=-10,
          stars=0, dungeon_skill_req=15),
    Armor('super_heavy_boots', rarity='epic', part='boots',
          defense=78, speed=-10,
          stars=0, dungeon_skill_req=15),

    Armor('super_heavy_helmet', rarity='legendary', part='helmet',
          defense=197, speed=-10,
          stars=0, dungeon_skill_req=15),
    Armor('super_heavy_chestplate', rarity='legendary', part='chestplate',
          defense=317, speed=-10,
          stars=0, dungeon_skill_req=15),
    Armor('super_heavy_leggings', rarity='legendary', part='leggings',
          defense=275, speed=-10,
          stars=0, dungeon_skill_req=15),
    Armor('super_heavy_boots', rarity='legendary', part='boots',
          defense=176, speed=-10,
          stars=0, dungeon_skill_req=15),

    Armor('adaptive_helmet', rarity='epic', part='helmet',
          strength=15, health=110, defense=50, intelligence=15,
          stars=0, dungeon_completion_req=3),
    Armor('adaptive_chestplate', rarity='epic', part='chestplate',
          strength=15, health=170, defense=85, intelligence=15,
          stars=0, dungeon_completion_req=3),
    Armor('adaptive_leggings', rarity='epic', part='leggings',
          strength=15, health=145, defense=65, intelligence=15,
          stars=0, dungeon_completion_req=3),
    Armor('adaptive_boots', rarity='epic', part='boots',
          strength=15, health=90, defense=45, intelligence=15,
          stars=0, dungeon_completion_req=3),

    Armor('shadow_assassin_helmet', rarity='epic', part='helmet',
          strength=25, crit_damage=25, health=160, defense=70, speed=7,
          stars=0, dungeon_completion_req=5),
    Armor('shadow_assassin_chestplate', rarity='epic', part='chestplate',
          strength=25, crit_damage=25, health=240, defense=110, speed=7,
          stars=0, dungeon_completion_req=5),
    Armor('shadow_assassin_leggings', rarity='epic', part='leggings',
          strength=25, crit_damage=25, health=210, defense=95, speed=7,
          stars=0, dungeon_completion_req=5),
    Armor('shadow_assassin_boots', rarity='epic', part='boots',
          strength=25, crit_damage=25, health=125, defense=55, speed=7,
          stars=0, dungeon_completion_req=5),

    Armor('necromancer_lord_helmet', rarity='legendary', part='helmet',
          health=200, defense=160, intelligence=15,
          stars=0, dungeon_completion_req=6),
    Armor('necromancer_lord_chestplate', rarity='legendary', part='chestplate',
          health=300, defense=250, intelligence=10,
          stars=0, dungeon_completion_req=6),
    Armor('necromancer_lord_leggings', rarity='legendary', part='leggings',
          health=250, defense=220, intelligence=10,
          stars=0, dungeon_completion_req=6),
    Armor('necromancer_lord_boots', rarity='legendary', part='boots',
          health=180, defense=150, intelligence=10,
          stars=0, dungeon_completion_req=6),

    Armor('wither_helmet', rarity='legendary', part='helmet',
          health=200, defense=100, intelligence=30,
          stars=0, dungeon_completion_req=7),
    Armor('wither_chestplate', rarity='legendary', part='chestplate',
          health=300, defense=250, intelligence=10,
          stars=0, dungeon_completion_req=7),
    Armor('wither_leggings', rarity='legendary', part='leggings',
          health=250, defense=220, intelligence=10,
          stars=0, dungeon_completion_req=7),
    Armor('wither_boots', rarity='legendary', part='boots',
          health=180, defense=150, intelligence=10,
          stars=0, dungeon_completion_req=7),

    Armor('goldors_helmet', rarity='legendary', part='helmet',
          health=210, defense=180, intelligence=30,
          stars=0, dungeon_completion_req=7),
    Armor('goldors_chestplate', rarity='legendary', part='chestplate',
          health=310, defense=275, intelligence=20,
          stars=0, dungeon_completion_req=7),
    Armor('goldors_leggings', rarity='legendary', part='leggings',
          health=250, defense=220, intelligence=20,
          stars=0, dungeon_completion_req=7),
    Armor('goldors_boots', rarity='legendary', part='boots',
          health=190, defense=165, intelligence=20,
          stars=0, dungeon_completion_req=7),

    Armor('storms_helmet', rarity='legendary', part='helmet',
          health=180, defense=80, intelligence=400,
          stars=0, dungeon_completion_req=7),
    Armor('storms_chestplate', rarity='legendary', part='chestplate',
          health=260, defense=120, intelligence=250,
          stars=0, dungeon_completion_req=7),
    Armor('storms_leggings', rarity='legendary', part='leggings',
          health=230, defense=105, intelligence=250,
          stars=0, dungeon_completion_req=7),
    Armor('storms_boots', rarity='legendary', part='boots',
          health=145, defense=65, intelligence=250,
          stars=0, dungeon_completion_req=7),

    Armor('necrons_helmet', rarity='legendary', part='helmet',
          strength=40, crit_damage=30, health=180, defense=100, intelligence=30,
          stars=0, dungeon_completion_req=7),
    Armor('necrons_chestplate', rarity='legendary', part='chestplate',
          strength=40, crit_damage=30, health=260, defense=140, intelligence=10,
          stars=0, dungeon_completion_req=7),
    Armor('necrons_leggings', rarity='legendary', part='leggings',
          strength=40, crit_damage=30, health=230, defense=125, intelligence=10,
          stars=0, dungeon_completion_req=7),
    Armor('necrons_boots', rarity='legendary', part='boots',
          strength=40, crit_damage=30, health=145, defense=80, intelligence=10,
          stars=0, dungeon_completion_req=7),

    Armor('maxors_helmet', rarity='legendary', part='helmet',
          crit_damage=30, health=180, defense=80, intelligence=15, speed=30,
          stars=0, dungeon_completion_req=7),
    Armor('maxors_chestplate', rarity='legendary', part='chestplate',
          crit_damage=30, health=260, defense=120, intelligence=10, speed=30,
          stars=0, dungeon_completion_req=7),
    Armor('maxors_leggings', rarity='legendary', part='leggings',
          crit_damage=30, health=230, defense=105, intelligence=10, speed=30,
          stars=0, dungeon_completion_req=7),
    Armor('maxors_boots', rarity='legendary', part='boots',
          crit_damage=30, health=145, defense=65, intelligence=10, speed=30,
          stars=0, dungeon_completion_req=7),
]
