from ..item import get_item
from ..object import *


COMBAT_MINION_RECIPES = [
    Recipe('zombie_minion_1', 'combat',
           [(get_item('wooden_sword'), 1),
            (Item('rotten_flesh'), 80)],
           (get_item('zombie_minion', tier=1), 1),
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_2', 'combat',
           [(get_item('zombie_minion', tier=1), 1),
            (Item('rotten_flesh'), 160)],
           (get_item('zombie_minion', tier=2), 1),
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_3', 'combat',
           [(get_item('zombie_minion', tier=2), 1),
            (Item('rotten_flesh'), 320)],
           (get_item('zombie_minion', tier=3), 1),
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_4', 'combat',
           [(get_item('zombie_minion', tier=3), 1),
            (Item('rotten_flesh'), 512)],
           (get_item('zombie_minion', tier=4), 1),
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_5', 'combat',
           [(get_item('zombie_minion', tier=4), 1),
            (Item('enchanted_rotten_flesh'), 8)],
           (get_item('zombie_minion', tier=5), 1),
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_6', 'combat',
           [(get_item('zombie_minion', tier=5), 1),
            (Item('enchanted_rotten_flesh'), 16)],
           (get_item('zombie_minion', tier=6), 1),
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_7', 'combat',
           [(get_item('zombie_minion', tier=6), 1),
            (Item('enchanted_rotten_flesh'), 32)],
           (get_item('zombie_minion', tier=7), 1),
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_8', 'combat',
           [(get_item('zombie_minion', tier=7), 1),
            (Item('enchanted_rotten_flesh'), 64)],
           (get_item('zombie_minion', tier=8), 1),
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_9', 'combat',
           [(get_item('zombie_minion', tier=8), 1),
            (Item('enchanted_rotten_flesh'), 128)],
           (get_item('zombie_minion', tier=9), 1),
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_10', 'combat',
           [(get_item('zombie_minion', tier=9), 1),
            (Item('enchanted_rotten_flesh'), 256)],
           (get_item('zombie_minion', tier=10), 1),
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_11', 'combat',
           [(get_item('zombie_minion', tier=10), 1),
            (Item('enchanted_rotten_flesh'), 512)],
           (get_item('zombie_minion', tier=11), 1),
           collection_req=('rotten_flesh', 1)),
    RecipeGroup('zombie_minion', 'combat',
                ['zombie_minion_1', 'zombie_minion_2', 'zombie_minion_3',
                 'zombie_minion_4', 'zombie_minion_5', 'zombie_minion_6',
                 'zombie_minion_7', 'zombie_minion_8', 'zombie_minion_9',
                 'zombie_minion_10', 'zombie_minion_11'],
                collection_req=('rotten_flesh', 1)),

    Recipe('skeleton_minion_1', 'combat',
           [(get_item('wooden_sword'), 1),
            (Item('bone'), 80)],
           (get_item('skeleton_minion', tier=1), 1),
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_2', 'combat',
           [(get_item('skeleton_minion', tier=1), 1),
            (Item('bone'), 160)],
           (get_item('skeleton_minion', tier=2), 1),
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_3', 'combat',
           [(get_item('skeleton_minion', tier=2), 1),
            (Item('bone'), 320)],
           (get_item('skeleton_minion', tier=3), 1),
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_4', 'combat',
           [(get_item('skeleton_minion', tier=3), 1),
            (Item('bone'), 512)],
           (get_item('skeleton_minion', tier=4), 1),
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_5', 'combat',
           [(get_item('skeleton_minion', tier=4), 1),
            (Item('enchanted_bone'), 8)],
           (get_item('skeleton_minion', tier=5), 1),
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_6', 'combat',
           [(get_item('skeleton_minion', tier=5), 1),
            (Item('enchanted_bone'), 16)],
           (get_item('skeleton_minion', tier=6), 1),
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_7', 'combat',
           [(get_item('skeleton_minion', tier=6), 1),
            (Item('enchanted_bone'), 32)],
           (get_item('skeleton_minion', tier=7), 1),
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_8', 'combat',
           [(get_item('skeleton_minion', tier=7), 1),
            (Item('enchanted_bone'), 64)],
           (get_item('skeleton_minion', tier=8), 1),
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_9', 'combat',
           [(get_item('skeleton_minion', tier=8), 1),
            (Item('enchanted_bone'), 128)],
           (get_item('skeleton_minion', tier=9), 1),
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_10', 'combat',
           [(get_item('skeleton_minion', tier=9), 1),
            (Item('enchanted_bone'), 256)],
           (get_item('skeleton_minion', tier=10), 1),
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_11', 'combat',
           [(get_item('skeleton_minion', tier=10), 1),
            (Item('enchanted_bone'), 512)],
           (get_item('skeleton_minion', tier=11), 1),
           collection_req=('bone', 1)),
    RecipeGroup('skeleton_minion', 'combat',
                ['skeleton_minion_1', 'skeleton_minion_2', 'skeleton_minion_3',
                 'skeleton_minion_4', 'skeleton_minion_5', 'skeleton_minion_6',
                 'skeleton_minion_7', 'skeleton_minion_8', 'skeleton_minion_9',
                 'skeleton_minion_10', 'skeleton_minion_11'],
                collection_req=('bone', 1)),

    Recipe('spider_minion_1', 'combat',
           [(get_item('wooden_sword'), 1),
            (Item('string'), 80)],
           (get_item('spider_minion', tier=1), 1),
           collection_req=('string', 1)),
    Recipe('spider_minion_2', 'combat',
           [(get_item('spider_minion', tier=1), 1),
            (Item('string'), 160)],
           (get_item('spider_minion', tier=2), 1),
           collection_req=('string', 1)),
    Recipe('spider_minion_3', 'combat',
           [(get_item('spider_minion', tier=2), 1),
            (Item('string'), 320)],
           (get_item('spider_minion', tier=3), 1),
           collection_req=('string', 1)),
    Recipe('spider_minion_4', 'combat',
           [(get_item('spider_minion', tier=3), 1),
            (Item('string'), 512)],
           (get_item('spider_minion', tier=4), 1),
           collection_req=('string', 1)),
    Recipe('spider_minion_5', 'combat',
           [(get_item('spider_minion', tier=4), 1),
            (Item('enchanted_string'), 8)],
           (get_item('spider_minion', tier=5), 1),
           collection_req=('string', 1)),
    Recipe('spider_minion_6', 'combat',
           [(get_item('spider_minion', tier=5), 1),
            (Item('enchanted_string'), 16)],
           (get_item('spider_minion', tier=6), 1),
           collection_req=('string', 1)),
    Recipe('spider_minion_7', 'combat',
           [(get_item('spider_minion', tier=6), 1),
            (Item('enchanted_string'), 32)],
           (get_item('spider_minion', tier=7), 1),
           collection_req=('string', 1)),
    Recipe('spider_minion_8', 'combat',
           [(get_item('spider_minion', tier=7), 1),
            (Item('enchanted_string'), 64)],
           (get_item('spider_minion', tier=8), 1),
           collection_req=('string', 1)),
    Recipe('spider_minion_9', 'combat',
           [(get_item('spider_minion', tier=8), 1),
            (Item('enchanted_string'), 128)],
           (get_item('spider_minion', tier=9), 1),
           collection_req=('string', 1)),
    Recipe('spider_minion_10', 'combat',
           [(get_item('spider_minion', tier=9), 1),
            (Item('enchanted_string'), 256)],
           (get_item('spider_minion', tier=10), 1),
           collection_req=('string', 1)),
    Recipe('spider_minion_11', 'combat',
           [(get_item('spider_minion', tier=10), 1),
            (Item('enchanted_string'), 512)],
           (get_item('spider_minion', tier=11), 1),
           collection_req=('string', 1)),
    RecipeGroup('spider_minion', 'combat',
                ['spider_minion_1', 'spider_minion_2', 'spider_minion_3',
                 'spider_minion_4', 'spider_minion_5', 'spider_minion_6',
                 'spider_minion_7', 'spider_minion_8', 'spider_minion_9',
                 'spider_minion_10', 'spider_minion_11'],
                collection_req=('string', 1)),

    Recipe('cave_spider_minion_1', 'combat',
           [(get_item('wooden_sword'), 1),
            (Item('spider_eye'), 80)],
           (get_item('cave_spider_minion', tier=1), 1),
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_2', 'combat',
           [(get_item('cave_spider_minion', tier=1), 1),
            (Item('spider_eye'), 160)],
           (get_item('cave_spider_minion', tier=2), 1),
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_3', 'combat',
           [(get_item('cave_spider_minion', tier=2), 1),
            (Item('spider_eye'), 320)],
           (get_item('cave_spider_minion', tier=3), 1),
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_4', 'combat',
           [(get_item('cave_spider_minion', tier=3), 1),
            (Item('spider_eye'), 512)],
           (get_item('cave_spider_minion', tier=4), 1),
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_5', 'combat',
           [(get_item('cave_spider_minion', tier=4), 1),
            (Item('enchanted_spider_eye'), 8)],
           (get_item('cave_spider_minion', tier=5), 1),
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_6', 'combat',
           [(get_item('cave_spider_minion', tier=5), 1),
            (Item('enchanted_spider_eye'), 24)],
           (get_item('cave_spider_minion', tier=6), 1),
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_7', 'combat',
           [(get_item('cave_spider_minion', tier=6), 1),
            (Item('enchanted_spider_eye'), 64)],
           (get_item('cave_spider_minion', tier=7), 1),
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_8', 'combat',
           [(get_item('cave_spider_minion', tier=7), 1),
            (Item('enchanted_spider_eye'), 128)],
           (get_item('cave_spider_minion', tier=8), 1),
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_9', 'combat',
           [(get_item('cave_spider_minion', tier=8), 1),
            (Item('enchanted_spider_eye'), 256)],
           (get_item('cave_spider_minion', tier=9), 1),
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_10', 'combat',
           [(get_item('cave_spider_minion', tier=9), 1),
            (Item('enchanted_spider_eye'), 512)],
           (get_item('cave_spider_minion', tier=10), 1),
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_11', 'combat',
           [(get_item('cave_spider_minion', tier=10), 1),
            (Item('enchanted_fermented_spider_eye'), 16)],
           (get_item('cave_spider_minion', tier=11), 1),
           collection_req=('spider_eye', 1)),
    RecipeGroup('cave_spider_minion', 'combat',
                ['cave_spider_minion_1', 'cave_spider_minion_2',
                 'cave_spider_minion_3', 'cave_spider_minion_4',
                 'cave_spider_minion_5', 'cave_spider_minion_6',
                 'cave_spider_minion_7', 'cave_spider_minion_8',
                 'cave_spider_minion_9', 'cave_spider_minion_10',
                 'cave_spider_minion_11'],
                collection_req=('spider_eye', 1)),

    Recipe('creeper_minion_1', 'combat',
           [(get_item('wooden_sword'), 1),
            (Item('gunpowder'), 80)],
           (get_item('creeper_minion', tier=1), 1),
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_2', 'combat',
           [(get_item('creeper_minion', tier=1), 1),
            (Item('gunpowder'), 160)],
           (get_item('creeper_minion', tier=2), 1),
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_3', 'combat',
           [(get_item('creeper_minion', tier=2), 1),
            (Item('gunpowder'), 320)],
           (get_item('creeper_minion', tier=3), 1),
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_4', 'combat',
           [(get_item('creeper_minion', tier=3), 1),
            (Item('gunpowder'), 512)],
           (get_item('creeper_minion', tier=4), 1),
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_5', 'combat',
           [(get_item('creeper_minion', tier=4), 1),
            (Item('enchanted_gunpowder'), 8)],
           (get_item('creeper_minion', tier=5), 1),
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_6', 'combat',
           [(get_item('creeper_minion', tier=5), 1),
            (Item('enchanted_gunpowder'), 24)],
           (get_item('creeper_minion', tier=6), 1),
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_7', 'combat',
           [(get_item('creeper_minion', tier=6), 1),
            (Item('enchanted_gunpowder'), 64)],
           (get_item('creeper_minion', tier=7), 1),
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_8', 'combat',
           [(get_item('creeper_minion', tier=7), 1),
            (Item('enchanted_gunpowder'), 128)],
           (get_item('creeper_minion', tier=8), 1),
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_9', 'combat',
           [(get_item('creeper_minion', tier=8), 1),
            (Item('enchanted_gunpowder'), 256)],
           (get_item('creeper_minion', tier=9), 1),
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_10', 'combat',
           [(get_item('creeper_minion', tier=9), 1),
            (Item('enchanted_gunpowder'), 512)],
           (get_item('creeper_minion', tier=10), 1),
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_11', 'combat',
           [(get_item('creeper_minion', tier=10), 1),
            (Item('enchanted_firework_rocket'), 16)],
           (get_item('creeper_minion', tier=11), 1),
           collection_req=('gunpowder', 1)),
    RecipeGroup('creeper_minion', 'combat',
                ['creeper_minion_1', 'creeper_minion_2', 'creeper_minion_3',
                 'creeper_minion_4', 'creeper_minion_5', 'creeper_minion_6',
                 'creeper_minion_7', 'creeper_minion_8', 'creeper_minion_9',
                 'creeper_minion_10', 'creeper_minion_11'],
                collection_req=('gunpowder', 1)),

    Recipe('enderman_minion_1', 'combat',
           [(get_item('wooden_sword'), 1),
            (Item('ender_pearl'), 64)],
           (get_item('enderman_minion', tier=1), 1),
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_2', 'combat',
           [(get_item('enderman_minion', tier=1), 1),
            (Item('ender_pearl'), 128)],
           (get_item('enderman_minion', tier=2), 1),
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_3', 'combat',
           [(get_item('enderman_minion', tier=2), 1),
            (Item('enchanted_ender_pearl'), 8)],
           (get_item('enderman_minion', tier=3), 1),
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_4', 'combat',
           [(get_item('enderman_minion', tier=3), 1),
            (Item('enchanted_ender_pearl'), 24)],
           (get_item('enderman_minion', tier=4), 1),
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_5', 'combat',
           [(get_item('enderman_minion', tier=4), 1),
            (Item('enchanted_ender_pearl'), 48)],
           (get_item('enderman_minion', tier=5), 1),
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_6', 'combat',
           [(get_item('enderman_minion', tier=5), 1),
            (Item('enchanted_ender_pearl'), 96)],
           (get_item('enderman_minion', tier=6), 1),
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_7', 'combat',
           [(get_item('enderman_minion', tier=6), 1),
            (Item('enchanted_eye_of_ender'), 8)],
           (get_item('enderman_minion', tier=7), 1),
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_8', 'combat',
           [(get_item('enderman_minion', tier=7), 1),
            (Item('enchanted_eye_of_ender'), 24)],
           (get_item('enderman_minion', tier=8), 1),
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_9', 'combat',
           [(get_item('enderman_minion', tier=8), 1),
            (Item('enchanted_eye_of_ender'), 48)],
           (get_item('enderman_minion', tier=9), 1),
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_10', 'combat',
           [(get_item('enderman_minion', tier=9), 1),
            (Item('enchanted_eye_of_ender'), 96)],
           (get_item('enderman_minion', tier=10), 1),
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_11', 'combat',
           [(get_item('enderman_minion', tier=10), 1),
            (Item('enchanted_eye_of_ender'), 192)],
           (get_item('enderman_minion', tier=11), 1),
           collection_req=('ender_pearl', 1)),
    RecipeGroup('enderman_minion', 'combat',
                ['enderman_minion_1', 'enderman_minion_2', 'enderman_minion_3',
                 'enderman_minion_4', 'enderman_minion_5', 'enderman_minion_6',
                 'enderman_minion_7', 'enderman_minion_8', 'enderman_minion_9',
                 'enderman_minion_10', 'enderman_minion_11'],
                collection_req=('ender_pearl', 1)),

    Recipe('ghast_minion_1', 'combat',
           [(get_item('wooden_sword'), 1),
            (Item('ghast_tear'), 64)],
           (get_item('ghast_minion', tier=1), 1),
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_2', 'combat',
           [(get_item('ghast_minion', tier=1), 1),
            (Item('ghast_tear'), 128)],
           (get_item('ghast_minion', tier=2), 1),
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_3', 'combat',
           [(get_item('ghast_minion', tier=2), 1),
            (Item('ghast_tear'), 256)],
           (get_item('ghast_minion', tier=3), 1),
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_4', 'combat',
           [(get_item('ghast_minion', tier=3), 1),
            (Item('ghast_tear'), 512)],
           (get_item('ghast_minion', tier=4), 1),
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_5', 'combat',
           [(get_item('ghast_minion', tier=4), 1),
            (Item('enchanted_ghast_tear'), 256)],
           (get_item('ghast_minion', tier=5), 1),
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_6', 'combat',
           [(get_item('ghast_minion', tier=5), 1),
            (Item('enchanted_ghast_tear'), 512)],
           (get_item('ghast_minion', tier=6), 1),
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_7', 'combat',
           [(get_item('ghast_minion', tier=6), 1),
            (Item('silver_fang'), 32)],
           (get_item('ghast_minion', tier=7), 1),
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_8', 'combat',
           [(get_item('ghast_minion', tier=7), 1),
            (Item('silver_fang'), 64)],
           (get_item('ghast_minion', tier=8), 1),
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_9', 'combat',
           [(get_item('ghast_minion', tier=8), 1),
            (Item('silver_fang'), 128)],
           (get_item('ghast_minion', tier=9), 1),
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_10', 'combat',
           [(get_item('ghast_minion', tier=9), 1),
            (Item('silver_fang'), 256)],
           (get_item('ghast_minion', tier=10), 1),
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_11', 'combat',
           [(get_item('ghast_minion', tier=10), 1),
            (Item('silver_fang'), 512)],
           (get_item('ghast_minion', tier=11), 1),
           collection_req=('ghast_tear', 1)),
    RecipeGroup('ghast_minion', 'combat',
                ['ghast_minion_1', 'ghast_minion_2', 'ghast_minion_3',
                 'ghast_minion_4', 'ghast_minion_5', 'ghast_minion_6',
                 'ghast_minion_7', 'ghast_minion_8', 'ghast_minion_9',
                 'ghast_minion_10', 'ghast_minion_11'],
                collection_req=('ghast_tear', 1)),

    Recipe('slime_minion_1', 'combat',
           [(get_item('wooden_sword'), 1),
            (Item('slime_ball'), 80)],
           (get_item('slime_minion', tier=1), 1),
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_2', 'combat',
           [(get_item('slime_minion', tier=1), 1),
            (Item('slime_ball'), 160)],
           (get_item('slime_minion', tier=2), 1),
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_3', 'combat',
           [(get_item('slime_minion', tier=2), 1),
            (Item('slime_ball'), 320)],
           (get_item('slime_minion', tier=3), 1),
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_4', 'combat',
           [(get_item('slime_minion', tier=3), 1),
            (Item('slime_ball'), 512)],
           (get_item('slime_minion', tier=4), 1),
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_5', 'combat',
           [(get_item('slime_minion', tier=4), 1),
            (Item('enchanted_slime_ball'), 8)],
           (get_item('slime_minion', tier=5), 1),
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_6', 'combat',
           [(get_item('slime_minion', tier=5), 1),
            (Item('enchanted_slime_ball'), 24)],
           (get_item('slime_minion', tier=6), 1),
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_7', 'combat',
           [(get_item('slime_minion', tier=6), 1),
            (Item('enchanted_slime_ball'), 64)],
           (get_item('slime_minion', tier=7), 1),
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_8', 'combat',
           [(get_item('slime_minion', tier=7), 1),
            (Item('enchanted_slime_ball'), 128)],
           (get_item('slime_minion', tier=8), 1),
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_9', 'combat',
           [(get_item('slime_minion', tier=8), 1),
            (Item('enchanted_slime_ball'), 256)],
           (get_item('slime_minion', tier=9), 1),
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_10', 'combat',
           [(get_item('slime_minion', tier=9), 1),
            (Item('enchanted_slime_ball'), 512)],
           (get_item('slime_minion', tier=10), 1),
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_11', 'combat',
           [(get_item('slime_minion', tier=10), 1),
            (Item('enchanted_slime_block'), 8)],
           (get_item('slime_minion', tier=11), 1),
           collection_req=('slime_ball', 1)),
    RecipeGroup('slime_minion', 'combat',
                ['slime_minion_1', 'slime_minion_2', 'slime_minion_3',
                 'slime_minion_4', 'slime_minion_5', 'slime_minion_6',
                 'slime_minion_7', 'slime_minion_8', 'slime_minion_9',
                 'slime_minion_10', 'slime_minion_11'],
                collection_req=('slime_ball', 1)),

    Recipe('blaze_minion_1', 'combat',
           [(get_item('wooden_sword'), 1),
            (Item('blaze_rod'), 80)],
           (get_item('blaze_minion', tier=1), 1),
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_2', 'combat',
           [(get_item('blaze_minion', tier=1), 1),
            (Item('blaze_rod'), 160)],
           (get_item('blaze_minion', tier=2), 1),
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_3', 'combat',
           [(get_item('blaze_minion', tier=2), 1),
            (Item('blaze_rod'), 320)],
           (get_item('blaze_minion', tier=3), 1),
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_4', 'combat',
           [(get_item('blaze_minion', tier=3), 1),
            (Item('blaze_rod'), 512)],
           (get_item('blaze_minion', tier=4), 1),
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_5', 'combat',
           [(get_item('blaze_minion', tier=4), 1),
            (Item('enchanted_blaze_powder'), 8)],
           (get_item('blaze_minion', tier=5), 1),
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_6', 'combat',
           [(get_item('blaze_minion', tier=5), 1),
            (Item('enchanted_blaze_powder'), 24)],
           (get_item('blaze_minion', tier=6), 1),
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_7', 'combat',
           [(get_item('blaze_minion', tier=6), 1),
            (Item('enchanted_blaze_powder'), 64)],
           (get_item('blaze_minion', tier=7), 1),
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_8', 'combat',
           [(get_item('blaze_minion', tier=7), 1),
            (Item('enchanted_blaze_powder'), 128)],
           (get_item('blaze_minion', tier=8), 1),
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_9', 'combat',
           [(get_item('blaze_minion', tier=8), 1),
            (Item('enchanted_blaze_powder'), 256)],
           (get_item('blaze_minion', tier=9), 1),
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_10', 'combat',
           [(get_item('blaze_minion', tier=9), 1),
            (Item('enchanted_blaze_powder'), 512)],
           (get_item('blaze_minion', tier=10), 1),
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_11', 'combat',
           [(get_item('blaze_minion', tier=10), 1),
            (Item('enchanted_blaze_rod'), 8)],
           (get_item('blaze_minion', tier=11), 1),
           collection_req=('blaze_rod', 1)),
    RecipeGroup('blaze_minion', 'combat',
                ['blaze_minion_1', 'blaze_minion_2', 'blaze_minion_3',
                 'blaze_minion_4', 'blaze_minion_5', 'blaze_minion_6',
                 'blaze_minion_7', 'blaze_minion_8', 'blaze_minion_9',
                 'blaze_minion_10', 'blaze_minion_11'],
                collection_req=('blaze_rod', 1)),

    Recipe('magma_cube_minion_1', 'combat',
           [(get_item('wooden_sword'), 1),
            (Item('magma_cream'), 80)],
           (get_item('magma_cube_minion', tier=1), 1),
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_2', 'combat',
           [(get_item('magma_cube_minion', tier=1), 1),
            (Item('magma_cream'), 160)],
           (get_item('magma_cube_minion', tier=2), 1),
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_3', 'combat',
           [(get_item('magma_cube_minion', tier=2), 1),
            (Item('magma_cream'), 320)],
           (get_item('magma_cube_minion', tier=3), 1),
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_4', 'combat',
           [(get_item('magma_cube_minion', tier=3), 1),
            (Item('magma_cream'), 512)],
           (get_item('magma_cube_minion', tier=4), 1),
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_5', 'combat',
           [(get_item('magma_cube_minion', tier=4), 1),
            (Item('enchanted_blaze_powder'), 8)],
           (get_item('magma_cube_minion', tier=5), 1),
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_6', 'combat',
           [(get_item('magma_cube_minion', tier=5), 1),
            (Item('enchanted_magma_cream'), 16)],
           (get_item('magma_cube_minion', tier=6), 1),
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_7', 'combat',
           [(get_item('magma_cube_minion', tier=6), 1),
            (Item('enchanted_magma_cream'), 32)],
           (get_item('magma_cube_minion', tier=7), 1),
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_8', 'combat',
           [(get_item('magma_cube_minion', tier=7), 1),
            (Item('enchanted_magma_cream'), 64)],
           (get_item('magma_cube_minion', tier=8), 1),
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_9', 'combat',
           [(get_item('magma_cube_minion', tier=8), 1),
            (Item('enchanted_magma_cream'), 128)],
           (get_item('magma_cube_minion', tier=9), 1),
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_10', 'combat',
           [(get_item('magma_cube_minion', tier=9), 1),
            (Item('enchanted_magma_cream'), 256)],
           (get_item('magma_cube_minion', tier=10), 1),
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_11', 'combat',
           [(get_item('magma_cube_minion', tier=10), 1),
            (Item('enchanted_magma_cream'), 512)],
           (get_item('magma_cube_minion', tier=11), 1),
           collection_req=('magma_cream', 1)),
    RecipeGroup('magma_cube_minion', 'combat',
                ['magma_cube_minion_1', 'magma_cube_minion_2',
                 'magma_cube_minion_3', 'magma_cube_minion_4',
                 'magma_cube_minion_5', 'magma_cube_minion_6',
                 'magma_cube_minion_7', 'magma_cube_minion_8',
                 'magma_cube_minion_9', 'magma_cube_minion_10',
                 'magma_cube_minion_11'],
                collection_req=('magma_cream', 1)),
]
