from ..object import *


COMBAT_MINION_RECIPES = [
    Recipe('zombie_minion_1', 'combat',
           [{'name': 'wooden_sword'},
            {'name': 'rotten_flesh', 'count': 80}],
           {'name': 'zombie_minion', 'tier': 1},
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_2', 'combat',
           [{'name': 'zombie_minion', 'tier': 1},
            {'name': 'rotten_flesh', 'count': 160}],
           {'name': 'zombie_minion', 'tier': 2},
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_3', 'combat',
           [{'name': 'zombie_minion', 'tier': 2},
            {'name': 'rotten_flesh', 'count': 320}],
           {'name': 'zombie_minion', 'tier': 3},
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_4', 'combat',
           [{'name': 'zombie_minion', 'tier': 3},
            {'name': 'rotten_flesh', 'count': 512}],
           {'name': 'zombie_minion', 'tier': 4},
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_5', 'combat',
           [{'name': 'zombie_minion', 'tier': 4},
            {'name': 'enchanted_rotten_flesh', 'count': 8}],
           {'name': 'zombie_minion', 'tier': 5},
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_6', 'combat',
           [{'name': 'zombie_minion', 'tier': 5},
            {'name': 'enchanted_rotten_flesh', 'count': 16}],
           {'name': 'zombie_minion', 'tier': 6},
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_7', 'combat',
           [{'name': 'zombie_minion', 'tier': 6},
            {'name': 'enchanted_rotten_flesh', 'count': 32}],
           {'name': 'zombie_minion', 'tier': 7},
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_8', 'combat',
           [{'name': 'zombie_minion', 'tier': 7},
            {'name': 'enchanted_rotten_flesh', 'count': 64}],
           {'name': 'zombie_minion', 'tier': 8},
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_9', 'combat',
           [{'name': 'zombie_minion', 'tier': 8},
            {'name': 'enchanted_rotten_flesh', 'count': 128}],
           {'name': 'zombie_minion', 'tier': 9},
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_10', 'combat',
           [{'name': 'zombie_minion', 'tier': 9},
            {'name': 'enchanted_rotten_flesh', 'count': 256}],
           {'name': 'zombie_minion', 'tier': 10},
           collection_req=('rotten_flesh', 1)),
    Recipe('zombie_minion_11', 'combat',
           [{'name': 'zombie_minion', 'tier': 10},
            {'name': 'enchanted_rotten_flesh', 'count': 512}],
           {'name': 'zombie_minion', 'tier': 11},
           collection_req=('rotten_flesh', 1)),
    RecipeGroup('zombie_minion', 'combat',
                ['zombie_minion_1', 'zombie_minion_2', 'zombie_minion_3',
                 'zombie_minion_4', 'zombie_minion_5', 'zombie_minion_6',
                 'zombie_minion_7', 'zombie_minion_8', 'zombie_minion_9',
                 'zombie_minion_10', 'zombie_minion_11'],
                collection_req=('rotten_flesh', 1)),

    Recipe('skeleton_minion_1', 'combat',
           [{'name': 'wooden_sword'},
            {'name': 'bone', 'count': 80}],
           {'name': 'skeleton_minion', 'tier': 1},
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_2', 'combat',
           [{'name': 'skeleton_minion', 'tier': 1},
            {'name': 'bone', 'count': 160}],
           {'name': 'skeleton_minion', 'tier': 2},
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_3', 'combat',
           [{'name': 'skeleton_minion', 'tier': 2},
            {'name': 'bone', 'count': 320}],
           {'name': 'skeleton_minion', 'tier': 3},
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_4', 'combat',
           [{'name': 'skeleton_minion', 'tier': 3},
            {'name': 'bone', 'count': 512}],
           {'name': 'skeleton_minion', 'tier': 4},
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_5', 'combat',
           [{'name': 'skeleton_minion', 'tier': 4},
            {'name': 'enchanted_bone', 'count': 8}],
           {'name': 'skeleton_minion', 'tier': 5},
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_6', 'combat',
           [{'name': 'skeleton_minion', 'tier': 5},
            {'name': 'enchanted_bone', 'count': 16}],
           {'name': 'skeleton_minion', 'tier': 6},
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_7', 'combat',
           [{'name': 'skeleton_minion', 'tier': 6},
            {'name': 'enchanted_bone', 'count': 32}],
           {'name': 'skeleton_minion', 'tier': 7},
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_8', 'combat',
           [{'name': 'skeleton_minion', 'tier': 7},
            {'name': 'enchanted_bone', 'count': 64}],
           {'name': 'skeleton_minion', 'tier': 8},
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_9', 'combat',
           [{'name': 'skeleton_minion', 'tier': 8},
            {'name': 'enchanted_bone', 'count': 128}],
           {'name': 'skeleton_minion', 'tier': 9},
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_10', 'combat',
           [{'name': 'skeleton_minion', 'tier': 9},
            {'name': 'enchanted_bone', 'count': 256}],
           {'name': 'skeleton_minion', 'tier': 10},
           collection_req=('bone', 1)),
    Recipe('skeleton_minion_11', 'combat',
           [{'name': 'skeleton_minion', 'tier': 10},
            {'name': 'enchanted_bone', 'count': 512}],
           {'name': 'skeleton_minion', 'tier': 11},
           collection_req=('bone', 1)),
    RecipeGroup('skeleton_minion', 'combat',
                ['skeleton_minion_1', 'skeleton_minion_2', 'skeleton_minion_3',
                 'skeleton_minion_4', 'skeleton_minion_5', 'skeleton_minion_6',
                 'skeleton_minion_7', 'skeleton_minion_8', 'skeleton_minion_9',
                 'skeleton_minion_10', 'skeleton_minion_11'],
                collection_req=('bone', 1)),

    Recipe('spider_minion_1', 'combat',
           [{'name': 'wooden_sword'},
            {'name': 'string', 'count': 80}],
           {'name': 'spider_minion', 'tier': 1},
           collection_req=('string', 1)),
    Recipe('spider_minion_2', 'combat',
           [{'name': 'spider_minion', 'tier': 1},
            {'name': 'string', 'count': 160}],
           {'name': 'spider_minion', 'tier': 2},
           collection_req=('string', 1)),
    Recipe('spider_minion_3', 'combat',
           [{'name': 'spider_minion', 'tier': 2},
            {'name': 'string', 'count': 320}],
           {'name': 'spider_minion', 'tier': 3},
           collection_req=('string', 1)),
    Recipe('spider_minion_4', 'combat',
           [{'name': 'spider_minion', 'tier': 3},
            {'name': 'string', 'count': 512}],
           {'name': 'spider_minion', 'tier': 4},
           collection_req=('string', 1)),
    Recipe('spider_minion_5', 'combat',
           [{'name': 'spider_minion', 'tier': 4},
            {'name': 'enchanted_string', 'count': 8}],
           {'name': 'spider_minion', 'tier': 5},
           collection_req=('string', 1)),
    Recipe('spider_minion_6', 'combat',
           [{'name': 'spider_minion', 'tier': 5},
            {'name': 'enchanted_string', 'count': 16}],
           {'name': 'spider_minion', 'tier': 6},
           collection_req=('string', 1)),
    Recipe('spider_minion_7', 'combat',
           [{'name': 'spider_minion', 'tier': 6},
            {'name': 'enchanted_string', 'count': 32}],
           {'name': 'spider_minion', 'tier': 7},
           collection_req=('string', 1)),
    Recipe('spider_minion_8', 'combat',
           [{'name': 'spider_minion', 'tier': 7},
            {'name': 'enchanted_string', 'count': 64}],
           {'name': 'spider_minion', 'tier': 8},
           collection_req=('string', 1)),
    Recipe('spider_minion_9', 'combat',
           [{'name': 'spider_minion', 'tier': 8},
            {'name': 'enchanted_string', 'count': 128}],
           {'name': 'spider_minion', 'tier': 9},
           collection_req=('string', 1)),
    Recipe('spider_minion_10', 'combat',
           [{'name': 'spider_minion', 'tier': 9},
            {'name': 'enchanted_string', 'count': 256}],
           {'name': 'spider_minion', 'tier': 10},
           collection_req=('string', 1)),
    Recipe('spider_minion_11', 'combat',
           [{'name': 'spider_minion', 'tier': 10},
            {'name': 'enchanted_string', 'count': 512}],
           {'name': 'spider_minion', 'tier': 11},
           collection_req=('string', 1)),
    RecipeGroup('spider_minion', 'combat',
                ['spider_minion_1', 'spider_minion_2', 'spider_minion_3',
                 'spider_minion_4', 'spider_minion_5', 'spider_minion_6',
                 'spider_minion_7', 'spider_minion_8', 'spider_minion_9',
                 'spider_minion_10', 'spider_minion_11'],
                collection_req=('string', 1)),

    Recipe('cave_spider_minion_1', 'combat',
           [{'name': 'wooden_sword'},
            {'name': 'spider_eye', 'count': 80}],
           {'name': 'cave_spider_minion', 'tier': 1},
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_2', 'combat',
           [{'name': 'cave_spider_minion', 'tier': 1},
            {'name': 'spider_eye', 'count': 160}],
           {'name': 'cave_spider_minion', 'tier': 2},
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_3', 'combat',
           [{'name': 'cave_spider_minion', 'tier': 2},
            {'name': 'spider_eye', 'count': 320}],
           {'name': 'cave_spider_minion', 'tier': 3},
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_4', 'combat',
           [{'name': 'cave_spider_minion', 'tier': 3},
            {'name': 'spider_eye', 'count': 512}],
           {'name': 'cave_spider_minion', 'tier': 4},
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_5', 'combat',
           [{'name': 'cave_spider_minion', 'tier': 4},
            {'name': 'enchanted_spider_eye', 'count': 8}],
           {'name': 'cave_spider_minion', 'tier': 5},
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_6', 'combat',
           [{'name': 'cave_spider_minion', 'tier': 5},
            {'name': 'enchanted_spider_eye', 'count': 24}],
           {'name': 'cave_spider_minion', 'tier': 6},
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_7', 'combat',
           [{'name': 'cave_spider_minion', 'tier': 6},
            {'name': 'enchanted_spider_eye', 'count': 64}],
           {'name': 'cave_spider_minion', 'tier': 7},
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_8', 'combat',
           [{'name': 'cave_spider_minion', 'tier': 7},
            {'name': 'enchanted_spider_eye', 'count': 128}],
           {'name': 'cave_spider_minion', 'tier': 8},
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_9', 'combat',
           [{'name': 'cave_spider_minion', 'tier': 8},
            {'name': 'enchanted_spider_eye', 'count': 256}],
           {'name': 'cave_spider_minion', 'tier': 9},
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_10', 'combat',
           [{'name': 'cave_spider_minion', 'tier': 9},
            {'name': 'enchanted_spider_eye', 'count': 512}],
           {'name': 'cave_spider_minion', 'tier': 10},
           collection_req=('spider_eye', 1)),
    Recipe('cave_spider_minion_11', 'combat',
           [{'name': 'cave_spider_minion', 'tier': 10},
            {'name': 'enchanted_fermented_spider_eye', 'count': 16}],
           {'name': 'cave_spider_minion', 'tier': 11},
           collection_req=('spider_eye', 1)),
    RecipeGroup('cave_spider_minion', 'combat',
                ['cave_spider_minion_1', 'cave_spider_minion_2',
                 'cave_spider_minion_3', 'cave_spider_minion_4',
                 'cave_spider_minion_5', 'cave_spider_minion_6',
                 'cave_spider_minion_7', 'cave_spider_minion_8',
                 'cave_spider_minion_9', 'cave_spider_minion_10',
                 'cave_spider_minion_11'],
                collection_req=('spider_eye', 1)),

    Recipe('creeper_minion_1', 'combat',
           [{'name': 'wooden_sword'},
            {'name': 'gunpowder', 'count': 80}],
           {'name': 'creeper_minion', 'tier': 1},
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_2', 'combat',
           [{'name': 'creeper_minion', 'tier': 1},
            {'name': 'gunpowder', 'count': 160}],
           {'name': 'creeper_minion', 'tier': 2},
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_3', 'combat',
           [{'name': 'creeper_minion', 'tier': 2},
            {'name': 'gunpowder', 'count': 320}],
           {'name': 'creeper_minion', 'tier': 3},
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_4', 'combat',
           [{'name': 'creeper_minion', 'tier': 3},
            {'name': 'gunpowder', 'count': 512}],
           {'name': 'creeper_minion', 'tier': 4},
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_5', 'combat',
           [{'name': 'creeper_minion', 'tier': 4},
            {'name': 'enchanted_gunpowder', 'count': 8}],
           {'name': 'creeper_minion', 'tier': 5},
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_6', 'combat',
           [{'name': 'creeper_minion', 'tier': 5},
            {'name': 'enchanted_gunpowder', 'count': 24}],
           {'name': 'creeper_minion', 'tier': 6},
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_7', 'combat',
           [{'name': 'creeper_minion', 'tier': 6},
            {'name': 'enchanted_gunpowder', 'count': 64}],
           {'name': 'creeper_minion', 'tier': 7},
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_8', 'combat',
           [{'name': 'creeper_minion', 'tier': 7},
            {'name': 'enchanted_gunpowder', 'count': 128}],
           {'name': 'creeper_minion', 'tier': 8},
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_9', 'combat',
           [{'name': 'creeper_minion', 'tier': 8},
            {'name': 'enchanted_gunpowder', 'count': 256}],
           {'name': 'creeper_minion', 'tier': 9},
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_10', 'combat',
           [{'name': 'creeper_minion', 'tier': 9},
            {'name': 'enchanted_gunpowder', 'count': 512}],
           {'name': 'creeper_minion', 'tier': 10},
           collection_req=('gunpowder', 1)),
    Recipe('creeper_minion_11', 'combat',
           [{'name': 'creeper_minion', 'tier': 10},
            {'name': 'enchanted_firework_rocket', 'count': 16}],
           {'name': 'creeper_minion', 'tier': 11},
           collection_req=('gunpowder', 1)),
    RecipeGroup('creeper_minion', 'combat',
                ['creeper_minion_1', 'creeper_minion_2', 'creeper_minion_3',
                 'creeper_minion_4', 'creeper_minion_5', 'creeper_minion_6',
                 'creeper_minion_7', 'creeper_minion_8', 'creeper_minion_9',
                 'creeper_minion_10', 'creeper_minion_11'],
                collection_req=('gunpowder', 1)),

    Recipe('enderman_minion_1', 'combat',
           [{'name': 'wooden_sword'},
            {'name': 'ender_pearl', 'count': 64}],
           {'name': 'enderman_minion', 'tier': 1},
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_2', 'combat',
           [{'name': 'enderman_minion', 'tier': 1},
            {'name': 'ender_pearl', 'count': 128}],
           {'name': 'enderman_minion', 'tier': 2},
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_3', 'combat',
           [{'name': 'enderman_minion', 'tier': 2},
            {'name': 'enchanted_ender_pearl', 'count': 8}],
           {'name': 'enderman_minion', 'tier': 3},
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_4', 'combat',
           [{'name': 'enderman_minion', 'tier': 3},
            {'name': 'enchanted_ender_pearl', 'count': 24}],
           {'name': 'enderman_minion', 'tier': 4},
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_5', 'combat',
           [{'name': 'enderman_minion', 'tier': 4},
            {'name': 'enchanted_ender_pearl', 'count': 48}],
           {'name': 'enderman_minion', 'tier': 5},
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_6', 'combat',
           [{'name': 'enderman_minion', 'tier': 5},
            {'name': 'enchanted_ender_pearl', 'count': 96}],
           {'name': 'enderman_minion', 'tier': 6},
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_7', 'combat',
           [{'name': 'enderman_minion', 'tier': 6},
            {'name': 'enchanted_eye_of_ender', 'count': 8}],
           {'name': 'enderman_minion', 'tier': 7},
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_8', 'combat',
           [{'name': 'enderman_minion', 'tier': 7},
            {'name': 'enchanted_eye_of_ender', 'count': 24}],
           {'name': 'enderman_minion', 'tier': 8},
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_9', 'combat',
           [{'name': 'enderman_minion', 'tier': 8},
            {'name': 'enchanted_eye_of_ender', 'count': 48}],
           {'name': 'enderman_minion', 'tier': 9},
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_10', 'combat',
           [{'name': 'enderman_minion', 'tier': 9},
            {'name': 'enchanted_eye_of_ender', 'count': 96}],
           {'name': 'enderman_minion', 'tier': 10},
           collection_req=('ender_pearl', 1)),
    Recipe('enderman_minion_11', 'combat',
           [{'name': 'enderman_minion', 'tier': 10},
            {'name': 'enchanted_eye_of_ender', 'count': 192}],
           {'name': 'enderman_minion', 'tier': 11},
           collection_req=('ender_pearl', 1)),
    RecipeGroup('enderman_minion', 'combat',
                ['enderman_minion_1', 'enderman_minion_2', 'enderman_minion_3',
                 'enderman_minion_4', 'enderman_minion_5', 'enderman_minion_6',
                 'enderman_minion_7', 'enderman_minion_8', 'enderman_minion_9',
                 'enderman_minion_10', 'enderman_minion_11'],
                collection_req=('ender_pearl', 1)),

    Recipe('ghast_minion_1', 'combat',
           [{'name': 'wooden_sword'},
            {'name': 'ghast_tear', 'count': 64}],
           {'name': 'ghast_minion', 'tier': 1},
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_2', 'combat',
           [{'name': 'ghast_minion', 'tier': 1},
            {'name': 'ghast_tear', 'count': 128}],
           {'name': 'ghast_minion', 'tier': 2},
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_3', 'combat',
           [{'name': 'ghast_minion', 'tier': 2},
            {'name': 'ghast_tear', 'count': 256}],
           {'name': 'ghast_minion', 'tier': 3},
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_4', 'combat',
           [{'name': 'ghast_minion', 'tier': 3},
            {'name': 'ghast_tear', 'count': 512}],
           {'name': 'ghast_minion', 'tier': 4},
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_5', 'combat',
           [{'name': 'ghast_minion', 'tier': 4},
            {'name': 'enchanted_ghast_tear', 'count': 256}],
           {'name': 'ghast_minion', 'tier': 5},
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_6', 'combat',
           [{'name': 'ghast_minion', 'tier': 5},
            {'name': 'enchanted_ghast_tear', 'count': 512}],
           {'name': 'ghast_minion', 'tier': 6},
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_7', 'combat',
           [{'name': 'ghast_minion', 'tier': 6},
            {'name': 'silver_fang', 'count': 32}],
           {'name': 'ghast_minion', 'tier': 7},
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_8', 'combat',
           [{'name': 'ghast_minion', 'tier': 7},
            {'name': 'silver_fang', 'count': 64}],
           {'name': 'ghast_minion', 'tier': 8},
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_9', 'combat',
           [{'name': 'ghast_minion', 'tier': 8},
            {'name': 'silver_fang', 'count': 128}],
           {'name': 'ghast_minion', 'tier': 9},
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_10', 'combat',
           [{'name': 'ghast_minion', 'tier': 9},
            {'name': 'silver_fang', 'count': 256}],
           {'name': 'ghast_minion', 'tier': 10},
           collection_req=('ghast_tear', 1)),
    Recipe('ghast_minion_11', 'combat',
           [{'name': 'ghast_minion', 'tier': 10},
            {'name': 'silver_fang', 'count': 512}],
           {'name': 'ghast_minion', 'tier': 11},
           collection_req=('ghast_tear', 1)),
    RecipeGroup('ghast_minion', 'combat',
                ['ghast_minion_1', 'ghast_minion_2', 'ghast_minion_3',
                 'ghast_minion_4', 'ghast_minion_5', 'ghast_minion_6',
                 'ghast_minion_7', 'ghast_minion_8', 'ghast_minion_9',
                 'ghast_minion_10', 'ghast_minion_11'],
                collection_req=('ghast_tear', 1)),

    Recipe('slime_minion_1', 'combat',
           [{'name': 'wooden_sword'},
            {'name': 'slime_ball', 'count': 80}],
           {'name': 'slime_minion', 'tier': 1},
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_2', 'combat',
           [{'name': 'slime_minion', 'tier': 1},
            {'name': 'slime_ball', 'count': 160}],
           {'name': 'slime_minion', 'tier': 2},
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_3', 'combat',
           [{'name': 'slime_minion', 'tier': 2},
            {'name': 'slime_ball', 'count': 320}],
           {'name': 'slime_minion', 'tier': 3},
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_4', 'combat',
           [{'name': 'slime_minion', 'tier': 3},
            {'name': 'slime_ball', 'count': 512}],
           {'name': 'slime_minion', 'tier': 4},
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_5', 'combat',
           [{'name': 'slime_minion', 'tier': 4},
            {'name': 'enchanted_slime_ball', 'count': 8}],
           {'name': 'slime_minion', 'tier': 5},
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_6', 'combat',
           [{'name': 'slime_minion', 'tier': 5},
            {'name': 'enchanted_slime_ball', 'count': 24}],
           {'name': 'slime_minion', 'tier': 6},
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_7', 'combat',
           [{'name': 'slime_minion', 'tier': 6},
            {'name': 'enchanted_slime_ball', 'count': 64}],
           {'name': 'slime_minion', 'tier': 7},
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_8', 'combat',
           [{'name': 'slime_minion', 'tier': 7},
            {'name': 'enchanted_slime_ball', 'count': 128}],
           {'name': 'slime_minion', 'tier': 8},
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_9', 'combat',
           [{'name': 'slime_minion', 'tier': 8},
            {'name': 'enchanted_slime_ball', 'count': 256}],
           {'name': 'slime_minion', 'tier': 9},
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_10', 'combat',
           [{'name': 'slime_minion', 'tier': 9},
            {'name': 'enchanted_slime_ball', 'count': 512}],
           {'name': 'slime_minion', 'tier': 10},
           collection_req=('slime_ball', 1)),
    Recipe('slime_minion_11', 'combat',
           [{'name': 'slime_minion', 'tier': 10},
            {'name': 'enchanted_slime_block', 'count': 8}],
           {'name': 'slime_minion', 'tier': 11},
           collection_req=('slime_ball', 1)),
    RecipeGroup('slime_minion', 'combat',
                ['slime_minion_1', 'slime_minion_2', 'slime_minion_3',
                 'slime_minion_4', 'slime_minion_5', 'slime_minion_6',
                 'slime_minion_7', 'slime_minion_8', 'slime_minion_9',
                 'slime_minion_10', 'slime_minion_11'],
                collection_req=('slime_ball', 1)),

    Recipe('blaze_minion_1', 'combat',
           [{'name': 'wooden_sword'},
            {'name': 'blaze_rod', 'count': 80}],
           {'name': 'blaze_minion', 'tier': 1},
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_2', 'combat',
           [{'name': 'blaze_minion', 'tier': 1},
            {'name': 'blaze_rod', 'count': 160}],
           {'name': 'blaze_minion', 'tier': 2},
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_3', 'combat',
           [{'name': 'blaze_minion', 'tier': 2},
            {'name': 'blaze_rod', 'count': 320}],
           {'name': 'blaze_minion', 'tier': 3},
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_4', 'combat',
           [{'name': 'blaze_minion', 'tier': 3},
            {'name': 'blaze_rod', 'count': 512}],
           {'name': 'blaze_minion', 'tier': 4},
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_5', 'combat',
           [{'name': 'blaze_minion', 'tier': 4},
            {'name': 'enchanted_blaze_powder', 'count': 8}],
           {'name': 'blaze_minion', 'tier': 5},
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_6', 'combat',
           [{'name': 'blaze_minion', 'tier': 5},
            {'name': 'enchanted_blaze_powder', 'count': 24}],
           {'name': 'blaze_minion', 'tier': 6},
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_7', 'combat',
           [{'name': 'blaze_minion', 'tier': 6},
            {'name': 'enchanted_blaze_powder', 'count': 64}],
           {'name': 'blaze_minion', 'tier': 7},
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_8', 'combat',
           [{'name': 'blaze_minion', 'tier': 7},
            {'name': 'enchanted_blaze_powder', 'count': 128}],
           {'name': 'blaze_minion', 'tier': 8},
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_9', 'combat',
           [{'name': 'blaze_minion', 'tier': 8},
            {'name': 'enchanted_blaze_powder', 'count': 256}],
           {'name': 'blaze_minion', 'tier': 9},
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_10', 'combat',
           [{'name': 'blaze_minion', 'tier': 9},
            {'name': 'enchanted_blaze_powder', 'count': 512}],
           {'name': 'blaze_minion', 'tier': 10},
           collection_req=('blaze_rod', 1)),
    Recipe('blaze_minion_11', 'combat',
           [{'name': 'blaze_minion', 'tier': 10},
            {'name': 'enchanted_blaze_rod', 'count': 8}],
           {'name': 'blaze_minion', 'tier': 11},
           collection_req=('blaze_rod', 1)),
    RecipeGroup('blaze_minion', 'combat',
                ['blaze_minion_1', 'blaze_minion_2', 'blaze_minion_3',
                 'blaze_minion_4', 'blaze_minion_5', 'blaze_minion_6',
                 'blaze_minion_7', 'blaze_minion_8', 'blaze_minion_9',
                 'blaze_minion_10', 'blaze_minion_11'],
                collection_req=('blaze_rod', 1)),

    Recipe('magma_cube_minion_1', 'combat',
           [{'name': 'wooden_sword'},
            {'name': 'magma_cream', 'count': 80}],
           {'name': 'magma_cube_minion', 'tier': 1},
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_2', 'combat',
           [{'name': 'magma_cube_minion', 'tier': 1},
            {'name': 'magma_cream', 'count': 160}],
           {'name': 'magma_cube_minion', 'tier': 2},
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_3', 'combat',
           [{'name': 'magma_cube_minion', 'tier': 2},
            {'name': 'magma_cream', 'count': 320}],
           {'name': 'magma_cube_minion', 'tier': 3},
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_4', 'combat',
           [{'name': 'magma_cube_minion', 'tier': 3},
            {'name': 'magma_cream', 'count': 512}],
           {'name': 'magma_cube_minion', 'tier': 4},
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_5', 'combat',
           [{'name': 'magma_cube_minion', 'tier': 4},
            {'name': 'enchanted_blaze_powder', 'count': 8}],
           {'name': 'magma_cube_minion', 'tier': 5},
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_6', 'combat',
           [{'name': 'magma_cube_minion', 'tier': 5},
            {'name': 'enchanted_magma_cream', 'count': 16}],
           {'name': 'magma_cube_minion', 'tier': 6},
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_7', 'combat',
           [{'name': 'magma_cube_minion', 'tier': 6},
            {'name': 'enchanted_magma_cream', 'count': 32}],
           {'name': 'magma_cube_minion', 'tier': 7},
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_8', 'combat',
           [{'name': 'magma_cube_minion', 'tier': 7},
            {'name': 'enchanted_magma_cream', 'count': 64}],
           {'name': 'magma_cube_minion', 'tier': 8},
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_9', 'combat',
           [{'name': 'magma_cube_minion', 'tier': 8},
            {'name': 'enchanted_magma_cream', 'count': 128}],
           {'name': 'magma_cube_minion', 'tier': 9},
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_10', 'combat',
           [{'name': 'magma_cube_minion', 'tier': 9},
            {'name': 'enchanted_magma_cream', 'count': 256}],
           {'name': 'magma_cube_minion', 'tier': 10},
           collection_req=('magma_cream', 1)),
    Recipe('magma_cube_minion_11', 'combat',
           [{'name': 'magma_cube_minion', 'tier': 10},
            {'name': 'enchanted_magma_cream', 'count': 512}],
           {'name': 'magma_cube_minion', 'tier': 11},
           collection_req=('magma_cream', 1)),
    RecipeGroup('magma_cube_minion', 'combat',
                ['magma_cube_minion_1', 'magma_cube_minion_2',
                 'magma_cube_minion_3', 'magma_cube_minion_4',
                 'magma_cube_minion_5', 'magma_cube_minion_6',
                 'magma_cube_minion_7', 'magma_cube_minion_8',
                 'magma_cube_minion_9', 'magma_cube_minion_10',
                 'magma_cube_minion_11'],
                collection_req=('magma_cream', 1)),
]
