from ..object import *


FARMING_RECIPES = [
    Recipe('wooden_hoe', 'farming',
           [{'name': 'planks', 'count': 2},
            {'name': 'stick', 'count': 2}],
           {'name': 'wooden_hoe'}),
    Recipe('gold_hoe', 'farming',
           [{'name': 'gold', 'count': 2},
            {'name': 'stick', 'count': 2}],
           {'name': 'golden_hoe'}),
    Recipe('stone_hoe', 'farming',
           [{'name': 'cobblestone', 'count': 2},
            {'name': 'stick', 'count': 2}],
           {'name': 'stone_hoe'}),
    Recipe('iron_hoe', 'farming',
           [{'name': 'iron', 'count': 2},
            {'name': 'stick', 'count': 2}],
           {'name': 'iron_hoe'}),
    Recipe('diamond_hoe', 'farming',
           [{'name': 'diamond', 'count': 2},
            {'name': 'stick', 'count': 2}],
           {'name': 'diamond_hoe'}),

    Recipe('wheat_to_bread', 'farming',
           [{'name': 'wheat', 'count': 3}],
           {'name': 'bread'}),
    Recipe('wheat_to_hay', 'farming',
           [{'name': 'wheat', 'count': 9}],
           {'name': 'hay_bale'}),
    Recipe('hay_to_wheat', 'farming',
           [{'name': 'hay_bale'}],
           {'name': 'wheat', 'count': 9}),
    Recipe('carrot_to_golden', 'farming',
           [{'name': 'carrot'},
            {'name': 'gold_nugget', 'count': 8}],
           {'name': 'golden_carrot'}),
    Recipe('glistering_melon', 'farming',
           [{'name': 'melon'},
            {'name': 'gold_nugget', 'count': 8}],
           {'name': 'glistering_melon'}),
    Recipe('melon_block', 'farming',
           [{'name': 'melon', 'count': 9}],
           {'name': 'melon_block'}),
    Recipe('cane_to_sugar', 'farming',
           [{'name': 'sugar_cane'}],
           {'name': 'sugar'}),
    Recipe('cane_to_paper', 'farming',
           [{'name': 'sugar_cane', 'count': 3}],
           {'name': 'paper', 'count': 3}),
    Recipe('paper_to_book', 'farming',
           [{'name': 'paper', 'count': 3},
            {'name': 'leather'}],
           {'name': 'book'}),
    Recipe('string_to_wool', 'farming',
           [{'name': 'string', 'count': 4}],
           {'name': 'wool'}),
    Recipe('hide_to_leather', 'farming',
           [{'name': 'rabbit_hide', 'count': 4}],
           {'name': 'leather'}),

    Recipe('harvesting_book', 'enchanting',
           [{'name': 'paper', 'count': 48},
            {'name': 'wheat', 'count': 16}],
           {'name': 'enchanted_book', 'enchantments': {'harvesting': 4}},
           collection_req=('wheat', 2)),
    Recipe('farm_suit_helmet', 'farming',
           [{'name': 'hay_bale', 'count': 5}],
           {'name': 'farm_suit_helmet'},
           collection_req=('wheat', 3)),
    Recipe('farm_suit_chestplate', 'farming',
           [{'name': 'hay_bale', 'count': 8}],
           {'name': 'farm_suit_chestplate'},
           collection_req=('wheat', 3)),
    Recipe('farm_suit_leggings', 'farming',
           [{'name': 'hay_bale', 'count': 7}],
           {'name': 'farm_suit_leggings'},
           collection_req=('wheat', 3)),
    Recipe('farm_suit_boots', 'farming',
           [{'name': 'hay_bale', 'count': 4}],
           {'name': 'farm_suit_boots'},
           collection_req=('wheat', 3)),
    RecipeGroup('farm_suit_armor', 'farming',
                ['farm_suit_helmet', 'farm_suit_chestplate',
                 'farm_suit_leggings', 'farm_suit_boots'],
                collection_req=('wheat', 3)),
    Recipe('farming_talisman', 'farming',
           [{'name': 'hay_bale', 'count': 5},
            {'name': 'seeds', 'count': 4}],
           {'name': 'farming_talisman'},
           collection_req=('wheat', 4)),
    Recipe('bread_to_enchanted', 'farming',
           [{'name': 'wheat', 'count': 144}],
           {'name': 'enchanted_bread'},
           collection_req=('wheat', 5)),
    Recipe('hay_to_enchanted', 'farming',
           [{'name': 'hay_bale', 'count': 144}],
           {'name': 'enchanted_hay_bale'},
           collection_req=('wheat', 7)),
    Recipe('farm_helmet', 'farming',
           [{'name': 'enchanted_hay_bale', 'count': 5}],
           {'name': 'farm_helmet'},
           collection_req=('wheat', 9)),
    Recipe('farm_chestplate', 'farming',
           [{'name': 'enchanted_hay_bale', 'count': 8}],
           {'name': 'farm_chestplate'},
           collection_req=('wheat', 9)),
    Recipe('farm_leggings', 'farming',
           [{'name': 'enchanted_hay_bale', 'count': 7}],
           {'name': 'farm_leggings'},
           collection_req=('wheat', 9)),
    Recipe('farm_boots', 'farming',
           [{'name': 'enchanted_hay_bale', 'count': 4}],
           {'name': 'farm_boots'},
           collection_req=('wheat', 9)),
    RecipeGroup('farm_armor', 'farming',
                ['farm_helmet', 'farm_chestplate',
                 'farm_leggings', 'farm_boots'],
                collection_req=('wheat', 9)),
    Recipe('hay_to_tighted', 'farming',
           [{'name': 'enchanted_hay_bale', 'count': 144}],
           {'name': 'tightly_tied_hay_bale'},
           collection_req=('wheat', 11)),

    Recipe('carrot_to_enchanted', 'farming',
           [{'name': 'carrot', 'count': 160}],
           {'name': 'enchanted_carrot'},
           collection_req=('carrot', 4)),
    Recipe('carrot_to_enchanted_golden', 'farming',
           [{'name': 'golden_carrot', 'count': 32},
            {'name': 'enchanted_carrot', 'count': 128}],
           {'name': 'enchanted_golden_carrot'},
           collection_req=('carrot', 7)),

    Recipe('vaccine_talisman', 'farming',
           [{'name': 'poisonous_potato', 'count': 9}],
           {'name': 'vaccine_talisman'},
           collection_req=('potato', 3)),
    Recipe('potato_to_enchanted', 'farming',
           [{'name': 'potato', 'count': 160}],
           {'name': 'enchanted_potato'},
           collection_req=('potato', 4)),
    Recipe('scroll_to_barn', 'farming',
           [{'name': 'enchanted_ender_pearl', 'count': 16},
            {'name': 'enchanted_carrot', 'count': 48},
            {'name': 'enchanted_potato', 'count': 80}],
           {'name': 'travel_scroll_to_barn'},
           collection_req=('potato', 6)),
    Recipe('potato_to_enchanted_baked', 'farming',
           [{'name': 'enchanted_potato', 'count': 160}],
           {'name': 'enchanted_baked_potato'},
           collection_req=('potato', 7)),
    Recipe('hot_potato_book', 'farming',
           [{'name': 'enchanted_baked_potato'},
            {'name': 'paper', 'count': 3}],
           {'name': 'hot_potato_book'},
           collection_req=('potato', 8)),

    Recipe('pumpkin_helmet', 'farming',
           [{'name': 'pumpkin', 'count': 5}],
           {'name': 'pumpkin_helmet'},
           collection_req=('pumpkin', 2)),
    Recipe('pumpkin_chestplate', 'farming',
           [{'name': 'pumpkin', 'count': 8}],
           {'name': 'pumpkin_chestplate'},
           collection_req=('pumpkin', 2)),
    Recipe('pumpkin_leggings', 'farming',
           [{'name': 'pumpkin', 'count': 7}],
           {'name': 'pumpkin_leggings'},
           collection_req=('pumpkin', 2)),
    Recipe('pumpkin_boots', 'farming',
           [{'name': 'pumpkin', 'count': 4}],
           {'name': 'pumpkin_boots'},
           collection_req=('pumpkin', 2)),
    RecipeGroup('pumpkin_armor', 'farming',
                ['pumpkin_helmet', 'pumpkin_chestplate',
                 'pumpkin_leggings', 'pumpkin_boots'],
                collection_req=('pumpkin', 2)),
    Recipe('pumpkin_to_enchanted', 'farming',
           [{'name': 'pumpkin', 'count': 160}],
           {'name': 'enchanted_pumpkin'},
           collection_req=('pumpkin', 3)),
    Recipe('cubism_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'pumpkin', 'count': 32}],
           {'name': 'enchanted_book', 'enchantments': {'cubism': 4}},
           collection_req=('pumpkin', 4)),
    Recipe('pumpkin_to_polished', 'farming',
           [{'name': 'enchanted_pumpkin', 'count': 160}],
           {'name': 'polished_pumpkin'},
           collection_req=('pumpkin', 10)),

    Recipe('farmer_boots', 'farming',
           [{'name': 'enchanted_pumpkin', 'count': 256}],
           {'name': 'farmer_boots'},
           collection_req=('pumpkin', 9)),
    Recipe('ranchers_boots', 'farming',
           [{'name': 'farmer_boots'},
            {'name': 'polished_pumpkin', 'count': 16}],
           {'name': 'ranchers_boots'},
           collection_req=('pumpkin', 11)),

    Recipe('melon_to_enchanted', 'farming',
           [{'name': 'melon', 'count': 160}],
           {'name': 'enchanted_melon'},
           collection_req=('melon', 4)),
    Recipe('melon_to_enchanted_glistering', 'farming',
           [{'name': 'glistering_melon', 'count': 256}],
           {'name': 'enchanted_glistering_melon'},
           collection_req=('melon', 5)),
    Recipe('melon_to_enchanted_block', 'farming',
           [{'name': 'enchanted_melon', 'count': 160}],
           {'name': 'enchanted_melon_block'},
           collection_req=('melon', 6)),

    Recipe('mushroom_helmet', 'farming',
           [{'name': 'mushroom', 'count': 5}],
           {'name': 'mushroom_helmet'},
           collection_req=('mushroom', 3)),
    Recipe('mushroom_chestplate', 'farming',
           [{'name': 'mushroom', 'count': 8}],
           {'name': 'mushroom_chestplate'},
           collection_req=('mushroom', 3)),
    Recipe('mushroom_leggings', 'farming',
           [{'name': 'mushroom', 'count': 7}],
           {'name': 'mushroom_leggings'},
           collection_req=('mushroom', 3)),
    Recipe('mushroom_boots', 'farming',
           [{'name': 'mushroom', 'count': 4}],
           {'name': 'mushroom_boots'},
           collection_req=('mushroom', 3)),
    RecipeGroup('mushroom_armor', 'farming',
                ['mushroom_helmet', 'mushroom_chestplate',
                 'mushroom_leggings', 'mushroom_boots'],
                collection_req=('mushroom', 3)),
    Recipe('mushroom_block', 'farming',
           [{'name': 'mushroom', 'count': 9}],
           {'name': 'mushroom_block'},
           collection_req=('mushroom', 5)),
    Recipe('mushroom_to_enchanted', 'farming',
           [{'name': 'mushroom', 'count': 160}],
           {'name': 'enchanted_mushroom'},
           collection_req=('mushroom', 6)),
    Recipe('night_vision_charm', 'farming',
           [{'name': 'enchanted_mushroom', 'count': 8}],
           {'name': 'night_vision_charm'},
           collection_req=('mushroom', 7)),
    Recipe('mushroom_to_enchanted_block', 'farming',
           [{'name': 'mushroom_block', 'count': 576}],
           {'name': 'enchanted_mushroom_block'},
           collection_req=('mushroom', 8)),
    Recipe('uncommon_bat_pet', 'farming',
           [{'name': 'enchanted_mushroom', 'count': 64},
            {'name': 'enchanted_egg'}],
           {'name': 'bat_pet', 'rarity': 'uncommon'},
           collection_req=('mushroom', 9)),
    Recipe('epic_bat_pet', 'farming',
           [{'name': 'enchanted_mushroom', 'count': 64},
            {'name': 'super_enchanted_egg'}],
           {'name': 'bat_pet', 'rarity': 'epic'},
           collection_req=('mushroom', 9)),
    RecipeGroup('bat_pet', 'farming',
                ['uncommon_bat_pet', 'epic_bat_pet'],
                collection_req=('mushroom', 9)),

    Recipe('cocoa_to_enchanted', 'farming',
           [{'name': 'cocoa', 'count': 160}],
           {'name': 'enchanted_cocoa'},
           collection_req=('cocoa', 4)),
    Recipe('scroll_to_desert', 'farming',
           [{'name': 'enchanted_ender_pearl', 'count': 16},
            {'name': 'enchanted_cactus_green', 'count': 48},
            {'name': 'enchanted_cocoa', 'count': 80}],
           {'name': 'travel_scroll_to_desert'},
           collection_req=('cocoa', 5)),
    Recipe('cocoa_to_enchanted_cookie', 'farming',
           [{'name': 'enchanted_cocoa', 'count': 128},
            {'name': 'wheat', 'count': 32}],
           {'name': 'enchanted_cookie'},
           collection_req=('cocoa', 6)),

    Recipe('cactus_helmet', 'farming',
           [{'name': 'cactus', 'count': 5}],
           {'name': 'cactus_helmet'},
           collection_req=('cactus', 2)),
    Recipe('cactus_chestplate', 'farming',
           [{'name': 'cactus', 'count': 8}],
           {'name': 'cactus_chestplate'},
           collection_req=('cactus', 2)),
    Recipe('cactus_leggings', 'farming',
           [{'name': 'cactus', 'count': 7}],
           {'name': 'cactus_leggings'},
           collection_req=('cactus', 2)),
    Recipe('cactus_boots', 'farming',
           [{'name': 'cactus', 'count': 4}],
           {'name': 'cactus_boots'},
           collection_req=('cactus', 2)),
    RecipeGroup('cactus_armor', 'farming',
                ['cactus_helmet', 'cactus_chestplate',
                 'cactus_leggings', 'cactus_boots'],
                collection_req=('cactus', 2)),
    Recipe('cactus_to_enchanted_green', 'farming',
           [{'name': 'cactus', 'count': 160}],
           {'name': 'enchanted_cactus_green'},
           collection_req=('cactus', 4)),
    Recipe('piercing_book', 'enchanting',
           [{'name': 'paper', 'count': 3},
            {'name': 'cactus', 'count': 10},
            {'name': 'arrow'}],
           {'name': 'enchanted_book', 'enchantments': {'piercing': 1}},
           collection_req=('cactus', 6)),
    Recipe('thorns_book', 'enchanting',
           [{'name': 'paper', 'count': 6},
            {'name': 'enchanted_cactus_green', 'count': 2}],
           {'name': 'enchanted_book', 'enchantments': {'thorns': 2}},
           collection_req=('cactus', 7)),
    Recipe('cactus_to_enchanted', 'farming',
           [{'name': 'enchanted_cactus_green', 'count': 160}],
           {'name': 'enchanted_cactus'},
           collection_req=('cactus', 8)),

    Recipe('speed_talisman', 'farming',
           [{'name': 'sugar_cane', 'count': 108}],
           {'name': 'speed_talisman'},
           collection_req=('sugar_cane', 2)),
    Recipe('cane_to_enchanted_sugar', 'farming',
           [{'name': 'sugar_cane', 'count': 160}],
           {'name': 'enchanted_sugar'},
           collection_req=('sugar_cane', 4)),
    Recipe('cane_to_enchanted_paper', 'farming',
           [{'name': 'sugar_cane', 'count': 192}],
           {'name': 'enchanted_paper'},
           collection_req=('sugar_cane', 5)),
    Recipe('speed_ring', 'farming',
           [{'name': 'speed_talisman'},
            {'name': 'enchanted_sugar', 'count': 96}],
           {'name': 'speed_ring'},
           collection_req=('sugar_cane', 5)),
    Recipe('cane_to_enchanted_bookshelf', 'farming',
           [{'name': 'enchanted_paper', 'count': 6},
            {'name': 'enchanted_oak', 'count': 6}],
           {'name': 'enchanted_bookshelf'},
           collection_req=('sugar_cane', 6)),
    Recipe('cane_to_enchanted', 'farming',
           [{'name': 'enchanted_sugar', 'count': 160}],
           {'name': 'enchanted_sugar_cane'},
           collection_req=('sugar_cane', 8)),
    Recipe('speed_artifact', 'farming',
           [{'name': 'speed_ring'},
            {'name': 'enchanted_sugar_cane', 'count': 48}],
           {'name': 'speed_artifact'},
           collection_req=('sugar_cane', 8)),
    Recipe('speedster_helmet', 'farming',
           [{'name': 'enchanted_sugar_cane', 'count': 5}],
           {'name': 'speedster_helmet'},
           collection_req=('sugar_cane', 9)),
    Recipe('speedster_chestplate', 'farming',
           [{'name': 'enchanted_sugar_cane', 'count': 8}],
           {'name': 'speedster_chestplate'},
           collection_req=('sugar_cane', 9)),
    Recipe('speedster_leggings', 'farming',
           [{'name': 'enchanted_sugar_cane', 'count': 7}],
           {'name': 'speedster_leggings'},
           collection_req=('sugar_cane', 9)),
    Recipe('speedster_boots', 'farming',
           [{'name': 'enchanted_sugar_cane', 'count': 4}],
           {'name': 'speedster_boots'},
           collection_req=('sugar_cane', 9)),
    RecipeGroup('speedster_armor', 'farming',
                ['speedster_helmet', 'speedster_chestplate',
                 'speedster_leggings', 'speedster_boots'],
                collection_req=('sugar_cane', 9)),

    Recipe('projectile_protection_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'arrow', 'count': 8}],
           {'name': 'enchanted_book', 'enchantments': {'projectile_protection': 4}},
           collection_req=('feather', 1)),
    Recipe('feather_talisman', 'farming',
           [{'name': 'feather', 'count': 108}],
           {'name': 'feather_talisman'},
           collection_req=('feather', 4)),
    Recipe('feather_to_enchanted', 'farming',
           [{'name': 'feather', 'count': 160}],
           {'name': 'enchanted_feather'},
           collection_req=('feather', 5)),
    Recipe('feather_ring', 'farming',
           [{'name': 'feather_talisman'},
            {'name': 'enchanted_feather', 'count': 7}],
           {'name': 'feather_ring'},
           collection_req=('feather', 7)),
    Recipe('feather_artifact', 'farming',
           [{'name': 'feather_ring'},
            {'name': 'enchanted_feather', 'count': 128}],
           {'name': 'feather_artifact'},
           collection_req=('feather', 9)),

    Recipe('cow_head', 'farming',
           [{'name': 'beef', 'count': 8}],
           {'name': 'cow_head'},
           collection_req=('leather', 2)),
    Recipe('beef_to_enchanted', 'farming',
           [{'name': 'beef', 'count': 160}],
           {'name': 'enchanted_beef'},
           collection_req=('leather', 4)),
    Recipe('leather_to_enchanted', 'farming',
           [{'name': 'leather', 'count': 576}],
           {'name': 'enchanted_leather'},
           collection_req=('leather', 6)),
    Recipe('uncommon_horse_pet', 'farming',
           [{'name': 'enchanted_leather', 'count': 8},
            {'name': 'enchanted_egg'}],
           {'name': 'horse_pet', 'rarity': 'uncommon'},
           collection_req=('leather', 9)),
    Recipe('epic_horse_pet', 'farming',
           [{'name': 'enchanted_leather', 'count': 8},
            {'name': 'super_enchanted_egg'}],
           {'name': 'horse_pet', 'rarity': 'epic'},
           collection_req=('leather', 9)),
    RecipeGroup('horse_pet', 'farming',
                ['uncommon_horse_pet', 'epic_horse_pet'],
                collection_req=('leather', 9)),

    Recipe('uncommon_pig_pet', 'farming',
           [{'name': 'pork', 'count': 512},
            {'name': 'enchanted_egg'}],
           {'name': 'pig_pet', 'rarity': 'uncommon'},
           collection_req=('pork', 3)),
    Recipe('epic_pig_pet', 'farming',
           [{'name': 'pork', 'count': 512},
            {'name': 'super_enchanted_egg'}],
           {'name': 'pig_pet', 'rarity': 'epic'},
           collection_req=('pork', 3)),
    RecipeGroup('pig_pet', 'farming',
                ['uncommon_pig_pet', 'epic_pig_pet'],
                collection_req=('pork', 3)),
    Recipe('pork_to_enchanted', 'farming',
           [{'name': 'pork', 'count': 160}],
           {'name': 'enchanted_pork'},
           collection_req=('pork', 4)),
    Recipe('piggy_bank', 'farming',
           [{'name': 'enchanted_pork', 'count': 40},
            {'name': 'chest'}],
           {'name': 'piggy_bank'},
           collection_req=('pork', 5)),
    Recipe('repair_cracked_piggy_bank', 'farming',
           [{'name': 'cracked_piggy_bank'},
            {'name': 'enchanted_pork', 'count': 8}],
           {'name': 'piggy_bank'},
           collection_req=('pork', 5)),
    Recipe('repair_broken_piggy_bank', 'farming',
           [{'name': 'broken_piggy_bank'},
            {'name': 'enchanted_pork', 'count': 8}],
           {'name': 'piggy_bank'},
           collection_req=('pork', 5)),
    Recipe('pork_to_enchanted_grilled', 'farming',
           [{'name': 'enchanted_pork', 'count': 160}],
           {'name': 'enchanted_grilled_pork'},
           collection_req=('pork', 7)),
    Recipe('pigman_pet', 'farming',
           [{'name': 'enchanted_grilled_pork', 'count': 8},
            {'name': 'super_enchanted_egg'}],
           {'name': 'pigman_pet', 'rarity': 'epic'},
           collection_req=('pork', 8)),
    Recipe('pigman_sword', 'farming',
           [{'name': 'enchanted_grilled_pork', 'count': 48},
            {'name': 'stick'}],
           {'name': 'pigman_sword'},
           collection_req=('pork', 9)),

    Recipe('chicken_to_enchanted', 'farming',
           [{'name': 'chicken', 'count': 160}],
           {'name': 'enchanted_chicken'},
           collection_req=('chicken', 4)),
    Recipe('egg_to_enchanted', 'farming',
           [{'name': 'egg', 'count': 144}],
           {'name': 'enchanted_egg'},
           collection_req=('chicken', 5)),
    Recipe('uncommon_chicken_pet', 'farming',
           [{'name': 'enchanted_chicken', 'count': 64},
            {'name': 'enchanted_egg'}],
           {'name': 'chicken_pet', 'rarity': 'uncommon'},
           collection_req=('chicken', 6)),
    Recipe('epic_chicken_pet', 'farming',
           [{'name': 'enchanted_chicken', 'count': 64},
            {'name': 'super_enchanted_egg'}],
           {'name': 'chicken_pet', 'rarity': 'epic'},
           collection_req=('chicken', 6)),
    RecipeGroup('chicken_pet', 'farming',
                ['uncommon_chicken_pet', 'epic_chicken_pet'],
                collection_req=('chicken', 6)),
    Recipe('enchanted_cake', 'farming',
           [{'name': 'enchanted_egg'},
            {'name': 'enchanted_sugar'},
            {'name': 'wheat'}],
           {'name': 'enchanted_cake'},
           collection_req=('chicken', 7)),
    Recipe('egg_to_super_enchanted', 'farming',
           [{'name': 'enchanted_egg', 'count': 144}],
           {'name': 'super_enchanted_egg'},
           collection_req=('chicken', 9)),

    Recipe('mutton_to_enchanted', 'farming',
           [{'name': 'mutton', 'count': 160}],
           {'name': 'enchanted_mutton'},
           collection_req=('mutton', 5)),
    Recipe('mutton_to_enchanted_cooked', 'farming',
           [{'name': 'enchanted_mutton', 'count': 160}],
           {'name': 'enchanted_cooked_mutton'},
           collection_req=('mutton', 8)),

    Recipe('rabbit_to_enchanted', 'farming',
           [{'name': 'rabbit', 'count': 160}],
           {'name': 'enchanted_rabbit'}),
    Recipe('uncommon_rabbit_pet', 'farming',
           [{'name': 'rabbit', 'count': 64},
            {'name': 'enchanted_egg'}],
           {'name': 'rabbit_pet', 'rarity': 'uncommon'},
           collection_req=('rabbit', 2)),
    Recipe('epic_rabbit_pet', 'farming',
           [{'name': 'rabbit', 'count': 64},
            {'name': 'super_enchanted_egg'}],
           {'name': 'rabbit_pet', 'rarity': 'epic'},
           collection_req=('rabbit', 2)),
    RecipeGroup('rabbit_pet', 'farming',
                ['uncommon_rabbit_pet', 'epic_rabbit_pet'],
                collection_req=('rabbit', 2)),
    Recipe('rabbit_foot_to_enchanted', 'farming',
           [{'name': 'rabbit_foot', 'count': 160}],
           {'name': 'enchanted_rabbit_foot'},
           collection_req=('rabbit', 4)),
    Recipe('luck_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'rabbit_hide', 'count': 8}],
           {'name': 'enchanted_book', 'enchantments': {'luck': 4}},
           collection_req=('rabbit', 5)),
    Recipe('rabbit_hide_to_enchanted', 'farming',
           [{'name': 'rabbit_hide', 'count': 576}],
           {'name': 'enchanted_rabbit_hide'},
           collection_req=('rabbit', 6)),
    Recipe('luck_of_the_sea_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'rabbit_foot', 'count': 16}],
           {'name': 'enchanted_book', 'enchantments': {'luck_of_the_sea': 4}},
           collection_req=('rabbit', 7)),

    Recipe('nether_wart_to_enchanted', 'farming',
           [{'name': 'nether_wart', 'count': 160}],
           {'name': 'enchanted_nether_wart'},
           collection_req=('nether_wart', 4)),
    Recipe('nether_wart_to_mutant', 'farming',
           [{'name': 'enchanted_nether_wart', 'count': 160}],
           {'name': 'mutant_nether_wart'},
           collection_req=('nether_wart', 12)),
]
