from ..item import get_item, get_scroll
from ..object import Item, Recipe, EnchantedBook


__all__ = ['FARMING_RECIPES']

FARMING_RECIPES = [
    Recipe('wooden_hoe', 'farming',
           [(Item('planks'), 2),
            (Item('stick'), 2)],
           (get_item('wooden_hoe'), 1)),
    Recipe('gold_hoe', 'farming',
           [(Item('gold'), 2),
            (Item('stick'), 2)],
           (get_item('golden_hoe'), 1)),
    Recipe('stone_hoe', 'farming',
           [(Item('cobblestone'), 2),
            (Item('stick'), 2)],
           (get_item('stone_hoe'), 1)),
    Recipe('iron_hoe', 'farming',
           [(Item('iron'), 2),
            (Item('stick'), 2)],
           (get_item('iron_hoe'), 1)),
    Recipe('diamond_hoe', 'farming',
           [(Item('diamond'), 2),
            (Item('stick'), 2)],
           (get_item('diamond_hoe'), 1)),

    Recipe('wheat_to_bread', 'farming',
           [(Item('wheat'), 3)],
           (Item('bread'), 1)),
    Recipe('wheat_to_hay', 'farming',
           [(Item('wheat'), 9)],
           (Item('hay_bale'), 1)),
    Recipe('hay_to_wheat', 'farming',
           [(Item('hay_bale'), 1)],
           (Item('wheat'), 9)),
    Recipe('carrot_to_golden', 'farming',
           [(Item('carrot'), 1),
            (Item('gold_nugget'), 8)],
           (Item('golden_carrot'), 1)),
    Recipe('glistering_melon', 'farming',
           [(Item('melon'), 1),
            (Item('gold_nugget'), 8)],
           (Item('glistering_melon'), 1)),
    Recipe('cane_to_sugar', 'farming',
           [(Item('sugar_cane'), 1)],
           (Item('sugar'), 1)),
    Recipe('cane_to_paper', 'farming',
           [(Item('sugar_cane'), 3)],
           (Item('paper'), 3)),
    Recipe('paper_to_book', 'farming',
           [(Item('paper'), 3),
            (Item('leather'), 1)],
           (Item('book'), 1)),
    Recipe('string_to_wool', 'farming',
           [(Item('string'), 4)],
           (Item('wool'), 1)),
    Recipe('hide_to_leather', 'farming',
           [(Item('rabbit_hide'), 4)],
           (Item('leather'), 1)),

    Recipe('harvesting_book', 'farming',
           [(Item('paper'), 48),
            (Item('wheat'), 16)],
           (EnchantedBook({'harvesting': 4}), 1),
           collection_req=('wheat', 2)),
    Recipe('farm_suit_helmet', 'farming',
           [(Item('hay_bale'), 5)],
           (get_item('farm_suit_helmet'), 1),
           collection_req=('wheat', 3)),
    Recipe('farm_suit_chestplate', 'farming',
           [(Item('hay_bale'), 8)],
           (get_item('farm_suit_chestplate'), 1),
           collection_req=('wheat', 3)),
    Recipe('farm_suit_leggings', 'farming',
           [(Item('hay_bale'), 7)],
           (get_item('farm_suit_leggings'), 1),
           collection_req=('wheat', 3)),
    Recipe('farm_suit_boots', 'farming',
           [(Item('hay_bale'), 4)],
           (get_item('farm_suit_boots'), 1),
           collection_req=('wheat', 3)),

    Recipe('bread_to_enchanted', 'farming',
           [(Item('wheat'), 144)],
           (Item('enchanted_bread'), 1),
           collection_req=('wheat', 5)),
    Recipe('hay_to_enchanted', 'farming',
           [(Item('hay_bale'), 144)],
           (Item('enchanted_hay_bale'), 1),
           collection_req=('wheat', 7)),

    Recipe('farm_helmet', 'farming',
           [(Item('enchanted_hay_bale'), 5)],
           (get_item('farm_helmet'), 1),
           collection_req=('wheat', 9)),
    Recipe('farm_chestplate', 'farming',
           [(Item('enchanted_hay_bale'), 8)],
           (get_item('farm_chestplate'), 1),
           collection_req=('wheat', 9)),
    Recipe('farm_leggings', 'farming',
           [(Item('enchanted_hay_bale'), 7)],
           (get_item('farm_leggings'), 1),
           collection_req=('wheat', 9)),
    Recipe('farm_boots', 'farming',
           [(Item('enchanted_hay_bale'), 4)],
           (get_item('farm_boots'), 1),
           collection_req=('wheat', 9)),

    Recipe('hay_to_tighted', 'farming',
           [(Item('enchanted_hay_bale'), 144)],
           (Item('tightly_tied_hay_bale'), 1),
           collection_req=('wheat', 11)),

    Recipe('carrot_to_enchanted', 'farming',
           [(Item('carrot'), 160)],
           (Item('enchanted_carrot'), 1),
           collection_req=('carrot', 4)),
    Recipe('carrot_to_enchanted_golden', 'farming',
           [(Item('golden_carrot'), 32),
            (Item('enchanted_carrot'), 128)],
           (Item('enchanted_golden_carrot'), 1),
           collection_req=('carrot', 7)),

    Recipe('potato_to_enchanted', 'farming',
           [(Item('potato'), 160)],
           (Item('enchanted_potato'), 1),
           collection_req=('potato', 4)),
    Recipe('scroll_to_barn', 'farming',
           [(Item('enchanted_ender_pearl'), 16),
            (Item('enchanted_carrot'), 48),
            (Item('enchanted_potato'), 80)],
           (get_scroll('barn'), 1),
           collection_req=('potato', 6)),
    Recipe('potato_to_enchanted_baked', 'farming',
           [(Item('enchanted_potato'), 160)],
           (Item('enchanted_baked_potato'), 1),
           collection_req=('potato', 7)),

    Recipe('pumpkin_helmet', 'farming',
           [(Item('pumpkin'), 5)],
           (get_item('pumpkin_helmet'), 1),
           collection_req=('pumpkin', 2)),
    Recipe('pumpkin_chestplate', 'farming',
           [(Item('pumpkin'), 8)],
           (get_item('pumpkin_chestplate'), 1),
           collection_req=('pumpkin', 2)),
    Recipe('pumpkin_leggings', 'farming',
           [(Item('pumpkin'), 7)],
           (get_item('pumpkin_leggings'), 1),
           collection_req=('pumpkin', 2)),
    Recipe('pumpkin_boots', 'farming',
           [(Item('pumpkin'), 4)],
           (get_item('pumpkin_boots'), 1),
           collection_req=('pumpkin', 2)),

    Recipe('pumpkin_to_enchanted', 'farming',
           [(Item('pumpkin'), 160)],
           (Item('enchanted_pumpkin'), 1),
           collection_req=('pumpkin', 3)),
    Recipe('cubism_book', 'farming',
           [(Item('paper'), 24),
            (Item('pumpkin'), 32)],
           (EnchantedBook({'cubism': 4}), 1),
           collection_req=('pumpkin', 4)),
    Recipe('pumpkin_to_polished', 'farming',
           [(Item('enchanted_pumpkin'), 160)],
           (Item('polished_pumpkin'), 1),
           collection_req=('pumpkin', 10)),

    Recipe('farmer_boots', 'farming',
           [(Item('enchanted_pumpkin'), 256)],
           (get_item('farmer_boots'), 1),
           collection_req=('pumpkin', 9)),
    Recipe('ranchers_boots', 'farming',
           [(get_item('farmer_boots'), 1),
            (Item('polished_pumpkin'), 16)],
           (get_item('ranchers_boots'), 1),
           collection_req=('pumpkin', 11)),

    Recipe('melon_to_enchanted', 'farming',
           [(Item('melon'), 160)],
           (Item('enchanted_melon'), 1),
           collection_req=('melon', 4)),
    Recipe('melon_to_enchanted_glistering', 'farming',
           [(Item('glistering_melon'), 256)],
           (Item('enchanted_glistering_melon'), 1),
           collection_req=('melon', 5)),
    Recipe('melon_to_enchanted_block', 'farming',
           [(Item('enchanted_melon'), 160)],
           (Item('enchanted_melon_block'), 1),
           collection_req=('melon', 6)),

    Recipe('mushroom_helmet', 'farming',
           [(Item('mushroom'), 5)],
           (get_item('mushroom_helmet'), 1),
           collection_req=('mushroom', 3)),
    Recipe('mushroom_chestplate', 'farming',
           [(Item('mushroom'), 8)],
           (get_item('mushroom_chestplate'), 1),
           collection_req=('mushroom', 3)),
    Recipe('mushroom_leggings', 'farming',
           [(Item('mushroom'), 7)],
           (get_item('mushroom_leggings'), 1),
           collection_req=('mushroom', 3)),
    Recipe('mushroom_boots', 'farming',
           [(Item('mushroom'), 4)],
           (get_item('mushroom_boots'), 1),
           collection_req=('mushroom', 3)),

    Recipe('mushroom_block', 'farming',
           [(Item('mushroom'), 9)],
           (Item('mushroom_block'), 1),
           collection_req=('mushroom', 5)),
    Recipe('mushroom_to_enchanted', 'farming',
           [(Item('mushroom'), 160)],
           (Item('enchanted_mushroom'), 1),
           collection_req=('mushroom', 6)),
    Recipe('mushroom_to_enchanted_block', 'farming',
           [(Item('mushroom_block'), 576)],
           (Item('enchanted_mushroom_block'), 1),
           collection_req=('mushroom', 8)),
    Recipe('uncommon_bat_pet', 'farming',
           [(Item('enchanted_mushroom'), 64),
            (Item('enchanted_egg'), 1)],
           (get_item('bat_pet', rarity='uncommon'), 1),
           collection_req=('mushroom', 9)),
    Recipe('epic_bat_pet', 'farming',
           [(Item('enchanted_mushroom'), 64),
            (Item('super_enchanted_egg'), 1)],
           (get_item('bat_pet', rarity='epic'), 1),
           collection_req=('mushroom', 9)),

    Recipe('cocoa_to_enchanted', 'farming',
           [(Item('cocoa'), 160)],
           (Item('enchanted_cocoa'), 1),
           collection_req=('cocoa', 4)),
    Recipe('scroll_to_desert', 'farming',
           [(Item('enchanted_ender_pearl'), 16),
            (Item('enchanted_cactus_green'), 48),
            (Item('enchanted_cocoa'), 80)],
           (get_scroll('desert'), 1),
           collection_req=('cocoa', 5)),
    Recipe('cocoa_to_enchanted_cookie', 'farming',
           [(Item('enchanted_cocoa'), 128),
            (Item('wheat'), 32)],
           (Item('enchanted_cookie'), 1),
           collection_req=('cocoa', 6)),

    Recipe('cactus_helmet', 'farming',
           [(Item('cactus'), 5)],
           (get_item('cactus_helmet'), 1),
           collection_req=('cactus', 2)),
    Recipe('cactus_chestplate', 'farming',
           [(Item('cactus'), 8)],
           (get_item('cactus_chestplate'), 1),
           collection_req=('cactus', 2)),
    Recipe('cactus_leggings', 'farming',
           [(Item('cactus'), 7)],
           (get_item('cactus_leggings'), 1),
           collection_req=('cactus', 2)),
    Recipe('cactus_boots', 'farming',
           [(Item('cactus'), 4)],
           (get_item('cactus_boots'), 1),
           collection_req=('cactus', 2)),

    Recipe('cactus_to_enchanted_green', 'farming',
           [(Item('cactus'), 160)],
           (Item('enchanted_cactus_green'), 1),
           collection_req=('cactus', 4)),
    Recipe('piercing_book', 'farming',
           [(Item('paper'), 3),
            (Item('cactus'), 10),
            (Item('arrow'), 1)],
           (EnchantedBook({'piercing': 1}), 1),
           collection_req=('cactus', 6)),
    Recipe('thorns_book', 'farming',
           [(Item('paper'), 6),
            (Item('enchanted_cactus_green'), 2)],
           (EnchantedBook({'thorns': 2}), 1),
           collection_req=('cactus', 7)),
    Recipe('cactus_to_enchanted', 'farming',
           [(Item('enchanted_cactus_green'), 160)],
           (Item('enchanted_cactus'), 1),
           collection_req=('cactus', 8)),

    Recipe('cane_to_enchanted_sugar', 'farming',
           [(Item('sugar_cane'), 160)],
           (Item('enchanted_sugar'), 1),
           collection_req=('sugar_cane', 4)),
    Recipe('cane_to_enchanted_paper', 'farming',
           [(Item('sugar_cane'), 192)],
           (Item('enchanted_paper'), 1),
           collection_req=('sugar_cane', 5)),
    Recipe('cane_to_enchanted_bookshelf', 'farming',
           [(Item('enchanted_paper'), 6),
            (Item('enchanted_oak'), 6)],
           (Item('enchanted_bookshelf'), 1),
           collection_req=('sugar_cane', 6)),
    Recipe('cane_to_enchanted', 'farming',
           [(Item('enchanted_sugar'), 160)],
           (Item('enchanted_sugar_cane'), 1),
           collection_req=('sugar_cane', 8)),

    Recipe('speedster_helmet', 'farming',
           [(Item('enchanted_sugar_cane'), 5)],
           (get_item('speedster_helmet'), 1),
           collection_req=('sugar_cane', 9)),
    Recipe('speedster_chestplate', 'farming',
           [(Item('enchanted_sugar_cane'), 8)],
           (get_item('speedster_chestplate'), 1),
           collection_req=('sugar_cane', 9)),
    Recipe('speedster_leggings', 'farming',
           [(Item('enchanted_sugar_cane'), 7)],
           (get_item('speedster_leggings'), 1),
           collection_req=('sugar_cane', 9)),
    Recipe('speedster_boots', 'farming',
           [(Item('enchanted_sugar_cane'), 4)],
           (get_item('speedster_boots'), 1),
           collection_req=('sugar_cane', 9)),

    Recipe('projectile_protection_book', 'farming',
           [(Item('paper'), 24),
            (Item('arrow'), 8)],
           (EnchantedBook({'projectile_protection': 4}), 1),
           collection_req=('feather', 1)),
    Recipe('feather_to_enchanted', 'farming',
           [(Item('feather'), 160)],
           (Item('enchanted_feather'), 1),
           collection_req=('feather', 5)),

    Recipe('cow_head', 'farming',
           [(Item('beef'), 8)],
           (get_item('cow_head'), 1),
           collection_req=('leather', 2)),
    Recipe('beef_to_enchanted', 'farming',
           [(Item('beef'), 160)],
           (Item('enchanted_beef'), 1),
           collection_req=('leather', 4)),
    Recipe('leather_to_enchanted', 'farming',
           [(Item('leather'), 576)],
           (Item('enchanted_leather'), 1),
           collection_req=('leather', 6)),
    Recipe('uncommon_horse_pet', 'farming',
           [(Item('enchanted_leather'), 8),
            (Item('enchanted_egg'), 1)],
           (get_item('horse_pet', rarity='uncommon'), 1),
           collection_req=('leather', 9)),
    Recipe('epic_horse_pet', 'farming',
           [(Item('enchanted_leather'), 8),
            (Item('super_enchanted_egg'), 1)],
           (get_item('horse_pet', rarity='epic'), 1),
           collection_req=('leather', 9)),

    Recipe('uncommon_pig_pet', 'farming',
           [(Item('pork'), 512),
            (Item('enchanted_egg'), 1)],
           (get_item('pig_pet', rarity='uncommon'), 1),
           collection_req=('pork', 3)),
    Recipe('epic_pig_pet', 'farming',
           [(Item('pork'), 512),
            (Item('super_enchanted_egg'), 1)],
           (get_item('pig_pet', rarity='epic'), 1),
           collection_req=('pork', 3)),
    Recipe('pork_to_enchanted', 'farming',
           [(Item('pork'), 160)],
           (Item('enchanted_pork'), 1),
           collection_req=('pork', 4)),
    Recipe('pork_to_enchanted_grilled', 'farming',
           [(Item('enchanted_pork'), 160)],
           (Item('enchanted_grilled_pork'), 1),
           collection_req=('pork', 7)),
    Recipe('epic_pigman_pet', 'farming',
           [(Item('enchanted_grilled_pork'), 8),
            (Item('super_enchanted_egg'), 1)],
           (get_item('pigman_pet', rarity='epic'), 1),
           collection_req=('pork', 8)),
    Recipe('pigman_sword', 'farming',
           [(Item('enchanted_grilled_pork'), 48),
            (Item('stick'), 1)],
           (get_item('pigman_sword'), 1),
           collection_req=('pork', 9)),

    Recipe('chicken_to_enchanted', 'farming',
           [(Item('chicken'), 160)],
           (Item('enchanted_chicken'), 1),
           collection_req=('chicken', 4)),
    Recipe('egg_to_enchanted', 'farming',
           [(Item('egg'), 144)],
           (Item('enchanted_egg'), 1),
           collection_req=('chicken', 5)),
    Recipe('uncommon_chicken_pet', 'farming',
           [(Item('enchanted_chicken'), 64),
            (Item('enchanted_egg'), 1)],
           (get_item('chicken_pet', rarity='uncommon'), 1),
           collection_req=('chicken', 6)),
    Recipe('epic_chicken_pet', 'farming',
           [(Item('enchanted_chicken'), 64),
            (Item('super_enchanted_egg'), 1)],
           (get_item('chicken_pet', rarity='epic'), 1),
           collection_req=('chicken', 6)),
    Recipe('enchanted_cake', 'farming',
           [(Item('enchanted_egg'), 1),
            (Item('enchanted_sugar'), 1),
            (Item('wheat'), 1)],
           (Item('enchanted_cake'), 1),
           collection_req=('chicken', 7)),
    Recipe('egg_to_super_enchanted', 'farming',
           [(Item('enchanted_egg'), 144)],
           (Item('super_enchanted_egg'), 1),
           collection_req=('chicken', 9)),

    Recipe('mutton_to_enchanted', 'farming',
           [(Item('mutton'), 160)],
           (Item('enchanted_mutton'), 1),
           collection_req=('mutton', 5)),
    Recipe('mutton_to_enchanted_cooked', 'farming',
           [(Item('enchanted_mutton'), 160)],
           (Item('enchanted_mutton_cooked'), 1),
           collection_req=('mutton', 8)),

    Recipe('rabbit_to_enchanted', 'farming',
           [(Item('rabbit'), 160)],
           (Item('enchanted_rabbit'), 1)),
    Recipe('uncommon_rabbit_pet', 'farming',
           [(Item('rabbit'), 64),
            (Item('enchanted_egg'), 1)],
           (get_item('rabbit_pet', rarity='uncommon'), 1),
           collection_req=('rabbit', 2)),
    Recipe('epic_rabbit_pet', 'farming',
           [(Item('rabbit'), 64),
            (Item('super_enchanted_egg'), 1)],
           (get_item('rabbit_pet', rarity='epic'), 1),
           collection_req=('rabbit', 2)),
    Recipe('rabbit_foot_to_enchanted', 'farming',
           [(Item('rabbit_foot'), 160)],
           (Item('enchanted_rabbit_foot'), 1),
           collection_req=('rabbit', 4)),
    Recipe('luck_book', 'farming',
           [(Item('paper'), 24),
            (Item('rabbit_hide'), 8)],
           (EnchantedBook({'luck': 4}), 1),
           collection_req=('rabbit', 5)),
    Recipe('rabbit_hide_to_enchanted', 'farming',
           [(Item('rabbit_hide'), 576)],
           (Item('enchanted_rabbit_hide'), 1),
           collection_req=('rabbit', 6)),
    Recipe('luck_of_the_sea_book', 'farming',
           [(Item('paper'), 24),
            (Item('rabbit_foot'), 16)],
           (EnchantedBook({'luck_of_the_sea': 4}), 1),
           collection_req=('rabbit', 7)),

    Recipe('nether_wart_to_enchanted', 'farming',
           [(Item('nether_wart'), 160)],
           (Item('enchanted_nether_wart'), 1),
           collection_req=('nether_wart', 4)),
    Recipe('nether_wart_to_mutant', 'farming',
           [(Item('enchanted_nether_wart'), 160)],
           (Item('mutant_nether_wart'), 1),
           collection_req=('nether_wart', 12)),
]
