from ..object import *


FARMING_MINION_RECIPES = [
    Recipe('wheat_minion_1', 'farming',
           [{'name': 'wooden_hoe'},
            {'name': 'wheat', 'count': 80}],
           {'name': 'wheat_minion', 'tier': 1},
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_2', 'farming',
           [{'name': 'wheat_minion', 'tier': 1},
            {'name': 'wheat', 'count': 160}],
           {'name': 'wheat_minion', 'tier': 2},
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_3', 'farming',
           [{'name': 'wheat_minion', 'tier': 2},
            {'name': 'wheat', 'count': 320}],
           {'name': 'wheat_minion', 'tier': 3},
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_4', 'farming',
           [{'name': 'wheat_minion', 'tier': 3},
            {'name': 'wheat', 'count': 512}],
           {'name': 'wheat_minion', 'tier': 4},
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_5', 'farming',
           [{'name': 'wheat_minion', 'tier': 4},
            {'name': 'hay_bale', 'count': 96}],
           {'name': 'wheat_minion', 'tier': 5},
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_6', 'farming',
           [{'name': 'wheat_minion', 'tier': 5},
            {'name': 'hay_bale', 'count': 192}],
           {'name': 'wheat_minion', 'tier': 6},
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_7', 'farming',
           [{'name': 'wheat_minion', 'tier': 6},
            {'name': 'hay_bale', 'count': 384}],
           {'name': 'wheat_minion', 'tier': 7},
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_8', 'farming',
           [{'name': 'wheat_minion', 'tier': 7},
            {'name': 'hay_bale', 'count': 512}],
           {'name': 'wheat_minion', 'tier': 8},
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_9', 'farming',
           [{'name': 'wheat_minion', 'tier': 8},
            {'name': 'enchanted_hay_bale', 'count': 8}],
           {'name': 'wheat_minion', 'tier': 9},
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_10', 'farming',
           [{'name': 'wheat_minion', 'tier': 9},
            {'name': 'enchanted_hay_bale', 'count': 16}],
           {'name': 'wheat_minion', 'tier': 10},
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_11', 'farming',
           [{'name': 'wheat_minion', 'tier': 10},
            {'name': 'enchanted_hay_bale', 'count': 32}],
           {'name': 'wheat_minion', 'tier': 11},
           collection_req=('wheat', 1)),
    RecipeGroup('wheat_minion', 'farming',
                ['wheat_minion_1', 'wheat_minion_2', 'wheat_minion_3',
                 'wheat_minion_4', 'wheat_minion_5', 'wheat_minion_6',
                 'wheat_minion_7', 'wheat_minion_8', 'wheat_minion_9',
                 'wheat_minion_10', 'wheat_minion_11'],
                collection_req=('wheat', 1)),

    Recipe('carrot_minion_1', 'farming',
           [{'name': 'wooden_hoe'},
            {'name': 'carrot', 'count': 128}],
           {'name': 'carrot_minion', 'tier': 1},
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_2', 'farming',
           [{'name': 'carrot_minion', 'tier': 1},
            {'name': 'carrot', 'count': 256}],
           {'name': 'carrot_minion', 'tier': 2},
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_3', 'farming',
           [{'name': 'carrot_minion', 'tier': 2},
            {'name': 'carrot', 'count': 512}],
           {'name': 'carrot_minion', 'tier': 3},
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_4', 'farming',
           [{'name': 'carrot_minion', 'tier': 3},
            {'name': 'enchanted_carrot', 'count': 8}],
           {'name': 'carrot_minion', 'tier': 4},
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_5', 'farming',
           [{'name': 'carrot_minion', 'tier': 4},
            {'name': 'enchanted_carrot', 'count': 24}],
           {'name': 'carrot_minion', 'tier': 5},
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_6', 'farming',
           [{'name': 'carrot_minion', 'tier': 5},
            {'name': 'enchanted_carrot', 'count': 64}],
           {'name': 'carrot_minion', 'tier': 6},
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_7', 'farming',
           [{'name': 'carrot_minion', 'tier': 6},
            {'name': 'enchanted_carrot', 'count': 128}],
           {'name': 'carrot_minion', 'tier': 7},
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_8', 'farming',
           [{'name': 'carrot_minion', 'tier': 7},
            {'name': 'enchanted_carrot', 'count': 256}],
           {'name': 'carrot_minion', 'tier': 8},
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_9', 'farming',
           [{'name': 'carrot_minion', 'tier': 8},
            {'name': 'enchanted_carrot', 'count': 512}],
           {'name': 'carrot_minion', 'tier': 9},
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_10', 'farming',
           [{'name': 'carrot_minion', 'tier': 9},
            {'name': 'enchanted_golden_carrot', 'count': 8}],
           {'name': 'carrot_minion', 'tier': 10},
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_11', 'farming',
           [{'name': 'carrot_minion', 'tier': 10},
            {'name': 'enchanted_golden_carrot', 'count': 16}],
           {'name': 'carrot_minion', 'tier': 11},
           collection_req=('carrot', 1)),
    RecipeGroup('carrot_minion', 'farming',
                ['carrot_minion_1', 'carrot_minion_2', 'carrot_minion_3',
                 'carrot_minion_4', 'carrot_minion_5', 'carrot_minion_6',
                 'carrot_minion_7', 'carrot_minion_8', 'carrot_minion_9',
                 'carrot_minion_10', 'carrot_minion_11'],
                collection_req=('carrot', 1)),

    Recipe('potato_minion_1', 'farming',
           [{'name': 'wooden_hoe'},
            {'name': 'potato', 'count': 128}],
           {'name': 'potato_minion', 'tier': 1},
           collection_req=('potato', 1)),
    Recipe('potato_minion_2', 'farming',
           [{'name': 'potato_minion', 'tier': 1},
            {'name': 'potato', 'count': 256}],
           {'name': 'potato_minion', 'tier': 2},
           collection_req=('potato', 1)),
    Recipe('potato_minion_3', 'farming',
           [{'name': 'potato_minion', 'tier': 2},
            {'name': 'potato', 'count': 512}],
           {'name': 'potato_minion', 'tier': 3},
           collection_req=('potato', 1)),
    Recipe('potato_minion_4', 'farming',
           [{'name': 'potato_minion', 'tier': 3},
            {'name': 'enchanted_potato', 'count': 8}],
           {'name': 'potato_minion', 'tier': 4},
           collection_req=('potato', 1)),
    Recipe('potato_minion_5', 'farming',
           [{'name': 'potato_minion', 'tier': 4},
            {'name': 'enchanted_potato', 'count': 24}],
           {'name': 'potato_minion', 'tier': 5},
           collection_req=('potato', 1)),
    Recipe('potato_minion_6', 'farming',
           [{'name': 'potato_minion', 'tier': 5},
            {'name': 'enchanted_potato', 'count': 64}],
           {'name': 'potato_minion', 'tier': 6},
           collection_req=('potato', 1)),
    Recipe('potato_minion_7', 'farming',
           [{'name': 'potato_minion', 'tier': 6},
            {'name': 'enchanted_potato', 'count': 128}],
           {'name': 'potato_minion', 'tier': 7},
           collection_req=('potato', 1)),
    Recipe('potato_minion_8', 'farming',
           [{'name': 'potato_minion', 'tier': 7},
            {'name': 'enchanted_potato', 'count': 256}],
           {'name': 'potato_minion', 'tier': 8},
           collection_req=('potato', 1)),
    Recipe('potato_minion_9', 'farming',
           [{'name': 'potato_minion', 'tier': 8},
            {'name': 'enchanted_potato', 'count': 512}],
           {'name': 'potato_minion', 'tier': 9},
           collection_req=('potato', 1)),
    Recipe('potato_minion_10', 'farming',
           [{'name': 'potato_minion', 'tier': 9},
            {'name': 'enchanted_baked_potato', 'count': 8}],
           {'name': 'potato_minion', 'tier': 10},
           collection_req=('potato', 1)),
    Recipe('potato_minion_11', 'farming',
           [{'name': 'potato_minion', 'tier': 10},
            {'name': 'enchanted_baked_potato', 'count': 16}],
           {'name': 'potato_minion', 'tier': 11},
           collection_req=('potato', 1)),
    RecipeGroup('potato_minion', 'farming',
                ['potato_minion_1', 'potato_minion_2', 'potato_minion_3',
                 'potato_minion_4', 'potato_minion_5', 'potato_minion_6',
                 'potato_minion_7', 'potato_minion_8', 'potato_minion_9',
                 'potato_minion_10', 'potato_minion_11'],
                collection_req=('potato', 1)),

    Recipe('pumpkin_minion_1', 'farming',
           [{'name': 'wooden_hoe'},
            {'name': 'pumpkin', 'count': 80}],
           {'name': 'pumpkin_minion', 'tier': 1},
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_2', 'farming',
           [{'name': 'pumpkin_minion', 'tier': 1},
            {'name': 'pumpkin', 'count': 160}],
           {'name': 'pumpkin_minion', 'tier': 2},
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_3', 'farming',
           [{'name': 'pumpkin_minion', 'tier': 2},
            {'name': 'pumpkin', 'count': 320}],
           {'name': 'pumpkin_minion', 'tier': 3},
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_4', 'farming',
           [{'name': 'pumpkin_minion', 'tier': 3},
            {'name': 'pumpkin', 'count': 512}],
           {'name': 'pumpkin_minion', 'tier': 4},
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_5', 'farming',
           [{'name': 'pumpkin_minion', 'tier': 4},
            {'name': 'enchanted_pumpkin', 'count': 8}],
           {'name': 'pumpkin_minion', 'tier': 5},
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_6', 'farming',
           [{'name': 'pumpkin_minion', 'tier': 5},
            {'name': 'enchanted_pumpkin', 'count': 16}],
           {'name': 'pumpkin_minion', 'tier': 6},
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_7', 'farming',
           [{'name': 'pumpkin_minion', 'tier': 6},
            {'name': 'enchanted_pumpkin', 'count': 32}],
           {'name': 'pumpkin_minion', 'tier': 7},
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_8', 'farming',
           [{'name': 'pumpkin_minion', 'tier': 7},
            {'name': 'enchanted_pumpkin', 'count': 64}],
           {'name': 'pumpkin_minion', 'tier': 8},
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_9', 'farming',
           [{'name': 'pumpkin_minion', 'tier': 8},
            {'name': 'enchanted_pumpkin', 'count': 128}],
           {'name': 'pumpkin_minion', 'tier': 9},
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_10', 'farming',
           [{'name': 'pumpkin_minion', 'tier': 9},
            {'name': 'enchanted_pumpkin', 'count': 256}],
           {'name': 'pumpkin_minion', 'tier': 10},
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_11', 'farming',
           [{'name': 'pumpkin_minion', 'tier': 10},
            {'name': 'enchanted_pumpkin', 'count': 512}],
           {'name': 'pumpkin_minion', 'tier': 11},
           collection_req=('pumpkin', 1)),
    RecipeGroup('pumpkin_minion', 'farming',
                ['pumpkin_minion_1', 'pumpkin_minion_2', 'pumpkin_minion_3',
                 'pumpkin_minion_4', 'pumpkin_minion_5', 'pumpkin_minion_6',
                 'pumpkin_minion_7', 'pumpkin_minion_8', 'pumpkin_minion_9',
                 'pumpkin_minion_10', 'pumpkin_minion_11'],
                collection_req=('pumpkin', 1)),

    Recipe('melon_minion_1', 'farming',
           [{'name': 'wooden_hoe'},
            {'name': 'melon', 'count': 256}],
           {'name': 'melon_minion', 'tier': 1},
           collection_req=('melon', 1)),
    Recipe('melon_minion_2', 'farming',
           [{'name': 'melon_minion', 'tier': 1},
            {'name': 'melon', 'count': 512}],
           {'name': 'melon_minion', 'tier': 2},
           collection_req=('melon', 1)),
    Recipe('melon_minion_3', 'farming',
           [{'name': 'melon_minion', 'tier': 2},
            {'name': 'melon_block', 'count': 128}],
           {'name': 'melon_minion', 'tier': 3},
           collection_req=('melon', 1)),
    Recipe('melon_minion_4', 'farming',
           [{'name': 'melon_minion', 'tier': 3},
            {'name': 'melon_block', 'count': 256}],
           {'name': 'melon_minion', 'tier': 4},
           collection_req=('melon', 1)),
    Recipe('melon_minion_5', 'farming',
           [{'name': 'melon_minion', 'tier': 4},
            {'name': 'melon_block', 'count': 512}],
           {'name': 'melon_minion', 'tier': 5},
           collection_req=('melon', 1)),
    Recipe('melon_minion_6', 'farming',
           [{'name': 'melon_minion', 'tier': 5},
            {'name': 'enchanted_melon', 'count': 64}],
           {'name': 'melon_minion', 'tier': 6},
           collection_req=('melon', 1)),
    Recipe('melon_minion_7', 'farming',
           [{'name': 'melon_minion', 'tier': 6},
            {'name': 'enchanted_melon', 'count': 128}],
           {'name': 'melon_minion', 'tier': 7},
           collection_req=('melon', 1)),
    Recipe('melon_minion_8', 'farming',
           [{'name': 'melon_minion', 'tier': 7},
            {'name': 'enchanted_melon', 'count': 256}],
           {'name': 'melon_minion', 'tier': 8},
           collection_req=('melon', 1)),
    Recipe('melon_minion_9', 'farming',
           [{'name': 'melon_minion', 'tier': 8},
            {'name': 'enchanted_melon', 'count': 512}],
           {'name': 'melon_minion', 'tier': 9},
           collection_req=('melon', 1)),
    Recipe('melon_minion_10', 'farming',
           [{'name': 'melon_minion', 'tier': 9},
            {'name': 'enchanted_melon_block', 'count': 8}],
           {'name': 'melon_minion', 'tier': 10},
           collection_req=('melon', 1)),
    Recipe('melon_minion_11', 'farming',
           [{'name': 'melon_minion', 'tier': 10},
            {'name': 'enchanted_melon_block', 'count': 16}],
           {'name': 'melon_minion', 'tier': 11},
           collection_req=('melon', 1)),
    RecipeGroup('melon_minion', 'farming',
                ['melon_minion_1', 'melon_minion_2', 'melon_minion_3',
                 'melon_minion_4', 'melon_minion_5', 'melon_minion_6',
                 'melon_minion_7', 'melon_minion_8', 'melon_minion_9',
                 'melon_minion_10', 'melon_minion_11'],
                collection_req=('melon', 1)),

    Recipe('mushroom_minion_1', 'farming',
           [{'name': 'wooden_hoe'},
            {'name': 'mushroom_block', 'count': 80}],
           {'name': 'mushroom_minion', 'tier': 1},
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_2', 'farming',
           [{'name': 'mushroom_minion', 'tier': 1},
            {'name': 'mushroom_block', 'count': 160}],
           {'name': 'mushroom_minion', 'tier': 2},
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_3', 'farming',
           [{'name': 'mushroom_minion', 'tier': 2},
            {'name': 'mushroom_block', 'count': 320}],
           {'name': 'mushroom_minion', 'tier': 3},
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_4', 'farming',
           [{'name': 'mushroom_minion', 'tier': 3},
            {'name': 'mushroom_block', 'count': 512}],
           {'name': 'mushroom_minion', 'tier': 4},
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_5', 'farming',
           [{'name': 'mushroom_minion', 'tier': 4},
            {'name': 'enchanted_mushroom', 'count': 8}],
           {'name': 'mushroom_minion', 'tier': 5},
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_6', 'farming',
           [{'name': 'mushroom_minion', 'tier': 5},
            {'name': 'enchanted_mushroom', 'count': 16}],
           {'name': 'mushroom_minion', 'tier': 6},
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_7', 'farming',
           [{'name': 'mushroom_minion', 'tier': 6},
            {'name': 'enchanted_mushroom', 'count': 32}],
           {'name': 'mushroom_minion', 'tier': 7},
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_8', 'farming',
           [{'name': 'mushroom_minion', 'tier': 7},
            {'name': 'enchanted_mushroom', 'count': 64}],
           {'name': 'mushroom_minion', 'tier': 8},
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_9', 'farming',
           [{'name': 'mushroom_minion', 'tier': 8},
            {'name': 'enchanted_mushroom', 'count': 128}],
           {'name': 'mushroom_minion', 'tier': 9},
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_10', 'farming',
           [{'name': 'mushroom_minion', 'tier': 9},
            {'name': 'enchanted_mushroom', 'count': 256}],
           {'name': 'mushroom_minion', 'tier': 10},
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_11', 'farming',
           [{'name': 'mushroom_minion', 'tier': 10},
            {'name': 'enchanted_mushroom', 'count': 512}],
           {'name': 'mushroom_minion', 'tier': 11},
           collection_req=('mushroom', 1)),
    RecipeGroup('mushroom_minion', 'farming',
                ['mushroom_minion_1', 'mushroom_minion_2', 'mushroom_minion_3',
                 'mushroom_minion_4', 'mushroom_minion_5', 'mushroom_minion_6',
                 'mushroom_minion_7', 'mushroom_minion_8', 'mushroom_minion_9',
                 'mushroom_minion_10', 'mushroom_minion_11'],
                collection_req=('mushroom', 1)),

    Recipe('cocoa_minion_1', 'farming',
           [{'name': 'wooden_hoe'},
            {'name': 'cocoa', 'count': 80}],
           {'name': 'cocoa_minion', 'tier': 1},
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_2', 'farming',
           [{'name': 'cocoa_minion', 'tier': 1},
            {'name': 'cocoa', 'count': 160}],
           {'name': 'cocoa_minion', 'tier': 2},
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_3', 'farming',
           [{'name': 'cocoa_minion', 'tier': 2},
            {'name': 'cocoa', 'count': 320}],
           {'name': 'cocoa_minion', 'tier': 3},
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_4', 'farming',
           [{'name': 'cocoa_minion', 'tier': 3},
            {'name': 'cocoa', 'count': 512}],
           {'name': 'cocoa_minion', 'tier': 4},
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_5', 'farming',
           [{'name': 'cocoa_minion', 'tier': 4},
            {'name': 'enchanted_cocoa', 'count': 8}],
           {'name': 'cocoa_minion', 'tier': 5},
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_6', 'farming',
           [{'name': 'cocoa_minion', 'tier': 5},
            {'name': 'enchanted_cocoa', 'count': 24}],
           {'name': 'cocoa_minion', 'tier': 6},
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_7', 'farming',
           [{'name': 'cocoa_minion', 'tier': 6},
            {'name': 'enchanted_cocoa', 'count': 64}],
           {'name': 'cocoa_minion', 'tier': 7},
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_8', 'farming',
           [{'name': 'cocoa_minion', 'tier': 7},
            {'name': 'enchanted_cocoa', 'count': 128}],
           {'name': 'cocoa_minion', 'tier': 8},
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_9', 'farming',
           [{'name': 'cocoa_minion', 'tier': 8},
            {'name': 'enchanted_cocoa', 'count': 256}],
           {'name': 'cocoa_minion', 'tier': 9},
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_10', 'farming',
           [{'name': 'cocoa_minion', 'tier': 9},
            {'name': 'enchanted_cocoa', 'count': 512}],
           {'name': 'cocoa_minion', 'tier': 10},
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_11', 'farming',
           [{'name': 'cocoa_minion', 'tier': 10},
            {'name': 'enchanted_cookie', 'count': 8}],
           {'name': 'cocoa_minion', 'tier': 11},
           collection_req=('cocoa', 1)),
    RecipeGroup('cocoa_minion', 'farming',
                ['cocoa_minion_1', 'cocoa_minion_2', 'cocoa_minion_3',
                 'cocoa_minion_4', 'cocoa_minion_5', 'cocoa_minion_6',
                 'cocoa_minion_7', 'cocoa_minion_8', 'cocoa_minion_9',
                 'cocoa_minion_10', 'cocoa_minion_11'],
                collection_req=('cocoa', 1)),

    Recipe('cactus_minion_1', 'farming',
           [{'name': 'wooden_hoe'},
            {'name': 'cactus', 'count': 128}],
           {'name': 'cactus_minion', 'tier': 1},
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_2', 'farming',
           [{'name': 'cactus_minion', 'tier': 1},
            {'name': 'cactus', 'count': 256}],
           {'name': 'cactus_minion', 'tier': 2},
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_3', 'farming',
           [{'name': 'cactus_minion', 'tier': 2},
            {'name': 'cactus', 'count': 512}],
           {'name': 'cactus_minion', 'tier': 3},
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_4', 'farming',
           [{'name': 'cactus_minion', 'tier': 3},
            {'name': 'enchanted_cactus_green', 'count': 8}],
           {'name': 'cactus_minion', 'tier': 4},
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_5', 'farming',
           [{'name': 'cactus_minion', 'tier': 4},
            {'name': 'enchanted_cactus_green', 'count': 24}],
           {'name': 'cactus_minion', 'tier': 5},
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_6', 'farming',
           [{'name': 'cactus_minion', 'tier': 5},
            {'name': 'enchanted_cactus_green', 'count': 64}],
           {'name': 'cactus_minion', 'tier': 6},
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_7', 'farming',
           [{'name': 'cactus_minion', 'tier': 6},
            {'name': 'enchanted_cactus_green', 'count': 128}],
           {'name': 'cactus_minion', 'tier': 7},
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_8', 'farming',
           [{'name': 'cactus_minion', 'tier': 7},
            {'name': 'enchanted_cactus_green', 'count': 256}],
           {'name': 'cactus_minion', 'tier': 8},
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_9', 'farming',
           [{'name': 'cactus_minion', 'tier': 8},
            {'name': 'enchanted_cactus_green', 'count': 512}],
           {'name': 'cactus_minion', 'tier': 9},
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_10', 'farming',
           [{'name': 'cactus_minion', 'tier': 9},
            {'name': 'enchanted_cactus', 'count': 8}],
           {'name': 'cactus_minion', 'tier': 10},
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_11', 'farming',
           [{'name': 'cactus_minion', 'tier': 10},
            {'name': 'enchanted_cactus', 'count': 16}],
           {'name': 'cactus_minion', 'tier': 11},
           collection_req=('cactus', 1)),
    RecipeGroup('cactus_minion', 'farming',
                ['cactus_minion_1', 'cactus_minion_2', 'cactus_minion_3',
                 'cactus_minion_4', 'cactus_minion_5', 'cactus_minion_6',
                 'cactus_minion_7', 'cactus_minion_8', 'cactus_minion_9',
                 'cactus_minion_10', 'cactus_minion_11'],
                collection_req=('cactus', 1)),

    Recipe('sugar_cane_minion_1', 'farming',
           [{'name': 'wooden_hoe'},
            {'name': 'sugar_cane', 'count': 128}],
           {'name': 'sugar_cane_minion', 'tier': 1},
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_2', 'farming',
           [{'name': 'sugar_cane_minion', 'tier': 1},
            {'name': 'sugar_cane', 'count': 256}],
           {'name': 'sugar_cane_minion', 'tier': 2},
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_3', 'farming',
           [{'name': 'sugar_cane_minion', 'tier': 2},
            {'name': 'sugar_cane', 'count': 512}],
           {'name': 'sugar_cane_minion', 'tier': 3},
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_4', 'farming',
           [{'name': 'sugar_cane_minion', 'tier': 3},
            {'name': 'enchanted_sugar', 'count': 8}],
           {'name': 'sugar_cane_minion', 'tier': 4},
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_5', 'farming',
           [{'name': 'sugar_cane_minion', 'tier': 4},
            {'name': 'enchanted_sugar', 'count': 24}],
           {'name': 'sugar_cane_minion', 'tier': 5},
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_6', 'farming',
           [{'name': 'sugar_cane_minion', 'tier': 5},
            {'name': 'enchanted_sugar', 'count': 64}],
           {'name': 'sugar_cane_minion', 'tier': 6},
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_7', 'farming',
           [{'name': 'sugar_cane_minion', 'tier': 6},
            {'name': 'enchanted_sugar', 'count': 128}],
           {'name': 'sugar_cane_minion', 'tier': 7},
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_8', 'farming',
           [{'name': 'sugar_cane_minion', 'tier': 7},
            {'name': 'enchanted_sugar', 'count': 256}],
           {'name': 'sugar_cane_minion', 'tier': 8},
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_9', 'farming',
           [{'name': 'sugar_cane_minion', 'tier': 8},
            {'name': 'enchanted_sugar', 'count': 512}],
           {'name': 'sugar_cane_minion', 'tier': 9},
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_10', 'farming',
           [{'name': 'sugar_cane_minion', 'tier': 9},
            {'name': 'enchanted_sugar_cane', 'count': 8}],
           {'name': 'sugar_cane_minion', 'tier': 10},
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_11', 'farming',
           [{'name': 'sugar_cane_minion', 'tier': 10},
            {'name': 'enchanted_sugar_cane', 'count': 16}],
           {'name': 'sugar_cane_minion', 'tier': 11},
           collection_req=('sugar_cane', 1)),
    RecipeGroup('sugar_cane_minion', 'farming',
                ['sugar_cane_minion_1', 'sugar_cane_minion_2',
                 'sugar_cane_minion_3', 'sugar_cane_minion_4',
                 'sugar_cane_minion_5', 'sugar_cane_minion_6',
                 'sugar_cane_minion_7', 'sugar_cane_minion_8',
                 'sugar_cane_minion_9', 'sugar_cane_minion_10',
                 'sugar_cane_minion_11'],
                collection_req=('sugar_cane', 1)),

    Recipe('cow_minion_1', 'farming',
           [{'name': 'wooden_sword'},
            {'name': 'beef', 'count': 64}],
           {'name': 'cow_minion', 'tier': 1},
           collection_req=('leather', 1)),
    Recipe('cow_minion_2', 'farming',
           [{'name': 'cow_minion', 'tier': 1},
            {'name': 'beef', 'count': 128}],
           {'name': 'cow_minion', 'tier': 2},
           collection_req=('leather', 1)),
    Recipe('cow_minion_3', 'farming',
           [{'name': 'cow_minion', 'tier': 2},
            {'name': 'beef', 'count': 256}],
           {'name': 'cow_minion', 'tier': 3},
           collection_req=('leather', 1)),
    Recipe('cow_minion_4', 'farming',
           [{'name': 'cow_minion', 'tier': 3},
            {'name': 'beef', 'count': 512}],
           {'name': 'cow_minion', 'tier': 4},
           collection_req=('leather', 1)),
    Recipe('cow_minion_5', 'farming',
           [{'name': 'cow_minion', 'tier': 4},
            {'name': 'enchanted_beef', 'count': 8}],
           {'name': 'cow_minion', 'tier': 5},
           collection_req=('leather', 1)),
    Recipe('cow_minion_6', 'farming',
           [{'name': 'cow_minion', 'tier': 5},
            {'name': 'enchanted_beef', 'count': 16}],
           {'name': 'cow_minion', 'tier': 6},
           collection_req=('leather', 1)),
    Recipe('cow_minion_7', 'farming',
           [{'name': 'cow_minion', 'tier': 6},
            {'name': 'enchanted_beef', 'count': 32}],
           {'name': 'cow_minion', 'tier': 7},
           collection_req=('leather', 1)),
    Recipe('cow_minion_8', 'farming',
           [{'name': 'cow_minion', 'tier': 7},
            {'name': 'enchanted_beef', 'count': 64}],
           {'name': 'cow_minion', 'tier': 8},
           collection_req=('leather', 1)),
    Recipe('cow_minion_9', 'farming',
           [{'name': 'cow_minion', 'tier': 8},
            {'name': 'enchanted_beef', 'count': 128}],
           {'name': 'cow_minion', 'tier': 9},
           collection_req=('leather', 1)),
    Recipe('cow_minion_10', 'farming',
           [{'name': 'cow_minion', 'tier': 9},
            {'name': 'enchanted_beef', 'count': 256}],
           {'name': 'cow_minion', 'tier': 10},
           collection_req=('leather', 1)),
    Recipe('cow_minion_11', 'farming',
           [{'name': 'cow_minion', 'tier': 10},
            {'name': 'enchanted_beef', 'count': 512}],
           {'name': 'cow_minion', 'tier': 11},
           collection_req=('leather', 1)),
    RecipeGroup('cow_minion', 'farming',
                ['cow_minion_1', 'cow_minion_2', 'cow_minion_3', 'cow_minion_4',
                 'cow_minion_5', 'cow_minion_6', 'cow_minion_7', 'cow_minion_8',
                 'cow_minion_9', 'cow_minion_10', 'cow_minion_11'],
                collection_req=('leather', 1)),

    Recipe('pig_minion_1', 'farming',
           [{'name': 'wooden_sword'},
            {'name': 'pork', 'count': 64}],
           {'name': 'pig_minion', 'tier': 1},
           collection_req=('pork', 1)),
    Recipe('pig_minion_2', 'farming',
           [{'name': 'pig_minion', 'tier': 1},
            {'name': 'pork', 'count': 128}],
           {'name': 'pig_minion', 'tier': 2},
           collection_req=('pork', 1)),
    Recipe('pig_minion_3', 'farming',
           [{'name': 'pig_minion', 'tier': 2},
            {'name': 'pork', 'count': 256}],
           {'name': 'pig_minion', 'tier': 3},
           collection_req=('pork', 1)),
    Recipe('pig_minion_4', 'farming',
           [{'name': 'pig_minion', 'tier': 3},
            {'name': 'pork', 'count': 512}],
           {'name': 'pig_minion', 'tier': 4},
           collection_req=('pork', 1)),
    Recipe('pig_minion_5', 'farming',
           [{'name': 'pig_minion', 'tier': 4},
            {'name': 'enchanted_pork', 'count': 8}],
           {'name': 'pig_minion', 'tier': 5},
           collection_req=('pork', 1)),
    Recipe('pig_minion_6', 'farming',
           [{'name': 'pig_minion', 'tier': 5},
            {'name': 'enchanted_pork', 'count': 24}],
           {'name': 'pig_minion', 'tier': 6},
           collection_req=('pork', 1)),
    Recipe('pig_minion_7', 'farming',
           [{'name': 'pig_minion', 'tier': 6},
            {'name': 'enchanted_pork', 'count': 64}],
           {'name': 'pig_minion', 'tier': 7},
           collection_req=('pork', 1)),
    Recipe('pig_minion_8', 'farming',
           [{'name': 'pig_minion', 'tier': 7},
            {'name': 'enchanted_pork', 'count': 128}],
           {'name': 'pig_minion', 'tier': 8},
           collection_req=('pork', 1)),
    Recipe('pig_minion_9', 'farming',
           [{'name': 'pig_minion', 'tier': 8},
            {'name': 'enchanted_pork', 'count': 256}],
           {'name': 'pig_minion', 'tier': 9},
           collection_req=('pork', 1)),
    Recipe('pig_minion_10', 'farming',
           [{'name': 'pig_minion', 'tier': 9},
            {'name': 'enchanted_pork', 'count': 512}],
           {'name': 'pig_minion', 'tier': 10},
           collection_req=('pork', 1)),
    Recipe('pig_minion_11', 'farming',
           [{'name': 'pig_minion', 'tier': 10},
            {'name': 'enchanted_grilled_pork', 'count': 8}],
           {'name': 'pig_minion', 'tier': 11},
           collection_req=('pork', 1)),
    RecipeGroup('pig_minion', 'farming',
                ['pig_minion_1', 'pig_minion_2', 'pig_minion_3', 'pig_minion_4',
                 'pig_minion_5', 'pig_minion_6', 'pig_minion_7', 'pig_minion_8',
                 'pig_minion_9', 'pig_minion_10', 'pig_minion_11'],
                collection_req=('pork', 1)),

    Recipe('chicken_minion_1', 'farming',
           [{'name': 'wooden_sword'},
            {'name': 'chicken', 'count': 64}],
           {'name': 'chicken_minion', 'tier': 1},
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_2', 'farming',
           [{'name': 'chicken_minion', 'tier': 1},
            {'name': 'chicken', 'count': 128}],
           {'name': 'chicken_minion', 'tier': 2},
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_3', 'farming',
           [{'name': 'chicken_minion', 'tier': 2},
            {'name': 'chicken', 'count': 256}],
           {'name': 'chicken_minion', 'tier': 3},
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_4', 'farming',
           [{'name': 'chicken_minion', 'tier': 3},
            {'name': 'chicken', 'count': 512}],
           {'name': 'chicken_minion', 'tier': 4},
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_5', 'farming',
           [{'name': 'chicken_minion', 'tier': 4},
            {'name': 'enchanted_chicken', 'count': 8}],
           {'name': 'chicken_minion', 'tier': 5},
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_6', 'farming',
           [{'name': 'chicken_minion', 'tier': 5},
            {'name': 'enchanted_chicken', 'count': 16}],
           {'name': 'chicken_minion', 'tier': 6},
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_7', 'farming',
           [{'name': 'chicken_minion', 'tier': 6},
            {'name': 'enchanted_chicken', 'count': 32}],
           {'name': 'chicken_minion', 'tier': 7},
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_8', 'farming',
           [{'name': 'chicken_minion', 'tier': 7},
            {'name': 'enchanted_chicken', 'count': 64}],
           {'name': 'chicken_minion', 'tier': 8},
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_9', 'farming',
           [{'name': 'chicken_minion', 'tier': 8},
            {'name': 'enchanted_chicken', 'count': 128}],
           {'name': 'chicken_minion', 'tier': 9},
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_10', 'farming',
           [{'name': 'chicken_minion', 'tier': 9},
            {'name': 'enchanted_chicken', 'count': 256}],
           {'name': 'chicken_minion', 'tier': 10},
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_11', 'farming',
           [{'name': 'chicken_minion', 'tier': 10},
            {'name': 'enchanted_chicken', 'count': 512}],
           {'name': 'chicken_minion', 'tier': 11},
           collection_req=('chicken', 1)),
    RecipeGroup('chicken_minion', 'farming',
                ['chicken_minion_1', 'chicken_minion_2', 'chicken_minion_3',
                 'chicken_minion_4', 'chicken_minion_5', 'chicken_minion_6',
                 'chicken_minion_7', 'chicken_minion_8', 'chicken_minion_9',
                 'chicken_minion_10', 'chicken_minion_11'],
                collection_req=('chicken', 1)),

    Recipe('sheep_minion_1', 'farming',
           [{'name': 'wooden_sword'},
            {'name': 'mutton', 'count': 64}],
           {'name': 'sheep_minion', 'tier': 1},
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_2', 'farming',
           [{'name': 'sheep_minion', 'tier': 1},
            {'name': 'mutton', 'count': 128}],
           {'name': 'sheep_minion', 'tier': 2},
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_3', 'farming',
           [{'name': 'sheep_minion', 'tier': 2},
            {'name': 'mutton', 'count': 256}],
           {'name': 'sheep_minion', 'tier': 3},
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_4', 'farming',
           [{'name': 'sheep_minion', 'tier': 3},
            {'name': 'mutton', 'count': 512}],
           {'name': 'sheep_minion', 'tier': 4},
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_5', 'farming',
           [{'name': 'sheep_minion', 'tier': 4},
            {'name': 'enchanted_mutton', 'count': 8}],
           {'name': 'sheep_minion', 'tier': 5},
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_6', 'farming',
           [{'name': 'sheep_minion', 'tier': 5},
            {'name': 'enchanted_mutton', 'count': 24}],
           {'name': 'sheep_minion', 'tier': 6},
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_7', 'farming',
           [{'name': 'sheep_minion', 'tier': 6},
            {'name': 'enchanted_mutton', 'count': 64}],
           {'name': 'sheep_minion', 'tier': 7},
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_8', 'farming',
           [{'name': 'sheep_minion', 'tier': 7},
            {'name': 'enchanted_mutton', 'count': 128}],
           {'name': 'sheep_minion', 'tier': 8},
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_9', 'farming',
           [{'name': 'sheep_minion', 'tier': 8},
            {'name': 'enchanted_mutton', 'count': 256}],
           {'name': 'sheep_minion', 'tier': 9},
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_10', 'farming',
           [{'name': 'sheep_minion', 'tier': 9},
            {'name': 'enchanted_mutton', 'count': 512}],
           {'name': 'sheep_minion', 'tier': 10},
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_11', 'farming',
           [{'name': 'sheep_minion', 'tier': 10},
            {'name': 'enchanted_cooked_mutton', 'count': 8}],
           {'name': 'sheep_minion', 'tier': 11},
           collection_req=('mutton', 1)),
    RecipeGroup('sheep_minion', 'farming',
                ['sheep_minion_1', 'sheep_minion_2', 'sheep_minion_3',
                 'sheep_minion_4', 'sheep_minion_5', 'sheep_minion_6',
                 'sheep_minion_7', 'sheep_minion_8', 'sheep_minion_9',
                 'sheep_minion_10', 'sheep_minion_11'],
                collection_req=('mutton', 1)),

    Recipe('rabbit_minion_1', 'farming',
           [{'name': 'wooden_sword'},
            {'name': 'rabbit', 'count': 64}],
           {'name': 'rabbit_minion', 'tier': 1},
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_2', 'farming',
           [{'name': 'rabbit_minion', 'tier': 1},
            {'name': 'rabbit', 'count': 128}],
           {'name': 'rabbit_minion', 'tier': 2},
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_3', 'farming',
           [{'name': 'rabbit_minion', 'tier': 2},
            {'name': 'rabbit', 'count': 256}],
           {'name': 'rabbit_minion', 'tier': 3},
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_4', 'farming',
           [{'name': 'rabbit_minion', 'tier': 3},
            {'name': 'rabbit', 'count': 512}],
           {'name': 'rabbit_minion', 'tier': 4},
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_5', 'farming',
           [{'name': 'rabbit_minion', 'tier': 4},
            {'name': 'enchanted_rabbit_foot', 'count': 32}],
           {'name': 'rabbit_minion', 'tier': 5},
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_6', 'farming',
           [{'name': 'rabbit_minion', 'tier': 5},
            {'name': 'enchanted_rabbit_foot', 'count': 64}],
           {'name': 'rabbit_minion', 'tier': 6},
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_7', 'farming',
           [{'name': 'rabbit_minion', 'tier': 6},
            {'name': 'enchanted_rabbit_foot', 'count': 128}],
           {'name': 'rabbit_minion', 'tier': 7},
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_8', 'farming',
           [{'name': 'rabbit_minion', 'tier': 7},
            {'name': 'enchanted_rabbit_foot', 'count': 256}],
           {'name': 'rabbit_minion', 'tier': 8},
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_9', 'farming',
           [{'name': 'rabbit_minion', 'tier': 8},
            {'name': 'enchanted_rabbit_foot', 'count': 512}],
           {'name': 'rabbit_minion', 'tier': 9},
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_10', 'farming',
           [{'name': 'rabbit_minion', 'tier': 9},
            {'name': 'enchanted_rabbit_hide', 'count': 256}],
           {'name': 'rabbit_minion', 'tier': 10},
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_11', 'farming',
           [{'name': 'rabbit_minion', 'tier': 10},
            {'name': 'enchanted_rabbit_hide', 'count': 512}],
           {'name': 'rabbit_minion', 'tier': 11},
           collection_req=('rabbit', 1)),
    RecipeGroup('rabbit_minion', 'farming',
                ['rabbit_minion_1', 'rabbit_minion_2', 'rabbit_minion_3',
                 'rabbit_minion_4', 'rabbit_minion_5', 'rabbit_minion_6',
                 'rabbit_minion_7', 'rabbit_minion_8', 'rabbit_minion_9',
                 'rabbit_minion_10', 'rabbit_minion_11'],
                collection_req=('rabbit', 1)),

    Recipe('nether_wart_minion_1', 'farming',
           [{'name': 'wooden_hoe'},
            {'name': 'nether_wart', 'count': 80}],
           {'name': 'nether_wart_minion', 'tier': 1},
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_2', 'farming',
           [{'name': 'nether_wart_minion', 'tier': 1},
            {'name': 'nether_wart', 'count': 160}],
           {'name': 'nether_wart_minion', 'tier': 2},
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_3', 'farming',
           [{'name': 'nether_wart_minion', 'tier': 2},
            {'name': 'nether_wart', 'count': 320}],
           {'name': 'nether_wart_minion', 'tier': 3},
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_4', 'farming',
           [{'name': 'nether_wart_minion', 'tier': 3},
            {'name': 'nether_wart', 'count': 512}],
           {'name': 'nether_wart_minion', 'tier': 4},
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_5', 'farming',
           [{'name': 'nether_wart_minion', 'tier': 4},
            {'name': 'enchanted_nether_wart', 'count': 8}],
           {'name': 'nether_wart_minion', 'tier': 5},
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_6', 'farming',
           [{'name': 'nether_wart_minion', 'tier': 5},
            {'name': 'enchanted_nether_wart', 'count': 16}],
           {'name': 'nether_wart_minion', 'tier': 6},
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_7', 'farming',
           [{'name': 'nether_wart_minion', 'tier': 6},
            {'name': 'enchanted_nether_wart', 'count': 32}],
           {'name': 'nether_wart_minion', 'tier': 7},
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_8', 'farming',
           [{'name': 'nether_wart_minion', 'tier': 7},
            {'name': 'enchanted_nether_wart', 'count': 64}],
           {'name': 'nether_wart_minion', 'tier': 8},
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_9', 'farming',
           [{'name': 'nether_wart_minion', 'tier': 8},
            {'name': 'enchanted_nether_wart', 'count': 128}],
           {'name': 'nether_wart_minion', 'tier': 9},
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_10', 'farming',
           [{'name': 'nether_wart_minion', 'tier': 9},
            {'name': 'enchanted_nether_wart', 'count': 256}],
           {'name': 'nether_wart_minion', 'tier': 10},
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_11', 'farming',
           [{'name': 'nether_wart_minion', 'tier': 10},
            {'name': 'enchanted_nether_wart', 'count': 512}],
           {'name': 'nether_wart_minion', 'tier': 11},
           collection_req=('nether_wart', 1)),
    RecipeGroup('nether_wart_minion', 'farming',
                ['nether_wart_minion_1', 'nether_wart_minion_2',
                 'nether_wart_minion_3', 'nether_wart_minion_4',
                 'nether_wart_minion_5', 'nether_wart_minion_6',
                 'nether_wart_minion_7', 'nether_wart_minion_8',
                 'nether_wart_minion_9', 'nether_wart_minion_10',
                 'nether_wart_minion_11'],
                collection_req=('nether_wart', 1)),
]
