from ..item import get_item
from ..object import *


FARMING_MINION_RECIPES = [
    Recipe('wheat_minion_1', 'farming',
           [(get_item('wooden_hoe'), 1),
            (Item('wheat'), 80)],
           (get_item('wheat_minion', tier=1), 1),
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_2', 'farming',
           [(get_item('wheat_minion', tier=1), 1),
            (Item('wheat'), 160)],
           (get_item('wheat_minion', tier=2), 1),
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_3', 'farming',
           [(get_item('wheat_minion', tier=2), 1),
            (Item('wheat'), 320)],
           (get_item('wheat_minion', tier=3), 1),
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_4', 'farming',
           [(get_item('wheat_minion', tier=3), 1),
            (Item('wheat'), 512)],
           (get_item('wheat_minion', tier=4), 1),
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_5', 'farming',
           [(get_item('wheat_minion', tier=4), 1),
            (Item('hay_bale'), 96)],
           (get_item('wheat_minion', tier=5), 1),
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_6', 'farming',
           [(get_item('wheat_minion', tier=5), 1),
            (Item('hay_bale'), 192)],
           (get_item('wheat_minion', tier=6), 1),
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_7', 'farming',
           [(get_item('wheat_minion', tier=6), 1),
            (Item('hay_bale'), 384)],
           (get_item('wheat_minion', tier=7), 1),
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_8', 'farming',
           [(get_item('wheat_minion', tier=7), 1),
            (Item('hay_bale'), 512)],
           (get_item('wheat_minion', tier=8), 1),
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_9', 'farming',
           [(get_item('wheat_minion', tier=8), 1),
            (Item('enchanted_hay_bale'), 8)],
           (get_item('wheat_minion', tier=9), 1),
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_10', 'farming',
           [(get_item('wheat_minion', tier=9), 1),
            (Item('enchanted_hay_bale'), 16)],
           (get_item('wheat_minion', tier=10), 1),
           collection_req=('wheat', 1)),
    Recipe('wheat_minion_11', 'farming',
           [(get_item('wheat_minion', tier=10), 1),
            (Item('enchanted_hay_bale'), 32)],
           (get_item('wheat_minion', tier=11), 1),
           collection_req=('wheat', 1)),
    RecipeGroup('wheat_minion', 'farming',
                ['wheat_minion_1', 'wheat_minion_2', 'wheat_minion_3',
                 'wheat_minion_4', 'wheat_minion_5', 'wheat_minion_6',
                 'wheat_minion_7', 'wheat_minion_8', 'wheat_minion_9',
                 'wheat_minion_10', 'wheat_minion_11'],
                collection_req=('wheat', 1)),

    Recipe('carrot_minion_1', 'farming',
           [(get_item('wooden_hoe'), 1),
            (Item('carrot'), 128)],
           (get_item('carrot_minion', tier=1), 1),
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_2', 'farming',
           [(get_item('carrot_minion', tier=1), 1),
            (Item('carrot'), 256)],
           (get_item('carrot_minion', tier=2), 1),
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_3', 'farming',
           [(get_item('carrot_minion', tier=2), 1),
            (Item('carrot'), 512)],
           (get_item('carrot_minion', tier=3), 1),
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_4', 'farming',
           [(get_item('carrot_minion', tier=3), 1),
            (Item('enchanted_carrot'), 8)],
           (get_item('carrot_minion', tier=4), 1),
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_5', 'farming',
           [(get_item('carrot_minion', tier=4), 1),
            (Item('enchanted_carrot'), 24)],
           (get_item('carrot_minion', tier=5), 1),
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_6', 'farming',
           [(get_item('carrot_minion', tier=5), 1),
            (Item('enchanted_carrot'), 64)],
           (get_item('carrot_minion', tier=6), 1),
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_7', 'farming',
           [(get_item('carrot_minion', tier=6), 1),
            (Item('enchanted_carrot'), 128)],
           (get_item('carrot_minion', tier=7), 1),
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_8', 'farming',
           [(get_item('carrot_minion', tier=7), 1),
            (Item('enchanted_carrot'), 256)],
           (get_item('carrot_minion', tier=8), 1),
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_9', 'farming',
           [(get_item('carrot_minion', tier=8), 1),
            (Item('enchanted_carrot'), 512)],
           (get_item('carrot_minion', tier=9), 1),
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_10', 'farming',
           [(get_item('carrot_minion', tier=9), 1),
            (Item('enchanted_golden_carrot'), 8)],
           (get_item('carrot_minion', tier=10), 1),
           collection_req=('carrot', 1)),
    Recipe('carrot_minion_11', 'farming',
           [(get_item('carrot_minion', tier=10), 1),
            (Item('enchanted_golden_carrot'), 16)],
           (get_item('carrot_minion', tier=11), 1),
           collection_req=('carrot', 1)),
    RecipeGroup('carrot_minion', 'farming',
                ['carrot_minion_1', 'carrot_minion_2', 'carrot_minion_3',
                 'carrot_minion_4', 'carrot_minion_5', 'carrot_minion_6',
                 'carrot_minion_7', 'carrot_minion_8', 'carrot_minion_9',
                 'carrot_minion_10', 'carrot_minion_11'],
                collection_req=('carrot', 1)),

    Recipe('potato_minion_1', 'farming',
           [(get_item('wooden_hoe'), 1),
            (Item('potato'), 128)],
           (get_item('potato_minion', tier=1), 1),
           collection_req=('potato', 1)),
    Recipe('potato_minion_2', 'farming',
           [(get_item('potato_minion', tier=1), 1),
            (Item('potato'), 256)],
           (get_item('potato_minion', tier=2), 1),
           collection_req=('potato', 1)),
    Recipe('potato_minion_3', 'farming',
           [(get_item('potato_minion', tier=2), 1),
            (Item('potato'), 512)],
           (get_item('potato_minion', tier=3), 1),
           collection_req=('potato', 1)),
    Recipe('potato_minion_4', 'farming',
           [(get_item('potato_minion', tier=3), 1),
            (Item('enchanted_potato'), 8)],
           (get_item('potato_minion', tier=4), 1),
           collection_req=('potato', 1)),
    Recipe('potato_minion_5', 'farming',
           [(get_item('potato_minion', tier=4), 1),
            (Item('enchanted_potato'), 24)],
           (get_item('potato_minion', tier=5), 1),
           collection_req=('potato', 1)),
    Recipe('potato_minion_6', 'farming',
           [(get_item('potato_minion', tier=5), 1),
            (Item('enchanted_potato'), 64)],
           (get_item('potato_minion', tier=6), 1),
           collection_req=('potato', 1)),
    Recipe('potato_minion_7', 'farming',
           [(get_item('potato_minion', tier=6), 1),
            (Item('enchanted_potato'), 128)],
           (get_item('potato_minion', tier=7), 1),
           collection_req=('potato', 1)),
    Recipe('potato_minion_8', 'farming',
           [(get_item('potato_minion', tier=7), 1),
            (Item('enchanted_potato'), 256)],
           (get_item('potato_minion', tier=8), 1),
           collection_req=('potato', 1)),
    Recipe('potato_minion_9', 'farming',
           [(get_item('potato_minion', tier=8), 1),
            (Item('enchanted_potato'), 512)],
           (get_item('potato_minion', tier=9), 1),
           collection_req=('potato', 1)),
    Recipe('potato_minion_10', 'farming',
           [(get_item('potato_minion', tier=9), 1),
            (Item('enchanted_baked_potato'), 8)],
           (get_item('potato_minion', tier=10), 1),
           collection_req=('potato', 1)),
    Recipe('potato_minion_11', 'farming',
           [(get_item('potato_minion', tier=10), 1),
            (Item('enchanted_baked_potato'), 16)],
           (get_item('potato_minion', tier=11), 1),
           collection_req=('potato', 1)),
    RecipeGroup('potato_minion', 'farming',
                ['potato_minion_1', 'potato_minion_2', 'potato_minion_3',
                 'potato_minion_4', 'potato_minion_5', 'potato_minion_6',
                 'potato_minion_7', 'potato_minion_8', 'potato_minion_9',
                 'potato_minion_10', 'potato_minion_11'],
                collection_req=('potato', 1)),

    Recipe('pumpkin_minion_1', 'farming',
           [(get_item('wooden_hoe'), 1),
            (Item('pumpkin'), 80)],
           (get_item('pumpkin_minion', tier=1), 1),
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_2', 'farming',
           [(get_item('pumpkin_minion', tier=1), 1),
            (Item('pumpkin'), 160)],
           (get_item('pumpkin_minion', tier=2), 1),
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_3', 'farming',
           [(get_item('pumpkin_minion', tier=2), 1),
            (Item('pumpkin'), 320)],
           (get_item('pumpkin_minion', tier=3), 1),
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_4', 'farming',
           [(get_item('pumpkin_minion', tier=3), 1),
            (Item('pumpkin'), 512)],
           (get_item('pumpkin_minion', tier=4), 1),
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_5', 'farming',
           [(get_item('pumpkin_minion', tier=4), 1),
            (Item('enchanted_pumpkin'), 8)],
           (get_item('pumpkin_minion', tier=5), 1),
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_6', 'farming',
           [(get_item('pumpkin_minion', tier=5), 1),
            (Item('enchanted_pumpkin'), 16)],
           (get_item('pumpkin_minion', tier=6), 1),
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_7', 'farming',
           [(get_item('pumpkin_minion', tier=6), 1),
            (Item('enchanted_pumpkin'), 32)],
           (get_item('pumpkin_minion', tier=7), 1),
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_8', 'farming',
           [(get_item('pumpkin_minion', tier=7), 1),
            (Item('enchanted_pumpkin'), 64)],
           (get_item('pumpkin_minion', tier=8), 1),
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_9', 'farming',
           [(get_item('pumpkin_minion', tier=8), 1),
            (Item('enchanted_pumpkin'), 128)],
           (get_item('pumpkin_minion', tier=9), 1),
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_10', 'farming',
           [(get_item('pumpkin_minion', tier=9), 1),
            (Item('enchanted_pumpkin'), 256)],
           (get_item('pumpkin_minion', tier=10), 1),
           collection_req=('pumpkin', 1)),
    Recipe('pumpkin_minion_11', 'farming',
           [(get_item('pumpkin_minion', tier=10), 1),
            (Item('enchanted_pumpkin'), 512)],
           (get_item('pumpkin_minion', tier=11), 1),
           collection_req=('pumpkin', 1)),
    RecipeGroup('pumpkin_minion', 'farming',
                ['pumpkin_minion_1', 'pumpkin_minion_2', 'pumpkin_minion_3',
                 'pumpkin_minion_4', 'pumpkin_minion_5', 'pumpkin_minion_6',
                 'pumpkin_minion_7', 'pumpkin_minion_8', 'pumpkin_minion_9',
                 'pumpkin_minion_10', 'pumpkin_minion_11'],
                collection_req=('pumpkin', 1)),

    Recipe('melon_minion_1', 'farming',
           [(get_item('wooden_hoe'), 1),
            (Item('melon'), 256)],
           (get_item('melon_minion', tier=1), 1),
           collection_req=('melon', 1)),
    Recipe('melon_minion_2', 'farming',
           [(get_item('melon_minion', tier=1), 1),
            (Item('melon'), 512)],
           (get_item('melon_minion', tier=2), 1),
           collection_req=('melon', 1)),
    Recipe('melon_minion_3', 'farming',
           [(get_item('melon_minion', tier=2), 1),
            (Item('melon_block'), 128)],
           (get_item('melon_minion', tier=3), 1),
           collection_req=('melon', 1)),
    Recipe('melon_minion_4', 'farming',
           [(get_item('melon_minion', tier=3), 1),
            (Item('melon_block'), 256)],
           (get_item('melon_minion', tier=4), 1),
           collection_req=('melon', 1)),
    Recipe('melon_minion_5', 'farming',
           [(get_item('melon_minion', tier=4), 1),
            (Item('melon_block'), 512)],
           (get_item('melon_minion', tier=5), 1),
           collection_req=('melon', 1)),
    Recipe('melon_minion_6', 'farming',
           [(get_item('melon_minion', tier=5), 1),
            (Item('enchanted_melon'), 64)],
           (get_item('melon_minion', tier=6), 1),
           collection_req=('melon', 1)),
    Recipe('melon_minion_7', 'farming',
           [(get_item('melon_minion', tier=6), 1),
            (Item('enchanted_melon'), 128)],
           (get_item('melon_minion', tier=7), 1),
           collection_req=('melon', 1)),
    Recipe('melon_minion_8', 'farming',
           [(get_item('melon_minion', tier=7), 1),
            (Item('enchanted_melon'), 256)],
           (get_item('melon_minion', tier=8), 1),
           collection_req=('melon', 1)),
    Recipe('melon_minion_9', 'farming',
           [(get_item('melon_minion', tier=8), 1),
            (Item('enchanted_melon'), 512)],
           (get_item('melon_minion', tier=9), 1),
           collection_req=('melon', 1)),
    Recipe('melon_minion_10', 'farming',
           [(get_item('melon_minion', tier=9), 1),
            (Item('enchanted_melon_block'), 8)],
           (get_item('melon_minion', tier=10), 1),
           collection_req=('melon', 1)),
    Recipe('melon_minion_11', 'farming',
           [(get_item('melon_minion', tier=10), 1),
            (Item('enchanted_melon_block'), 16)],
           (get_item('melon_minion', tier=11), 1),
           collection_req=('melon', 1)),
    RecipeGroup('melon_minion', 'farming',
                ['melon_minion_1', 'melon_minion_2', 'melon_minion_3',
                 'melon_minion_4', 'melon_minion_5', 'melon_minion_6',
                 'melon_minion_7', 'melon_minion_8', 'melon_minion_9',
                 'melon_minion_10', 'melon_minion_11'],
                collection_req=('melon', 1)),

    Recipe('mushroom_minion_1', 'farming',
           [(get_item('wooden_hoe'), 1),
            (Item('mushroom_block'), 80)],
           (get_item('mushroom_minion', tier=1), 1),
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_2', 'farming',
           [(get_item('mushroom_minion', tier=1), 1),
            (Item('mushroom_block'), 160)],
           (get_item('mushroom_minion', tier=2), 1),
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_3', 'farming',
           [(get_item('mushroom_minion', tier=2), 1),
            (Item('mushroom_block'), 320)],
           (get_item('mushroom_minion', tier=3), 1),
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_4', 'farming',
           [(get_item('mushroom_minion', tier=3), 1),
            (Item('mushroom_block'), 512)],
           (get_item('mushroom_minion', tier=4), 1),
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_5', 'farming',
           [(get_item('mushroom_minion', tier=4), 1),
            (Item('enchanted_mushroom'), 8)],
           (get_item('mushroom_minion', tier=5), 1),
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_6', 'farming',
           [(get_item('mushroom_minion', tier=5), 1),
            (Item('enchanted_mushroom'), 16)],
           (get_item('mushroom_minion', tier=6), 1),
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_7', 'farming',
           [(get_item('mushroom_minion', tier=6), 1),
            (Item('enchanted_mushroom'), 32)],
           (get_item('mushroom_minion', tier=7), 1),
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_8', 'farming',
           [(get_item('mushroom_minion', tier=7), 1),
            (Item('enchanted_mushroom'), 64)],
           (get_item('mushroom_minion', tier=8), 1),
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_9', 'farming',
           [(get_item('mushroom_minion', tier=8), 1),
            (Item('enchanted_mushroom'), 128)],
           (get_item('mushroom_minion', tier=9), 1),
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_10', 'farming',
           [(get_item('mushroom_minion', tier=9), 1),
            (Item('enchanted_mushroom'), 256)],
           (get_item('mushroom_minion', tier=10), 1),
           collection_req=('mushroom', 1)),
    Recipe('mushroom_minion_11', 'farming',
           [(get_item('mushroom_minion', tier=10), 1),
            (Item('enchanted_mushroom'), 512)],
           (get_item('mushroom_minion', tier=11), 1),
           collection_req=('mushroom', 1)),
    RecipeGroup('mushroom_minion', 'farming',
                ['mushroom_minion_1', 'mushroom_minion_2', 'mushroom_minion_3',
                 'mushroom_minion_4', 'mushroom_minion_5', 'mushroom_minion_6',
                 'mushroom_minion_7', 'mushroom_minion_8', 'mushroom_minion_9',
                 'mushroom_minion_10', 'mushroom_minion_11'],
                collection_req=('mushroom', 1)),

    Recipe('cocoa_minion_1', 'farming',
           [(get_item('wooden_hoe'), 1),
            (Item('cocoa'), 80)],
           (get_item('cocoa_minion', tier=1), 1),
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_2', 'farming',
           [(get_item('cocoa_minion', tier=1), 1),
            (Item('cocoa'), 160)],
           (get_item('cocoa_minion', tier=2), 1),
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_3', 'farming',
           [(get_item('cocoa_minion', tier=2), 1),
            (Item('cocoa'), 320)],
           (get_item('cocoa_minion', tier=3), 1),
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_4', 'farming',
           [(get_item('cocoa_minion', tier=3), 1),
            (Item('cocoa'), 512)],
           (get_item('cocoa_minion', tier=4), 1),
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_5', 'farming',
           [(get_item('cocoa_minion', tier=4), 1),
            (Item('enchanted_cocoa'), 8)],
           (get_item('cocoa_minion', tier=5), 1),
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_6', 'farming',
           [(get_item('cocoa_minion', tier=5), 1),
            (Item('enchanted_cocoa'), 24)],
           (get_item('cocoa_minion', tier=6), 1),
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_7', 'farming',
           [(get_item('cocoa_minion', tier=6), 1),
            (Item('enchanted_cocoa'), 64)],
           (get_item('cocoa_minion', tier=7), 1),
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_8', 'farming',
           [(get_item('cocoa_minion', tier=7), 1),
            (Item('enchanted_cocoa'), 128)],
           (get_item('cocoa_minion', tier=8), 1),
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_9', 'farming',
           [(get_item('cocoa_minion', tier=8), 1),
            (Item('enchanted_cocoa'), 256)],
           (get_item('cocoa_minion', tier=9), 1),
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_10', 'farming',
           [(get_item('cocoa_minion', tier=9), 1),
            (Item('enchanted_cocoa'), 512)],
           (get_item('cocoa_minion', tier=10), 1),
           collection_req=('cocoa', 1)),
    Recipe('cocoa_minion_11', 'farming',
           [(get_item('cocoa_minion', tier=10), 1),
            (Item('enchanted_cookie'), 8)],
           (get_item('cocoa_minion', tier=11), 1),
           collection_req=('cocoa', 1)),
    RecipeGroup('cocoa_minion', 'farming',
                ['cocoa_minion_1', 'cocoa_minion_2', 'cocoa_minion_3',
                 'cocoa_minion_4', 'cocoa_minion_5', 'cocoa_minion_6',
                 'cocoa_minion_7', 'cocoa_minion_8', 'cocoa_minion_9',
                 'cocoa_minion_10', 'cocoa_minion_11'],
                collection_req=('cocoa', 1)),

    Recipe('cactus_minion_1', 'farming',
           [(get_item('wooden_hoe'), 1),
            (Item('cactus'), 128)],
           (get_item('cactus_minion', tier=1), 1),
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_2', 'farming',
           [(get_item('cactus_minion', tier=1), 1),
            (Item('cactus'), 256)],
           (get_item('cactus_minion', tier=2), 1),
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_3', 'farming',
           [(get_item('cactus_minion', tier=2), 1),
            (Item('cactus'), 512)],
           (get_item('cactus_minion', tier=3), 1),
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_4', 'farming',
           [(get_item('cactus_minion', tier=3), 1),
            (Item('enchanted_cactus_green'), 8)],
           (get_item('cactus_minion', tier=4), 1),
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_5', 'farming',
           [(get_item('cactus_minion', tier=4), 1),
            (Item('enchanted_cactus_green'), 24)],
           (get_item('cactus_minion', tier=5), 1),
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_6', 'farming',
           [(get_item('cactus_minion', tier=5), 1),
            (Item('enchanted_cactus_green'), 64)],
           (get_item('cactus_minion', tier=6), 1),
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_7', 'farming',
           [(get_item('cactus_minion', tier=6), 1),
            (Item('enchanted_cactus_green'), 128)],
           (get_item('cactus_minion', tier=7), 1),
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_8', 'farming',
           [(get_item('cactus_minion', tier=7), 1),
            (Item('enchanted_cactus_green'), 256)],
           (get_item('cactus_minion', tier=8), 1),
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_9', 'farming',
           [(get_item('cactus_minion', tier=8), 1),
            (Item('enchanted_cactus_green'), 512)],
           (get_item('cactus_minion', tier=9), 1),
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_10', 'farming',
           [(get_item('cactus_minion', tier=9), 1),
            (Item('enchanted_cactus'), 8)],
           (get_item('cactus_minion', tier=10), 1),
           collection_req=('cactus', 1)),
    Recipe('cactus_minion_11', 'farming',
           [(get_item('cactus_minion', tier=10), 1),
            (Item('enchanted_cactus'), 16)],
           (get_item('cactus_minion', tier=11), 1),
           collection_req=('cactus', 1)),
    RecipeGroup('cactus_minion', 'farming',
                ['cactus_minion_1', 'cactus_minion_2', 'cactus_minion_3',
                 'cactus_minion_4', 'cactus_minion_5', 'cactus_minion_6',
                 'cactus_minion_7', 'cactus_minion_8', 'cactus_minion_9',
                 'cactus_minion_10', 'cactus_minion_11'],
                collection_req=('cactus', 1)),

    Recipe('sugar_cane_minion_1', 'farming',
           [(get_item('wooden_hoe'), 1),
            (Item('sugar_cane'), 128)],
           (get_item('sugar_cane_minion', tier=1), 1),
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_2', 'farming',
           [(get_item('sugar_cane_minion', tier=1), 1),
            (Item('sugar_cane'), 256)],
           (get_item('sugar_cane_minion', tier=2), 1),
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_3', 'farming',
           [(get_item('sugar_cane_minion', tier=2), 1),
            (Item('sugar_cane'), 512)],
           (get_item('sugar_cane_minion', tier=3), 1),
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_4', 'farming',
           [(get_item('sugar_cane_minion', tier=3), 1),
            (Item('enchanted_sugar'), 8)],
           (get_item('sugar_cane_minion', tier=4), 1),
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_5', 'farming',
           [(get_item('sugar_cane_minion', tier=4), 1),
            (Item('enchanted_sugar'), 24)],
           (get_item('sugar_cane_minion', tier=5), 1),
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_6', 'farming',
           [(get_item('sugar_cane_minion', tier=5), 1),
            (Item('enchanted_sugar'), 64)],
           (get_item('sugar_cane_minion', tier=6), 1),
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_7', 'farming',
           [(get_item('sugar_cane_minion', tier=6), 1),
            (Item('enchanted_sugar'), 128)],
           (get_item('sugar_cane_minion', tier=7), 1),
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_8', 'farming',
           [(get_item('sugar_cane_minion', tier=7), 1),
            (Item('enchanted_sugar'), 256)],
           (get_item('sugar_cane_minion', tier=8), 1),
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_9', 'farming',
           [(get_item('sugar_cane_minion', tier=8), 1),
            (Item('enchanted_sugar'), 512)],
           (get_item('sugar_cane_minion', tier=9), 1),
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_10', 'farming',
           [(get_item('sugar_cane_minion', tier=9), 1),
            (Item('enchanted_sugar_cane'), 8)],
           (get_item('sugar_cane_minion', tier=10), 1),
           collection_req=('sugar_cane', 1)),
    Recipe('sugar_cane_minion_11', 'farming',
           [(get_item('sugar_cane_minion', tier=10), 1),
            (Item('enchanted_sugar_cane'), 16)],
           (get_item('sugar_cane_minion', tier=11), 1),
           collection_req=('sugar_cane', 1)),
    RecipeGroup('sugar_cane_minion', 'farming',
                ['sugar_cane_minion_1', 'sugar_cane_minion_2',
                 'sugar_cane_minion_3', 'sugar_cane_minion_4',
                 'sugar_cane_minion_5', 'sugar_cane_minion_6',
                 'sugar_cane_minion_7', 'sugar_cane_minion_8',
                 'sugar_cane_minion_9', 'sugar_cane_minion_10',
                 'sugar_cane_minion_11'],
                collection_req=('sugar_cane', 1)),

    Recipe('cow_minion_1', 'farming',
           [(get_item('wooden_sword'), 1),
            (Item('beef'), 64)],
           (get_item('cow_minion', tier=1), 1),
           collection_req=('leather', 1)),
    Recipe('cow_minion_2', 'farming',
           [(get_item('cow_minion', tier=1), 1),
            (Item('beef'), 128)],
           (get_item('cow_minion', tier=2), 1),
           collection_req=('leather', 1)),
    Recipe('cow_minion_3', 'farming',
           [(get_item('cow_minion', tier=2), 1),
            (Item('beef'), 256)],
           (get_item('cow_minion', tier=3), 1),
           collection_req=('leather', 1)),
    Recipe('cow_minion_4', 'farming',
           [(get_item('cow_minion', tier=3), 1),
            (Item('beef'), 512)],
           (get_item('cow_minion', tier=4), 1),
           collection_req=('leather', 1)),
    Recipe('cow_minion_5', 'farming',
           [(get_item('cow_minion', tier=4), 1),
            (Item('enchanted_beef'), 8)],
           (get_item('cow_minion', tier=5), 1),
           collection_req=('leather', 1)),
    Recipe('cow_minion_6', 'farming',
           [(get_item('cow_minion', tier=5), 1),
            (Item('enchanted_beef'), 16)],
           (get_item('cow_minion', tier=6), 1),
           collection_req=('leather', 1)),
    Recipe('cow_minion_7', 'farming',
           [(get_item('cow_minion', tier=6), 1),
            (Item('enchanted_beef'), 32)],
           (get_item('cow_minion', tier=7), 1),
           collection_req=('leather', 1)),
    Recipe('cow_minion_8', 'farming',
           [(get_item('cow_minion', tier=7), 1),
            (Item('enchanted_beef'), 64)],
           (get_item('cow_minion', tier=8), 1),
           collection_req=('leather', 1)),
    Recipe('cow_minion_9', 'farming',
           [(get_item('cow_minion', tier=8), 1),
            (Item('enchanted_beef'), 128)],
           (get_item('cow_minion', tier=9), 1),
           collection_req=('leather', 1)),
    Recipe('cow_minion_10', 'farming',
           [(get_item('cow_minion', tier=9), 1),
            (Item('enchanted_beef'), 256)],
           (get_item('cow_minion', tier=10), 1),
           collection_req=('leather', 1)),
    Recipe('cow_minion_11', 'farming',
           [(get_item('cow_minion', tier=10), 1),
            (Item('enchanted_beef'), 512)],
           (get_item('cow_minion', tier=11), 1),
           collection_req=('leather', 1)),
    RecipeGroup('cow_minion', 'farming',
                ['cow_minion_1', 'cow_minion_2', 'cow_minion_3', 'cow_minion_4',
                 'cow_minion_5', 'cow_minion_6', 'cow_minion_7', 'cow_minion_8',
                 'cow_minion_9', 'cow_minion_10', 'cow_minion_11'],
                collection_req=('leather', 1)),

    Recipe('pig_minion_1', 'farming',
           [(get_item('wooden_sword'), 1),
            (Item('pork'), 64)],
           (get_item('pig_minion', tier=1), 1),
           collection_req=('pork', 1)),
    Recipe('pig_minion_2', 'farming',
           [(get_item('pig_minion', tier=1), 1),
            (Item('pork'), 128)],
           (get_item('pig_minion', tier=2), 1),
           collection_req=('pork', 1)),
    Recipe('pig_minion_3', 'farming',
           [(get_item('pig_minion', tier=2), 1),
            (Item('pork'), 256)],
           (get_item('pig_minion', tier=3), 1),
           collection_req=('pork', 1)),
    Recipe('pig_minion_4', 'farming',
           [(get_item('pig_minion', tier=3), 1),
            (Item('pork'), 512)],
           (get_item('pig_minion', tier=4), 1),
           collection_req=('pork', 1)),
    Recipe('pig_minion_5', 'farming',
           [(get_item('pig_minion', tier=4), 1),
            (Item('enchanted_pork'), 8)],
           (get_item('pig_minion', tier=5), 1),
           collection_req=('pork', 1)),
    Recipe('pig_minion_6', 'farming',
           [(get_item('pig_minion', tier=5), 1),
            (Item('enchanted_pork'), 24)],
           (get_item('pig_minion', tier=6), 1),
           collection_req=('pork', 1)),
    Recipe('pig_minion_7', 'farming',
           [(get_item('pig_minion', tier=6), 1),
            (Item('enchanted_pork'), 64)],
           (get_item('pig_minion', tier=7), 1),
           collection_req=('pork', 1)),
    Recipe('pig_minion_8', 'farming',
           [(get_item('pig_minion', tier=7), 1),
            (Item('enchanted_pork'), 128)],
           (get_item('pig_minion', tier=8), 1),
           collection_req=('pork', 1)),
    Recipe('pig_minion_9', 'farming',
           [(get_item('pig_minion', tier=8), 1),
            (Item('enchanted_pork'), 256)],
           (get_item('pig_minion', tier=9), 1),
           collection_req=('pork', 1)),
    Recipe('pig_minion_10', 'farming',
           [(get_item('pig_minion', tier=9), 1),
            (Item('enchanted_pork'), 512)],
           (get_item('pig_minion', tier=10), 1),
           collection_req=('pork', 1)),
    Recipe('pig_minion_11', 'farming',
           [(get_item('pig_minion', tier=10), 1),
            (Item('enchanted_grilled_pork'), 8)],
           (get_item('pig_minion', tier=11), 1),
           collection_req=('pork', 1)),
    RecipeGroup('pig_minion', 'farming',
                ['pig_minion_1', 'pig_minion_2', 'pig_minion_3', 'pig_minion_4',
                 'pig_minion_5', 'pig_minion_6', 'pig_minion_7', 'pig_minion_8',
                 'pig_minion_9', 'pig_minion_10', 'pig_minion_11'],
                collection_req=('pork', 1)),

    Recipe('chicken_minion_1', 'farming',
           [(get_item('wooden_sword'), 1),
            (Item('chicken'), 64)],
           (get_item('chicken_minion', tier=1), 1),
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_2', 'farming',
           [(get_item('chicken_minion', tier=1), 1),
            (Item('chicken'), 128)],
           (get_item('chicken_minion', tier=2), 1),
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_3', 'farming',
           [(get_item('chicken_minion', tier=2), 1),
            (Item('chicken'), 256)],
           (get_item('chicken_minion', tier=3), 1),
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_4', 'farming',
           [(get_item('chicken_minion', tier=3), 1),
            (Item('chicken'), 512)],
           (get_item('chicken_minion', tier=4), 1),
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_5', 'farming',
           [(get_item('chicken_minion', tier=4), 1),
            (Item('enchanted_chicken'), 8)],
           (get_item('chicken_minion', tier=5), 1),
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_6', 'farming',
           [(get_item('chicken_minion', tier=5), 1),
            (Item('enchanted_chicken'), 16)],
           (get_item('chicken_minion', tier=6), 1),
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_7', 'farming',
           [(get_item('chicken_minion', tier=6), 1),
            (Item('enchanted_chicken'), 32)],
           (get_item('chicken_minion', tier=7), 1),
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_8', 'farming',
           [(get_item('chicken_minion', tier=7), 1),
            (Item('enchanted_chicken'), 64)],
           (get_item('chicken_minion', tier=8), 1),
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_9', 'farming',
           [(get_item('chicken_minion', tier=8), 1),
            (Item('enchanted_chicken'), 128)],
           (get_item('chicken_minion', tier=9), 1),
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_10', 'farming',
           [(get_item('chicken_minion', tier=9), 1),
            (Item('enchanted_chicken'), 256)],
           (get_item('chicken_minion', tier=10), 1),
           collection_req=('chicken', 1)),
    Recipe('chicken_minion_11', 'farming',
           [(get_item('chicken_minion', tier=10), 1),
            (Item('enchanted_chicken'), 512)],
           (get_item('chicken_minion', tier=11), 1),
           collection_req=('chicken', 1)),
    RecipeGroup('chicken_minion', 'farming',
                ['chicken_minion_1', 'chicken_minion_2', 'chicken_minion_3',
                 'chicken_minion_4', 'chicken_minion_5', 'chicken_minion_6',
                 'chicken_minion_7', 'chicken_minion_8', 'chicken_minion_9',
                 'chicken_minion_10', 'chicken_minion_11'],
                collection_req=('chicken', 1)),

    Recipe('sheep_minion_1', 'farming',
           [(get_item('wooden_sword'), 1),
            (Item('mutton'), 64)],
           (get_item('sheep_minion', tier=1), 1),
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_2', 'farming',
           [(get_item('sheep_minion', tier=1), 1),
            (Item('mutton'), 128)],
           (get_item('sheep_minion', tier=2), 1),
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_3', 'farming',
           [(get_item('sheep_minion', tier=2), 1),
            (Item('mutton'), 256)],
           (get_item('sheep_minion', tier=3), 1),
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_4', 'farming',
           [(get_item('sheep_minion', tier=3), 1),
            (Item('mutton'), 512)],
           (get_item('sheep_minion', tier=4), 1),
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_5', 'farming',
           [(get_item('sheep_minion', tier=4), 1),
            (Item('enchanted_mutton'), 8)],
           (get_item('sheep_minion', tier=5), 1),
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_6', 'farming',
           [(get_item('sheep_minion', tier=5), 1),
            (Item('enchanted_mutton'), 24)],
           (get_item('sheep_minion', tier=6), 1),
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_7', 'farming',
           [(get_item('sheep_minion', tier=6), 1),
            (Item('enchanted_mutton'), 64)],
           (get_item('sheep_minion', tier=7), 1),
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_8', 'farming',
           [(get_item('sheep_minion', tier=7), 1),
            (Item('enchanted_mutton'), 128)],
           (get_item('sheep_minion', tier=8), 1),
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_9', 'farming',
           [(get_item('sheep_minion', tier=8), 1),
            (Item('enchanted_mutton'), 256)],
           (get_item('sheep_minion', tier=9), 1),
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_10', 'farming',
           [(get_item('sheep_minion', tier=9), 1),
            (Item('enchanted_mutton'), 512)],
           (get_item('sheep_minion', tier=10), 1),
           collection_req=('mutton', 1)),
    Recipe('sheep_minion_11', 'farming',
           [(get_item('sheep_minion', tier=10), 1),
            (Item('enchanted_cooked_mutton'), 8)],
           (get_item('sheep_minion', tier=11), 1),
           collection_req=('mutton', 1)),
    RecipeGroup('sheep_minion', 'farming',
                ['sheep_minion_1', 'sheep_minion_2', 'sheep_minion_3',
                 'sheep_minion_4', 'sheep_minion_5', 'sheep_minion_6',
                 'sheep_minion_7', 'sheep_minion_8', 'sheep_minion_9',
                 'sheep_minion_10', 'sheep_minion_11'],
                collection_req=('mutton', 1)),

    Recipe('rabbit_minion_1', 'farming',
           [(get_item('wooden_sword'), 1),
            (Item('rabbit'), 64)],
           (get_item('rabbit_minion', tier=1), 1),
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_2', 'farming',
           [(get_item('rabbit_minion', tier=1), 1),
            (Item('rabbit'), 128)],
           (get_item('rabbit_minion', tier=2), 1),
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_3', 'farming',
           [(get_item('rabbit_minion', tier=2), 1),
            (Item('rabbit'), 256)],
           (get_item('rabbit_minion', tier=3), 1),
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_4', 'farming',
           [(get_item('rabbit_minion', tier=3), 1),
            (Item('rabbit'), 512)],
           (get_item('rabbit_minion', tier=4), 1),
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_5', 'farming',
           [(get_item('rabbit_minion', tier=4), 1),
            (Item('enchanted_rabbit_foot'), 32)],
           (get_item('rabbit_minion', tier=5), 1),
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_6', 'farming',
           [(get_item('rabbit_minion', tier=5), 1),
            (Item('enchanted_rabbit_foot'), 64)],
           (get_item('rabbit_minion', tier=6), 1),
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_7', 'farming',
           [(get_item('rabbit_minion', tier=6), 1),
            (Item('enchanted_rabbit_foot'), 128)],
           (get_item('rabbit_minion', tier=7), 1),
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_8', 'farming',
           [(get_item('rabbit_minion', tier=7), 1),
            (Item('enchanted_rabbit_foot'), 256)],
           (get_item('rabbit_minion', tier=8), 1),
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_9', 'farming',
           [(get_item('rabbit_minion', tier=8), 1),
            (Item('enchanted_rabbit_foot'), 512)],
           (get_item('rabbit_minion', tier=9), 1),
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_10', 'farming',
           [(get_item('rabbit_minion', tier=9), 1),
            (Item('enchanted_rabbit_hide'), 256)],
           (get_item('rabbit_minion', tier=10), 1),
           collection_req=('rabbit', 1)),
    Recipe('rabbit_minion_11', 'farming',
           [(get_item('rabbit_minion', tier=10), 1),
            (Item('enchanted_rabbit_hide'), 512)],
           (get_item('rabbit_minion', tier=11), 1),
           collection_req=('rabbit', 1)),
    RecipeGroup('rabbit_minion', 'farming',
                ['rabbit_minion_1', 'rabbit_minion_2', 'rabbit_minion_3',
                 'rabbit_minion_4', 'rabbit_minion_5', 'rabbit_minion_6',
                 'rabbit_minion_7', 'rabbit_minion_8', 'rabbit_minion_9',
                 'rabbit_minion_10', 'rabbit_minion_11'],
                collection_req=('rabbit', 1)),

    Recipe('nether_wart_minion_1', 'farming',
           [(get_item('wooden_hoe'), 1),
            (Item('nether_wart'), 80)],
           (get_item('nether_wart_minion', tier=1), 1),
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_2', 'farming',
           [(get_item('nether_wart_minion', tier=1), 1),
            (Item('nether_wart'), 160)],
           (get_item('nether_wart_minion', tier=2), 1),
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_3', 'farming',
           [(get_item('nether_wart_minion', tier=2), 1),
            (Item('nether_wart'), 320)],
           (get_item('nether_wart_minion', tier=3), 1),
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_4', 'farming',
           [(get_item('nether_wart_minion', tier=3), 1),
            (Item('nether_wart'), 512)],
           (get_item('nether_wart_minion', tier=4), 1),
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_5', 'farming',
           [(get_item('nether_wart_minion', tier=4), 1),
            (Item('enchanted_nether_wart'), 8)],
           (get_item('nether_wart_minion', tier=5), 1),
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_6', 'farming',
           [(get_item('nether_wart_minion', tier=5), 1),
            (Item('enchanted_nether_wart'), 16)],
           (get_item('nether_wart_minion', tier=6), 1),
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_7', 'farming',
           [(get_item('nether_wart_minion', tier=6), 1),
            (Item('enchanted_nether_wart'), 32)],
           (get_item('nether_wart_minion', tier=7), 1),
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_8', 'farming',
           [(get_item('nether_wart_minion', tier=7), 1),
            (Item('enchanted_nether_wart'), 64)],
           (get_item('nether_wart_minion', tier=8), 1),
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_9', 'farming',
           [(get_item('nether_wart_minion', tier=8), 1),
            (Item('enchanted_nether_wart'), 128)],
           (get_item('nether_wart_minion', tier=9), 1),
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_10', 'farming',
           [(get_item('nether_wart_minion', tier=9), 1),
            (Item('enchanted_nether_wart'), 256)],
           (get_item('nether_wart_minion', tier=10), 1),
           collection_req=('nether_wart', 1)),
    Recipe('nether_wart_minion_11', 'farming',
           [(get_item('nether_wart_minion', tier=10), 1),
            (Item('enchanted_nether_wart'), 512)],
           (get_item('nether_wart_minion', tier=11), 1),
           collection_req=('nether_wart', 1)),
    RecipeGroup('nether_wart_minion', 'farming',
                ['nether_wart_minion_1', 'nether_wart_minion_2',
                 'nether_wart_minion_3', 'nether_wart_minion_4',
                 'nether_wart_minion_5', 'nether_wart_minion_6',
                 'nether_wart_minion_7', 'nether_wart_minion_8',
                 'nether_wart_minion_9', 'nether_wart_minion_10',
                 'nether_wart_minion_11'],
                collection_req=('nether_wart', 1)),
]
