from ..object import *


FISHING_MINION_RECIPES = [
    Recipe('fishing_minion_1', 'fishing',
           [{'name': 'wooden_sword'},
            {'name': 'fish', 'count': 64}],
           {'name': 'fishing_minion', 'tier': 1},
           collection_req=('fish', 1)),
    Recipe('fishing_minion_2', 'fishing',
           [{'name': 'fishing_minion', 'tier': 1},
            {'name': 'fish', 'count': 128}],
           {'name': 'fishing_minion', 'tier': 2},
           collection_req=('fish', 1)),
    Recipe('fishing_minion_3', 'fishing',
           [{'name': 'fishing_minion', 'tier': 2},
            {'name': 'fish', 'count': 256}],
           {'name': 'fishing_minion', 'tier': 3},
           collection_req=('fish', 1)),
    Recipe('fishing_minion_4', 'fishing',
           [{'name': 'fishing_minion', 'tier': 3},
            {'name': 'fish', 'count': 512}],
           {'name': 'fishing_minion', 'tier': 4},
           collection_req=('fish', 1)),
    Recipe('fishing_minion_5', 'fishing',
           [{'name': 'fishing_minion', 'tier': 4},
            {'name': 'enchanted_fish', 'count': 8}],
           {'name': 'fishing_minion', 'tier': 5},
           collection_req=('fish', 1)),
    Recipe('fishing_minion_6', 'fishing',
           [{'name': 'fishing_minion', 'tier': 5},
            {'name': 'enchanted_fish', 'count': 24}],
           {'name': 'fishing_minion', 'tier': 6},
           collection_req=('fish', 1)),
    Recipe('fishing_minion_7', 'fishing',
           [{'name': 'fishing_minion', 'tier': 6},
            {'name': 'enchanted_fish', 'count': 64}],
           {'name': 'fishing_minion', 'tier': 7},
           collection_req=('fish', 1)),
    Recipe('fishing_minion_8', 'fishing',
           [{'name': 'fishing_minion', 'tier': 7},
            {'name': 'enchanted_fish', 'count': 128}],
           {'name': 'fishing_minion', 'tier': 8},
           collection_req=('fish', 1)),
    Recipe('fishing_minion_9', 'fishing',
           [{'name': 'fishing_minion', 'tier': 8},
            {'name': 'enchanted_fish', 'count': 256}],
           {'name': 'fishing_minion', 'tier': 9},
           collection_req=('fish', 1)),
    Recipe('fishing_minion_10', 'fishing',
           [{'name': 'fishing_minion', 'tier': 9},
            {'name': 'enchanted_fish', 'count': 512}],
           {'name': 'fishing_minion', 'tier': 10},
           collection_req=('fish', 1)),
    Recipe('fishing_minion_11', 'fishing',
           [{'name': 'fishing_minion', 'tier': 10},
            {'name': 'enchanted_cooked_fish', 'count': 8}],
           {'name': 'fishing_minion', 'tier': 11},
           collection_req=('fish', 1)),
    RecipeGroup('fishing_minion', 'fishing',
                ['fishing_minion_1', 'fishing_minion_2', 'fishing_minion_3',
                 'fishing_minion_4', 'fishing_minion_5', 'fishing_minion_6',
                 'fishing_minion_7', 'fishing_minion_8', 'fishing_minion_9',
                 'fishing_minion_10', 'fishing_minion_11'],
                collection_req=('fish', 1)),

    Recipe('clay_minion_1', 'fishing',
           [{'name': 'wooden_pickaxe'},
            {'name': 'clay', 'count': 64}],
           {'name': 'clay_minion', 'tier': 1},
           collection_req=('clay', 1)),
    Recipe('clay_minion_2', 'fishing',
           [{'name': 'clay_minion', 'tier': 1},
            {'name': 'clay', 'count': 128}],
           {'name': 'clay_minion', 'tier': 2},
           collection_req=('clay', 1)),
    Recipe('clay_minion_3', 'fishing',
           [{'name': 'clay_minion', 'tier': 2},
            {'name': 'clay', 'count': 256}],
           {'name': 'clay_minion', 'tier': 3},
           collection_req=('clay', 1)),
    Recipe('clay_minion_4', 'fishing',
           [{'name': 'clay_minion', 'tier': 3},
            {'name': 'clay', 'count': 512}],
           {'name': 'clay_minion', 'tier': 4},
           collection_req=('clay', 1)),
    Recipe('clay_minion_5', 'fishing',
           [{'name': 'clay_minion', 'tier': 4},
            {'name': 'enchanted_clay', 'count': 8}],
           {'name': 'clay_minion', 'tier': 5},
           collection_req=('clay', 1)),
    Recipe('clay_minion_6', 'fishing',
           [{'name': 'clay_minion', 'tier': 5},
            {'name': 'enchanted_clay', 'count': 16}],
           {'name': 'clay_minion', 'tier': 6},
           collection_req=('clay', 1)),
    Recipe('clay_minion_7', 'fishing',
           [{'name': 'clay_minion', 'tier': 6},
            {'name': 'enchanted_clay', 'count': 32}],
           {'name': 'clay_minion', 'tier': 7},
           collection_req=('clay', 1)),
    Recipe('clay_minion_8', 'fishing',
           [{'name': 'clay_minion', 'tier': 7},
            {'name': 'enchanted_clay', 'count': 64}],
           {'name': 'clay_minion', 'tier': 8},
           collection_req=('clay', 1)),
    Recipe('clay_minion_9', 'fishing',
           [{'name': 'clay_minion', 'tier': 8},
            {'name': 'enchanted_clay', 'count': 128}],
           {'name': 'clay_minion', 'tier': 9},
           collection_req=('clay', 1)),
    Recipe('clay_minion_10', 'fishing',
           [{'name': 'clay_minion', 'tier': 9},
            {'name': 'enchanted_clay', 'count': 256}],
           {'name': 'clay_minion', 'tier': 10},
           collection_req=('clay', 1)),
    Recipe('clay_minion_11', 'fishing',
           [{'name': 'clay_minion', 'tier': 10},
            {'name': 'enchanted_clay', 'count': 512}],
           {'name': 'clay_minion', 'tier': 11},
           collection_req=('clay', 1)),
    RecipeGroup('clay_minion', 'fishing',
                ['clay_minion_1', 'clay_minion_2', 'clay_minion_3',
                 'clay_minion_4', 'clay_minion_5', 'clay_minion_6',
                 'clay_minion_7', 'clay_minion_8', 'clay_minion_9',
                 'clay_minion_10', 'clay_minion_11'],
                collection_req=('clay', 1)),
]
