from ..item import get_item
from ..object import *


FISHING_MINION_RECIPES = [
    Recipe('fishing_minion_1', 'fishing',
           [(get_item('wooden_sword'), 1),
            (Item('fish'), 64)],
           (get_item('fishing_minion', tier=1), 1),
           collection_req=('fish', 1)),
    Recipe('fishing_minion_2', 'fishing',
           [(get_item('fishing_minion', tier=1), 1),
            (Item('fish'), 128)],
           (get_item('fishing_minion', tier=2), 1),
           collection_req=('fish', 1)),
    Recipe('fishing_minion_3', 'fishing',
           [(get_item('fishing_minion', tier=2), 1),
            (Item('fish'), 256)],
           (get_item('fishing_minion', tier=3), 1),
           collection_req=('fish', 1)),
    Recipe('fishing_minion_4', 'fishing',
           [(get_item('fishing_minion', tier=3), 1),
            (Item('fish'), 512)],
           (get_item('fishing_minion', tier=4), 1),
           collection_req=('fish', 1)),
    Recipe('fishing_minion_5', 'fishing',
           [(get_item('fishing_minion', tier=4), 1),
            (Item('enchanted_fish'), 8)],
           (get_item('fishing_minion', tier=5), 1),
           collection_req=('fish', 1)),
    Recipe('fishing_minion_6', 'fishing',
           [(get_item('fishing_minion', tier=5), 1),
            (Item('enchanted_fish'), 24)],
           (get_item('fishing_minion', tier=6), 1),
           collection_req=('fish', 1)),
    Recipe('fishing_minion_7', 'fishing',
           [(get_item('fishing_minion', tier=6), 1),
            (Item('enchanted_fish'), 64)],
           (get_item('fishing_minion', tier=7), 1),
           collection_req=('fish', 1)),
    Recipe('fishing_minion_8', 'fishing',
           [(get_item('fishing_minion', tier=7), 1),
            (Item('enchanted_fish'), 128)],
           (get_item('fishing_minion', tier=8), 1),
           collection_req=('fish', 1)),
    Recipe('fishing_minion_9', 'fishing',
           [(get_item('fishing_minion', tier=8), 1),
            (Item('enchanted_fish'), 256)],
           (get_item('fishing_minion', tier=9), 1),
           collection_req=('fish', 1)),
    Recipe('fishing_minion_10', 'fishing',
           [(get_item('fishing_minion', tier=9), 1),
            (Item('enchanted_fish'), 512)],
           (get_item('fishing_minion', tier=10), 1),
           collection_req=('fish', 1)),
    Recipe('fishing_minion_11', 'fishing',
           [(get_item('fishing_minion', tier=10), 1),
            (Item('enchanted_cooked_fish'), 8)],
           (get_item('fishing_minion', tier=11), 1),
           collection_req=('fish', 1)),
    RecipeGroup('fishing_minion', 'fishing',
                ['fishing_minion_1', 'fishing_minion_2', 'fishing_minion_3',
                 'fishing_minion_4', 'fishing_minion_5', 'fishing_minion_6',
                 'fishing_minion_7', 'fishing_minion_8', 'fishing_minion_9',
                 'fishing_minion_10', 'fishing_minion_11'],
                collection_req=('fish', 1)),

    Recipe('clay_minion_1', 'fishing',
           [(get_item('wooden_pickaxe'), 1),
            (Item('clay'), 64)],
           (get_item('clay_minion', tier=1), 1),
           collection_req=('clay', 1)),
    Recipe('clay_minion_2', 'fishing',
           [(get_item('clay_minion', tier=1), 1),
            (Item('clay'), 128)],
           (get_item('clay_minion', tier=2), 1),
           collection_req=('clay', 1)),
    Recipe('clay_minion_3', 'fishing',
           [(get_item('clay_minion', tier=2), 1),
            (Item('clay'), 256)],
           (get_item('clay_minion', tier=3), 1),
           collection_req=('clay', 1)),
    Recipe('clay_minion_4', 'fishing',
           [(get_item('clay_minion', tier=3), 1),
            (Item('clay'), 512)],
           (get_item('clay_minion', tier=4), 1),
           collection_req=('clay', 1)),
    Recipe('clay_minion_5', 'fishing',
           [(get_item('clay_minion', tier=4), 1),
            (Item('enchanted_clay'), 8)],
           (get_item('clay_minion', tier=5), 1),
           collection_req=('clay', 1)),
    Recipe('clay_minion_6', 'fishing',
           [(get_item('clay_minion', tier=5), 1),
            (Item('enchanted_clay'), 16)],
           (get_item('clay_minion', tier=6), 1),
           collection_req=('clay', 1)),
    Recipe('clay_minion_7', 'fishing',
           [(get_item('clay_minion', tier=6), 1),
            (Item('enchanted_clay'), 32)],
           (get_item('clay_minion', tier=7), 1),
           collection_req=('clay', 1)),
    Recipe('clay_minion_8', 'fishing',
           [(get_item('clay_minion', tier=7), 1),
            (Item('enchanted_clay'), 64)],
           (get_item('clay_minion', tier=8), 1),
           collection_req=('clay', 1)),
    Recipe('clay_minion_9', 'fishing',
           [(get_item('clay_minion', tier=8), 1),
            (Item('enchanted_clay'), 128)],
           (get_item('clay_minion', tier=9), 1),
           collection_req=('clay', 1)),
    Recipe('clay_minion_10', 'fishing',
           [(get_item('clay_minion', tier=9), 1),
            (Item('enchanted_clay'), 256)],
           (get_item('clay_minion', tier=10), 1),
           collection_req=('clay', 1)),
    Recipe('clay_minion_11', 'fishing',
           [(get_item('clay_minion', tier=10), 1),
            (Item('enchanted_clay'), 512)],
           (get_item('clay_minion', tier=11), 1),
           collection_req=('clay', 1)),
    RecipeGroup('clay_minion', 'fishing',
                ['clay_minion_1', 'clay_minion_2', 'clay_minion_3',
                 'clay_minion_4', 'clay_minion_5', 'clay_minion_6',
                 'clay_minion_7', 'clay_minion_8', 'clay_minion_9',
                 'clay_minion_10', 'clay_minion_11'],
                collection_req=('clay', 1)),
]
