from ..object import *


FISHING_RECIPES = [
    Recipe('fishing_rod', 'fishing',
           [{'name': 'stick', 'count': 3},
            {'name': 'string', 'count': 2}],
           {'name': 'fishing_rod'}),

    Recipe('divers_mask', 'fishing',
           [{'name': 'emperors_skull', 'count': 5}],
           {'name': 'divers_mask'}),
    Recipe('divers_shirt', 'fishing',
           [{'name': 'emperors_skull', 'count': 8}],
           {'name': 'divers_shirt'}),
    Recipe('divers_trunks', 'fishing',
           [{'name': 'emperors_skull', 'count': 7}],
           {'name': 'divers_trunks'}),
    Recipe('divers_boots', 'fishing',
           [{'name': 'emperors_skull', 'count': 4}],
           {'name': 'divers_boots'}),
    RecipeGroup('divers_armor', 'fishing',
                ['divers_helmet', 'divers_chestplate',
                 'divers_leggings', 'divers_boots']),

    Recipe('carrot_bait', 'fishing',
           [{'name': 'carrot'},
            {'name': 'fish'}],
           {'name': 'carrot_bait'}),
    Recipe('shark_bait', 'fishing',
           [{'name': 'shark_fin', 'count': 2}],
           {'name': 'shark_bait', 'count': 16}),

    Recipe('fish_hat', 'fishing',
           [{'name': 'fish', 'count': 8}],
           {'name': 'fish_hat'},
           collection_req=('fish', 1)),
    Recipe('angler_helmet', 'fishing',
           [{'name': 'fish', 'count': 5}],
           {'name': 'angler_helmet'},
           collection_req=('fish', 5)),
    Recipe('angler_chestplate', 'fishing',
           [{'name': 'fish', 'count': 8}],
           {'name': 'angler_chestplate'},
           collection_req=('fish', 5)),
    Recipe('angler_leggings', 'fishing',
           [{'name': 'fish', 'count': 7}],
           {'name': 'angler_leggings'},
           collection_req=('fish', 5)),
    Recipe('angler_boots', 'fishing',
           [{'name': 'fish', 'count': 4}],
           {'name': 'angler_boots'},
           collection_req=('fish', 5)),
    RecipeGroup('angler_armor', 'fishing',
                ['angler_helmet', 'angler_chestplate',
                 'angler_leggings', 'angler_boots'],
                collection_req=('fish', 5)),
    Recipe('fish_to_enchanted', 'fishing',
           [{'name': 'fish', 'count': 160}],
           {'name': 'enchanted_fish'},
           collection_req=('fish', 6)),
    Recipe('fish_to_enchanted_cooked', 'fishing',
           [{'name': 'enchanted_fish', 'count': 160}],
           {'name': 'enchanted_cooked_fish'},
           collection_req=('fish', 8)),

    Recipe('minnow_bait', 'fishing',
           [{'name': 'fish', 'count': 2}],
           {'name': 'minnow_bait'},
           collection_req=('salmon', 1)),
    Recipe('lure_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'salmon', 'count': 8}],
           {'name': 'enchanted_book', 'enchantments': {'lure': 4}},
           collection_req=('salmon', 3)),
    Recipe('salmon_to_enchanted', 'fishing',
           [{'name': 'salmon', 'count': 160}],
           {'name': 'enchanted_salmon'},
           collection_req=('salmon', 4)),
    Recipe('speedster_rod', 'fishing',
           [{'name': 'salmon', 'count': 96},
            {'name': 'string', 'count': 2}],
           {'name': 'speedster_rod'},
           collection_req=('salmon', 5)),
    Recipe('fish_bait', 'fishing',
           [{'name': 'fish', 'count': 2},
            {'name': 'salmon'}],
           {'name': 'fish_bait'},
           collection_req=('salmon', 6)),
    Recipe('salmon_to_enchanted_cooked', 'fishing',
           [{'name': 'enchanted_salmon', 'count': 160}],
           {'name': 'enchanted_cooked_salmon'},
           collection_req=('salmon', 8)),
    Recipe('salmon_helmet', 'fishing',
           [{'name': 'enchanted_salmon', 'count': 5}],
           {'name': 'salmon_helmet'},
           collection_req=('salmon', 9)),
    Recipe('salmon_chestplate', 'fishing',
           [{'name': 'enchanted_salmon', 'count': 8}],
           {'name': 'salmon_chestplate'},
           collection_req=('salmon', 9)),
    Recipe('salmon_leggings', 'fishing',
           [{'name': 'enchanted_salmon', 'count': 7}],
           {'name': 'salmon_leggings'},
           collection_req=('salmon', 9)),
    Recipe('salmon_boots', 'fishing',
           [{'name': 'enchanted_salmon', 'count': 4}],
           {'name': 'salmon_boots'},
           collection_req=('salmon', 9)),
    RecipeGroup('salmon_armor', 'fishing',
                ['salmon_helmet', 'salmon_chestplate',
                 'salmon_leggings', 'salmon_boots'],
                collection_req=('salmon', 9)),

    Recipe('clownfish_hat', 'fishing',
           [{'name': 'clownfish', 'count': 8}],
           {'name': 'clownfish_hat'},
           collection_req=('clownfish', 1)),
    Recipe('magnet_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'clownfish', 'count': 8},
            {'name': 'quartz', 'count': 8}],
           {'name': 'enchanted_book', 'enchantments': {'magnet': 4}},
           collection_req=('clownfish', 3)),

    Recipe('pufferfish_hat', 'fishing',
           [{'name': 'pufferfish', 'count': 8}],
           {'name': 'pufferfish_hat'},
           collection_req=('pufferfish', 1)),
    Recipe('pufferfish_to_enchanted', 'fishing',
           [{'name': 'pufferfish', 'count': 160}],
           {'name': 'enchanted_pufferfish'},
           collection_req=('pufferfish', 2)),
    Recipe('cleave_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'pufferfish', 'count': 40}],
           {'name': 'enchanted_book', 'enchantments': {'cleave': 4}},
           collection_req=('pufferfish', 3)),
    Recipe('spiked_bait', 'fishing',
           [{'name': 'fish'},
            {'name': 'pufferfish'}],
           {'name': 'spiked_bait'},
           collection_req=('pufferfish', 5)),
    Recipe('spiked_hook_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'pufferfish', 'count': 64},
            {'name': 'gravel', 'count': 40}],
           {'name': 'enchanted_book', 'enchantments': {'spiked_hook': 4}},
           collection_req=('pufferfish', 6)),

    Recipe('impaling_book', 'enchanting',
           [{'name': 'paper', 'count': 6},
            {'name': 'prismarine_shard', 'count': 20}],
           {'name': 'enchanted_book', 'enchantments': {'impaling': 2}},
           collection_req=('prismarine_shard', 1)),
    Recipe('prismarine_blade', 'fishing',
           [{'name': 'prismarine_shard', 'count': 64},
            {'name': 'stick'}],
           {'name': 'prismarine_blade'},
           collection_req=('prismarine_shard', 2)),
    Recipe('prismarine_shard_to_enchanted', 'fishing',
           [{'name': 'prismarine_shard', 'count': 80}],
           {'name': 'enchanted_prismarine_shard'},
           collection_req=('prismarine_shard', 3)),
    Recipe('prismarine_rod', 'fishing',
           [{'name': 'prismarine_shard', 'count': 2},
            {'name': 'prismarine_crystals'},
            {'name': 'string', 'count': 2}],
           {'name': 'prismarine_rod'},
           collection_req=('prismarine_shard', 4)),
    Recipe('prismarine_bow', 'fishing',
           [{'name': 'prismarine_shard', 'count': 48},
            {'name': 'string', 'count': 3}],
           {'name': 'prismarine_bow'},
           collection_req=('prismarine_shard', 5)),

    Recipe('light_bait', 'fishing',
           [{'name': 'prismarine_crystals', 'count': 2},
            {'name': 'fish'}],
           {'name': 'light_bait'},
           collection_req=('prismarine_crystals', 2)),
    Recipe('prismarine_crystals_to_enchanted', 'fishing',
           [{'name': 'prismarine_crystals', 'count': 80}],
           {'name': 'enchanted_prismarine_crystals'},
           collection_req=('prismarine_crystals', 3)),
    Recipe('guardian_chestplate', 'fishing',
           [{'name': 'prismarine_shard', 'count': 256},
            {'name': 'prismarine_crystals', 'count': 256}],
           {'name': 'guardian_chestplate'},
           collection_req=('prismarine_crystals', 5)),
    Recipe('blessed_bait', 'fishing',
           [{'name': 'prismarine_crystals'},
            {'name': 'fish'},
            {'name': 'gold_block'}],
           {'name': 'blessed_bait'},
           collection_req=('prismarine_crystals', 6)),
    Recipe('blessing_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'enchanted_pufferfish', 'count': 8},
            {'name': 'gold_block', 'count': 64}],
           {'name': 'enchanted_book', 'enchantments': {'blessing': 4}},
           collection_req=('prismarine_crystals', 7)),

    Recipe('clay_to_enchanted', 'fishing',
           [{'name': 'clay', 'count': 160}],
           {'name': 'enchanted_clay'},
           collection_req=('clay', 2)),
    Recipe('frail_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'pufferfish', 'count': 64},
            {'name': 'lily_pad', 'count': 40}],
           {'name': 'enchanted_book', 'enchantments': {'frail': 4}},
           collection_req=('clay', 4)),

    Recipe('spooky_bait', 'fishing',
           [{'name': 'pumpkin'},
            {'name': 'fish'}],
           {'name': 'spooky_bait'},
           collection_req=('lily_pad', 1)),
    Recipe('blobfish_hat', 'fishing',
           [{'name': 'lily_pad', 'count': 5},
            {'name': 'clay', 'count': 4}],
           {'name': 'blobfish_hat'},
           collection_req=('lily_pad', 2)),
    Recipe('healing_talisman', 'fishing',
           [{'name': 'lily_pad', 'count': 144}],
           {'name': 'healing_talisman'},
           collection_req=('lily_pad', 3)),
    Recipe('lily_pad_to_enchanted', 'fishing',
           [{'name': 'lily_pad', 'count': 160}],
           {'name': 'enchanted_lily_pad'},
           collection_req=('lily_pad', 4)),
    Recipe('challenging_rod', 'fishing',
           [{'name': 'fishing_rod'},
            {'name': 'lily_pad', 'count': 512}],
           {'name': 'challenging_rod'},
           collection_req=('lily_pad', 5)),
    Recipe('whale_bait', 'fishing',
           [{'name': 'fish_bait'},
            {'name': 'light_bait'},
            {'name': 'dark_bait'},
            {'name': 'blessed_bait'}],
           {'name': 'whale_bait'},
           collection_req=('lily_pad', 6)),
    Recipe('rod_of_champions', 'fishing',
           [{'name': 'challenging_rod'},
            {'name': 'enchanted_lily_pad', 'count': 8}],
           {'name': 'rod_of_champions'},
           collection_req=('lily_pad', 7)),
    Recipe('healing_ring', 'fishing',
           [{'name': 'healing_talisman'},
            {'name': 'enchanted_lily_pad', 'count': 4}],
           {'name': 'healing_ring'},
           collection_req=('lily_pad', 8)),
    Recipe('rod_of_legends', 'fishing',
           [{'name': 'rod_of_champions'},
            {'name': 'enchanted_lily_pad', 'count': 128}],
           {'name': 'rod_of_legends'},
           collection_req=('lily_pad', 9)),

    Recipe('squid_hat', 'fishing',
           [{'name': 'ink_sack', 'count': 8}],
           {'name': 'squid_hat'},
           collection_req=('ink_sack', 1)),
    Recipe('dark_bait', 'fishing',
           [{'name': 'ink_sack'},
            {'name': 'fish'}],
           {'name': 'dark_bait'},
           collection_req=('ink_sack', 2)),
    Recipe('ink_sack_to_enchanted', 'fishing',
           [{'name': 'ink_sack', 'count': 80}],
           {'name': 'enchanted_ink_sack'},
           collection_req=('ink_sack', 3)),
    Recipe('caster_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'whale_bait', 'count': 8},
            {'name': 'lily_pad', 'count': 8}],
           {'name': 'enchanted_book', 'enchantments': {'caster': 4}},
           collection_req=('ink_sack', 5)),
    Recipe('angler_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'ink_sack', 'count': 32}],
           {'name': 'enchanted_book', 'enchantments': {'angler': 4}},
           collection_req=('ink_sack', 7)),
    Recipe('ink_wand', 'fishing',
           [{'name': 'enchanted_ink_sack', 'count': 64},
            {'name': 'stick'}],
           {'name': 'ink_wand'},
           collection_req=('ink_sack', 9)),

    Recipe('sponge_rod', 'fishing',
           [{'name': 'sponge', 'count': 3},
            {'name': 'string', 'count': 2}],
           {'name': 'sponge_rod'},
           collection_req=('sponge', 1)),
    Recipe('sponge_to_enchanted', 'fishing',
           [{'name': 'sponge', 'count': 40}],
           {'name': 'enchanted_sponge'},
           collection_req=('sponge', 3)),
    Recipe('sea_creature_talisman', 'fishing',
           [{'name': 'sponge', 'count': 18}],
           {'name': 'sea_creature_talisman'},
           collection_req=('sponge', 4)),
    Recipe('stereo_pants', 'fishing',
           [{'name': 'enchanted_sponge', 'count': 3},
            {'name': 'prismarine_shard', 'count': 4}],
           {'name': 'stereo_pants'},
           collection_req=('sponge', 5)),
    Recipe('sea_creature_ring', 'fishing',
           [{'name': 'sea_creature_talisman'},
            {'name': 'enchanted_sponge', 'count': 2},
            {'name': 'sponge', 'count': 6}],
           {'name': 'sea_creature_ring'},
           collection_req=('sponge', 6)),
    Recipe('sponge_to_enchanted_wet', 'fishing',
           [{'name': 'enchanted_sponge', 'count': 40}],
           {'name': 'enchanted_wet_sponge'},
           collection_req=('sponge', 7)),
    Recipe('sea_creature_artifact', 'fishing',
           [{'name': 'sea_creature_ring'},
            {'name': 'enchanted_sponge', 'count': 64}],
           {'name': 'sea_creature_artifact'},
           collection_req=('sponge', 8)),
    Recipe('sponge_helmet', 'fishing',
           [{'name': 'enchanted_wet_sponge', 'count': 5}],
           {'name': 'sponge_helmet'},
           collection_req=('sponge', 9)),
    Recipe('sponge_chestplate', 'fishing',
           [{'name': 'enchanted_wet_sponge', 'count': 8}],
           {'name': 'sponge_chestplate'},
           collection_req=('sponge', 9)),
    Recipe('sponge_leggings', 'fishing',
           [{'name': 'enchanted_wet_sponge', 'count': 7}],
           {'name': 'sponge_leggings'},
           collection_req=('sponge', 9)),
    Recipe('sponge_boots', 'fishing',
           [{'name': 'enchanted_wet_sponge', 'count': 4}],
           {'name': 'sponge_boots'},
           collection_req=('sponge', 9)),
    RecipeGroup('sponge_armor', 'fishing',
                ['sponge_helmet', 'sponge_chestplate',
                 'sponge_leggings', 'sponge_boots'],
                collection_req=('sponge', 9)),
]
