from ..item import get_item, get_scroll
from ..object import Item, Recipe, EnchantedBook


__all__ = ['FORAGING_RECIPES']

FORAGING_RECIPES = [
    Recipe('wooden_axe', 'foraging',
           [(Item('planks'), 3),
            (Item('stick'), 2)],
           (get_item('wooden_axe'), 1)),
    Recipe('gold_axe', 'foraging',
           [(Item('gold'), 3),
            (Item('stick'), 2)],
           (get_item('golden_axe'), 1)),
    Recipe('stone_axe', 'foraging',
           [(Item('cobblestone'), 3),
            (Item('stick'), 2)],
           (get_item('stone_axe'), 1)),
    Recipe('iron_axe', 'foraging',
           [(Item('iron'), 3),
            (Item('stick'), 2)],
           (get_item('iron_axe'), 1)),
    Recipe('diamond_axe', 'foraging',
           [(Item('diamond'), 3),
            (Item('stick'), 2)],
           (get_item('diamond_axe'), 1)),

    Recipe('oak_to_planks', 'foraging',
           [(Item('oak_wood'), 1)],
           (Item('planks'), 4)),
    Recipe('birch_to_planks', 'foraging',
           [(Item('birch_wood'), 1)],
           (Item('planks'), 4)),
    Recipe('spruce_to_planks', 'foraging',
           [(Item('spruce_wood'), 1)],
           (Item('planks'), 4)),
    Recipe('dark_to_planks', 'foraging',
           [(Item('dark_oak_wood'), 1)],
           (Item('planks'), 4)),
    Recipe('acacia_to_planks', 'foraging',
           [(Item('acacia_wood'), 1)],
           (Item('planks'), 4)),
    Recipe('jungle_to_planks', 'foraging',
           [(Item('jungle_wood'), 1)],
           (Item('planks'), 4)),
    Recipe('planks_to_stick', 'foraging',
           [(Item('planks'), 2)],
           (Item('stick'), 4)),

    Recipe('oak_leaves', 'foraging',
           [(Item('oak_sapling'), 1)],
           (Item('oak_leaves'), 1),
           collection_req=('oak_wood', 2)),

    Recipe('leaflet_helmet', 'foraging',
           [(Item('oak_leaves'), 5)],
           (get_item('leaflet_helmet'), 1),
           collection_req=('oak_wood', 3)),
    Recipe('leaflet_chestplate', 'foraging',
           [(Item('oak_leaves'), 8)],
           (get_item('leaflet_chestplate'), 1),
           collection_req=('oak_wood', 3)),
    Recipe('leaflet_leggings', 'foraging',
           [(Item('oak_leaves'), 7)],
           (get_item('leaflet_leggings'), 1),
           collection_req=('oak_wood', 3)),
    Recipe('leaflet_boots', 'foraging',
           [(Item('oak_leaves'), 4)],
           (get_item('leaflet_boots'), 1),
           collection_req=('oak_wood', 3)),

    Recipe('oak_to_enchanted', 'foraging',
           [(Item('oak_wood'), 160)],
           (Item('enchanted_oak'), 1),
           collection_req=('oak_wood', 6)),

    Recipe('birch_leaves', 'foraging',
           [(Item('birch_sapling'), 1)],
           (Item('birch_leaves'), 1),
           collection_req=('birch_wood', 2)),
    Recipe('birch_to_enchanted', 'foraging',
           [(Item('birch_wood'), 160)],
           (Item('enchanted_birch'), 1),
           collection_req=('birch_wood', 6)),
    Recipe('scroll_to_park', 'foraging',
           [(Item('enchanted_ender_pearl'), 16),
            (Item('enchanted_birch'), 128)],
           (get_scroll('park'), 1),
           collection_req=('birch_wood', 8)),

    Recipe('spruce_leaves', 'foraging',
           [(Item('spruce_sapling'), 1)],
           (Item('spruce_leaves'), 1),
           collection_req=('spruce_wood', 2)),
    Recipe('spruce_to_enchanted', 'foraging',
           [(Item('spruce_wood'), 160)],
           (Item('enchanted_spruce'), 1),
           collection_req=('spruce_wood', 5)),
    Recipe('uncommon_wolf_pet', 'combat',
           [(Item('enchanted_spruce'), 512),
            (Item('enchanted_egg'), 1)],
           (get_item('wolf_pet', rarity='uncommon'), 1),
           collection_req=('spruce_wood', 8)),
    Recipe('epic_wolf_pet', 'combat',
           [(Item('enchanted_spruce'), 512),
            (Item('super_enchanted_egg'), 1)],
           (get_item('wolf_pet', rarity='epic'), 1),
           collection_req=('spruce_wood', 8)),

    Recipe('dark_oak_leaves', 'foraging',
           [(Item('dark_oak_sapling'), 1)],
           (Item('dark_oak_leaves'), 1),
           collection_req=('dark_oak_wood', 2)),
    Recipe('dark_oak_to_enchanted', 'foraging',
           [(Item('dark_oak_wood'), 160)],
           (Item('enchanted_dark_oak'), 1),
           collection_req=('dark_oak_wood', 5)),
    Recipe('growth_book', 'foraging',
           [(Item('paper'), 24),
            (Item('enchanted_dark_oak'), 8)],
           (EnchantedBook(enchantments={'growth': 4}), 1),
           collection_req=('dark_oak_wood', 7)),

    Recipe('growth_helmet', 'foraging',
           [(Item('enchanted_dark_oak'), 320)],
           (get_item('growth_helmet'), 1),
           collection_req=('dark_oak_wood', 9)),
    Recipe('growth_chestplate', 'foraging',
           [(Item('enchanted_dark_oak'), 512)],
           (get_item('growth_chestplate'), 1),
           collection_req=('dark_oak_wood', 9)),
    Recipe('growth_leggings', 'foraging',
           [(Item('enchanted_dark_oak'), 448)],
           (get_item('growth_leggings'), 1),
           collection_req=('dark_oak_wood', 9)),
    Recipe('growth_boots', 'foraging',
           [(Item('enchanted_dark_oak'), 256)],
           (get_item('growth_boots'), 1),
           collection_req=('dark_oak_wood', 9)),

    Recipe('acacia_leaves', 'foraging',
           [(Item('acacia_sapling'), 1)],
           (Item('acacia_leaves'), 1),
           collection_req=('acacia_wood', 2)),
    Recipe('acacia_to_enchanted', 'foraging',
           [(Item('acacia_wood'), 160)],
           (Item('enchanted_acacia'), 1),
           collection_req=('acacia_wood', 6)),
    Recipe('savanna_bow', 'foraging',
           [(Item('enchanted_acacia'), 3),
            (Item('enchanted_string'), 3)],
           (Item('savanna_bow'), 1),
           collection_req=('acacia_wood', 7)),

    Recipe('jungle_leaves', 'foraging',
           [(Item('jungle_sapling'), 1)],
           (Item('jungle_leaves'), 1),
           collection_req=('jungle_wood', 2)),
    Recipe('jungle_to_enchanted', 'foraging',
           [(Item('jungle_wood'), 160)],
           (Item('enchanted_jungle'), 1),
           collection_req=('jungle_wood', 6)),
    Recipe('jungle_axe', 'foraging',
           [(Item('enchanted_jungle'), 3),
            (Item('stick'), 2)],
           (get_item('jungle_axe'), 1),
           collection_req=('jungle_wood', 7)),
    Recipe('uncommon_ocelot_pet', 'foraging',
           [(Item('enchanted_jungle'), 512),
            (Item('enchanted_egg'), 1)],
           (get_item('ocelot_pet', rarity='uncommon'), 1),
           collection_req=('jungle_wood', 9)),
    Recipe('epic_ocelot_pet', 'foraging',
           [(Item('enchanted_jungle'), 512),
            (Item('super_enchanted_egg'), 1)],
           (get_item('ocelot_pet', rarity='epic'), 1),
           collection_req=('jungle_wood', 9)),

    Recipe('dandelion_to_enchanted', 'foraging',
           [(Item('dandelion'), 160)],
           (Item('enchanted_dandelion'), 1)),
    Recipe('poppy_to_enchanted', 'foraging',
           [(Item('poppy'), 576)],
           (Item('enchanted_poppy'), 1)),
]
