from ..object import *


FORAGING_MINION_RECIPES = [
    Recipe('oak_minion_1', 'foraging',
           [{'name': 'wooden_axe'},
            {'name': 'oak_wood', 'count': 80}],
           {'name': 'oak_minion', 'tier': 1},
           collection_req=('oak_wood', 1)),
    Recipe('oak_minion_2', 'foraging',
           [{'name': 'oak_minion', 'tier': 1},
            {'name': 'oak_wood', 'count': 160}],
           {'name': 'oak_minion', 'tier': 2},
           collection_req=('oak_wood', 1)),
    Recipe('oak_minion_3', 'foraging',
           [{'name': 'oak_minion', 'tier': 2},
            {'name': 'oak_wood', 'count': 320}],
           {'name': 'oak_minion', 'tier': 3},
           collection_req=('oak_wood', 1)),
    Recipe('oak_minion_4', 'foraging',
           [{'name': 'oak_minion', 'tier': 3},
            {'name': 'oak_wood', 'count': 512}],
           {'name': 'oak_minion', 'tier': 4},
           collection_req=('oak_wood', 1)),
    Recipe('oak_minion_5', 'foraging',
           [{'name': 'oak_minion', 'tier': 4},
            {'name': 'enchanted_oak', 'count': 8}],
           {'name': 'oak_minion', 'tier': 5},
           collection_req=('oak_wood', 1)),
    Recipe('oak_minion_6', 'foraging',
           [{'name': 'oak_minion', 'tier': 5},
            {'name': 'enchanted_oak', 'count': 16}],
           {'name': 'oak_minion', 'tier': 6},
           collection_req=('oak_wood', 1)),
    Recipe('oak_minion_7', 'foraging',
           [{'name': 'oak_minion', 'tier': 6},
            {'name': 'enchanted_oak', 'count': 32}],
           {'name': 'oak_minion', 'tier': 7},
           collection_req=('oak_wood', 1)),
    Recipe('oak_minion_8', 'foraging',
           [{'name': 'oak_minion', 'tier': 7},
            {'name': 'enchanted_oak', 'count': 64}],
           {'name': 'oak_minion', 'tier': 8},
           collection_req=('oak_wood', 1)),
    Recipe('oak_minion_9', 'foraging',
           [{'name': 'oak_minion', 'tier': 8},
            {'name': 'enchanted_oak', 'count': 128}],
           {'name': 'oak_minion', 'tier': 9},
           collection_req=('oak_wood', 1)),
    Recipe('oak_minion_10', 'foraging',
           [{'name': 'oak_minion', 'tier': 9},
            {'name': 'enchanted_oak', 'count': 256}],
           {'name': 'oak_minion', 'tier': 10},
           collection_req=('oak_wood', 1)),
    Recipe('oak_minion_11', 'foraging',
           [{'name': 'oak_minion', 'tier': 10},
            {'name': 'enchanted_oak', 'count': 512}],
           {'name': 'oak_minion', 'tier': 11},
           collection_req=('oak_wood', 1)),
    RecipeGroup('oak_minion', 'foraging',
                ['oak_minion_1', 'oak_minion_2', 'oak_minion_3',
                 'oak_minion_4', 'oak_minion_5', 'oak_minion_6',
                 'oak_minion_7', 'oak_minion_8', 'oak_minion_9',
                 'oak_minion_10', 'oak_minion_11'],
                collection_req=('oak_wood', 1)),

    Recipe('birch_minion_1', 'foraging',
           [{'name': 'wooden_axe'},
            {'name': 'birch_wood', 'count': 80}],
           {'name': 'birch_minion', 'tier': 1},
           collection_req=('birch_wood', 1)),
    Recipe('birch_minion_2', 'foraging',
           [{'name': 'birch_minion', 'tier': 1},
            {'name': 'birch_wood', 'count': 160}],
           {'name': 'birch_minion', 'tier': 2},
           collection_req=('birch_wood', 1)),
    Recipe('birch_minion_3', 'foraging',
           [{'name': 'birch_minion', 'tier': 2},
            {'name': 'birch_wood', 'count': 320}],
           {'name': 'birch_minion', 'tier': 3},
           collection_req=('birch_wood', 1)),
    Recipe('birch_minion_4', 'foraging',
           [{'name': 'birch_minion', 'tier': 3},
            {'name': 'birch_wood', 'count': 512}],
           {'name': 'birch_minion', 'tier': 4},
           collection_req=('birch_wood', 1)),
    Recipe('birch_minion_5', 'foraging',
           [{'name': 'birch_minion', 'tier': 4},
            {'name': 'enchanted_birch', 'count': 8}],
           {'name': 'birch_minion', 'tier': 5},
           collection_req=('birch_wood', 1)),
    Recipe('birch_minion_6', 'foraging',
           [{'name': 'birch_minion', 'tier': 5},
            {'name': 'enchanted_birch', 'count': 16}],
           {'name': 'birch_minion', 'tier': 6},
           collection_req=('birch_wood', 1)),
    Recipe('birch_minion_7', 'foraging',
           [{'name': 'birch_minion', 'tier': 6},
            {'name': 'enchanted_birch', 'count': 32}],
           {'name': 'birch_minion', 'tier': 7},
           collection_req=('birch_wood', 1)),
    Recipe('birch_minion_8', 'foraging',
           [{'name': 'birch_minion', 'tier': 7},
            {'name': 'enchanted_birch', 'count': 64}],
           {'name': 'birch_minion', 'tier': 8},
           collection_req=('birch_wood', 1)),
    Recipe('birch_minion_9', 'foraging',
           [{'name': 'birch_minion', 'tier': 8},
            {'name': 'enchanted_birch', 'count': 128}],
           {'name': 'birch_minion', 'tier': 9},
           collection_req=('birch_wood', 1)),
    Recipe('birch_minion_10', 'foraging',
           [{'name': 'birch_minion', 'tier': 9},
            {'name': 'enchanted_birch', 'count': 256}],
           {'name': 'birch_minion', 'tier': 10},
           collection_req=('birch_wood', 1)),
    Recipe('birch_minion_11', 'foraging',
           [{'name': 'birch_minion', 'tier': 10},
            {'name': 'enchanted_birch', 'count': 512}],
           {'name': 'birch_minion', 'tier': 11},
           collection_req=('birch_wood', 1)),
    RecipeGroup('birch_minion', 'foraging',
                ['birch_minion_1', 'birch_minion_2', 'birch_minion_3',
                 'birch_minion_4', 'birch_minion_5', 'birch_minion_6',
                 'birch_minion_7', 'birch_minion_8', 'birch_minion_9',
                 'birch_minion_10', 'birch_minion_11'],
                collection_req=('birch_wood', 1)),

    Recipe('spruce_minion_1', 'foraging',
           [{'name': 'wooden_axe'},
            {'name': 'spruce_wood', 'count': 80}],
           {'name': 'spruce_minion', 'tier': 1},
           collection_req=('spruce_wood', 1)),
    Recipe('spruce_minion_2', 'foraging',
           [{'name': 'spruce_minion', 'tier': 1},
            {'name': 'spruce_wood', 'count': 160}],
           {'name': 'spruce_minion', 'tier': 2},
           collection_req=('spruce_wood', 1)),
    Recipe('spruce_minion_3', 'foraging',
           [{'name': 'spruce_minion', 'tier': 2},
            {'name': 'spruce_wood', 'count': 320}],
           {'name': 'spruce_minion', 'tier': 3},
           collection_req=('spruce_wood', 1)),
    Recipe('spruce_minion_4', 'foraging',
           [{'name': 'spruce_minion', 'tier': 3},
            {'name': 'spruce_wood', 'count': 512}],
           {'name': 'spruce_minion', 'tier': 4},
           collection_req=('spruce_wood', 1)),
    Recipe('spruce_minion_5', 'foraging',
           [{'name': 'spruce_minion', 'tier': 4},
            {'name': 'enchanted_spruce', 'count': 8}],
           {'name': 'spruce_minion', 'tier': 5},
           collection_req=('spruce_wood', 1)),
    Recipe('spruce_minion_6', 'foraging',
           [{'name': 'spruce_minion', 'tier': 5},
            {'name': 'enchanted_spruce', 'count': 16}],
           {'name': 'spruce_minion', 'tier': 6},
           collection_req=('spruce_wood', 1)),
    Recipe('spruce_minion_7', 'foraging',
           [{'name': 'spruce_minion', 'tier': 6},
            {'name': 'enchanted_spruce', 'count': 32}],
           {'name': 'spruce_minion', 'tier': 7},
           collection_req=('spruce_wood', 1)),
    Recipe('spruce_minion_8', 'foraging',
           [{'name': 'spruce_minion', 'tier': 7},
            {'name': 'enchanted_spruce', 'count': 64}],
           {'name': 'spruce_minion', 'tier': 8},
           collection_req=('spruce_wood', 1)),
    Recipe('spruce_minion_9', 'foraging',
           [{'name': 'spruce_minion', 'tier': 8},
            {'name': 'enchanted_spruce', 'count': 128}],
           {'name': 'spruce_minion', 'tier': 9},
           collection_req=('spruce_wood', 1)),
    Recipe('spruce_minion_10', 'foraging',
           [{'name': 'spruce_minion', 'tier': 9},
            {'name': 'enchanted_spruce', 'count': 256}],
           {'name': 'spruce_minion', 'tier': 10},
           collection_req=('spruce_wood', 1)),
    Recipe('spruce_minion_11', 'foraging',
           [{'name': 'spruce_minion', 'tier': 10},
            {'name': 'enchanted_spruce', 'count': 512}],
           {'name': 'spruce_minion', 'tier': 11},
           collection_req=('spruce_wood', 1)),
    RecipeGroup('spruce_minion', 'foraging',
                ['spruce_minion_1', 'spruce_minion_2', 'spruce_minion_3',
                 'spruce_minion_4', 'spruce_minion_5', 'spruce_minion_6',
                 'spruce_minion_7', 'spruce_minion_8', 'spruce_minion_9',
                 'spruce_minion_10', 'spruce_minion_11'],
                collection_req=('spruce_wood', 1)),

    Recipe('dark_oak_minion_1', 'foraging',
           [{'name': 'wooden_axe'},
            {'name': 'dark_oak_wood', 'count': 80}],
           {'name': 'dark_oak_minion', 'tier': 1},
           collection_req=('dark_oak_wood', 1)),
    Recipe('dark_oak_minion_2', 'foraging',
           [{'name': 'dark_oak_minion', 'tier': 1},
            {'name': 'dark_oak_wood', 'count': 160}],
           {'name': 'dark_oak_minion', 'tier': 2},
           collection_req=('dark_oak_wood', 1)),
    Recipe('dark_oak_minion_3', 'foraging',
           [{'name': 'dark_oak_minion', 'tier': 2},
            {'name': 'dark_oak_wood', 'count': 320}],
           {'name': 'dark_oak_minion', 'tier': 3},
           collection_req=('dark_oak_wood', 1)),
    Recipe('dark_oak_minion_4', 'foraging',
           [{'name': 'dark_oak_minion', 'tier': 3},
            {'name': 'dark_oak_wood', 'count': 512}],
           {'name': 'dark_oak_minion', 'tier': 4},
           collection_req=('dark_oak_wood', 1)),
    Recipe('dark_oak_minion_5', 'foraging',
           [{'name': 'dark_oak_minion', 'tier': 4},
            {'name': 'enchanted_dark_oak', 'count': 8}],
           {'name': 'dark_oak_minion', 'tier': 5},
           collection_req=('dark_oak_wood', 1)),
    Recipe('dark_oak_minion_6', 'foraging',
           [{'name': 'dark_oak_minion', 'tier': 5},
            {'name': 'enchanted_dark_oak', 'count': 16}],
           {'name': 'dark_oak_minion', 'tier': 6},
           collection_req=('dark_oak_wood', 1)),
    Recipe('dark_oak_minion_7', 'foraging',
           [{'name': 'dark_oak_minion', 'tier': 6},
            {'name': 'enchanted_dark_oak', 'count': 32}],
           {'name': 'dark_oak_minion', 'tier': 7},
           collection_req=('dark_oak_wood', 1)),
    Recipe('dark_oak_minion_8', 'foraging',
           [{'name': 'dark_oak_minion', 'tier': 7},
            {'name': 'enchanted_dark_oak', 'count': 64}],
           {'name': 'dark_oak_minion', 'tier': 8},
           collection_req=('dark_oak_wood', 1)),
    Recipe('dark_oak_minion_9', 'foraging',
           [{'name': 'dark_oak_minion', 'tier': 8},
            {'name': 'enchanted_dark_oak', 'count': 128}],
           {'name': 'dark_oak_minion', 'tier': 9},
           collection_req=('dark_oak_wood', 1)),
    Recipe('dark_oak_minion_10', 'foraging',
           [{'name': 'dark_oak_minion', 'tier': 9},
            {'name': 'enchanted_dark_oak', 'count': 256}],
           {'name': 'dark_oak_minion', 'tier': 10},
           collection_req=('dark_oak_wood', 1)),
    Recipe('dark_oak_minion_11', 'foraging',
           [{'name': 'dark_oak_minion', 'tier': 10},
            {'name': 'enchanted_dark_oak', 'count': 512}],
           {'name': 'dark_oak_minion', 'tier': 11},
           collection_req=('dark_oak_wood', 1)),
    RecipeGroup('dark_oak_minion', 'foraging',
                ['dark_oak_minion_1', 'dark_oak_minion_2', 'dark_oak_minion_3',
                 'dark_oak_minion_4', 'dark_oak_minion_5', 'dark_oak_minion_6',
                 'dark_oak_minion_7', 'dark_oak_minion_8', 'dark_oak_minion_9',
                 'dark_oak_minion_10', 'dark_oak_minion_11'],
                collection_req=('dark_oak_wood', 1)),

    Recipe('acacia_minion_1', 'foraging',
           [{'name': 'wooden_axe'},
            {'name': 'acacia_wood', 'count': 80}],
           {'name': 'acacia_minion', 'tier': 1},
           collection_req=('acacia_wood', 1)),
    Recipe('acacia_minion_2', 'foraging',
           [{'name': 'acacia_minion', 'tier': 1},
            {'name': 'acacia_wood', 'count': 160}],
           {'name': 'acacia_minion', 'tier': 2},
           collection_req=('acacia_wood', 1)),
    Recipe('acacia_minion_3', 'foraging',
           [{'name': 'acacia_minion', 'tier': 2},
            {'name': 'acacia_wood', 'count': 320}],
           {'name': 'acacia_minion', 'tier': 3},
           collection_req=('acacia_wood', 1)),
    Recipe('acacia_minion_4', 'foraging',
           [{'name': 'acacia_minion', 'tier': 3},
            {'name': 'acacia_wood', 'count': 512}],
           {'name': 'acacia_minion', 'tier': 4},
           collection_req=('acacia_wood', 1)),
    Recipe('acacia_minion_5', 'foraging',
           [{'name': 'acacia_minion', 'tier': 4},
            {'name': 'enchanted_acacia', 'count': 8}],
           {'name': 'acacia_minion', 'tier': 5},
           collection_req=('acacia_wood', 1)),
    Recipe('acacia_minion_6', 'foraging',
           [{'name': 'acacia_minion', 'tier': 5},
            {'name': 'enchanted_acacia', 'count': 16}],
           {'name': 'acacia_minion', 'tier': 6},
           collection_req=('acacia_wood', 1)),
    Recipe('acacia_minion_7', 'foraging',
           [{'name': 'acacia_minion', 'tier': 6},
            {'name': 'enchanted_acacia', 'count': 32}],
           {'name': 'acacia_minion', 'tier': 7},
           collection_req=('acacia_wood', 1)),
    Recipe('acacia_minion_8', 'foraging',
           [{'name': 'acacia_minion', 'tier': 7},
            {'name': 'enchanted_acacia', 'count': 64}],
           {'name': 'acacia_minion', 'tier': 8},
           collection_req=('acacia_wood', 1)),
    Recipe('acacia_minion_9', 'foraging',
           [{'name': 'acacia_minion', 'tier': 8},
            {'name': 'enchanted_acacia', 'count': 128}],
           {'name': 'acacia_minion', 'tier': 9},
           collection_req=('acacia_wood', 1)),
    Recipe('acacia_minion_10', 'foraging',
           [{'name': 'acacia_minion', 'tier': 9},
            {'name': 'enchanted_acacia', 'count': 256}],
           {'name': 'acacia_minion', 'tier': 10},
           collection_req=('acacia_wood', 1)),
    Recipe('acacia_minion_11', 'foraging',
           [{'name': 'acacia_minion', 'tier': 10},
            {'name': 'enchanted_acacia', 'count': 512}],
           {'name': 'acacia_minion', 'tier': 11},
           collection_req=('acacia_wood', 1)),
    RecipeGroup('acacia_minion', 'foraging',
                ['acacia_minion_1', 'acacia_minion_2', 'acacia_minion_3',
                 'acacia_minion_4', 'acacia_minion_5', 'acacia_minion_6',
                 'acacia_minion_7', 'acacia_minion_8', 'acacia_minion_9',
                 'acacia_minion_10', 'acacia_minion_11'],
                collection_req=('acacia_wood', 1)),

    Recipe('jungle_minion_1', 'foraging',
           [{'name': 'wooden_axe'},
            {'name': 'jungle_wood', 'count': 80}],
           {'name': 'jungle_minion', 'tier': 1},
           collection_req=('jungle_wood', 1)),
    Recipe('jungle_minion_2', 'foraging',
           [{'name': 'jungle_minion', 'tier': 1},
            {'name': 'jungle_wood', 'count': 160}],
           {'name': 'jungle_minion', 'tier': 2},
           collection_req=('jungle_wood', 1)),
    Recipe('jungle_minion_3', 'foraging',
           [{'name': 'jungle_minion', 'tier': 2},
            {'name': 'jungle_wood', 'count': 320}],
           {'name': 'jungle_minion', 'tier': 3},
           collection_req=('jungle_wood', 1)),
    Recipe('jungle_minion_4', 'foraging',
           [{'name': 'jungle_minion', 'tier': 3},
            {'name': 'jungle_wood', 'count': 512}],
           {'name': 'jungle_minion', 'tier': 4},
           collection_req=('jungle_wood', 1)),
    Recipe('jungle_minion_5', 'foraging',
           [{'name': 'jungle_minion', 'tier': 4},
            {'name': 'enchanted_jungle', 'count': 8}],
           {'name': 'jungle_minion', 'tier': 5},
           collection_req=('jungle_wood', 1)),
    Recipe('jungle_minion_6', 'foraging',
           [{'name': 'jungle_minion', 'tier': 5},
            {'name': 'enchanted_jungle', 'count': 16}],
           {'name': 'jungle_minion', 'tier': 6},
           collection_req=('jungle_wood', 1)),
    Recipe('jungle_minion_7', 'foraging',
           [{'name': 'jungle_minion', 'tier': 6},
            {'name': 'enchanted_jungle', 'count': 32}],
           {'name': 'jungle_minion', 'tier': 7},
           collection_req=('jungle_wood', 1)),
    Recipe('jungle_minion_8', 'foraging',
           [{'name': 'jungle_minion', 'tier': 7},
            {'name': 'enchanted_jungle', 'count': 64}],
           {'name': 'jungle_minion', 'tier': 8},
           collection_req=('jungle_wood', 1)),
    Recipe('jungle_minion_9', 'foraging',
           [{'name': 'jungle_minion', 'tier': 8},
            {'name': 'enchanted_jungle', 'count': 128}],
           {'name': 'jungle_minion', 'tier': 9},
           collection_req=('jungle_wood', 1)),
    Recipe('jungle_minion_10', 'foraging',
           [{'name': 'jungle_minion', 'tier': 9},
            {'name': 'enchanted_jungle', 'count': 256}],
           {'name': 'jungle_minion', 'tier': 10},
           collection_req=('jungle_wood', 1)),
    Recipe('jungle_minion_11', 'foraging',
           [{'name': 'jungle_minion', 'tier': 10},
            {'name': 'enchanted_jungle', 'count': 512}],
           {'name': 'jungle_minion', 'tier': 11},
           collection_req=('jungle_wood', 1)),
    RecipeGroup('jungle_minion', 'foraging',
                ['jungle_minion_1', 'jungle_minion_2', 'jungle_minion_3',
                 'jungle_minion_4', 'jungle_minion_5', 'jungle_minion_6',
                 'jungle_minion_7', 'jungle_minion_8', 'jungle_minion_9',
                 'jungle_minion_10', 'jungle_minion_11'],
                collection_req=('jungle_wood', 1)),
]
