from ..object import *


FORAGING_RECIPES = [
    Recipe('wooden_axe', 'foraging',
           [{'name': 'planks', 'count': 3},
            {'name': 'stick', 'count': 2}],
           {'name': 'wooden_axe'}),
    Recipe('gold_axe', 'foraging',
           [{'name': 'gold', 'count': 3},
            {'name': 'stick', 'count': 2}],
           {'name': 'golden_axe'}),
    Recipe('stone_axe', 'foraging',
           [{'name': 'cobblestone', 'count': 3},
            {'name': 'stick', 'count': 2}],
           {'name': 'stone_axe'}),
    Recipe('iron_axe', 'foraging',
           [{'name': 'iron', 'count': 3},
            {'name': 'stick', 'count': 2}],
           {'name': 'iron_axe'}),
    Recipe('diamond_axe', 'foraging',
           [{'name': 'diamond', 'count': 3},
            {'name': 'stick', 'count': 2}],
           {'name': 'diamond_axe'}),

    Recipe('oak_to_planks', 'foraging',
           [{'name': 'oak_wood'}],
           {'name': 'planks', 'count': 4}),
    Recipe('birch_to_planks', 'foraging',
           [{'name': 'birch_wood'}],
           {'name': 'planks', 'count': 4}),
    Recipe('spruce_to_planks', 'foraging',
           [{'name': 'spruce_wood'}],
           {'name': 'planks', 'count': 4}),
    Recipe('dark_to_planks', 'foraging',
           [{'name': 'dark_oak_wood'}],
           {'name': 'planks', 'count': 4}),
    Recipe('acacia_to_planks', 'foraging',
           [{'name': 'acacia_wood'}],
           {'name': 'planks', 'count': 4}),
    Recipe('jungle_to_planks', 'foraging',
           [{'name': 'jungle_wood'}],
           {'name': 'planks', 'count': 4}),
    Recipe('planks_to_stick', 'foraging',
           [{'name': 'planks', 'count': 2}],
           {'name': 'stick', 'count': 4}),
    Recipe('planks_to_chest', 'foraging',
           [{'name': 'planks', 'count': 8}],
           {'name': 'chest'}),

    Recipe('dandelion_to_enchanted', 'foraging',
           [{'name': 'dandelion', 'count': 160}],
           {'name': 'enchanted_dandelion'}),
    Recipe('poppy_to_enchanted', 'foraging',
           [{'name': 'poppy', 'count': 576}],
           {'name': 'enchanted_poppy'}),

    Recipe('oak_leaves', 'foraging',
           [{'name': 'oak_sapling'}],
           {'name': 'oak_leaves'},
           collection_req=('oak_wood', 2)),
    Recipe('leaflet_helmet', 'foraging',
           [{'name': 'oak_leaves', 'count': 5}],
           {'name': 'leaflet_helmet'},
           collection_req=('oak_wood', 3)),
    Recipe('leaflet_chestplate', 'foraging',
           [{'name': 'oak_leaves', 'count': 8}],
           {'name': 'leaflet_chestplate'},
           collection_req=('oak_wood', 3)),
    Recipe('leaflet_leggings', 'foraging',
           [{'name': 'oak_leaves', 'count': 7}],
           {'name': 'leaflet_leggings'},
           collection_req=('oak_wood', 3)),
    Recipe('leaflet_boots', 'foraging',
           [{'name': 'oak_leaves', 'count': 4}],
           {'name': 'leaflet_boots'},
           collection_req=('oak_wood', 3)),
    RecipeGroup('leaflet_armor', 'foraging',
                ['leaflet_helmet', 'leaflet_chestplate',
                 'leaflet_leggings', 'leaflet_boots'],
                collection_req=('oak_wood', 3)),
    Recipe('oak_to_enchanted', 'foraging',
           [{'name': 'oak_wood', 'count': 160}],
           {'name': 'enchanted_oak'},
           collection_req=('oak_wood', 6)),
    Recipe('wood_affinity_talisman', 'foraging',
           [{'name': 'enchanted_oak'},
            {'name': 'oak_leaves', 'count': 8}],
           {'name': 'wood_affinity_talisman'},
           collection_req=('oak_wood', 8)),

    Recipe('birch_leaves', 'foraging',
           [{'name': 'birch_sapling'}],
           {'name': 'birch_leaves'},
           collection_req=('birch_wood', 2)),
    Recipe('birch_to_enchanted', 'foraging',
           [{'name': 'birch_wood', 'count': 160}],
           {'name': 'enchanted_birch'},
           collection_req=('birch_wood', 6)),
    Recipe('scroll_to_park', 'foraging',
           [{'name': 'enchanted_ender_pearl', 'count': 16},
            {'name': 'enchanted_birch', 'count': 128}],
           {'name': 'travel_scroll_to_park'},
           collection_req=('birch_wood', 8)),

    Recipe('spruce_leaves', 'foraging',
           [{'name': 'spruce_sapling'}],
           {'name': 'spruce_leaves'},
           collection_req=('spruce_wood', 2)),
    Recipe('spruce_to_enchanted', 'foraging',
           [{'name': 'spruce_wood', 'count': 160}],
           {'name': 'enchanted_spruce'},
           collection_req=('spruce_wood', 5)),
    Recipe('uncommon_wolf_pet', 'combat',
           [{'name': 'enchanted_spruce', 'count': 512},
            {'name': 'enchanted_egg'}],
           {'name': 'wolf_pet', 'rarity': 'uncommon'},
           collection_req=('spruce_wood', 8)),
    Recipe('epic_wolf_pet', 'combat',
           [{'name': 'enchanted_spruce', 'count': 512},
            {'name': 'super_enchanted_egg'}],
           {'name': 'wolf_pet', 'rarity': 'epic'},
           collection_req=('spruce_wood', 8)),
    RecipeGroup('wolf_pet', 'foraging',
                ['uncommon_wolf_pet', 'epic_wolf_pet'],
                collection_req=('spruce_wood', 8)),

    Recipe('dark_oak_leaves', 'foraging',
           [{'name': 'dark_oak_sapling'}],
           {'name': 'dark_oak_leaves'},
           collection_req=('dark_oak_wood', 2)),
    Recipe('dark_oak_to_enchanted', 'foraging',
           [{'name': 'dark_oak_wood', 'count': 160}],
           {'name': 'enchanted_dark_oak'},
           collection_req=('dark_oak_wood', 5)),
    Recipe('growth_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'enchanted_dark_oak', 'count': 8}],
           {'name': 'enchanted_book', 'enchantments': {'growth': 4}},
           collection_req=('dark_oak_wood', 7)),
    Recipe('growth_helmet', 'foraging',
           [{'name': 'enchanted_dark_oak', 'count': 320}],
           {'name': 'growth_helmet'},
           collection_req=('dark_oak_wood', 9)),
    Recipe('growth_chestplate', 'foraging',
           [{'name': 'enchanted_dark_oak', 'count': 512}],
           {'name': 'growth_chestplate'},
           collection_req=('dark_oak_wood', 9)),
    Recipe('growth_leggings', 'foraging',
           [{'name': 'enchanted_dark_oak', 'count': 448}],
           {'name': 'growth_leggings'},
           collection_req=('dark_oak_wood', 9)),
    Recipe('growth_boots', 'foraging',
           [{'name': 'enchanted_dark_oak', 'count': 256}],
           {'name': 'growth_boots'},
           collection_req=('dark_oak_wood', 9)),
    RecipeGroup('growth_armor', 'foraging',
                ['growth_helmet', 'growth_chestplate',
                 'growth_leggings', 'growth_boots'],
                collection_req=('dark_oak_wood', 9)),

    Recipe('acacia_leaves', 'foraging',
           [{'name': 'acacia_sapling'}],
           {'name': 'acacia_leaves'},
           collection_req=('acacia_wood', 2)),
    Recipe('acacia_to_enchanted', 'foraging',
           [{'name': 'acacia_wood', 'count': 160}],
           {'name': 'enchanted_acacia'},
           collection_req=('acacia_wood', 6)),
    Recipe('savanna_bow', 'foraging',
           [{'name': 'enchanted_acacia', 'count': 3},
            {'name': 'enchanted_string', 'count': 3}],
           {'name': 'savanna_bow'},
           collection_req=('acacia_wood', 7)),

    Recipe('jungle_leaves', 'foraging',
           [{'name': 'jungle_sapling'}],
           {'name': 'jungle_leaves'},
           collection_req=('jungle_wood', 2)),
    Recipe('jungle_to_enchanted', 'foraging',
           [{'name': 'jungle_wood', 'count': 160}],
           {'name': 'enchanted_jungle'},
           collection_req=('jungle_wood', 6)),
    Recipe('jungle_axe', 'foraging',
           [{'name': 'enchanted_jungle', 'count': 3},
            {'name': 'stick', 'count': 2}],
           {'name': 'jungle_axe'},
           collection_req=('jungle_wood', 7)),
    Recipe('uncommon_ocelot_pet', 'foraging',
           [{'name': 'enchanted_jungle', 'count': 512},
            {'name': 'enchanted_egg'}],
           {'name': 'ocelot_pet', 'rarity': 'uncommon'},
           collection_req=('jungle_wood', 9)),
    Recipe('epic_ocelot_pet', 'foraging',
           [{'name': 'enchanted_jungle', 'count': 512},
            {'name': 'super_enchanted_egg'}],
           {'name': 'ocelot_pet', 'rarity': 'epic'},
           collection_req=('jungle_wood', 9)),
    RecipeGroup('ocelot_pet', 'foraging',
                ['uncommon_ocelot_pet', 'epic_ocelot_pet'],
                collection_req=('jungle_wood', 9)),
]
