from ..item import get_item
from ..object import *


MINING_MINION_RECIPES = [
    Recipe('cobblestone_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('cobblestone'), 80)],
           (get_item('cobblestone_minion', tier=1), 1),
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_2', 'mining',
           [(get_item('cobblestone_minion', tier=1), 1),
            (Item('cobblestone'), 160)],
           (get_item('cobblestone_minion', tier=2), 1),
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_3', 'mining',
           [(get_item('cobblestone_minion', tier=2), 1),
            (Item('cobblestone'), 320)],
           (get_item('cobblestone_minion', tier=3), 1),
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_4', 'mining',
           [(get_item('cobblestone_minion', tier=3), 1),
            (Item('cobblestone'), 512)],
           (get_item('cobblestone_minion', tier=4), 1),
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_5', 'mining',
           [(get_item('cobblestone_minion', tier=4), 1),
            (Item('enchanted_cobblestone'), 8)],
           (get_item('cobblestone_minion', tier=5), 1),
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_6', 'mining',
           [(get_item('cobblestone_minion', tier=5), 1),
            (Item('enchanted_cobblestone'), 16)],
           (get_item('cobblestone_minion', tier=6), 1),
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_7', 'mining',
           [(get_item('cobblestone_minion', tier=6), 1),
            (Item('enchanted_cobblestone'), 32)],
           (get_item('cobblestone_minion', tier=7), 1),
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_8', 'mining',
           [(get_item('cobblestone_minion', tier=7), 1),
            (Item('enchanted_cobblestone'), 64)],
           (get_item('cobblestone_minion', tier=8), 1),
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_9', 'mining',
           [(get_item('cobblestone_minion', tier=8), 1),
            (Item('enchanted_cobblestone'), 128)],
           (get_item('cobblestone_minion', tier=9), 1),
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_10', 'mining',
           [(get_item('cobblestone_minion', tier=9), 1),
            (Item('enchanted_cobblestone'), 256)],
           (get_item('cobblestone_minion', tier=10), 1),
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_11', 'mining',
           [(get_item('cobblestone_minion', tier=10), 1),
            (Item('enchanted_cobblestone'), 512)],
           (get_item('cobblestone_minion', tier=11), 1),
           collection_req=('cobblestone', 1)),
    RecipeGroup('cobblestone_minion', 'mining',
                ['cobblestone_minion_1', 'cobblestone_minion_2',
                 'cobblestone_minion_3', 'cobblestone_minion_4',
                 'cobblestone_minion_5', 'cobblestone_minion_6',
                 'cobblestone_minion_7', 'cobblestone_minion_8',
                 'cobblestone_minion_9', 'cobblestone_minion_10',
                 'cobblestone_minion_11'],
                collection_req=('cobblestone', 1)),

    Recipe('coal_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('coal'), 80)],
           (get_item('coal_minion', tier=1), 1),
           collection_req=('coal', 1)),
    Recipe('coal_minion_2', 'mining',
           [(get_item('coal_minion', tier=1), 1),
            (Item('coal'), 160)],
           (get_item('coal_minion', tier=2), 1),
           collection_req=('coal', 1)),
    Recipe('coal_minion_3', 'mining',
           [(get_item('coal_minion', tier=2), 1),
            (Item('coal'), 320)],
           (get_item('coal_minion', tier=3), 1),
           collection_req=('coal', 1)),
    Recipe('coal_minion_4', 'mining',
           [(get_item('coal_minion', tier=3), 1),
            (Item('coal'), 512)],
           (get_item('coal_minion', tier=4), 1),
           collection_req=('coal', 1)),
    Recipe('coal_minion_5', 'mining',
           [(get_item('coal_minion', tier=4), 1),
            (Item('enchanted_coal'), 8)],
           (get_item('coal_minion', tier=5), 1),
           collection_req=('coal', 1)),
    Recipe('coal_minion_6', 'mining',
           [(get_item('coal_minion', tier=5), 1),
            (Item('enchanted_coal'), 24)],
           (get_item('coal_minion', tier=6), 1),
           collection_req=('coal', 1)),
    Recipe('coal_minion_7', 'mining',
           [(get_item('coal_minion', tier=6), 1),
            (Item('enchanted_coal'), 64)],
           (get_item('coal_minion', tier=7), 1),
           collection_req=('coal', 1)),
    Recipe('coal_minion_8', 'mining',
           [(get_item('coal_minion', tier=7), 1),
            (Item('enchanted_coal'), 128)],
           (get_item('coal_minion', tier=8), 1),
           collection_req=('coal', 1)),
    Recipe('coal_minion_9', 'mining',
           [(get_item('coal_minion', tier=8), 1),
            (Item('enchanted_coal'), 256)],
           (get_item('coal_minion', tier=9), 1),
           collection_req=('coal', 1)),
    Recipe('coal_minion_10', 'mining',
           [(get_item('coal_minion', tier=9), 1),
            (Item('enchanted_coal'), 512)],
           (get_item('coal_minion', tier=10), 1),
           collection_req=('coal', 1)),
    Recipe('coal_minion_11', 'mining',
           [(get_item('coal_minion', tier=10), 1),
            (Item('enchanted_coal_block'), 8)],
           (get_item('coal_minion', tier=11), 1),
           collection_req=('coal', 1)),
    RecipeGroup('coal_minion', 'mining',
                ['coal_minion_1', 'coal_minion_2', 'coal_minion_3',
                 'coal_minion_4', 'coal_minion_5', 'coal_minion_6',
                 'coal_minion_7', 'coal_minion_8', 'coal_minion_9',
                 'coal_minion_10', 'coal_minion_11'],
                collection_req=('coal', 1)),

    Recipe('iron_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('iron'), 80)],
           (get_item('iron_minion', tier=1), 1),
           collection_req=('iron', 1)),
    Recipe('iron_minion_2', 'mining',
           [(get_item('iron_minion', tier=1), 1),
            (Item('iron'), 160)],
           (get_item('iron_minion', tier=2), 1),
           collection_req=('iron', 1)),
    Recipe('iron_minion_3', 'mining',
           [(get_item('iron_minion', tier=2), 1),
            (Item('iron'), 320)],
           (get_item('iron_minion', tier=3), 1),
           collection_req=('iron', 1)),
    Recipe('iron_minion_4', 'mining',
           [(get_item('iron_minion', tier=3), 1),
            (Item('iron'), 512)],
           (get_item('iron_minion', tier=4), 1),
           collection_req=('iron', 1)),
    Recipe('iron_minion_5', 'mining',
           [(get_item('iron_minion', tier=4), 1),
            (Item('enchanted_iron'), 8)],
           (get_item('iron_minion', tier=5), 1),
           collection_req=('iron', 1)),
    Recipe('iron_minion_6', 'mining',
           [(get_item('iron_minion', tier=5), 1),
            (Item('enchanted_iron'), 24)],
           (get_item('iron_minion', tier=6), 1),
           collection_req=('iron', 1)),
    Recipe('iron_minion_7', 'mining',
           [(get_item('iron_minion', tier=6), 1),
            (Item('enchanted_iron'), 64)],
           (get_item('iron_minion', tier=7), 1),
           collection_req=('iron', 1)),
    Recipe('iron_minion_8', 'mining',
           [(get_item('iron_minion', tier=7), 1),
            (Item('enchanted_iron'), 128)],
           (get_item('iron_minion', tier=8), 1),
           collection_req=('iron', 1)),
    Recipe('iron_minion_9', 'mining',
           [(get_item('iron_minion', tier=8), 1),
            (Item('enchanted_iron'), 256)],
           (get_item('iron_minion', tier=9), 1),
           collection_req=('iron', 1)),
    Recipe('iron_minion_10', 'mining',
           [(get_item('iron_minion', tier=9), 1),
            (Item('enchanted_iron'), 512)],
           (get_item('iron_minion', tier=10), 1),
           collection_req=('iron', 1)),
    Recipe('iron_minion_11', 'mining',
           [(get_item('iron_minion', tier=10), 1),
            (Item('enchanted_iron_block'), 8)],
           (get_item('iron_minion', tier=11), 1),
           collection_req=('iron', 1)),
    RecipeGroup('iron_minion', 'mining',
                ['iron_minion_1', 'iron_minion_2', 'iron_minion_3',
                 'iron_minion_4', 'iron_minion_5', 'iron_minion_6',
                 'iron_minion_7', 'iron_minion_8', 'iron_minion_9',
                 'iron_minion_10', 'iron_minion_11'],
                collection_req=('iron', 1)),

    Recipe('gold_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('gold'), 80)],
           (get_item('gold_minion', tier=1), 1),
           collection_req=('gold', 1)),
    Recipe('gold_minion_2', 'mining',
           [(get_item('gold_minion', tier=1), 1),
            (Item('gold'), 160)],
           (get_item('gold_minion', tier=2), 1),
           collection_req=('gold', 1)),
    Recipe('gold_minion_3', 'mining',
           [(get_item('gold_minion', tier=2), 1),
            (Item('gold'), 320)],
           (get_item('gold_minion', tier=3), 1),
           collection_req=('gold', 1)),
    Recipe('gold_minion_4', 'mining',
           [(get_item('gold_minion', tier=3), 1),
            (Item('gold'), 512)],
           (get_item('gold_minion', tier=4), 1),
           collection_req=('gold', 1)),
    Recipe('gold_minion_5', 'mining',
           [(get_item('gold_minion', tier=4), 1),
            (Item('enchanted_gold'), 8)],
           (get_item('gold_minion', tier=5), 1),
           collection_req=('gold', 1)),
    Recipe('gold_minion_6', 'mining',
           [(get_item('gold_minion', tier=5), 1),
            (Item('enchanted_gold'), 24)],
           (get_item('gold_minion', tier=6), 1),
           collection_req=('gold', 1)),
    Recipe('gold_minion_7', 'mining',
           [(get_item('gold_minion', tier=6), 1),
            (Item('enchanted_gold'), 64)],
           (get_item('gold_minion', tier=7), 1),
           collection_req=('gold', 1)),
    Recipe('gold_minion_8', 'mining',
           [(get_item('gold_minion', tier=7), 1),
            (Item('enchanted_gold'), 128)],
           (get_item('gold_minion', tier=8), 1),
           collection_req=('gold', 1)),
    Recipe('gold_minion_9', 'mining',
           [(get_item('gold_minion', tier=8), 1),
            (Item('enchanted_gold'), 256)],
           (get_item('gold_minion', tier=9), 1),
           collection_req=('gold', 1)),
    Recipe('gold_minion_10', 'mining',
           [(get_item('gold_minion', tier=9), 1),
            (Item('enchanted_gold'), 512)],
           (get_item('gold_minion', tier=10), 1),
           collection_req=('gold', 1)),
    Recipe('gold_minion_11', 'mining',
           [(get_item('gold_minion', tier=10), 1),
            (Item('enchanted_gold_block'), 8)],
           (get_item('gold_minion', tier=11), 1),
           collection_req=('gold', 1)),
    RecipeGroup('gold_minion', 'mining',
                ['gold_minion_1', 'gold_minion_2', 'gold_minion_3',
                 'gold_minion_4', 'gold_minion_5', 'gold_minion_6',
                 'gold_minion_7', 'gold_minion_8', 'gold_minion_9',
                 'gold_minion_10', 'gold_minion_11'],
                collection_req=('gold', 1)),

    Recipe('diamond_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('diamond'), 80)],
           (get_item('diamond_minion', tier=1), 1),
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_2', 'mining',
           [(get_item('diamond_minion', tier=1), 1),
            (Item('diamond'), 160)],
           (get_item('diamond_minion', tier=2), 1),
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_3', 'mining',
           [(get_item('diamond_minion', tier=2), 1),
            (Item('diamond'), 320)],
           (get_item('diamond_minion', tier=3), 1),
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_4', 'mining',
           [(get_item('diamond_minion', tier=3), 1),
            (Item('diamond'), 512)],
           (get_item('diamond_minion', tier=4), 1),
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_5', 'mining',
           [(get_item('diamond_minion', tier=4), 1),
            (Item('enchanted_diamond'), 8)],
           (get_item('diamond_minion', tier=5), 1),
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_6', 'mining',
           [(get_item('diamond_minion', tier=5), 1),
            (Item('enchanted_diamond'), 24)],
           (get_item('diamond_minion', tier=6), 1),
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_7', 'mining',
           [(get_item('diamond_minion', tier=6), 1),
            (Item('enchanted_diamond'), 64)],
           (get_item('diamond_minion', tier=7), 1),
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_8', 'mining',
           [(get_item('diamond_minion', tier=7), 1),
            (Item('enchanted_diamond'), 128)],
           (get_item('diamond_minion', tier=8), 1),
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_9', 'mining',
           [(get_item('diamond_minion', tier=8), 1),
            (Item('enchanted_diamond'), 256)],
           (get_item('diamond_minion', tier=9), 1),
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_10', 'mining',
           [(get_item('diamond_minion', tier=9), 1),
            (Item('enchanted_diamond'), 512)],
           (get_item('diamond_minion', tier=10), 1),
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_11', 'mining',
           [(get_item('diamond_minion', tier=10), 1),
            (Item('enchanted_diamond_block'), 8)],
           (get_item('diamond_minion', tier=11), 1),
           collection_req=('diamond', 1)),
    RecipeGroup('diamond_minion', 'mining',
                ['diamond_minion_1', 'diamond_minion_2', 'diamond_minion_3',
                 'diamond_minion_4', 'diamond_minion_5', 'diamond_minion_6',
                 'diamond_minion_7', 'diamond_minion_8', 'diamond_minion_9',
                 'diamond_minion_10', 'diamond_minion_11'],
                collection_req=('diamond', 1)),

    Recipe('lapis_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('lapis'), 256)],
           (get_item('lapis_minion', tier=1), 1),
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_2', 'mining',
           [(get_item('lapis_minion', tier=1), 1),
            (Item('lapis'), 512)],
           (get_item('lapis_minion', tier=2), 1),
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_3', 'mining',
           [(get_item('lapis_minion', tier=2), 1),
            (Item('enchanted_lapis'), 8)],
           (get_item('lapis_minion', tier=3), 1),
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_4', 'mining',
           [(get_item('lapis_minion', tier=3), 1),
            (Item('enchanted_lapis'), 24)],
           (get_item('lapis_minion', tier=4), 1),
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_5', 'mining',
           [(get_item('lapis_minion', tier=4), 1),
            (Item('enchanted_lapis'), 64)],
           (get_item('lapis_minion', tier=5), 1),
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_6', 'mining',
           [(get_item('lapis_minion', tier=5), 1),
            (Item('enchanted_lapis'), 128)],
           (get_item('lapis_minion', tier=6), 1),
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_7', 'mining',
           [(get_item('lapis_minion', tier=6), 1),
            (Item('enchanted_lapis'), 256)],
           (get_item('lapis_minion', tier=7), 1),
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_8', 'mining',
           [(get_item('lapis_minion', tier=7), 1),
            (Item('enchanted_lapis'), 512)],
           (get_item('lapis_minion', tier=8), 1),
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_9', 'mining',
           [(get_item('lapis_minion', tier=8), 1),
            (Item('enchanted_lapis_block'), 8)],
           (get_item('lapis_minion', tier=9), 1),
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_10', 'mining',
           [(get_item('lapis_minion', tier=9), 1),
            (Item('enchanted_lapis_block'), 16)],
           (get_item('lapis_minion', tier=10), 1),
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_11', 'mining',
           [(get_item('lapis_minion', tier=10), 1),
            (Item('enchanted_lapis_block'), 32)],
           (get_item('lapis_minion', tier=11), 1),
           collection_req=('lapis', 1)),
    RecipeGroup('lapis_minion', 'mining',
                ['lapis_minion_1', 'lapis_minion_2', 'lapis_minion_3',
                 'lapis_minion_4', 'lapis_minion_5', 'lapis_minion_6',
                 'lapis_minion_7', 'lapis_minion_8', 'lapis_minion_9',
                 'lapis_minion_10', 'lapis_minion_11'],
                collection_req=('lapis', 1)),

    Recipe('emerald_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('emerald'), 80)],
           (get_item('emerald_minion', tier=1), 1),
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_2', 'mining',
           [(get_item('emerald_minion', tier=1), 1),
            (Item('emerald'), 160)],
           (get_item('emerald_minion', tier=2), 1),
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_3', 'mining',
           [(get_item('emerald_minion', tier=2), 1),
            (Item('emerald'), 320)],
           (get_item('emerald_minion', tier=3), 1),
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_4', 'mining',
           [(get_item('emerald_minion', tier=3), 1),
            (Item('emerald'), 512)],
           (get_item('emerald_minion', tier=4), 1),
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_5', 'mining',
           [(get_item('emerald_minion', tier=4), 1),
            (Item('enchanted_emerald'), 8)],
           (get_item('emerald_minion', tier=5), 1),
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_6', 'mining',
           [(get_item('emerald_minion', tier=5), 1),
            (Item('enchanted_emerald'), 24)],
           (get_item('emerald_minion', tier=6), 1),
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_7', 'mining',
           [(get_item('emerald_minion', tier=6), 1),
            (Item('enchanted_emerald'), 64)],
           (get_item('emerald_minion', tier=7), 1),
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_8', 'mining',
           [(get_item('emerald_minion', tier=7), 1),
            (Item('enchanted_emerald'), 128)],
           (get_item('emerald_minion', tier=8), 1),
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_9', 'mining',
           [(get_item('emerald_minion', tier=8), 1),
            (Item('enchanted_emerald'), 256)],
           (get_item('emerald_minion', tier=9), 1),
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_10', 'mining',
           [(get_item('emerald_minion', tier=9), 1),
            (Item('enchanted_emerald'), 512)],
           (get_item('emerald_minion', tier=10), 1),
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_11', 'mining',
           [(get_item('emerald_minion', tier=10), 1),
            (Item('enchanted_emerald_block'), 8)],
           (get_item('emerald_minion', tier=11), 1),
           collection_req=('emerald', 1)),
    RecipeGroup('emerald_minion', 'mining',
                ['emerald_minion_1', 'emerald_minion_2', 'emerald_minion_3',
                 'emerald_minion_4', 'emerald_minion_5', 'emerald_minion_6',
                 'emerald_minion_7', 'emerald_minion_8', 'emerald_minion_9',
                 'emerald_minion_10', 'emerald_minion_11'],
                collection_req=('emerald', 1)),

    Recipe('redstone_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('redstone'), 128)],
           (get_item('redstone_minion', tier=1), 1),
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_2', 'mining',
           [(get_item('redstone_minion', tier=1), 1),
            (Item('redstone'), 256)],
           (get_item('redstone_minion', tier=2), 1),
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_3', 'mining',
           [(get_item('redstone_minion', tier=2), 1),
            (Item('redstone'), 512)],
           (get_item('redstone_minion', tier=3), 1),
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_4', 'mining',
           [(get_item('redstone_minion', tier=3), 1),
            (Item('enchanted_redstone'), 8)],
           (get_item('redstone_minion', tier=4), 1),
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_5', 'mining',
           [(get_item('redstone_minion', tier=4), 1),
            (Item('enchanted_redstone'), 24)],
           (get_item('redstone_minion', tier=5), 1),
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_6', 'mining',
           [(get_item('redstone_minion', tier=5), 1),
            (Item('enchanted_redstone'), 64)],
           (get_item('redstone_minion', tier=6), 1),
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_7', 'mining',
           [(get_item('redstone_minion', tier=6), 1),
            (Item('enchanted_redstone'), 128)],
           (get_item('redstone_minion', tier=7), 1),
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_8', 'mining',
           [(get_item('redstone_minion', tier=7), 1),
            (Item('enchanted_redstone'), 256)],
           (get_item('redstone_minion', tier=8), 1),
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_9', 'mining',
           [(get_item('redstone_minion', tier=8), 1),
            (Item('enchanted_redstone'), 512)],
           (get_item('redstone_minion', tier=9), 1),
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_10', 'mining',
           [(get_item('redstone_minion', tier=9), 1),
            (Item('enchanted_redstone_block'), 8)],
           (get_item('redstone_minion', tier=10), 1),
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_11', 'mining',
           [(get_item('redstone_minion', tier=10), 1),
            (Item('enchanted_redstone_block'), 16)],
           (get_item('redstone_minion', tier=11), 1),
           collection_req=('redstone', 1)),
    RecipeGroup('redstone_minion', 'mining',
                ['redstone_minion_1', 'redstone_minion_2', 'redstone_minion_3',
                 'redstone_minion_4', 'redstone_minion_5', 'redstone_minion_6',
                 'redstone_minion_7', 'redstone_minion_8', 'redstone_minion_9',
                 'redstone_minion_10', 'redstone_minion_11'],
                collection_req=('redstone', 1)),

    Recipe('quartz_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('quartz'), 80)],
           (get_item('quartz_minion', tier=1), 1),
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_2', 'mining',
           [(get_item('quartz_minion', tier=1), 1),
            (Item('quartz'), 160)],
           (get_item('quartz_minion', tier=2), 1),
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_3', 'mining',
           [(get_item('quartz_minion', tier=2), 1),
            (Item('quartz'), 320)],
           (get_item('quartz_minion', tier=3), 1),
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_4', 'mining',
           [(get_item('quartz_minion', tier=3), 1),
            (Item('quartz'), 512)],
           (get_item('quartz_minion', tier=4), 1),
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_5', 'mining',
           [(get_item('quartz_minion', tier=4), 1),
            (Item('enchanted_quartz'), 8)],
           (get_item('quartz_minion', tier=5), 1),
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_6', 'mining',
           [(get_item('quartz_minion', tier=5), 1),
            (Item('enchanted_quartz'), 24)],
           (get_item('quartz_minion', tier=6), 1),
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_7', 'mining',
           [(get_item('quartz_minion', tier=6), 1),
            (Item('enchanted_quartz'), 64)],
           (get_item('quartz_minion', tier=7), 1),
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_8', 'mining',
           [(get_item('quartz_minion', tier=7), 1),
            (Item('enchanted_quartz'), 128)],
           (get_item('quartz_minion', tier=8), 1),
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_9', 'mining',
           [(get_item('quartz_minion', tier=8), 1),
            (Item('enchanted_quartz'), 256)],
           (get_item('quartz_minion', tier=9), 1),
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_10', 'mining',
           [(get_item('quartz_minion', tier=9), 1),
            (Item('enchanted_quartz'), 512)],
           (get_item('quartz_minion', tier=10), 1),
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_11', 'mining',
           [(get_item('quartz_minion', tier=10), 1),
            (Item('enchanted_quartz_block'), 8)],
           (get_item('quartz_minion', tier=11), 1),
           collection_req=('quartz', 1)),
    RecipeGroup('quartz_minion', 'mining',
                ['quartz_minion_1', 'quartz_minion_2', 'quartz_minion_3',
                 'quartz_minion_4', 'quartz_minion_5', 'quartz_minion_6',
                 'quartz_minion_7', 'quartz_minion_8', 'quartz_minion_9',
                 'quartz_minion_10', 'quartz_minion_11'],
                collection_req=('quartz', 1)),

    Recipe('obsidian_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('obsidian'), 80)],
           (get_item('obsidian_minion', tier=1), 1),
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_2', 'mining',
           [(get_item('obsidian_minion', tier=1), 1),
            (Item('obsidian'), 160)],
           (get_item('obsidian_minion', tier=2), 1),
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_3', 'mining',
           [(get_item('obsidian_minion', tier=2), 1),
            (Item('obsidian'), 320)],
           (get_item('obsidian_minion', tier=3), 1),
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_4', 'mining',
           [(get_item('obsidian_minion', tier=3), 1),
            (Item('obsidian'), 512)],
           (get_item('obsidian_minion', tier=4), 1),
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_5', 'mining',
           [(get_item('obsidian_minion', tier=4), 1),
            (Item('enchanted_obsidian'), 8)],
           (get_item('obsidian_minion', tier=5), 1),
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_6', 'mining',
           [(get_item('obsidian_minion', tier=5), 1),
            (Item('enchanted_obsidian'), 16)],
           (get_item('obsidian_minion', tier=6), 1),
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_7', 'mining',
           [(get_item('obsidian_minion', tier=6), 1),
            (Item('enchanted_obsidian'), 32)],
           (get_item('obsidian_minion', tier=7), 1),
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_8', 'mining',
           [(get_item('obsidian_minion', tier=7), 1),
            (Item('enchanted_obsidian'), 64)],
           (get_item('obsidian_minion', tier=8), 1),
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_9', 'mining',
           [(get_item('obsidian_minion', tier=8), 1),
            (Item('enchanted_obsidian'), 128)],
           (get_item('obsidian_minion', tier=9), 1),
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_10', 'mining',
           [(get_item('obsidian_minion', tier=9), 1),
            (Item('enchanted_obsidian'), 256)],
           (get_item('obsidian_minion', tier=10), 1),
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_11', 'mining',
           [(get_item('obsidian_minion', tier=10), 1),
            (Item('enchanted_obsidian'), 512)],
           (get_item('obsidian_minion', tier=11), 1),
           collection_req=('obsidian', 1)),
    RecipeGroup('obsidian_minion', 'mining',
                ['obsidian_minion_1', 'obsidian_minion_2', 'obsidian_minion_3',
                 'obsidian_minion_4', 'obsidian_minion_5', 'obsidian_minion_6',
                 'obsidian_minion_7', 'obsidian_minion_8', 'obsidian_minion_9',
                 'obsidian_minion_10', 'obsidian_minion_11'],
                collection_req=('obsidian', 1)),

    Recipe('glowstone_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('glowstone'), 128)],
           (get_item('glowstone_minion', tier=1), 1),
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_2', 'mining',
           [(get_item('glowstone_minion', tier=1), 1),
            (Item('glowstone'), 256)],
           (get_item('glowstone_minion', tier=2), 1),
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_3', 'mining',
           [(get_item('glowstone_minion', tier=2), 1),
            (Item('glowstone'), 512)],
           (get_item('glowstone_minion', tier=3), 1),
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_4', 'mining',
           [(get_item('glowstone_minion', tier=3), 1),
            (Item('enchanted_glowstone'), 8)],
           (get_item('glowstone_minion', tier=4), 1),
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_5', 'mining',
           [(get_item('glowstone_minion', tier=4), 1),
            (Item('enchanted_glowstone'), 24)],
           (get_item('glowstone_minion', tier=5), 1),
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_6', 'mining',
           [(get_item('glowstone_minion', tier=5), 1),
            (Item('enchanted_glowstone'), 64)],
           (get_item('glowstone_minion', tier=6), 1),
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_7', 'mining',
           [(get_item('glowstone_minion', tier=6), 1),
            (Item('enchanted_glowstone'), 128)],
           (get_item('glowstone_minion', tier=7), 1),
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_8', 'mining',
           [(get_item('glowstone_minion', tier=7), 1),
            (Item('enchanted_glowstone'), 256)],
           (get_item('glowstone_minion', tier=8), 1),
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_9', 'mining',
           [(get_item('glowstone_minion', tier=8), 1),
            (Item('enchanted_glowstone'), 512)],
           (get_item('glowstone_minion', tier=9), 1),
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_10', 'mining',
           [(get_item('glowstone_minion', tier=9), 1),
            (Item('enchanted_glowstone_block'), 8)],
           (get_item('glowstone_minion', tier=10), 1),
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_11', 'mining',
           [(get_item('glowstone_minion', tier=10), 1),
            (Item('enchanted_glowstone_block'), 16)],
           (get_item('glowstone_minion', tier=11), 1),
           collection_req=('glowstone', 1)),
    RecipeGroup('glowstone_minion', 'mining',
                ['glowstone_minion_1', 'glowstone_minion_2',
                 'glowstone_minion_3', 'glowstone_minion_4',
                 'glowstone_minion_5', 'glowstone_minion_6',
                 'glowstone_minion_7', 'glowstone_minion_8',
                 'glowstone_minion_9', 'glowstone_minion_10',
                 'glowstone_minion_11'],
                collection_req=('glowstone', 1)),

    Recipe('flint_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('flint'), 80)],
           (get_item('flint_minion', tier=1), 1),
           collection_req=('flint', 1)),
    Recipe('flint_minion_2', 'mining',
           [(get_item('flint_minion', tier=1), 1),
            (Item('flint'), 160)],
           (get_item('flint_minion', tier=2), 1),
           collection_req=('flint', 1)),
    Recipe('flint_minion_3', 'mining',
           [(get_item('flint_minion', tier=2), 1),
            (Item('flint'), 320)],
           (get_item('flint_minion', tier=3), 1),
           collection_req=('flint', 1)),
    Recipe('flint_minion_4', 'mining',
           [(get_item('flint_minion', tier=3), 1),
            (Item('flint'), 512)],
           (get_item('flint_minion', tier=4), 1),
           collection_req=('flint', 1)),
    Recipe('flint_minion_5', 'mining',
           [(get_item('flint_minion', tier=4), 1),
            (Item('enchanted_flint'), 8)],
           (get_item('flint_minion', tier=5), 1),
           collection_req=('flint', 1)),
    Recipe('flint_minion_6', 'mining',
           [(get_item('flint_minion', tier=5), 1),
            (Item('enchanted_flint'), 16)],
           (get_item('flint_minion', tier=6), 1),
           collection_req=('flint', 1)),
    Recipe('flint_minion_7', 'mining',
           [(get_item('flint_minion', tier=6), 1),
            (Item('enchanted_flint'), 32)],
           (get_item('flint_minion', tier=7), 1),
           collection_req=('flint', 1)),
    Recipe('flint_minion_8', 'mining',
           [(get_item('flint_minion', tier=7), 1),
            (Item('enchanted_flint'), 64)],
           (get_item('flint_minion', tier=8), 1),
           collection_req=('flint', 1)),
    Recipe('flint_minion_9', 'mining',
           [(get_item('flint_minion', tier=8), 1),
            (Item('enchanted_flint'), 128)],
           (get_item('flint_minion', tier=9), 1),
           collection_req=('flint', 1)),
    Recipe('flint_minion_10', 'mining',
           [(get_item('flint_minion', tier=9), 1),
            (Item('enchanted_flint'), 256)],
           (get_item('flint_minion', tier=10), 1),
           collection_req=('flint', 1)),
    Recipe('flint_minion_11', 'mining',
           [(get_item('flint_minion', tier=10), 1),
            (Item('enchanted_flint'), 512)],
           (get_item('flint_minion', tier=11), 1),
           collection_req=('flint', 1)),
    RecipeGroup('flint_minion', 'mining',
                ['flint_minion_1', 'flint_minion_2', 'flint_minion_3',
                 'flint_minion_4', 'flint_minion_5', 'flint_minion_6',
                 'flint_minion_7', 'flint_minion_8', 'flint_minion_9',
                 'flint_minion_10', 'flint_minion_11'],
                collection_req=('flint', 1)),

    Recipe('ice_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('ice'), 80)],
           (get_item('ice_minion', tier=1), 1),
           collection_req=('ice', 1)),
    Recipe('ice_minion_2', 'mining',
           [(get_item('ice_minion', tier=1), 1),
            (Item('ice'), 160)],
           (get_item('ice_minion', tier=2), 1),
           collection_req=('ice', 1)),
    Recipe('ice_minion_3', 'mining',
           [(get_item('ice_minion', tier=2), 1),
            (Item('ice'), 320)],
           (get_item('ice_minion', tier=3), 1),
           collection_req=('ice', 1)),
    Recipe('ice_minion_4', 'mining',
           [(get_item('ice_minion', tier=3), 1),
            (Item('ice'), 512)],
           (get_item('ice_minion', tier=4), 1),
           collection_req=('ice', 1)),
    Recipe('ice_minion_5', 'mining',
           [(get_item('ice_minion', tier=4), 1),
            (Item('packed_ice'), 128)],
           (get_item('ice_minion', tier=5), 1),
           collection_req=('ice', 1)),
    Recipe('ice_minion_6', 'mining',
           [(get_item('ice_minion', tier=5), 1),
            (Item('packed_ice'), 256)],
           (get_item('ice_minion', tier=6), 1),
           collection_req=('ice', 1)),
    Recipe('ice_minion_7', 'mining',
           [(get_item('ice_minion', tier=6), 1),
            (Item('packed_ice'), 512)],
           (get_item('ice_minion', tier=7), 1),
           collection_req=('ice', 1)),
    Recipe('ice_minion_8', 'mining',
           [(get_item('ice_minion', tier=7), 1),
            (Item('enchanted_ice'), 64)],
           (get_item('ice_minion', tier=8), 1),
           collection_req=('ice', 1)),
    Recipe('ice_minion_9', 'mining',
           [(get_item('ice_minion', tier=8), 1),
            (Item('enchanted_ice'), 128)],
           (get_item('ice_minion', tier=9), 1),
           collection_req=('ice', 1)),
    Recipe('ice_minion_10', 'mining',
           [(get_item('ice_minion', tier=9), 1),
            (Item('enchanted_ice'), 256)],
           (get_item('ice_minion', tier=10), 1),
           collection_req=('ice', 1)),
    Recipe('ice_minion_11', 'mining',
           [(get_item('ice_minion', tier=10), 1),
            (Item('enchanted_ice'), 512)],
           (get_item('ice_minion', tier=11), 1),
           collection_req=('ice', 1)),
    RecipeGroup('ice_minion', 'mining',
                ['ice_minion_1', 'ice_minion_2', 'ice_minion_3', 'ice_minion_4',
                 'ice_minion_5', 'ice_minion_6', 'ice_minion_7', 'ice_minion_8',
                 'ice_minion_9', 'ice_minion_10', 'ice_minion_11'],
                collection_req=('ice', 1)),

    Recipe('sand_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('sand'), 80)],
           (get_item('sand_minion', tier=1), 1),
           collection_req=('sand', 1)),
    Recipe('sand_minion_2', 'mining',
           [(get_item('sand_minion', tier=1), 1),
            (Item('sand'), 160)],
           (get_item('sand_minion', tier=2), 1),
           collection_req=('sand', 1)),
    Recipe('sand_minion_3', 'mining',
           [(get_item('sand_minion', tier=2), 1),
            (Item('sand'), 320)],
           (get_item('sand_minion', tier=3), 1),
           collection_req=('sand', 1)),
    Recipe('sand_minion_4', 'mining',
           [(get_item('sand_minion', tier=3), 1),
            (Item('sand'), 512)],
           (get_item('sand_minion', tier=4), 1),
           collection_req=('sand', 1)),
    Recipe('sand_minion_5', 'mining',
           [(get_item('sand_minion', tier=4), 1),
            (Item('enchanted_sand'), 8)],
           (get_item('sand_minion', tier=5), 1),
           collection_req=('sand', 1)),
    Recipe('sand_minion_6', 'mining',
           [(get_item('sand_minion', tier=5), 1),
            (Item('enchanted_sand'), 16)],
           (get_item('sand_minion', tier=6), 1),
           collection_req=('sand', 1)),
    Recipe('sand_minion_7', 'mining',
           [(get_item('sand_minion', tier=6), 1),
            (Item('enchanted_sand'), 32)],
           (get_item('sand_minion', tier=7), 1),
           collection_req=('sand', 1)),
    Recipe('sand_minion_8', 'mining',
           [(get_item('sand_minion', tier=7), 1),
            (Item('enchanted_sand'), 64)],
           (get_item('sand_minion', tier=8), 1),
           collection_req=('sand', 1)),
    Recipe('sand_minion_9', 'mining',
           [(get_item('sand_minion', tier=8), 1),
            (Item('enchanted_sand'), 128)],
           (get_item('sand_minion', tier=9), 1),
           collection_req=('sand', 1)),
    Recipe('sand_minion_10', 'mining',
           [(get_item('sand_minion', tier=9), 1),
            (Item('enchanted_sand'), 256)],
           (get_item('sand_minion', tier=10), 1),
           collection_req=('sand', 1)),
    Recipe('sand_minion_11', 'mining',
           [(get_item('sand_minion', tier=10), 1),
            (Item('enchanted_sand'), 512)],
           (get_item('sand_minion', tier=11), 1),
           collection_req=('sand', 1)),
    RecipeGroup('sand_minion', 'mining',
                ['sand_minion_1', 'sand_minion_2', 'sand_minion_3',
                 'sand_minion_4', 'sand_minion_5', 'sand_minion_6',
                 'sand_minion_7', 'sand_minion_8', 'sand_minion_9',
                 'sand_minion_10', 'sand_minion_11'],
                collection_req=('sand', 1)),

    Recipe('end_stone_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('end_stone'), 80)],
           (get_item('end_stone_minion', tier=1), 1),
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_2', 'mining',
           [(get_item('end_stone_minion', tier=1), 1),
            (Item('end_stone'), 160)],
           (get_item('end_stone_minion', tier=2), 1),
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_3', 'mining',
           [(get_item('end_stone_minion', tier=2), 1),
            (Item('end_stone'), 320)],
           (get_item('end_stone_minion', tier=3), 1),
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_4', 'mining',
           [(get_item('end_stone_minion', tier=3), 1),
            (Item('end_stone'), 512)],
           (get_item('end_stone_minion', tier=4), 1),
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_5', 'mining',
           [(get_item('end_stone_minion', tier=4), 1),
            (Item('enchanted_end_stone'), 8)],
           (get_item('end_stone_minion', tier=5), 1),
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_6', 'mining',
           [(get_item('end_stone_minion', tier=5), 1),
            (Item('enchanted_end_stone'), 16)],
           (get_item('end_stone_minion', tier=6), 1),
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_7', 'mining',
           [(get_item('end_stone_minion', tier=6), 1),
            (Item('enchanted_end_stone'), 32)],
           (get_item('end_stone_minion', tier=7), 1),
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_8', 'mining',
           [(get_item('end_stone_minion', tier=7), 1),
            (Item('enchanted_end_stone'), 64)],
           (get_item('end_stone_minion', tier=8), 1),
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_9', 'mining',
           [(get_item('end_stone_minion', tier=8), 1),
            (Item('enchanted_end_stone'), 128)],
           (get_item('end_stone_minion', tier=9), 1),
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_10', 'mining',
           [(get_item('end_stone_minion', tier=9), 1),
            (Item('enchanted_end_stone'), 256)],
           (get_item('end_stone_minion', tier=10), 1),
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_11', 'mining',
           [(get_item('end_stone_minion', tier=10), 1),
            (Item('enchanted_end_stone'), 512)],
           (get_item('end_stone_minion', tier=11), 1),
           collection_req=('end_stone', 1)),
    RecipeGroup('end_stone_minion', 'mining',
                ['end_stone_minion_1', 'end_stone_minion_2',
                 'end_stone_minion_3', 'end_stone_minion_4',
                 'end_stone_minion_5', 'end_stone_minion_6',
                 'end_stone_minion_7', 'end_stone_minion_8',
                 'end_stone_minion_9', 'end_stone_minion_10',
                 'end_stone_minion_11'],
                collection_req=('end_stone', 1)),

    Recipe('mithril_minion_1', 'mining',
           [(get_item('wooden_pickaxe'), 1),
            (Item('mithril'), 80)],
           (get_item('mithril_minion', tier=1), 1),
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_2', 'mining',
           [(get_item('mithril_minion', tier=1), 1),
            (Item('mithril'), 160)],
           (get_item('mithril_minion', tier=2), 1),
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_3', 'mining',
           [(get_item('mithril_minion', tier=2), 1),
            (Item('mithril'), 320)],
           (get_item('mithril_minion', tier=3), 1),
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_4', 'mining',
           [(get_item('mithril_minion', tier=3), 1),
            (Item('mithril'), 512)],
           (get_item('mithril_minion', tier=4), 1),
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_5', 'mining',
           [(get_item('mithril_minion', tier=4), 1),
            (Item('enchanted_mithril'), 8)],
           (get_item('mithril_minion', tier=5), 1),
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_6', 'mining',
           [(get_item('mithril_minion', tier=5), 1),
            (Item('enchanted_mithril'), 24)],
           (get_item('mithril_minion', tier=6), 1),
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_7', 'mining',
           [(get_item('mithril_minion', tier=6), 1),
            (Item('enchanted_mithril'), 64)],
           (get_item('mithril_minion', tier=7), 1),
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_8', 'mining',
           [(get_item('mithril_minion', tier=7), 1),
            (Item('enchanted_mithril'), 128)],
           (get_item('mithril_minion', tier=8), 1),
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_9', 'mining',
           [(get_item('mithril_minion', tier=8), 1),
            (Item('enchanted_mithril'), 256)],
           (get_item('mithril_minion', tier=9), 1),
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_10', 'mining',
           [(get_item('mithril_minion', tier=9), 1),
            (Item('enchanted_mithril'), 512)],
           (get_item('mithril_minion', tier=10), 1),
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_11', 'mining',
           [(get_item('mithril_minion', tier=10), 1),
            (Item('refined_mithril'), 8)],
           (get_item('mithril_minion', tier=11), 1),
           collection_req=('mithril', 1)),
    RecipeGroup('mithril_minion', 'mining',
                ['mithril_minion_1', 'mithril_minion_2', 'mithril_minion_3',
                 'mithril_minion_4', 'mithril_minion_5', 'mithril_minion_6',
                 'mithril_minion_7', 'mithril_minion_8', 'mithril_minion_9',
                 'mithril_minion_10', 'mithril_minion_11'],
                collection_req=('mithril', 1)),
]
