from ..object import *


MINING_RECIPES = [
    Recipe('wooden_pickaxe', 'mining',
           [{'name': 'planks', 'count': 3},
            {'name': 'stick', 'count': 2}],
           {'name': 'wooden_pickaxe'}),
    Recipe('gold_pickaxe', 'mining',
           [{'name': 'gold', 'count': 3},
            {'name': 'stick', 'count': 2}],
           {'name': 'golden_pickaxe'}),
    Recipe('stone_pickaxe', 'mining',
           [{'name': 'cobblestone', 'count': 3},
            {'name': 'stick', 'count': 2}],
           {'name': 'stone_pickaxe'}),
    Recipe('iron_pickaxe', 'mining',
           [{'name': 'iron', 'count': 3},
            {'name': 'stick', 'count': 2}],
           {'name': 'iron_pickaxe'}),
    Recipe('diamond_pickaxe', 'mining',
           [{'name': 'diamond', 'count': 3},
            {'name': 'stick', 'count': 2}],
           {'name': 'diamond_pickaxe'}),

    Recipe('coal_to_block', 'mining',
           [{'name': 'coal', 'count': 9}],
           {'name': 'coal_block'}),
    Recipe('block_to_coal', 'mining',
           [{'name': 'coal_block'}],
           {'name': 'coal', 'count': 9}),

    Recipe('iron_to_block', 'mining',
           [{'name': 'iron', 'count': 9}],
           {'name': 'iron_block'}),
    Recipe('block_to_iron', 'mining',
           [{'name': 'iron_block'}],
           {'name': 'iron', 'count': 9}),
    Recipe('nugget_to_iron', 'mining',
           [{'name': 'iron_nugget', 'count': 9}],
           {'name': 'iron'}),
    Recipe('iron_to_nugget', 'mining',
           [{'name': 'iron'}],
           {'name': 'iron_nugget', 'count': 9}),

    Recipe('gold_to_block', 'mining',
           [{'name': 'gold', 'count': 9}],
           {'name': 'gold_block'}),
    Recipe('block_to_gold', 'mining',
           [{'name': 'gold_block'}],
           {'name': 'gold', 'count': 9}),
    Recipe('nugget_to_gold', 'mining',
           [{'name': 'gold_nugget', 'count': 9}],
           {'name': 'gold'}),
    Recipe('gold_to_nugget', 'mining',
           [{'name': 'gold'}],
           {'name': 'gold_nugget', 'count': 9}),
    Recipe('golden_apple', 'mining',
           [{'name': 'gold', 'count': 8},
            {'name': 'apple'}],
           {'name': 'golden_apple'}),
    Recipe('enchanted_golden_apple', 'mining',
           [{'name': 'gold_block', 'count': 8},
            {'name': 'apple'}],
           {'name': 'enchanted_golden_apple'}),

    Recipe('diamond_to_block', 'mining',
           [{'name': 'diamond', 'count': 9}],
           {'name': 'diamond_block'}),
    Recipe('block_to_diamond', 'mining',
           [{'name': 'diamond_block'}],
           {'name': 'diamond', 'count': 9}),

    Recipe('lapis_to_block', 'mining',
           [{'name': 'lapis', 'count': 9}],
           {'name': 'lapis_block'}),
    Recipe('block_to_lapis', 'mining',
           [{'name': 'lapis_block'}],
           {'name': 'lapis', 'count': 9}),

    Recipe('emerald_to_block', 'mining',
           [{'name': 'emerald', 'count': 9}],
           {'name': 'emerald_block'}),
    Recipe('block_to_emerald', 'mining',
           [{'name': 'emerald_block'}],
           {'name': 'emerald', 'count': 9}),

    Recipe('redstone_to_block', 'mining',
           [{'name': 'redstone', 'count': 9}],
           {'name': 'redstone_block'}),
    Recipe('block_to_redstone', 'mining',
           [{'name': 'redstone_block'}],
           {'name': 'redstone', 'count': 9}),

    Recipe('glowstone_to_block', 'mining',
           [{'name': 'glowstone', 'count': 4}],
           {'name': 'glowstone_block'}),

    Recipe('life_steal_book', 'enchanting',
           [{'name': 'paper', 'count': 6},
            {'name': 'enchanted_golden_apple', 'count': 2}],
           {'name': 'enchanted_book', 'enchantments': {'life_steal': 4}}),

    Recipe('cobblestone_to_enchanted', 'mining',
           [{'name': 'cobblestone', 'count': 160}],
           {'name': 'enchanted_cobblestone'},
           collection_req=('cobblestone', 4)),
    Recipe('uncommon_silverfish_pet', 'mining',
           [{'name': 'enchanted_cobblestone', 'count': 64},
            {'name': 'enchanted_egg'}],
           {'name': 'silverfish_pet', 'rarity': 'uncommon'},
           collection_req=('cobblestone', 6)),
    Recipe('epic_silverfish_pet', 'mining',
           [{'name': 'enchanted_cobblestone', 'count': 64},
            {'name': 'super_enchanted_egg'}],
           {'name': 'silverfish_pet', 'rarity': 'epic'},
           collection_req=('cobblestone', 6)),
    RecipeGroup('silverfish_pet', 'mining',
                ['uncommon_silverfish_pet', 'epic_silverfish_pet'],
                collection_req=('cobblestone', 6)),
    Recipe('miners_outfit_helmet', 'mining',
           [{'name': 'enchanted_cobblestone', 'count': 5}],
           {'name': 'miners_outfit_helmet'},
           collection_req=('cobblestone', 7)),
    Recipe('miners_outfit_chestplate', 'mining',
           [{'name': 'enchanted_cobblestone', 'count': 8}],
           {'name': 'miners_outfit_chestplate'},
           collection_req=('cobblestone', 7)),
    Recipe('miners_outfit_leggings', 'mining',
           [{'name': 'enchanted_cobblestone', 'count': 7}],
           {'name': 'miners_outfit_leggings'},
           collection_req=('cobblestone', 7)),
    Recipe('miners_outfit_boots', 'mining',
           [{'name': 'enchanted_cobblestone', 'count': 4}],
           {'name': 'miners_outfit_boots'},
           collection_req=('cobblestone', 7)),
    RecipeGroup('miners_outfit_armor', 'mining',
                ['miners_outfit_helmet', 'miners_outfit_chestplate',
                 'miners_outfit_leggings', 'miners_outfit_boots'],
                collection_req=('cobblestone', 7)),

    Recipe('coal_to_enchanted', 'mining',
           [{'name': 'coal', 'count': 160}],
           {'name': 'enchanted_coal'},
           collection_req=('coal', 4)),
    Recipe('scroll_to_gold', 'mining',
           [{'name': 'enchanted_ender_pearl', 'count': 16},
            {'name': 'enchanted_iron', 'count': 48},
            {'name': 'enchanted_gold', 'count': 80}],
           {'name': 'travel_scroll_to_gold'},
           collection_req=('coal', 6)),
    Recipe('coal_to_enchanted_block', 'mining',
           [{'name': 'enchanted_coal', 'count': 160}],
           {'name': 'enchanted_coal_block'},
           collection_req=('coal', 7)),
    Recipe('epic_wither_skeleton_pet', 'mining',
           [{'name': 'enchanted_coal_block', 'count': 8},
            {'name': 'super_enchanted_egg'}],
           {'name': 'wither_skeleton_pet', 'rarity': 'epic'},
           collection_req=('coal', 9)),

    Recipe('golem_hat', 'mining',
           [{'name': 'iron', 'count': 40}],
           {'name': 'golem_hat'},
           collection_req=('iron', 2)),
    Recipe('protection_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'iron', 'count': 8}],
           {'name': 'enchanted_book', 'enchantments': {'protection': 4}},
           collection_req=('iron', 3)),
    Recipe('iron_to_enchanted', 'mining',
           [{'name': 'iron', 'count': 160}],
           {'name': 'enchanted_iron'},
           collection_req=('iron', 4)),
    Recipe('golem_armor_helmet', 'mining',
           [{'name': 'enchanted_iron', 'count': 50}],
           {'name': 'golem_armor_helmet'},
           collection_req=('iron', 6)),
    Recipe('golem_armor_chestplate', 'mining',
           [{'name': 'enchanted_iron', 'count': 80}],
           {'name': 'golem_armor_chestplate'},
           collection_req=('iron', 6)),
    Recipe('golem_armor_leggings', 'mining',
           [{'name': 'enchanted_iron', 'count': 70}],
           {'name': 'golem_armor_leggings'},
           collection_req=('iron', 6)),
    Recipe('golem_armor_boots', 'mining',
           [{'name': 'enchanted_iron', 'count': 40}],
           {'name': 'golem_armor_boots'},
           collection_req=('iron', 6)),
    RecipeGroup('golem_armor', 'mining',
                ['golem_armor_helmet', 'golem_armor_chestplate',
                 'golem_armor_leggings', 'golem_armor_boots'],
                collection_req=('iron', 6)),
    Recipe('iron_to_enchanted_block', 'mining',
           [{'name': 'enchanted_iron', 'count': 160}],
           {'name': 'enchanted_iron_block'},
           collection_req=('iron', 7)),
    Recipe('golem_sword', 'mining',
           [{'name': 'enchanted_iron_block', 'count': 2},
            {'name': 'stick'}],
           {'name': 'golem_sword'},
           collection_req=('iron', 8)),

    Recipe('cleaver', 'mining',
           [{'name': 'gold', 'count': 4},
            {'name': 'stick', 'count': 2}],
           {'name': 'cleaver'},
           collection_req=('gold', 2)),
    Recipe('looting_book', 'enchanting',
           [{'name': 'paper', 'count': 6},
            {'name': 'gold_block', 'count': 4}],
           {'name': 'enchanted_book', 'enchantments': {'looting': 2}},
           collection_req=('gold', 3)),
    Recipe('gold_to_enchanted', 'mining',
           [{'name': 'gold', 'count': 160}],
           {'name': 'enchanted_gold'},
           collection_req=('gold', 4)),
    Recipe('scavenger_book', 'enchanting',
           [{'name': 'paper', 'count': 6},
            {'name': 'gold_sword'}],
           {'name': 'enchanted_book', 'enchantments': {'scavenger': 2}},
           collection_req=('gold', 6)),
    Recipe('gold_to_enchanted_block', 'mining',
           [{'name': 'enchanted_gold', 'count': 160}],
           {'name': 'enchanted_gold_block'},
           collection_req=('gold', 7)),
    Recipe('fortune_book', 'enchanting',
           [{'name': 'paper', 'count': 6},
            {'name': 'enchanted_gold', 'count': 2}],
           {'name': 'enchanted_book', 'enchantments': {'fortune': 2}},
           collection_req=('gold', 8)),

    Recipe('execute_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'diamond', 'count': 40},
            {'name': 'flint', 'count': 40}],
           {'name': 'enchanted_book', 'enchantments': {'execute': 4}},
           collection_req=('diamond', 2)),
    Recipe('diamond_to_enchanted', 'mining',
           [{'name': 'diamond', 'count': 160}],
           {'name': 'enchanted_diamond'},
           collection_req=('diamond', 4)),
    Recipe('critical_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'enchanted_diamond', 'count': 8}],
           {'name': 'enchanted_book', 'enchantments': {'critical': 4}},
           collection_req=('diamond', 5)),
    Recipe('hardened_diamond_helmet', 'mining',
           [{'name': 'enchanted_diamond', 'count': 5}],
           {'name': 'hardened_diamond_helmet'},
           collection_req=('diamond', 7)),
    Recipe('hardened_diamond_chestplate', 'mining',
           [{'name': 'enchanted_diamond', 'count': 8}],
           {'name': 'hardened_diamond_chestplate'},
           collection_req=('diamond', 7)),
    Recipe('hardened_diamond_leggings', 'mining',
           [{'name': 'enchanted_diamond', 'count': 7}],
           {'name': 'hardened_diamond_leggings'},
           collection_req=('diamond', 7)),
    Recipe('hardened_diamond_boots', 'mining',
           [{'name': 'enchanted_diamond', 'count': 4}],
           {'name': 'hardened_diamond_boots'},
           collection_req=('diamond', 7)),
    RecipeGroup('hardened_diamond_armor', 'mining',
                ['hardened_diamond_helmet', 'hardened_diamond_chestplate',
                 'hardened_diamond_leggings', 'hardened_diamond_boots'],
                collection_req=('diamond', 7)),
    Recipe('diamond_to_enchanted_block', 'mining',
           [{'name': 'enchanted_diamond', 'count': 160}],
           {'name': 'enchanted_diamond_block'},
           collection_req=('diamond', 8)),
    Recipe('perfect_helmet', 'mining',
           [{'name': 'enchanted_diamond_block', 'count': 5}],
           {'name': 'perfect_helmet'},
           collection_req=('diamond', 9)),
    Recipe('perfect_chestplate', 'mining',
           [{'name': 'enchanted_diamond_block', 'count': 8}],
           {'name': 'perfect_chestplate'},
           collection_req=('diamond', 9)),
    Recipe('perfect_leggings', 'mining',
           [{'name': 'enchanted_diamond_block', 'count': 7}],
           {'name': 'perfect_leggings'},
           collection_req=('diamond', 9)),
    Recipe('perfect_boots', 'mining',
           [{'name': 'enchanted_diamond_block', 'count': 4}],
           {'name': 'perfect_boots'},
           collection_req=('diamond', 9)),
    RecipeGroup('perfect_armor', 'mining',
                ['perfect_helmet', 'perfect_chestplate',
                 'perfect_leggings', 'perfect_boots'],
                collection_req=('diamond', 9)),

    Recipe('experience_bottle', 'mining',
           [{'name': 'lapis', 'count': 6},
            {'name': 'bottle'}],
           {'name': 'experience_bottle'},
           collection_req=('lapis', 2)),
    Recipe('experience_book', 'enchanting',
           [{'name': 'paper', 'count': 6},
            {'name': 'lapis', 'count': 2}],
           {'name': 'enchanted_book', 'enchantments': {'experience': 2}},
           collection_req=('lapis', 3)),
    Recipe('lapis_to_enchanted', 'mining',
           [{'name': 'lapis', 'count': 160}],
           {'name': 'enchanted_lapis'},
           collection_req=('lapis', 4)),
    Recipe('grand_experience_bottle', 'mining',
           [{'name': 'enchanted_lapis', 'count': 6},
            {'name': 'bottle'}],
           {'name': 'grand_experience_bottle'},
           collection_req=('lapis', 5)),
    Recipe('lapis_to_enchanted_block', 'mining',
           [{'name': 'enchanted_lapis', 'count': 160}],
           {'name': 'enchanted_lapis_block'},
           collection_req=('lapis', 7)),
    Recipe('titanic_experience_bottle', 'mining',
           [{'name': 'enchanted_lapis_block', 'count': 6},
            {'name': 'bottle'}],
           {'name': 'titanic_experience_bottle'},
           collection_req=('lapis', 8)),
    Recipe('experience_artifact', 'mining',
           [{'name': 'enchanted_lapis_block', 'count': 9}],
           {'name': 'experience_artifact'},
           collection_req=('lapis', 9)),

    Recipe('emerald_to_enchanted', 'mining',
           [{'name': 'emerald', 'count': 160}],
           {'name': 'enchanted_emerald'},
           collection_req=('emerald', 4)),
    Recipe('emerald_ring', 'mining',
           [{'name': 'enchanted_emerald', 'count': 32}],
           {'name': 'emerald_ring'},
           collection_req=('emerald', 5)),
    Recipe('emerald_to_enchanted_block', 'mining',
           [{'name': 'enchanted_emerald', 'count': 160}],
           {'name': 'enchanted_emerald_block'},
           collection_req=('emerald', 7)),
    Recipe('emerald_blade', 'mining',
           [{'name': 'enchanted_emerald_block', 'count': 2},
            {'name': 'stick'}],
           {'name': 'emerald_blade'},
           collection_req=('emerald', 8)),
    Recipe('emerald_helmet', 'mining',
           [{'name': 'enchanted_emerald_block', 'count': 5}],
           {'name': 'emerald_helmet'},
           collection_req=('emerald', 9)),
    Recipe('emerald_chestplate', 'mining',
           [{'name': 'enchanted_emerald_block', 'count': 8}],
           {'name': 'emerald_chestplate'},
           collection_req=('emerald', 9)),
    Recipe('emerald_leggings', 'mining',
           [{'name': 'enchanted_emerald_block', 'count': 7}],
           {'name': 'emerald_leggings'},
           collection_req=('emerald', 9)),
    Recipe('emerald_boots', 'mining',
           [{'name': 'enchanted_emerald_block', 'count': 4}],
           {'name': 'emerald_boots'},
           collection_req=('emerald', 9)),
    RecipeGroup('emerald_armor', 'mining',
                ['emerald_helmet', 'emerald_chestplate',
                 'emerald_leggings', 'emerald_boots'],
                collection_req=('emerald', 9)),

    Recipe('efficiency_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'redstone', 'count': 8}],
           {'name': 'enchanted_book', 'enchantments': {'efficiency': 4}},
           collection_req=('redstone', 3)),
    Recipe('redstone_to_enchanted', 'mining',
           [{'name': 'redstone', 'count': 160}],
           {'name': 'enchanted_redstone'},
           collection_req=('redstone', 4)),
    Recipe('scroll_to_deep', 'mining',
           [{'name': 'enchanted_ender_pearl', 'count': 16},
            {'name': 'enchanted_redstone', 'count': 48},
            {'name': 'enchanted_lapis', 'count': 80}],
           {'name': 'travel_scroll_to_deep'},
           collection_req=('redstone', 7)),
    Recipe('redstone_to_enchanted_block', 'mining',
           [{'name': 'enchanted_redstone', 'count': 160}],
           {'name': 'enchanted_redstone_block'},
           collection_req=('redstone', 8)),

    Recipe('quartz_to_enchanted', 'mining',
           [{'name': 'quartz', 'count': 160}],
           {'name': 'enchanted_quartz'},
           collection_req=('quartz', 4)),
    Recipe('quartz_to_enchanted_block', 'mining',
           [{'name': 'enchanted_quartz', 'count': 160}],
           {'name': 'enchanted_quartz_block'},
           collection_req=('quartz', 6)),

    Recipe('lethality_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'obsidian', 'count': 24}],
           {'name': 'enchanted_book', 'enchantments': {'lethality': 4}},
           collection_req=('obsidian', 2)),
    Recipe('obsidian_to_enchanted', 'mining',
           [{'name': 'obsidian', 'count': 160}],
           {'name': 'enchanted_obsidian'},
           collection_req=('obsidian', 4)),
    Recipe('treecapitator', 'mining',
           [{'name': 'jungle_axe'},
            {'name': 'enchanted_obsidian', 'count': 512}],
           {'name': 'treecapitator'},
           collection_req=('obsidian', 8)),

    Recipe('glowstone_to_enchanted', 'mining',
           [{'name': 'glowstone', 'count': 160}],
           {'name': 'enchanted_glowstone'},
           collection_req=('glowstone', 4)),
    Recipe('glowstone_to_enchanted_block', 'mining',
           [{'name': 'enchanted_glowstone', 'count': 192}],
           {'name': 'enchanted_glowstone_block'},
           collection_req=('glowstone', 6)),
    Recipe('glowstone_to_enchanted_lamp', 'mining',
           [{'name': 'enchanted_redstone', 'count': 32},
            {'name': 'enchanted_glowstone', 'count': 128}],
           {'name': 'enchanted_redstone_lamp'},
           collection_req=('glowstone', 7)),

    Recipe('sharpness_book', 'enchanting',
           [{'name': 'paper', 'count': 24},
            {'name': 'flint', 'count': 8},
            {'name': 'iron_sword'}],
           {'name': 'enchanted_book', 'enchantments': {'sharpness': 4}},
           collection_req=('flint', 4)),
    Recipe('flint_to_enchanted', 'mining',
           [{'name': 'flint', 'count': 160}],
           {'name': 'enchanted_flint'},
           collection_req=('flint', 5)),
    Recipe('first_strike_book', 'enchanting',
           [{'name': 'paper', 'count': 12},
            {'name': 'enchanted_flint', 'count': 4},
            {'name': 'iron_sword'}],
           {'name': 'enchanted_book', 'enchantments': {'first_strike': 3}},
           collection_req=('flint', 6)),
    Recipe('scroll_to_spider', 'mining',
           [{'name': 'enchanted_ender_pearl', 'count': 16},
            {'name': 'enchanted_flint', 'count': 128}],
           {'name': 'travel_scroll_to_spider'},
           collection_req=('flint', 8)),

    Recipe('ice_to_packed', 'mining',
           [{'name': 'ice', 'count': 160}],
           {'name': 'packed_ice'},
           collection_req=('ice', 3)),
    Recipe('ice_to_enchanted', 'mining',
           [{'name': 'ice', 'count': 160}],
           {'name': 'enchanted_ice'},
           collection_req=('ice', 4)),
    Recipe('ice_bait', 'mining',
           [{'name': 'ice'},
            {'name': 'fish'}],
           {'name': 'ice_bait'},
           collection_req=('ice', 6)),
    Recipe('ice_to_enchanted_packed', 'mining',
           [{'name': 'enchanted_ice', 'count': 192}],
           {'name': 'enchanted_packed_ice'},
           collection_req=('ice', 7)),
    Recipe('frozen_scythe', 'mining',
           [{'name': 'enchanted_packed_ice', 'count': 64},
            {'name': 'stick', 'count': 2}],
           {'name': 'frozen_scythe'},
           collection_req=('ice', 8)),

    Recipe('frozen_blaze_helmet', 'mining',
           [{'name': 'enchanted_packed_ice', 'count': 64},
            {'name': 'blaze_helmet'}],
           {'name': 'frozen_blaze_helmet'},
           collection_req=('ice', 9)),
    Recipe('frozen_blaze_chestplate', 'mining',
           [{'name': 'enchanted_packed_ice', 'count': 64},
            {'name': 'blaze_chestplate'}],
           {'name': 'frozen_blaze_chestplate'},
           collection_req=('ice', 9)),
    Recipe('frozen_blaze_leggings', 'mining',
           [{'name': 'enchanted_packed_ice', 'count': 64},
            {'name': 'blaze_leggings'}],
           {'name': 'frozen_blaze_leggings'},
           collection_req=('ice', 9)),
    Recipe('frozen_blaze_boots', 'mining',
           [{'name': 'enchanted_packed_ice', 'count': 64},
            {'name': 'blaze_boots'}],
           {'name': 'frozen_blaze_boots'},
           collection_req=('ice', 9)),

    Recipe('netherrack_to_enchanted', 'mining',
           [{'name': 'netherrack', 'count': 160}],
           {'name': 'enchanted_netherrack'},
           collection_req=('netherrack', 4)),

    Recipe('sand_to_enchanted', 'mining',
           [{'name': 'sand', 'count': 160}],
           {'name': 'enchanted_sand'},
           collection_req=('sand', 5)),

    Recipe('end_stone_to_enchanted', 'mining',
           [{'name': 'end_stone', 'count': 160}],
           {'name': 'enchanted_end_stone'},
           collection_req=('end_stone', 4)),
    Recipe('uncommon_endermite_pet', 'mining',
           [{'name': 'enchanted_end_stone', 'count': 512},
            {'name': 'enchanted_egg'}],
           {'name': 'endermite_pet', 'rarity': 'uncommon'},
           collection_req=('end_stone', 7)),
    Recipe('epic_endermite_pet', 'mining',
           [{'name': 'enchanted_end_stone', 'count': 512},
            {'name': 'super_enchanted_egg'}],
           {'name': 'endermite_pet', 'rarity': 'epic'},
           collection_req=('end_stone', 7)),
    RecipeGroup('endermite_pet', 'mining',
                ['uncommon_endermite_pet', 'epic_endermite_pet'],
                collection_req=('end_stone', 7)),
    Recipe('scroll_to_end', 'mining',
           [{'name': 'enchanted_ender_pearl', 'count': 16},
            {'name': 'enchanted_obsidian', 'count': 48},
            {'name': 'enchanted_end_stone', 'count': 80}],
           {'name': 'travel_scroll_to_end'},
           collection_req=('end_stone', 8)),
    Recipe('end_stone_sword', 'mining',
           [{'name': 'enchanted_end_stone', 'count': 128},
            {'name': 'stick'}],
           {'name': 'end_stone_sword'},
           collection_req=('end_stone', 10)),

    Recipe('mithril_to_enchanted', 'mining',
           [{'name': 'mithril', 'count': 160}],
           {'name': 'enchanted_mithril'},
           collection_req=('mithril', 3)),
    Recipe('mithril_coat', 'mining',
           [{'name': 'enchanted_mithril', 'count': 32}],
           {'name': 'mithril_coat'},
           collection_req=('mithril', 5)),
    Recipe('uncommon_mithril_golem_pet', 'mining',
           [{'name': 'enchanted_cobblestone', 'count': 64},
            {'name': 'enchanted_egg'}],
           {'name': 'mithril_golem_pet', 'rarity': 'uncommon'},
           collection_req=('mithril', 7)),
    Recipe('epic_mithril_golem_pet', 'mining',
           [{'name': 'enchanted_cobblestone', 'count': 64},
            {'name': 'super_enchanted_egg'}],
           {'name': 'mithril_golem_pet', 'rarity': 'epic'},
           collection_req=('mithril', 7)),
    RecipeGroup('mithril_golem_pet', 'mining',
                ['uncommon_mithril_golem_pet', 'epic_mithril_golem_pet'],
                collection_req=('mithril', 7)),

    Recipe('titanium_to_enchanted', 'mining',
           [{'name': 'titanium', 'count': 160}],
           {'name': 'enchanted_titanium'}),

    Recipe('sorrow_helmet', 'mining',
           [{'name': 'sorrow', 'count': 15}],
           {'name': 'sorrow_helmet'}),
    Recipe('sorrow_chestplate', 'mining',
           [{'name': 'sorrow', 'count': 24}],
           {'name': 'sorrow_chestplate'}),
    Recipe('sorrow_leggings', 'mining',
           [{'name': 'sorrow', 'count': 21}],
           {'name': 'sorrow_leggings'}),
    Recipe('sorrow_boots', 'mining',
           [{'name': 'sorrow', 'count': 12}],
           {'name': 'sorrow_boots'}),
]
