from ..object import *


MINING_MINION_RECIPES = [
    Recipe('cobblestone_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'cobblestone', 'count': 80}],
           {'name': 'cobblestone_minion', 'tier': 1},
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_2', 'mining',
           [{'name': 'cobblestone_minion', 'tier': 1},
            {'name': 'cobblestone', 'count': 160}],
           {'name': 'cobblestone_minion', 'tier': 2},
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_3', 'mining',
           [{'name': 'cobblestone_minion', 'tier': 2},
            {'name': 'cobblestone', 'count': 320}],
           {'name': 'cobblestone_minion', 'tier': 3},
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_4', 'mining',
           [{'name': 'cobblestone_minion', 'tier': 3},
            {'name': 'cobblestone', 'count': 512}],
           {'name': 'cobblestone_minion', 'tier': 4},
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_5', 'mining',
           [{'name': 'cobblestone_minion', 'tier': 4},
            {'name': 'enchanted_cobblestone', 'count': 8}],
           {'name': 'cobblestone_minion', 'tier': 5},
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_6', 'mining',
           [{'name': 'cobblestone_minion', 'tier': 5},
            {'name': 'enchanted_cobblestone', 'count': 16}],
           {'name': 'cobblestone_minion', 'tier': 6},
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_7', 'mining',
           [{'name': 'cobblestone_minion', 'tier': 6},
            {'name': 'enchanted_cobblestone', 'count': 32}],
           {'name': 'cobblestone_minion', 'tier': 7},
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_8', 'mining',
           [{'name': 'cobblestone_minion', 'tier': 7},
            {'name': 'enchanted_cobblestone', 'count': 64}],
           {'name': 'cobblestone_minion', 'tier': 8},
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_9', 'mining',
           [{'name': 'cobblestone_minion', 'tier': 8},
            {'name': 'enchanted_cobblestone', 'count': 128}],
           {'name': 'cobblestone_minion', 'tier': 9},
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_10', 'mining',
           [{'name': 'cobblestone_minion', 'tier': 9},
            {'name': 'enchanted_cobblestone', 'count': 256}],
           {'name': 'cobblestone_minion', 'tier': 10},
           collection_req=('cobblestone', 1)),
    Recipe('cobblestone_minion_11', 'mining',
           [{'name': 'cobblestone_minion', 'tier': 10},
            {'name': 'enchanted_cobblestone', 'count': 512}],
           {'name': 'cobblestone_minion', 'tier': 11},
           collection_req=('cobblestone', 1)),
    RecipeGroup('cobblestone_minion', 'mining',
                ['cobblestone_minion_1', 'cobblestone_minion_2',
                 'cobblestone_minion_3', 'cobblestone_minion_4',
                 'cobblestone_minion_5', 'cobblestone_minion_6',
                 'cobblestone_minion_7', 'cobblestone_minion_8',
                 'cobblestone_minion_9', 'cobblestone_minion_10',
                 'cobblestone_minion_11'],
                collection_req=('cobblestone', 1)),

    Recipe('coal_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'coal', 'count': 80}],
           {'name': 'coal_minion', 'tier': 1},
           collection_req=('coal', 1)),
    Recipe('coal_minion_2', 'mining',
           [{'name': 'coal_minion', 'tier': 1},
            {'name': 'coal', 'count': 160}],
           {'name': 'coal_minion', 'tier': 2},
           collection_req=('coal', 1)),
    Recipe('coal_minion_3', 'mining',
           [{'name': 'coal_minion', 'tier': 2},
            {'name': 'coal', 'count': 320}],
           {'name': 'coal_minion', 'tier': 3},
           collection_req=('coal', 1)),
    Recipe('coal_minion_4', 'mining',
           [{'name': 'coal_minion', 'tier': 3},
            {'name': 'coal', 'count': 512}],
           {'name': 'coal_minion', 'tier': 4},
           collection_req=('coal', 1)),
    Recipe('coal_minion_5', 'mining',
           [{'name': 'coal_minion', 'tier': 4},
            {'name': 'enchanted_coal', 'count': 8}],
           {'name': 'coal_minion', 'tier': 5},
           collection_req=('coal', 1)),
    Recipe('coal_minion_6', 'mining',
           [{'name': 'coal_minion', 'tier': 5},
            {'name': 'enchanted_coal', 'count': 24}],
           {'name': 'coal_minion', 'tier': 6},
           collection_req=('coal', 1)),
    Recipe('coal_minion_7', 'mining',
           [{'name': 'coal_minion', 'tier': 6},
            {'name': 'enchanted_coal', 'count': 64}],
           {'name': 'coal_minion', 'tier': 7},
           collection_req=('coal', 1)),
    Recipe('coal_minion_8', 'mining',
           [{'name': 'coal_minion', 'tier': 7},
            {'name': 'enchanted_coal', 'count': 128}],
           {'name': 'coal_minion', 'tier': 8},
           collection_req=('coal', 1)),
    Recipe('coal_minion_9', 'mining',
           [{'name': 'coal_minion', 'tier': 8},
            {'name': 'enchanted_coal', 'count': 256}],
           {'name': 'coal_minion', 'tier': 9},
           collection_req=('coal', 1)),
    Recipe('coal_minion_10', 'mining',
           [{'name': 'coal_minion', 'tier': 9},
            {'name': 'enchanted_coal', 'count': 512}],
           {'name': 'coal_minion', 'tier': 10},
           collection_req=('coal', 1)),
    Recipe('coal_minion_11', 'mining',
           [{'name': 'coal_minion', 'tier': 10},
            {'name': 'enchanted_coal_block', 'count': 8}],
           {'name': 'coal_minion', 'tier': 11},
           collection_req=('coal', 1)),
    RecipeGroup('coal_minion', 'mining',
                ['coal_minion_1', 'coal_minion_2', 'coal_minion_3',
                 'coal_minion_4', 'coal_minion_5', 'coal_minion_6',
                 'coal_minion_7', 'coal_minion_8', 'coal_minion_9',
                 'coal_minion_10', 'coal_minion_11'],
                collection_req=('coal', 1)),

    Recipe('iron_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'iron', 'count': 80}],
           {'name': 'iron_minion', 'tier': 1},
           collection_req=('iron', 1)),
    Recipe('iron_minion_2', 'mining',
           [{'name': 'iron_minion', 'tier': 1},
            {'name': 'iron', 'count': 160}],
           {'name': 'iron_minion', 'tier': 2},
           collection_req=('iron', 1)),
    Recipe('iron_minion_3', 'mining',
           [{'name': 'iron_minion', 'tier': 2},
            {'name': 'iron', 'count': 320}],
           {'name': 'iron_minion', 'tier': 3},
           collection_req=('iron', 1)),
    Recipe('iron_minion_4', 'mining',
           [{'name': 'iron_minion', 'tier': 3},
            {'name': 'iron', 'count': 512}],
           {'name': 'iron_minion', 'tier': 4},
           collection_req=('iron', 1)),
    Recipe('iron_minion_5', 'mining',
           [{'name': 'iron_minion', 'tier': 4},
            {'name': 'enchanted_iron', 'count': 8}],
           {'name': 'iron_minion', 'tier': 5},
           collection_req=('iron', 1)),
    Recipe('iron_minion_6', 'mining',
           [{'name': 'iron_minion', 'tier': 5},
            {'name': 'enchanted_iron', 'count': 24}],
           {'name': 'iron_minion', 'tier': 6},
           collection_req=('iron', 1)),
    Recipe('iron_minion_7', 'mining',
           [{'name': 'iron_minion', 'tier': 6},
            {'name': 'enchanted_iron', 'count': 64}],
           {'name': 'iron_minion', 'tier': 7},
           collection_req=('iron', 1)),
    Recipe('iron_minion_8', 'mining',
           [{'name': 'iron_minion', 'tier': 7},
            {'name': 'enchanted_iron', 'count': 128}],
           {'name': 'iron_minion', 'tier': 8},
           collection_req=('iron', 1)),
    Recipe('iron_minion_9', 'mining',
           [{'name': 'iron_minion', 'tier': 8},
            {'name': 'enchanted_iron', 'count': 256}],
           {'name': 'iron_minion', 'tier': 9},
           collection_req=('iron', 1)),
    Recipe('iron_minion_10', 'mining',
           [{'name': 'iron_minion', 'tier': 9},
            {'name': 'enchanted_iron', 'count': 512}],
           {'name': 'iron_minion', 'tier': 10},
           collection_req=('iron', 1)),
    Recipe('iron_minion_11', 'mining',
           [{'name': 'iron_minion', 'tier': 10},
            {'name': 'enchanted_iron_block', 'count': 8}],
           {'name': 'iron_minion', 'tier': 11},
           collection_req=('iron', 1)),
    RecipeGroup('iron_minion', 'mining',
                ['iron_minion_1', 'iron_minion_2', 'iron_minion_3',
                 'iron_minion_4', 'iron_minion_5', 'iron_minion_6',
                 'iron_minion_7', 'iron_minion_8', 'iron_minion_9',
                 'iron_minion_10', 'iron_minion_11'],
                collection_req=('iron', 1)),

    Recipe('gold_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'gold', 'count': 80}],
           {'name': 'gold_minion', 'tier': 1},
           collection_req=('gold', 1)),
    Recipe('gold_minion_2', 'mining',
           [{'name': 'gold_minion', 'tier': 1},
            {'name': 'gold', 'count': 160}],
           {'name': 'gold_minion', 'tier': 2},
           collection_req=('gold', 1)),
    Recipe('gold_minion_3', 'mining',
           [{'name': 'gold_minion', 'tier': 2},
            {'name': 'gold', 'count': 320}],
           {'name': 'gold_minion', 'tier': 3},
           collection_req=('gold', 1)),
    Recipe('gold_minion_4', 'mining',
           [{'name': 'gold_minion', 'tier': 3},
            {'name': 'gold', 'count': 512}],
           {'name': 'gold_minion', 'tier': 4},
           collection_req=('gold', 1)),
    Recipe('gold_minion_5', 'mining',
           [{'name': 'gold_minion', 'tier': 4},
            {'name': 'enchanted_gold', 'count': 8}],
           {'name': 'gold_minion', 'tier': 5},
           collection_req=('gold', 1)),
    Recipe('gold_minion_6', 'mining',
           [{'name': 'gold_minion', 'tier': 5},
            {'name': 'enchanted_gold', 'count': 24}],
           {'name': 'gold_minion', 'tier': 6},
           collection_req=('gold', 1)),
    Recipe('gold_minion_7', 'mining',
           [{'name': 'gold_minion', 'tier': 6},
            {'name': 'enchanted_gold', 'count': 64}],
           {'name': 'gold_minion', 'tier': 7},
           collection_req=('gold', 1)),
    Recipe('gold_minion_8', 'mining',
           [{'name': 'gold_minion', 'tier': 7},
            {'name': 'enchanted_gold', 'count': 128}],
           {'name': 'gold_minion', 'tier': 8},
           collection_req=('gold', 1)),
    Recipe('gold_minion_9', 'mining',
           [{'name': 'gold_minion', 'tier': 8},
            {'name': 'enchanted_gold', 'count': 256}],
           {'name': 'gold_minion', 'tier': 9},
           collection_req=('gold', 1)),
    Recipe('gold_minion_10', 'mining',
           [{'name': 'gold_minion', 'tier': 9},
            {'name': 'enchanted_gold', 'count': 512}],
           {'name': 'gold_minion', 'tier': 10},
           collection_req=('gold', 1)),
    Recipe('gold_minion_11', 'mining',
           [{'name': 'gold_minion', 'tier': 10},
            {'name': 'enchanted_gold_block', 'count': 8}],
           {'name': 'gold_minion', 'tier': 11},
           collection_req=('gold', 1)),
    RecipeGroup('gold_minion', 'mining',
                ['gold_minion_1', 'gold_minion_2', 'gold_minion_3',
                 'gold_minion_4', 'gold_minion_5', 'gold_minion_6',
                 'gold_minion_7', 'gold_minion_8', 'gold_minion_9',
                 'gold_minion_10', 'gold_minion_11'],
                collection_req=('gold', 1)),

    Recipe('diamond_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'diamond', 'count': 80}],
           {'name': 'diamond_minion', 'tier': 1},
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_2', 'mining',
           [{'name': 'diamond_minion', 'tier': 1},
            {'name': 'diamond', 'count': 160}],
           {'name': 'diamond_minion', 'tier': 2},
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_3', 'mining',
           [{'name': 'diamond_minion', 'tier': 2},
            {'name': 'diamond', 'count': 320}],
           {'name': 'diamond_minion', 'tier': 3},
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_4', 'mining',
           [{'name': 'diamond_minion', 'tier': 3},
            {'name': 'diamond', 'count': 512}],
           {'name': 'diamond_minion', 'tier': 4},
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_5', 'mining',
           [{'name': 'diamond_minion', 'tier': 4},
            {'name': 'enchanted_diamond', 'count': 8}],
           {'name': 'diamond_minion', 'tier': 5},
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_6', 'mining',
           [{'name': 'diamond_minion', 'tier': 5},
            {'name': 'enchanted_diamond', 'count': 24}],
           {'name': 'diamond_minion', 'tier': 6},
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_7', 'mining',
           [{'name': 'diamond_minion', 'tier': 6},
            {'name': 'enchanted_diamond', 'count': 64}],
           {'name': 'diamond_minion', 'tier': 7},
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_8', 'mining',
           [{'name': 'diamond_minion', 'tier': 7},
            {'name': 'enchanted_diamond', 'count': 128}],
           {'name': 'diamond_minion', 'tier': 8},
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_9', 'mining',
           [{'name': 'diamond_minion', 'tier': 8},
            {'name': 'enchanted_diamond', 'count': 256}],
           {'name': 'diamond_minion', 'tier': 9},
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_10', 'mining',
           [{'name': 'diamond_minion', 'tier': 9},
            {'name': 'enchanted_diamond', 'count': 512}],
           {'name': 'diamond_minion', 'tier': 10},
           collection_req=('diamond', 1)),
    Recipe('diamond_minion_11', 'mining',
           [{'name': 'diamond_minion', 'tier': 10},
            {'name': 'enchanted_diamond_block', 'count': 8}],
           {'name': 'diamond_minion', 'tier': 11},
           collection_req=('diamond', 1)),
    RecipeGroup('diamond_minion', 'mining',
                ['diamond_minion_1', 'diamond_minion_2', 'diamond_minion_3',
                 'diamond_minion_4', 'diamond_minion_5', 'diamond_minion_6',
                 'diamond_minion_7', 'diamond_minion_8', 'diamond_minion_9',
                 'diamond_minion_10', 'diamond_minion_11'],
                collection_req=('diamond', 1)),

    Recipe('lapis_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'lapis', 'count': 256}],
           {'name': 'lapis_minion', 'tier': 1},
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_2', 'mining',
           [{'name': 'lapis_minion', 'tier': 1},
            {'name': 'lapis', 'count': 512}],
           {'name': 'lapis_minion', 'tier': 2},
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_3', 'mining',
           [{'name': 'lapis_minion', 'tier': 2},
            {'name': 'enchanted_lapis', 'count': 8}],
           {'name': 'lapis_minion', 'tier': 3},
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_4', 'mining',
           [{'name': 'lapis_minion', 'tier': 3},
            {'name': 'enchanted_lapis', 'count': 24}],
           {'name': 'lapis_minion', 'tier': 4},
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_5', 'mining',
           [{'name': 'lapis_minion', 'tier': 4},
            {'name': 'enchanted_lapis', 'count': 64}],
           {'name': 'lapis_minion', 'tier': 5},
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_6', 'mining',
           [{'name': 'lapis_minion', 'tier': 5},
            {'name': 'enchanted_lapis', 'count': 128}],
           {'name': 'lapis_minion', 'tier': 6},
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_7', 'mining',
           [{'name': 'lapis_minion', 'tier': 6},
            {'name': 'enchanted_lapis', 'count': 256}],
           {'name': 'lapis_minion', 'tier': 7},
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_8', 'mining',
           [{'name': 'lapis_minion', 'tier': 7},
            {'name': 'enchanted_lapis', 'count': 512}],
           {'name': 'lapis_minion', 'tier': 8},
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_9', 'mining',
           [{'name': 'lapis_minion', 'tier': 8},
            {'name': 'enchanted_lapis_block', 'count': 8}],
           {'name': 'lapis_minion', 'tier': 9},
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_10', 'mining',
           [{'name': 'lapis_minion', 'tier': 9},
            {'name': 'enchanted_lapis_block', 'count': 16}],
           {'name': 'lapis_minion', 'tier': 10},
           collection_req=('lapis', 1)),
    Recipe('lapis_minion_11', 'mining',
           [{'name': 'lapis_minion', 'tier': 10},
            {'name': 'enchanted_lapis_block', 'count': 32}],
           {'name': 'lapis_minion', 'tier': 11},
           collection_req=('lapis', 1)),
    RecipeGroup('lapis_minion', 'mining',
                ['lapis_minion_1', 'lapis_minion_2', 'lapis_minion_3',
                 'lapis_minion_4', 'lapis_minion_5', 'lapis_minion_6',
                 'lapis_minion_7', 'lapis_minion_8', 'lapis_minion_9',
                 'lapis_minion_10', 'lapis_minion_11'],
                collection_req=('lapis', 1)),

    Recipe('emerald_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'emerald', 'count': 80}],
           {'name': 'emerald_minion', 'tier': 1},
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_2', 'mining',
           [{'name': 'emerald_minion', 'tier': 1},
            {'name': 'emerald', 'count': 160}],
           {'name': 'emerald_minion', 'tier': 2},
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_3', 'mining',
           [{'name': 'emerald_minion', 'tier': 2},
            {'name': 'emerald', 'count': 320}],
           {'name': 'emerald_minion', 'tier': 3},
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_4', 'mining',
           [{'name': 'emerald_minion', 'tier': 3},
            {'name': 'emerald', 'count': 512}],
           {'name': 'emerald_minion', 'tier': 4},
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_5', 'mining',
           [{'name': 'emerald_minion', 'tier': 4},
            {'name': 'enchanted_emerald', 'count': 8}],
           {'name': 'emerald_minion', 'tier': 5},
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_6', 'mining',
           [{'name': 'emerald_minion', 'tier': 5},
            {'name': 'enchanted_emerald', 'count': 24}],
           {'name': 'emerald_minion', 'tier': 6},
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_7', 'mining',
           [{'name': 'emerald_minion', 'tier': 6},
            {'name': 'enchanted_emerald', 'count': 64}],
           {'name': 'emerald_minion', 'tier': 7},
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_8', 'mining',
           [{'name': 'emerald_minion', 'tier': 7},
            {'name': 'enchanted_emerald', 'count': 128}],
           {'name': 'emerald_minion', 'tier': 8},
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_9', 'mining',
           [{'name': 'emerald_minion', 'tier': 8},
            {'name': 'enchanted_emerald', 'count': 256}],
           {'name': 'emerald_minion', 'tier': 9},
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_10', 'mining',
           [{'name': 'emerald_minion', 'tier': 9},
            {'name': 'enchanted_emerald', 'count': 512}],
           {'name': 'emerald_minion', 'tier': 10},
           collection_req=('emerald', 1)),
    Recipe('emerald_minion_11', 'mining',
           [{'name': 'emerald_minion', 'tier': 10},
            {'name': 'enchanted_emerald_block', 'count': 8}],
           {'name': 'emerald_minion', 'tier': 11},
           collection_req=('emerald', 1)),
    RecipeGroup('emerald_minion', 'mining',
                ['emerald_minion_1', 'emerald_minion_2', 'emerald_minion_3',
                 'emerald_minion_4', 'emerald_minion_5', 'emerald_minion_6',
                 'emerald_minion_7', 'emerald_minion_8', 'emerald_minion_9',
                 'emerald_minion_10', 'emerald_minion_11'],
                collection_req=('emerald', 1)),

    Recipe('redstone_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'redstone', 'count': 128}],
           {'name': 'redstone_minion', 'tier': 1},
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_2', 'mining',
           [{'name': 'redstone_minion', 'tier': 1},
            {'name': 'redstone', 'count': 256}],
           {'name': 'redstone_minion', 'tier': 2},
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_3', 'mining',
           [{'name': 'redstone_minion', 'tier': 2},
            {'name': 'redstone', 'count': 512}],
           {'name': 'redstone_minion', 'tier': 3},
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_4', 'mining',
           [{'name': 'redstone_minion', 'tier': 3},
            {'name': 'enchanted_redstone', 'count': 8}],
           {'name': 'redstone_minion', 'tier': 4},
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_5', 'mining',
           [{'name': 'redstone_minion', 'tier': 4},
            {'name': 'enchanted_redstone', 'count': 24}],
           {'name': 'redstone_minion', 'tier': 5},
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_6', 'mining',
           [{'name': 'redstone_minion', 'tier': 5},
            {'name': 'enchanted_redstone', 'count': 64}],
           {'name': 'redstone_minion', 'tier': 6},
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_7', 'mining',
           [{'name': 'redstone_minion', 'tier': 6},
            {'name': 'enchanted_redstone', 'count': 128}],
           {'name': 'redstone_minion', 'tier': 7},
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_8', 'mining',
           [{'name': 'redstone_minion', 'tier': 7},
            {'name': 'enchanted_redstone', 'count': 256}],
           {'name': 'redstone_minion', 'tier': 8},
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_9', 'mining',
           [{'name': 'redstone_minion', 'tier': 8},
            {'name': 'enchanted_redstone', 'count': 512}],
           {'name': 'redstone_minion', 'tier': 9},
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_10', 'mining',
           [{'name': 'redstone_minion', 'tier': 9},
            {'name': 'enchanted_redstone_block', 'count': 8}],
           {'name': 'redstone_minion', 'tier': 10},
           collection_req=('redstone', 1)),
    Recipe('redstone_minion_11', 'mining',
           [{'name': 'redstone_minion', 'tier': 10},
            {'name': 'enchanted_redstone_block', 'count': 16}],
           {'name': 'redstone_minion', 'tier': 11},
           collection_req=('redstone', 1)),
    RecipeGroup('redstone_minion', 'mining',
                ['redstone_minion_1', 'redstone_minion_2', 'redstone_minion_3',
                 'redstone_minion_4', 'redstone_minion_5', 'redstone_minion_6',
                 'redstone_minion_7', 'redstone_minion_8', 'redstone_minion_9',
                 'redstone_minion_10', 'redstone_minion_11'],
                collection_req=('redstone', 1)),

    Recipe('quartz_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'quartz', 'count': 80}],
           {'name': 'quartz_minion', 'tier': 1},
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_2', 'mining',
           [{'name': 'quartz_minion', 'tier': 1},
            {'name': 'quartz', 'count': 160}],
           {'name': 'quartz_minion', 'tier': 2},
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_3', 'mining',
           [{'name': 'quartz_minion', 'tier': 2},
            {'name': 'quartz', 'count': 320}],
           {'name': 'quartz_minion', 'tier': 3},
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_4', 'mining',
           [{'name': 'quartz_minion', 'tier': 3},
            {'name': 'quartz', 'count': 512}],
           {'name': 'quartz_minion', 'tier': 4},
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_5', 'mining',
           [{'name': 'quartz_minion', 'tier': 4},
            {'name': 'enchanted_quartz', 'count': 8}],
           {'name': 'quartz_minion', 'tier': 5},
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_6', 'mining',
           [{'name': 'quartz_minion', 'tier': 5},
            {'name': 'enchanted_quartz', 'count': 24}],
           {'name': 'quartz_minion', 'tier': 6},
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_7', 'mining',
           [{'name': 'quartz_minion', 'tier': 6},
            {'name': 'enchanted_quartz', 'count': 64}],
           {'name': 'quartz_minion', 'tier': 7},
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_8', 'mining',
           [{'name': 'quartz_minion', 'tier': 7},
            {'name': 'enchanted_quartz', 'count': 128}],
           {'name': 'quartz_minion', 'tier': 8},
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_9', 'mining',
           [{'name': 'quartz_minion', 'tier': 8},
            {'name': 'enchanted_quartz', 'count': 256}],
           {'name': 'quartz_minion', 'tier': 9},
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_10', 'mining',
           [{'name': 'quartz_minion', 'tier': 9},
            {'name': 'enchanted_quartz', 'count': 512}],
           {'name': 'quartz_minion', 'tier': 10},
           collection_req=('quartz', 1)),
    Recipe('quartz_minion_11', 'mining',
           [{'name': 'quartz_minion', 'tier': 10},
            {'name': 'enchanted_quartz_block', 'count': 8}],
           {'name': 'quartz_minion', 'tier': 11},
           collection_req=('quartz', 1)),
    RecipeGroup('quartz_minion', 'mining',
                ['quartz_minion_1', 'quartz_minion_2', 'quartz_minion_3',
                 'quartz_minion_4', 'quartz_minion_5', 'quartz_minion_6',
                 'quartz_minion_7', 'quartz_minion_8', 'quartz_minion_9',
                 'quartz_minion_10', 'quartz_minion_11'],
                collection_req=('quartz', 1)),

    Recipe('obsidian_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'obsidian', 'count': 80}],
           {'name': 'obsidian_minion', 'tier': 1},
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_2', 'mining',
           [{'name': 'obsidian_minion', 'tier': 1},
            {'name': 'obsidian', 'count': 160}],
           {'name': 'obsidian_minion', 'tier': 2},
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_3', 'mining',
           [{'name': 'obsidian_minion', 'tier': 2},
            {'name': 'obsidian', 'count': 320}],
           {'name': 'obsidian_minion', 'tier': 3},
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_4', 'mining',
           [{'name': 'obsidian_minion', 'tier': 3},
            {'name': 'obsidian', 'count': 512}],
           {'name': 'obsidian_minion', 'tier': 4},
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_5', 'mining',
           [{'name': 'obsidian_minion', 'tier': 4},
            {'name': 'enchanted_obsidian', 'count': 8}],
           {'name': 'obsidian_minion', 'tier': 5},
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_6', 'mining',
           [{'name': 'obsidian_minion', 'tier': 5},
            {'name': 'enchanted_obsidian', 'count': 16}],
           {'name': 'obsidian_minion', 'tier': 6},
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_7', 'mining',
           [{'name': 'obsidian_minion', 'tier': 6},
            {'name': 'enchanted_obsidian', 'count': 32}],
           {'name': 'obsidian_minion', 'tier': 7},
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_8', 'mining',
           [{'name': 'obsidian_minion', 'tier': 7},
            {'name': 'enchanted_obsidian', 'count': 64}],
           {'name': 'obsidian_minion', 'tier': 8},
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_9', 'mining',
           [{'name': 'obsidian_minion', 'tier': 8},
            {'name': 'enchanted_obsidian', 'count': 128}],
           {'name': 'obsidian_minion', 'tier': 9},
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_10', 'mining',
           [{'name': 'obsidian_minion', 'tier': 9},
            {'name': 'enchanted_obsidian', 'count': 256}],
           {'name': 'obsidian_minion', 'tier': 10},
           collection_req=('obsidian', 1)),
    Recipe('obsidian_minion_11', 'mining',
           [{'name': 'obsidian_minion', 'tier': 10},
            {'name': 'enchanted_obsidian', 'count': 512}],
           {'name': 'obsidian_minion', 'tier': 11},
           collection_req=('obsidian', 1)),
    RecipeGroup('obsidian_minion', 'mining',
                ['obsidian_minion_1', 'obsidian_minion_2', 'obsidian_minion_3',
                 'obsidian_minion_4', 'obsidian_minion_5', 'obsidian_minion_6',
                 'obsidian_minion_7', 'obsidian_minion_8', 'obsidian_minion_9',
                 'obsidian_minion_10', 'obsidian_minion_11'],
                collection_req=('obsidian', 1)),

    Recipe('glowstone_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'glowstone', 'count': 128}],
           {'name': 'glowstone_minion', 'tier': 1},
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_2', 'mining',
           [{'name': 'glowstone_minion', 'tier': 1},
            {'name': 'glowstone', 'count': 256}],
           {'name': 'glowstone_minion', 'tier': 2},
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_3', 'mining',
           [{'name': 'glowstone_minion', 'tier': 2},
            {'name': 'glowstone', 'count': 512}],
           {'name': 'glowstone_minion', 'tier': 3},
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_4', 'mining',
           [{'name': 'glowstone_minion', 'tier': 3},
            {'name': 'enchanted_glowstone', 'count': 8}],
           {'name': 'glowstone_minion', 'tier': 4},
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_5', 'mining',
           [{'name': 'glowstone_minion', 'tier': 4},
            {'name': 'enchanted_glowstone', 'count': 24}],
           {'name': 'glowstone_minion', 'tier': 5},
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_6', 'mining',
           [{'name': 'glowstone_minion', 'tier': 5},
            {'name': 'enchanted_glowstone', 'count': 64}],
           {'name': 'glowstone_minion', 'tier': 6},
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_7', 'mining',
           [{'name': 'glowstone_minion', 'tier': 6},
            {'name': 'enchanted_glowstone', 'count': 128}],
           {'name': 'glowstone_minion', 'tier': 7},
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_8', 'mining',
           [{'name': 'glowstone_minion', 'tier': 7},
            {'name': 'enchanted_glowstone', 'count': 256}],
           {'name': 'glowstone_minion', 'tier': 8},
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_9', 'mining',
           [{'name': 'glowstone_minion', 'tier': 8},
            {'name': 'enchanted_glowstone', 'count': 512}],
           {'name': 'glowstone_minion', 'tier': 9},
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_10', 'mining',
           [{'name': 'glowstone_minion', 'tier': 9},
            {'name': 'enchanted_glowstone_block', 'count': 8}],
           {'name': 'glowstone_minion', 'tier': 10},
           collection_req=('glowstone', 1)),
    Recipe('glowstone_minion_11', 'mining',
           [{'name': 'glowstone_minion', 'tier': 10},
            {'name': 'enchanted_glowstone_block', 'count': 16}],
           {'name': 'glowstone_minion', 'tier': 11},
           collection_req=('glowstone', 1)),
    RecipeGroup('glowstone_minion', 'mining',
                ['glowstone_minion_1', 'glowstone_minion_2',
                 'glowstone_minion_3', 'glowstone_minion_4',
                 'glowstone_minion_5', 'glowstone_minion_6',
                 'glowstone_minion_7', 'glowstone_minion_8',
                 'glowstone_minion_9', 'glowstone_minion_10',
                 'glowstone_minion_11'],
                collection_req=('glowstone', 1)),

    Recipe('flint_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'flint', 'count': 80}],
           {'name': 'flint_minion', 'tier': 1},
           collection_req=('flint', 1)),
    Recipe('flint_minion_2', 'mining',
           [{'name': 'flint_minion', 'tier': 1},
            {'name': 'flint', 'count': 160}],
           {'name': 'flint_minion', 'tier': 2},
           collection_req=('flint', 1)),
    Recipe('flint_minion_3', 'mining',
           [{'name': 'flint_minion', 'tier': 2},
            {'name': 'flint', 'count': 320}],
           {'name': 'flint_minion', 'tier': 3},
           collection_req=('flint', 1)),
    Recipe('flint_minion_4', 'mining',
           [{'name': 'flint_minion', 'tier': 3},
            {'name': 'flint', 'count': 512}],
           {'name': 'flint_minion', 'tier': 4},
           collection_req=('flint', 1)),
    Recipe('flint_minion_5', 'mining',
           [{'name': 'flint_minion', 'tier': 4},
            {'name': 'enchanted_flint', 'count': 8}],
           {'name': 'flint_minion', 'tier': 5},
           collection_req=('flint', 1)),
    Recipe('flint_minion_6', 'mining',
           [{'name': 'flint_minion', 'tier': 5},
            {'name': 'enchanted_flint', 'count': 16}],
           {'name': 'flint_minion', 'tier': 6},
           collection_req=('flint', 1)),
    Recipe('flint_minion_7', 'mining',
           [{'name': 'flint_minion', 'tier': 6},
            {'name': 'enchanted_flint', 'count': 32}],
           {'name': 'flint_minion', 'tier': 7},
           collection_req=('flint', 1)),
    Recipe('flint_minion_8', 'mining',
           [{'name': 'flint_minion', 'tier': 7},
            {'name': 'enchanted_flint', 'count': 64}],
           {'name': 'flint_minion', 'tier': 8},
           collection_req=('flint', 1)),
    Recipe('flint_minion_9', 'mining',
           [{'name': 'flint_minion', 'tier': 8},
            {'name': 'enchanted_flint', 'count': 128}],
           {'name': 'flint_minion', 'tier': 9},
           collection_req=('flint', 1)),
    Recipe('flint_minion_10', 'mining',
           [{'name': 'flint_minion', 'tier': 9},
            {'name': 'enchanted_flint', 'count': 256}],
           {'name': 'flint_minion', 'tier': 10},
           collection_req=('flint', 1)),
    Recipe('flint_minion_11', 'mining',
           [{'name': 'flint_minion', 'tier': 10},
            {'name': 'enchanted_flint', 'count': 512}],
           {'name': 'flint_minion', 'tier': 11},
           collection_req=('flint', 1)),
    RecipeGroup('flint_minion', 'mining',
                ['flint_minion_1', 'flint_minion_2', 'flint_minion_3',
                 'flint_minion_4', 'flint_minion_5', 'flint_minion_6',
                 'flint_minion_7', 'flint_minion_8', 'flint_minion_9',
                 'flint_minion_10', 'flint_minion_11'],
                collection_req=('flint', 1)),

    Recipe('ice_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'ice', 'count': 80}],
           {'name': 'ice_minion', 'tier': 1},
           collection_req=('ice', 1)),
    Recipe('ice_minion_2', 'mining',
           [{'name': 'ice_minion', 'tier': 1},
            {'name': 'ice', 'count': 160}],
           {'name': 'ice_minion', 'tier': 2},
           collection_req=('ice', 1)),
    Recipe('ice_minion_3', 'mining',
           [{'name': 'ice_minion', 'tier': 2},
            {'name': 'ice', 'count': 320}],
           {'name': 'ice_minion', 'tier': 3},
           collection_req=('ice', 1)),
    Recipe('ice_minion_4', 'mining',
           [{'name': 'ice_minion', 'tier': 3},
            {'name': 'ice', 'count': 512}],
           {'name': 'ice_minion', 'tier': 4},
           collection_req=('ice', 1)),
    Recipe('ice_minion_5', 'mining',
           [{'name': 'ice_minion', 'tier': 4},
            {'name': 'packed_ice', 'count': 128}],
           {'name': 'ice_minion', 'tier': 5},
           collection_req=('ice', 1)),
    Recipe('ice_minion_6', 'mining',
           [{'name': 'ice_minion', 'tier': 5},
            {'name': 'packed_ice', 'count': 256}],
           {'name': 'ice_minion', 'tier': 6},
           collection_req=('ice', 1)),
    Recipe('ice_minion_7', 'mining',
           [{'name': 'ice_minion', 'tier': 6},
            {'name': 'packed_ice', 'count': 512}],
           {'name': 'ice_minion', 'tier': 7},
           collection_req=('ice', 1)),
    Recipe('ice_minion_8', 'mining',
           [{'name': 'ice_minion', 'tier': 7},
            {'name': 'enchanted_ice', 'count': 64}],
           {'name': 'ice_minion', 'tier': 8},
           collection_req=('ice', 1)),
    Recipe('ice_minion_9', 'mining',
           [{'name': 'ice_minion', 'tier': 8},
            {'name': 'enchanted_ice', 'count': 128}],
           {'name': 'ice_minion', 'tier': 9},
           collection_req=('ice', 1)),
    Recipe('ice_minion_10', 'mining',
           [{'name': 'ice_minion', 'tier': 9},
            {'name': 'enchanted_ice', 'count': 256}],
           {'name': 'ice_minion', 'tier': 10},
           collection_req=('ice', 1)),
    Recipe('ice_minion_11', 'mining',
           [{'name': 'ice_minion', 'tier': 10},
            {'name': 'enchanted_ice', 'count': 512}],
           {'name': 'ice_minion', 'tier': 11},
           collection_req=('ice', 1)),
    RecipeGroup('ice_minion', 'mining',
                ['ice_minion_1', 'ice_minion_2', 'ice_minion_3', 'ice_minion_4',
                 'ice_minion_5', 'ice_minion_6', 'ice_minion_7', 'ice_minion_8',
                 'ice_minion_9', 'ice_minion_10', 'ice_minion_11'],
                collection_req=('ice', 1)),

    Recipe('sand_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'sand', 'count': 80}],
           {'name': 'sand_minion', 'tier': 1},
           collection_req=('sand', 1)),
    Recipe('sand_minion_2', 'mining',
           [{'name': 'sand_minion', 'tier': 1},
            {'name': 'sand', 'count': 160}],
           {'name': 'sand_minion', 'tier': 2},
           collection_req=('sand', 1)),
    Recipe('sand_minion_3', 'mining',
           [{'name': 'sand_minion', 'tier': 2},
            {'name': 'sand', 'count': 320}],
           {'name': 'sand_minion', 'tier': 3},
           collection_req=('sand', 1)),
    Recipe('sand_minion_4', 'mining',
           [{'name': 'sand_minion', 'tier': 3},
            {'name': 'sand', 'count': 512}],
           {'name': 'sand_minion', 'tier': 4},
           collection_req=('sand', 1)),
    Recipe('sand_minion_5', 'mining',
           [{'name': 'sand_minion', 'tier': 4},
            {'name': 'enchanted_sand', 'count': 8}],
           {'name': 'sand_minion', 'tier': 5},
           collection_req=('sand', 1)),
    Recipe('sand_minion_6', 'mining',
           [{'name': 'sand_minion', 'tier': 5},
            {'name': 'enchanted_sand', 'count': 16}],
           {'name': 'sand_minion', 'tier': 6},
           collection_req=('sand', 1)),
    Recipe('sand_minion_7', 'mining',
           [{'name': 'sand_minion', 'tier': 6},
            {'name': 'enchanted_sand', 'count': 32}],
           {'name': 'sand_minion', 'tier': 7},
           collection_req=('sand', 1)),
    Recipe('sand_minion_8', 'mining',
           [{'name': 'sand_minion', 'tier': 7},
            {'name': 'enchanted_sand', 'count': 64}],
           {'name': 'sand_minion', 'tier': 8},
           collection_req=('sand', 1)),
    Recipe('sand_minion_9', 'mining',
           [{'name': 'sand_minion', 'tier': 8},
            {'name': 'enchanted_sand', 'count': 128}],
           {'name': 'sand_minion', 'tier': 9},
           collection_req=('sand', 1)),
    Recipe('sand_minion_10', 'mining',
           [{'name': 'sand_minion', 'tier': 9},
            {'name': 'enchanted_sand', 'count': 256}],
           {'name': 'sand_minion', 'tier': 10},
           collection_req=('sand', 1)),
    Recipe('sand_minion_11', 'mining',
           [{'name': 'sand_minion', 'tier': 10},
            {'name': 'enchanted_sand', 'count': 512}],
           {'name': 'sand_minion', 'tier': 11},
           collection_req=('sand', 1)),
    RecipeGroup('sand_minion', 'mining',
                ['sand_minion_1', 'sand_minion_2', 'sand_minion_3',
                 'sand_minion_4', 'sand_minion_5', 'sand_minion_6',
                 'sand_minion_7', 'sand_minion_8', 'sand_minion_9',
                 'sand_minion_10', 'sand_minion_11'],
                collection_req=('sand', 1)),

    Recipe('end_stone_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'end_stone', 'count': 80}],
           {'name': 'end_stone_minion', 'tier': 1},
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_2', 'mining',
           [{'name': 'end_stone_minion', 'tier': 1},
            {'name': 'end_stone', 'count': 160}],
           {'name': 'end_stone_minion', 'tier': 2},
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_3', 'mining',
           [{'name': 'end_stone_minion', 'tier': 2},
            {'name': 'end_stone', 'count': 320}],
           {'name': 'end_stone_minion', 'tier': 3},
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_4', 'mining',
           [{'name': 'end_stone_minion', 'tier': 3},
            {'name': 'end_stone', 'count': 512}],
           {'name': 'end_stone_minion', 'tier': 4},
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_5', 'mining',
           [{'name': 'end_stone_minion', 'tier': 4},
            {'name': 'enchanted_end_stone', 'count': 8}],
           {'name': 'end_stone_minion', 'tier': 5},
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_6', 'mining',
           [{'name': 'end_stone_minion', 'tier': 5},
            {'name': 'enchanted_end_stone', 'count': 16}],
           {'name': 'end_stone_minion', 'tier': 6},
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_7', 'mining',
           [{'name': 'end_stone_minion', 'tier': 6},
            {'name': 'enchanted_end_stone', 'count': 32}],
           {'name': 'end_stone_minion', 'tier': 7},
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_8', 'mining',
           [{'name': 'end_stone_minion', 'tier': 7},
            {'name': 'enchanted_end_stone', 'count': 64}],
           {'name': 'end_stone_minion', 'tier': 8},
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_9', 'mining',
           [{'name': 'end_stone_minion', 'tier': 8},
            {'name': 'enchanted_end_stone', 'count': 128}],
           {'name': 'end_stone_minion', 'tier': 9},
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_10', 'mining',
           [{'name': 'end_stone_minion', 'tier': 9},
            {'name': 'enchanted_end_stone', 'count': 256}],
           {'name': 'end_stone_minion', 'tier': 10},
           collection_req=('end_stone', 1)),
    Recipe('end_stone_minion_11', 'mining',
           [{'name': 'end_stone_minion', 'tier': 10},
            {'name': 'enchanted_end_stone', 'count': 512}],
           {'name': 'end_stone_minion', 'tier': 11},
           collection_req=('end_stone', 1)),
    RecipeGroup('end_stone_minion', 'mining',
                ['end_stone_minion_1', 'end_stone_minion_2',
                 'end_stone_minion_3', 'end_stone_minion_4',
                 'end_stone_minion_5', 'end_stone_minion_6',
                 'end_stone_minion_7', 'end_stone_minion_8',
                 'end_stone_minion_9', 'end_stone_minion_10',
                 'end_stone_minion_11'],
                collection_req=('end_stone', 1)),

    Recipe('mithril_minion_1', 'mining',
           [{'name': 'wooden_pickaxe'},
            {'name': 'mithril', 'count': 80}],
           {'name': 'mithril_minion', 'tier': 1},
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_2', 'mining',
           [{'name': 'mithril_minion', 'tier': 1},
            {'name': 'mithril', 'count': 160}],
           {'name': 'mithril_minion', 'tier': 2},
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_3', 'mining',
           [{'name': 'mithril_minion', 'tier': 2},
            {'name': 'mithril', 'count': 320}],
           {'name': 'mithril_minion', 'tier': 3},
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_4', 'mining',
           [{'name': 'mithril_minion', 'tier': 3},
            {'name': 'mithril', 'count': 512}],
           {'name': 'mithril_minion', 'tier': 4},
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_5', 'mining',
           [{'name': 'mithril_minion', 'tier': 4},
            {'name': 'enchanted_mithril', 'count': 8}],
           {'name': 'mithril_minion', 'tier': 5},
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_6', 'mining',
           [{'name': 'mithril_minion', 'tier': 5},
            {'name': 'enchanted_mithril', 'count': 24}],
           {'name': 'mithril_minion', 'tier': 6},
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_7', 'mining',
           [{'name': 'mithril_minion', 'tier': 6},
            {'name': 'enchanted_mithril', 'count': 64}],
           {'name': 'mithril_minion', 'tier': 7},
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_8', 'mining',
           [{'name': 'mithril_minion', 'tier': 7},
            {'name': 'enchanted_mithril', 'count': 128}],
           {'name': 'mithril_minion', 'tier': 8},
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_9', 'mining',
           [{'name': 'mithril_minion', 'tier': 8},
            {'name': 'enchanted_mithril', 'count': 256}],
           {'name': 'mithril_minion', 'tier': 9},
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_10', 'mining',
           [{'name': 'mithril_minion', 'tier': 9},
            {'name': 'enchanted_mithril', 'count': 512}],
           {'name': 'mithril_minion', 'tier': 10},
           collection_req=('mithril', 1)),
    Recipe('mithril_minion_11', 'mining',
           [{'name': 'mithril_minion', 'tier': 10},
            {'name': 'refined_mithril', 'count': 8}],
           {'name': 'mithril_minion', 'tier': 11},
           collection_req=('mithril', 1)),
    RecipeGroup('mithril_minion', 'mining',
                ['mithril_minion_1', 'mithril_minion_2', 'mithril_minion_3',
                 'mithril_minion_4', 'mithril_minion_5', 'mithril_minion_6',
                 'mithril_minion_7', 'mithril_minion_8', 'mithril_minion_9',
                 'mithril_minion_10', 'mithril_minion_11'],
                collection_req=('mithril', 1)),
]
