from ..object import *


MISC_RECIPES = [
    Recipe('diamond_to_refined', 'forging',
           [{'name': 'enchanted_diamond_block', 'count': 2}],
           {'name': 'refined_diamond'}),
    Recipe('mithril_to_refined', 'forging',
           [{'name': 'enchanted_mithril', 'count': 160}],
           {'name': 'refined_mithril'}),
    Recipe('titanium_to_refined', 'forging',
           [{'name': 'enchanted_titanium', 'count': 16}],
           {'name': 'refined_titanium'}),
    Recipe('fuel_tank', 'forging',
           [{'name': 'enchanted_coal_block', 'count': 2}],
           {'name': 'fuel_tank'}),
    Recipe('mithril_plate', 'forging',
           [{'name': 'refined_mithril', 'count': 5},
            {'name': 'golden_plate'},
            {'name': 'enchanted_iron_block'},
            {'name': 'refined_titanium'}],
           {'name': 'mithril_plate'}),
    Recipe('bejeweled_handle', 'forging',
           [{'name': 'glacite_jewel', 'count': 3}],
           {'name': 'bejeweled_handle'}),
    Recipe('golden_plate', 'forging',
           [{'name': 'enchanted_gold_block', 'count': 2},
            {'name': 'glacite_jewel', 'count': 5},
            {'name': 'refined_diamond'}],
           {'name': 'golden_plate'}),
    Recipe('drill_engine', 'forging',
           [{'name': 'enchanted_iron_block'},
            {'name': 'enchanted_redstone_block', 'count': 3},
            {'name': 'golden_plate'},
            {'name': 'treasurite', 'count': 10},
            {'name': 'refined_diamond'}],
           {'name': 'drill_engine'}),

    Recipe('mithril_pickaxe', 'forging',
           [{'name': 'enchanted_mithril', 'count': 30},
            {'name': 'bejeweled_handle'},
            {'name': 'enchanted_gold', 'count': 10}],
           {'name': 'mithril_pickaxe'}),
    Recipe('refined_mithril_pickaxe', 'forging',
           [{'name': 'refined_mithril', 'count': 3},
            {'name': 'bejeweled_handle', 'count': 2},
            {'name': 'refined_diamond'},
            {'name': 'enchanted_gold', 'count': 30}],
           {'name': 'refined_mithril_pickaxe'}),
    Recipe('mithril_drill_226', 'forging',
           [{'name': 'drill_engine'},
            {'name': 'refined_mithril', 'count': 3},
            {'name': 'fuel_tank'}],
           {'name': 'mithril_drill_226'}),
    Recipe('mithril_drill_326', 'forging',
           [{'name': 'mithril_drill_226'},
            {'name': 'golden_plate', 'count': 10},
            {'name': 'mithril_plate', 'count': 2}],
           {'name': 'mithril_drill_326'}),
    Recipe('titanium_drill_355', 'forging',
           [{'name': 'drill_engine'},
            {'name': 'fuel_tank'},
            {'name': 'golden_plate', 'count': 6},
            {'name': 'refined_titanium', 'count': 10},
            {'name': 'refined_mithril', 'count': 10}],
           {'name': 'titanium_drill_355'}),
    Recipe('titanium_drill_455', 'forging',
           [{'name': 'titanium_drill_355'},
            {'name': 'refined_diamond', 'count': 10},
            {'name': 'refined_titanium', 'count': 16},
            {'name': 'mithril_plate', 'count': 6}],
           {'name': 'titanium_drill_455'}),
    Recipe('titanium_drill_555', 'forging',
           [{'name': 'titanium_drill_455'},
            {'name': 'refined_diamond', 'count': 20},
            {'name': 'refined_titanium', 'count': 32},
            {'name': 'enchanted_iron_block', 'count': 2},
            {'name': 'mithril_plate', 'count': 15},
            {'name': 'plasma', 'count': 20}],
           {'name': 'titanium_drill_555'}),

    Recipe('titanium_talisman', 'forging',
           [{'name': 'refined_titanium', 'count': 2}],
           {'name': 'titanium_talisman'}),
    Recipe('titanium_ring', 'forging',
           [{'name': 'titanium_talisman'},
            {'name': 'refined_titanium', 'count': 6}],
           {'name': 'titanium_ring'}),
    Recipe('titanium_artifact', 'forging',
           [{'name': 'titanium_ring'},
            {'name': 'refined_titanium', 'count': 12}],
           {'name': 'titanium_artifact'}),
    Recipe('titanium_relic', 'forging',
           [{'name': 'titanium_artifact'},
            {'name': 'refined_titanium', 'count': 20}],
           {'name': 'titanium_relic'}),

    Recipe('glass', 'smelting',
           [{'name': 'sand'}],
           {'name': 'glass'}),
    Recipe('bottle', 'smelting',
           [{'name': 'glass', 'count': 3}],
           {'name': 'bottle', 'count': 3}),
]
