from typing import Any

from ..function.io import red
from ..function.util import includes, get

from .item import get_item
from .object import Item, Recipe


__all__ = ['RECIPES', 'get_recipe']


RECIPES = [
    Recipe('wooden_hoe', 'farming',
           [(Item('planks'), 2),
            (Item('stick'), 2)],
           (get_item('wooden_hoe'), 1)),
    Recipe('gold_hoe', 'farming',
           [(Item('gold'), 2),
            (Item('stick'), 2)],
           (get_item('golden_hoe'), 1)),
    Recipe('stone_hoe', 'farming',
           [(Item('cobblestone'), 2),
            (Item('stick'), 2)],
           (get_item('stone_hoe'), 1)),
    Recipe('iron_hoe', 'farming',
           [(Item('iron'), 2),
            (Item('stick'), 2)],
           (get_item('iron_hoe'), 1)),
    Recipe('diamond_hoe', 'farming',
           [(Item('diamond'), 2),
            (Item('stick'), 2)],
           (get_item('diamond_hoe'), 1)),

    Recipe('wheat_to_bread', 'farming',
           [(Item('wheat'), 3)],
           (Item('bread'), 1)),

    Recipe('wooden_pickaxe', 'mining',
           [(Item('planks'), 3),
            (Item('stick'), 2)],
           (get_item('wooden_pickaxe'), 1)),
    Recipe('gold_pickaxe', 'mining',
           [(Item('gold'), 3),
            (Item('stick'), 2)],
           (get_item('golden_pickaxe'), 1)),
    Recipe('stone_pickaxe', 'mining',
           [(Item('cobblestone'), 3),
            (Item('stick'), 2)],
           (get_item('stone_pickaxe'), 1)),
    Recipe('iron_pickaxe', 'mining',
           [(Item('iron'), 3),
            (Item('stick'), 2)],
           (get_item('iron_pickaxe'), 1)),
    Recipe('diamond_pickaxe', 'mining',
           [(Item('diamond'), 3),
            (Item('stick'), 2)],
           (get_item('diamond_pickaxe'), 1)),

    Recipe('coal_to_block', 'mining',
           [(Item('coal'), 9)],
           (Item('coal_block'), 1)),
    Recipe('block_to_coal', 'mining',
           [(Item('coal_block'), 1)],
           (Item('coal'), 9)),

    Recipe('iron_to_block', 'mining',
           [(Item('iron'), 9)],
           (Item('iron_block'), 1)),
    Recipe('block_to_iron', 'mining',
           [(Item('iron_block'), 1)],
           (Item('iron'), 9)),
    Recipe('nugget_to_iron', 'mining',
           [(Item('iron_nugget'), 9)],
           (Item('iron'), 1)),
    Recipe('iron_to_nugget', 'mining',
           [(Item('iron'), 1)],
           (Item('iron_nugget'), 9)),

    Recipe('gold_to_block', 'mining',
           [(Item('gold'), 9)],
           (Item('gold_block'), 1)),
    Recipe('block_to_gold', 'mining',
           [(Item('gold_block'), 1)],
           (Item('gold'), 9)),
    Recipe('nugget_to_gold', 'mining',
           [(Item('gold_nugget'), 9)],
           (Item('gold'), 1)),
    Recipe('gold_to_nugget', 'mining',
           [(Item('gold'), 1)],
           (Item('gold_nugget'), 9)),

    Recipe('diamond_to_block', 'mining',
           [(Item('diamond'), 9)],
           (Item('diamond_block'), 1)),
    Recipe('block_to_diamond', 'mining',
           [(Item('diamond_block'), 1)],
           (Item('diamond'), 9)),

    Recipe('lapis_to_block', 'mining',
           [(Item('lapis'), 9)],
           (Item('lapis_block'), 1)),
    Recipe('block_to_lapis', 'mining',
           [(Item('lapis_block'), 1)],
           (Item('lapis'), 9)),

    Recipe('emerald_to_block', 'mining',
           [(Item('emerald'), 9)],
           (Item('emerald_block'), 1)),
    Recipe('block_to_emerald', 'mining',
           [(Item('emerald_block'), 1)],
           (Item('emerald'), 9)),

    Recipe('redstone_to_block', 'mining',
           [(Item('redstone'), 9)],
           (Item('redstone_block'), 1)),
    Recipe('block_to_redstone', 'mining',
           [(Item('redstone_block'), 1)],
           (Item('redstone'), 9)),

    Recipe('ice_to_packed', 'mining',
           [(Item('ice'), 9)],
           (Item('packed_ice'), 1)),

    Recipe('leather_helmet', 'combat',
           [(Item('leather'), 5)],
           (get_item('leather_helmet'), 1)),
    Recipe('leather_chestplate', 'combat',
           [(Item('leather'), 8)],
           (get_item('leather_chestplate'), 1)),
    Recipe('leather_leggings', 'combat',
           [(Item('leather'), 7)],
           (get_item('leather_leggings'), 1)),
    Recipe('leather_boots', 'combat',
           [(Item('leather'), 4)],
           (get_item('leather_boots'), 1)),

    Recipe('golden_helmet', 'combat',
           [(Item('gold'), 5)],
           (get_item('golden_helmet'), 1)),
    Recipe('golden_chestplate', 'combat',
           [(Item('gold'), 8)],
           (get_item('golden_chestplate'), 1)),
    Recipe('golden_leggings', 'combat',
           [(Item('gold'), 7)],
           (get_item('golden_leggings'), 1)),
    Recipe('golden_boots', 'combat',
           [(Item('gold'), 4)],
           (get_item('golden_boots'), 1)),

    Recipe('iron_helmet', 'combat',
           [(Item('iron'), 5)],
           (get_item('iron_helmet'), 1)),
    Recipe('iron_chestplate', 'combat',
           [(Item('iron'), 8)],
           (get_item('iron_chestplate'), 1)),
    Recipe('iron_leggings', 'combat',
           [(Item('iron'), 7)],
           (get_item('iron_leggings'), 1)),
    Recipe('iron_boots', 'combat',
           [(Item('iron'), 4)],
           (get_item('iron_boots'), 1)),

    Recipe('diamond_helmet', 'combat',
           [(Item('diamond'), 5)],
           (get_item('diamond_helmet'), 1)),
    Recipe('diamond_chestplate', 'combat',
           [(Item('diamond'), 8)],
           (get_item('diamond_chestplate'), 1)),
    Recipe('diamond_leggings', 'combat',
           [(Item('diamond'), 7)],
           (get_item('diamond_leggings'), 1)),
    Recipe('diamond_boots', 'combat',
           [(Item('diamond'), 4)],
           (get_item('diamond_boots'), 1)),

    Recipe('arrow', 'combat',
           [(Item('flint'), 1),
            (Item('stick'), 1),
            (Item('feather'), 1)],
           (get_item('arrow'), 4)),

    Recipe('wooden_sword', 'combat',
           [(Item('planks'), 2),
            (Item('stick'), 1)],
           (get_item('wooden_sword'), 1)),
    Recipe('gold_sword', 'combat',
           [(Item('gold'), 2),
            (Item('stick'), 1)],
           (get_item('golden_sword'), 1)),
    Recipe('stone_sword', 'combat',
           [(Item('cobblestone'), 2),
            (Item('stick'), 1)],
           (get_item('stone_sword'), 1)),
    Recipe('iron_sword', 'combat',
           [(Item('iron'), 2),
            (Item('stick'), 1)],
           (get_item('iron_sword'), 1)),
    Recipe('diamond_sword', 'combat',
           [(Item('diamond'), 2),
            (Item('stick'), 1)],
           (get_item('diamond_sword'), 1)),
    Recipe('bow', 'combat',
           [(Item('stick'), 3),
            (Item('string'), 3)],
           (get_item('bow'), 1)),

    Recipe('blaze_rod_to_powder', 'combat',
           [(Item('blaze_rod'), 1)],
           (Item('blaze_powder'), 2)),

    Recipe('wooden_axe', 'foraging',
           [(Item('planks'), 3),
            (Item('stick'), 2)],
           (get_item('wooden_axe'), 1)),
    Recipe('gold_axe', 'foraging',
           [(Item('gold'), 3),
            (Item('stick'), 2)],
           (get_item('golden_axe'), 1)),
    Recipe('stone_axe', 'foraging',
           [(Item('cobblestone'), 3),
            (Item('stick'), 2)],
           (get_item('stone_axe'), 1)),
    Recipe('iron_axe', 'foraging',
           [(Item('iron'), 3),
            (Item('stick'), 2)],
           (get_item('iron_axe'), 1)),
    Recipe('diamond_axe', 'foraging',
           [(Item('diamond'), 3),
            (Item('stick'), 2)],
           (get_item('diamond_axe'), 1)),

    Recipe('oak_to_planks', 'foraging',
           [(Item('oak'), 1)],
           (Item('planks'), 4)),
    Recipe('birch_to_planks', 'foraging',
           [(Item('birch'), 1)],
           (Item('planks'), 4)),
    Recipe('spruce_to_planks', 'foraging',
           [(Item('spruce'), 1)],
           (Item('planks'), 4)),
    Recipe('dark_to_planks', 'foraging',
           [(Item('dark'), 1)],
           (Item('planks'), 4)),
    Recipe('acacia_to_planks', 'foraging',
           [(Item('acacia'), 1)],
           (Item('planks'), 4)),
    Recipe('jungle_to_planks', 'foraging',
           [(Item('jungle'), 1)],
           (Item('planks'), 4)),
    Recipe('planks_to_stick', 'foraging',
           [(Item('planks'), 2)],
           (Item('stick'), 4)),
]


def get_recipe(name: str, **kwargs) -> Recipe:
    if not includes(RECIPES, name):
        red(f'Invalid item: {name!r}')
        exit()
    return get(RECIPES, name, **kwargs)
