from ...object import *


__all__ = ['COMBAT_PETS']

COMBAT_PETS = [
    Pet('black_cat_pet', rarity='legendary', category='combat',
        speed=25, intelligence=100),

    Pet('blaze_pet', rarity='epic', category='combat',
        defense=30, intelligence=100),
    Pet('blaze_pet', rarity='legendary', category='combat',
        defense=30, intelligence=100),

    Pet('ender_dragon_pet', rarity='epic', category='combat',
        strength=50, crit_chance=10, crit_damage=50),
    Pet('ender_dragon_pet', rarity='legendary', category='combat',
        strength=50, crit_chance=10, crit_damage=50),

    Pet('enderman_pet', rarity='common', category='combat',
        crit_damage=75),
    Pet('enderman_pet', rarity='uncommon', category='combat',
        crit_damage=75),
    Pet('enderman_pet', rarity='rare', category='combat',
        crit_damage=75),
    Pet('enderman_pet', rarity='epic', category='combat',
        crit_damage=75),
    Pet('enderman_pet', rarity='legendary', category='combat',
        crit_damage=75),
    Pet('enderman_pet', rarity='mythic', category='combat',
        crit_damage=75),

    Pet('ghoul_pet', rarity='epic', category='combat',
        health=100, intelligence=70, ferocity=5),
    Pet('ghoul_pet', rarity='legendary', category='combat',
        health=100, intelligence=70, ferocity=5),

    Pet('golem_pet', rarity='epic', category='combat',
        health=150, strength=50),
    Pet('golem_pet', rarity='legendary', category='combat',
        health=150, strength=50),

    Pet('griffin_pet', rarity='common', category='combat',
        intelligence=10, strength=25,
        crit_chance=10, crit_damage=50, magic_find=10),
    Pet('griffin_pet', rarity='uncommon', category='combat',
        intelligence=10, strength=25,
        crit_chance=10, crit_damage=50, magic_find=10),
    Pet('griffin_pet', rarity='rare', category='combat',
        intelligence=10, strength=25,
        crit_chance=10, crit_damage=50, magic_find=10),
    Pet('griffin_pet', rarity='epic', category='combat',
        intelligence=10, strength=25,
        crit_chance=10, crit_damage=50, magic_find=10),
    Pet('griffin_pet', rarity='legendary', category='combat',
        intelligence=10, strength=25,
        crit_chance=10, crit_damage=50, magic_find=10),

    Pet('horse_pet', rarity='common', category='combat',
        speed=25, intelligence=50),
    Pet('horse_pet', rarity='uncommon', category='combat',
        speed=25, intelligence=50),
    Pet('horse_pet', rarity='rare', category='combat',
        speed=25, intelligence=50),
    Pet('horse_pet', rarity='epic', category='combat',
        speed=25, intelligence=50),
    Pet('horse_pet', rarity='legendary', category='combat',
        speed=25, intelligence=50),

    Pet('hound_pet', rarity='epic', category='combat',
        strength=40, attack_speed=15, ferocity=5),
    Pet('hound_pet', rarity='legendary', category='combat',
        strength=40, attack_speed=15, ferocity=5),

    Pet('jerry_pet', rarity='common', category='combat',
        intelligence=-100),
    Pet('jerry_pet', rarity='uncommon', category='combat',
        intelligence=-100),
    Pet('jerry_pet', rarity='rare', category='combat',
        intelligence=-100),
    Pet('jerry_pet', rarity='epic', category='combat',
        intelligence=-100),
    Pet('jerry_pet', rarity='legendary', category='combat',
        intelligence=-100),
    Pet('jerry_pet', rarity='mythic', category='combat',
        intelligence=-100),

    Pet('magma_cube_pet', rarity='common', category='combat',
        health=50, defense=100 / 3, strength=20),
    Pet('magma_cube_pet', rarity='uncommon', category='combat',
        health=50, defense=100 / 3, strength=20),
    Pet('magma_cube_pet', rarity='rare', category='combat',
        health=50, defense=100 / 3, strength=20),

    Pet('phoenix_pet', rarity='epic', category='combat',
        intelligence=50, strength=10),
    Pet('phoenix_pet', rarity='legendary', category='combat',
        intelligence=50, strength=10,
        abilities=['eternal_coins']),

    Pet('pigman_pet', rarity='epic', category='combat',
        defense=50, strength=50, ferocity=5),
    Pet('pigman_pet', rarity='legendary', category='combat',
        defense=50, strength=50, ferocity=5),

    Pet('skeleton_horse_pet', rarity='legendary', category='combat',
        speed=50, intelligence=100),

    Pet('skeleton_pet', rarity='common', category='combat',
        crit_chance=15, crit_damage=30),
    Pet('skeleton_pet', rarity='uncommon', category='combat',
        crit_chance=15, crit_damage=30),
    Pet('skeleton_pet', rarity='rare', category='combat',
        crit_chance=15, crit_damage=30),
    Pet('skeleton_pet', rarity='epic', category='combat',
        crit_chance=15, crit_damage=30),
    Pet('skeleton_pet', rarity='legendary', category='combat',
        crit_chance=15, crit_damage=30),

    Pet('snowman_pet', rarity='legendary', category='combat',
        strength=15, crit_damage=15, damage=25),

    Pet('spider_pet', rarity='common', category='combat',
        strength=10, crit_chance=10),
    Pet('spider_pet', rarity='uncommon', category='combat',
        strength=10, crit_chance=10),
    Pet('spider_pet', rarity='rare', category='combat',
        strength=10, crit_chance=10),
    Pet('spider_pet', rarity='epic', category='combat',
        strength=10, crit_chance=10),
    Pet('spider_pet', rarity='legendary', category='combat',
        strength=10, crit_chance=10),

    Pet('tarantula_pet', rarity='epic', category='combat',
        strength=10, crit_chance=10, crit_damage=30),
    Pet('tarantula_pet', rarity='legendary', category='combat',
        strength=10, crit_chance=10, crit_damage=30),

    Pet('tiger_pet', rarity='common', category='combat',
        strength=15, crit_chance=5, crit_damage=50, ferocity=25),
    Pet('tiger_pet', rarity='uncommon', category='combat',
        strength=15, crit_chance=5, crit_damage=50, ferocity=25),
    Pet('tiger_pet', rarity='rare', category='combat',
        strength=15, crit_chance=5, crit_damage=50, ferocity=25),
    Pet('tiger_pet', rarity='epic', category='combat',
        strength=15, crit_chance=5, crit_damage=50, ferocity=25),
    Pet('tiger_pet', rarity='legendary', category='combat',
        strength=15, crit_chance=5, crit_damage=50, ferocity=25),

    Pet('turtle_pet', rarity='epic', category='combat',
        health=50, defense=100),
    Pet('turtle_pet', rarity='legendary', category='combat',
        health=50, defense=100),

    Pet('wolf_pet', rarity='common', category='combat',
        health=50, speed=20, true_defense=10, crit_damage=10),
    Pet('wolf_pet', rarity='uncommon', category='combat',
        health=50, speed=20, true_defense=10, crit_damage=10),
    Pet('wolf_pet', rarity='rare', category='combat',
        health=50, speed=20, true_defense=10, crit_damage=10),
    Pet('wolf_pet', rarity='epic', category='combat',
        health=50, speed=20, true_defense=10, crit_damage=10),
    Pet('wolf_pet', rarity='legendary', category='combat',
        health=50, speed=20, true_defense=10, crit_damage=10),

    Pet('zombie_pet', rarity='common', category='combat',
        health=100, crit_damage=30),
    Pet('zombie_pet', rarity='uncommon', category='combat',
        health=100, crit_damage=30),
    Pet('zombie_pet', rarity='rare', category='combat',
        health=100, crit_damage=30),
    Pet('zombie_pet', rarity='epic', category='combat',
        health=100, crit_damage=30),
    Pet('zombie_pet', rarity='legendary', category='combat',
        health=100, crit_damage=30),
]
