from ...object import *


__all__ = ['FARMING_PETS']

FARMING_PETS = [
    Pet('bee_pet', rarity='common', category='farming',
        speed=10, intelligence=50, strength=30),
    Pet('bee_pet', rarity='uncommon', category='farming',
        speed=10, intelligence=50, strength=30),
    Pet('bee_pet', rarity='rare', category='farming',
        speed=10, intelligence=50, strength=30),
    Pet('bee_pet', rarity='epic', category='farming',
        speed=10, intelligence=50, strength=30),
    Pet('bee_pet', rarity='legendary', category='farming',
        speed=10, intelligence=50, strength=30),

    Pet('chicken_pet', rarity='common', category='farming',
        health=200),
    Pet('chicken_pet', rarity='uncommon', category='farming',
        health=200),
    Pet('chicken_pet', rarity='rare', category='farming',
        health=200),
    Pet('chicken_pet', rarity='epic', category='farming',
        health=200),
    Pet('chicken_pet', rarity='legendary', category='farming',
        health=200),

    Pet('elephant_pet', rarity='common', category='farming',
        health=100, intelligence=75),
    Pet('elephant_pet', rarity='uncommon', category='farming',
        health=100, intelligence=75),
    Pet('elephant_pet', rarity='rare', category='farming',
        health=100, intelligence=75),
    Pet('elephant_pet', rarity='epic', category='farming',
        health=100, intelligence=75),
    Pet('elephant_pet', rarity='legendary', category='farming',
        health=100, intelligence=75),

    Pet('rabbit_pet', rarity='common', category='farming',
        health=100, speed=20),
    Pet('rabbit_pet', rarity='uncommon', category='farming',
        health=100, speed=20),
    Pet('rabbit_pet', rarity='rare', category='farming',
        health=100, speed=20),
    Pet('rabbit_pet', rarity='epic', category='farming',
        health=100, speed=20),
    Pet('rabbit_pet', rarity='legendary', category='farming',
        health=100, speed=20),

    Pet('pig_pet', rarity='common', category='farming',
        speed=25),
    Pet('pig_pet', rarity='uncommon', category='farming',
        speed=25),
    Pet('pig_pet', rarity='rare', category='farming',
        speed=25),
    Pet('pig_pet', rarity='epic', category='farming',
        speed=25),
    Pet('pig_pet', rarity='legendary', category='farming',
        speed=25),
]
