from ...object import *


__all__ = ['FORAGING_PETS']

FORAGING_PETS = [
    Pet('giraffe_pet', rarity='common', category='foraging',
        health=100, crit_chance=5),
    Pet('giraffe_pet', rarity='uncommon', category='foraging',
        health=100, crit_chance=5),
    Pet('giraffe_pet', rarity='rare', category='foraging',
        health=100, crit_chance=5),
    Pet('giraffe_pet', rarity='epic', category='foraging',
        health=100, crit_chance=5),
    Pet('giraffe_pet', rarity='legendary', category='foraging',
        health=100, crit_chance=5),

    Pet('lion_pet', rarity='common', category='foraging',
        speed=25, strength=50, ferocity=5,
        abilities=['common_primal_force']),
    Pet('lion_pet', rarity='uncommon', category='foraging',
        speed=25, strength=50, ferocity=5,
        abilities=['uncommon_primal_force']),
    Pet('lion_pet', rarity='rare', category='foraging',
        speed=25, strength=50, ferocity=5,
        abilities=['rare_primal_force']),
    Pet('lion_pet', rarity='epic', category='foraging',
        speed=25, strength=50, ferocity=5,
        abilities=['epic_primal_force']),
    Pet('lion_pet', rarity='legendary', category='foraging',
        speed=25, strength=50, ferocity=5,
        abilities=['legendary_primal_force']),

    Pet('monkey_pet', rarity='common', category='foraging',
        speed=20, intelligence=50),
    Pet('monkey_pet', rarity='uncommon', category='foraging',
        speed=20, intelligence=50),
    Pet('monkey_pet', rarity='rare', category='foraging',
        speed=20, intelligence=50,
        abilities=['rare_vine_swing']),
    Pet('monkey_pet', rarity='epic', category='foraging',
        speed=20, intelligence=50,
        abilities=['epic_vine_swing']),
    Pet('monkey_pet', rarity='legendary', category='foraging',
        speed=20, intelligence=50,
        abilities=['epic_vine_swing', 'evolves_axes']),

    Pet('ocelot_pet', rarity='common', category='foraging',
        speed=50, ferocity=10),
    Pet('ocelot_pet', rarity='uncommon', category='foraging',
        speed=50, ferocity=10),
    Pet('ocelot_pet', rarity='rare', category='foraging',
        speed=50, ferocity=10),
    Pet('ocelot_pet', rarity='epic', category='foraging',
        speed=50, ferocity=10),
    Pet('ocelot_pet', rarity='legendary', category='foraging',
        speed=50, ferocity=10),
]
