from ...object import *


__all__ = ['MINING_PETS']

MINING_PETS = [
    Pet('bat_pet', rarity='common', category='mining',
        speed=5, intelligence=100),
    Pet('bat_pet', rarity='uncommon', category='mining',
        speed=5, intelligence=100),
    Pet('bat_pet', rarity='rare', category='mining',
        speed=5, intelligence=100),
    Pet('bat_pet', rarity='epic', category='mining',
        speed=5, intelligence=100),
    Pet('bat_pet', rarity='legendary', category='mining',
        speed=5, intelligence=100),

    Pet('endermite_pet', rarity='common', category='mining',
        intelligence=100),
    Pet('endermite_pet', rarity='uncommon', category='mining',
        intelligence=100),
    Pet('endermite_pet', rarity='rare', category='mining',
        intelligence=100),
    Pet('endermite_pet', rarity='epic', category='mining',
        intelligence=100),
    Pet('endermite_pet', rarity='legendary', category='mining',
        intelligence=100),

    Pet('rock_pet', rarity='common', category='mining',
        defense=200, true_defense=10),
    Pet('rock_pet', rarity='uncommon', category='mining',
        defense=200, true_defense=10),
    Pet('rock_pet', rarity='rare', category='mining',
        defense=200, true_defense=10),
    Pet('rock_pet', rarity='epic', category='mining',
        defense=200, true_defense=10),
    Pet('rock_pet', rarity='legendary', category='mining',
        defense=200, true_defense=10),

    Pet('silverfish_pet', rarity='common', category='mining',
        health=20, defense=100),
    Pet('silverfish_pet', rarity='uncommon', category='mining',
        health=20, defense=100),
    Pet('silverfish_pet', rarity='rare', category='mining',
        health=20, defense=100),
    Pet('silverfish_pet', rarity='epic', category='mining',
        health=20, defense=100),
    Pet('silverfish_pet', rarity='legendary', category='mining',
        health=20, defense=100),

    Pet('wither_skeleton_pet', rarity='epic', category='mining',
        defense=25, intelligence=25,
        strength=25, crit_chance=5, crit_damage=25),
    Pet('wither_skeleton_pet', rarity='legendary', category='mining',
        defense=25, intelligence=25,
        strength=25, crit_chance=5, crit_damage=25),

    Pet('mithril_golem_pet', rarity='common', category='mining',
        true_defense=50),
    Pet('mithril_golem_pet', rarity='uncommon', category='mining',
        true_defense=50),
    Pet('mithril_golem_pet', rarity='rare', category='mining',
        true_defense=50),
    Pet('mithril_golem_pet', rarity='epic', category='mining',
        true_defense=50),
    Pet('mithril_golem_pet', rarity='legendary', category='mining',
        true_defense=50),
]
