from ..object import *


COMBAT_COLLECTIONS = [
    Collection(
        'rotten_flesh', 'combat',
        [
            (50, 'zombie_minion'),
            (100, 'zombie_pickaxe'),
            (250, 'smite_book'),
            (1_000, 'rotten_flesh_to_enchanted'),
            (2_500, 'zombie_hat'),
            (5_000, 'zombies_heart'),
            (10_000, 'zombie_sword'),
            (25_000, 'zombie_armor'),
            (50_000, 'zombie_pet'),
        ],
    ),
    Collection(
        'bone', 'combat',
        [
            (50, 'skeleton_minion'),
            (100, 10),
            (250, 'power_book'),
            (1_000, 'skeleton_hat'),
            (2_500, 'bone_to_enchanted'),
            (5_000, 'skeleton_pet'),
            (10_000, 'hurricane_bow'),
            (25_000, 'skeletons_helmet'),
            (50_000, 'runaans_bow'),
            (150_000, 'bone_to_enchanted_block'),
        ],
    ),
    Collection(
        'string', 'combat',
        [
            (60, 'spider_minion'),
            (100, 10),
            (250, 25),
            (1_000, 'string_to_enchanted'),
            (2_500, 250),
            (5_000, 'infinite_quiver_book'),
            (10_000, 1_000),
            (25_000, 'spiders_boots'),
            (50_000, 'spider_pet'),
        ],
    ),
    Collection(
        'spider_eye', 'combat',
        [
            (50, 'cave_spider_minion'),
            (100, 'spider_sword'),
            (250, 'spider_hat'),
            (1_000, 'spider_eye_to_enchanted'),
            (2_500, 'bane_of_arthropods_book'),
            (5_000, 500),
            (10_000, 'spider_eye_to_enchanted_fermented'),
            (25_000, 2_500),
            (50_000, 'leaping_sword'),
        ],
    ),
    Collection(
        'gunpowder', 'combat',
        [
            (50, 'creeper_minion'),
            (100, 'creeper_hat'),
            (250, 'blast_protection_book'),
            (1_000, 'gunpowder_to_enchanted'),
            (2_500, 'thunderlord_book'),
            (5_000, 'gunpowder_to_enchanted_firework'),
            (10_000, 1_000),
            (25_000, 'creeper_pants'),
            (50_000, 'explosive_bow'),
        ],
    ),
    Collection(
        'ender_pearl', 'combat',
        [
            (50, 'enderman_minion'),
            (250, 'ender_pearl_to_enchanted'),
            (1_000, 'ender_slayer_book'),
            (2_500, 250),
            (5_000, 'ender_bow'),
            (10_000, 'ender_pearl_to_enchanted_eye'),
            (15_000, 1_500),
            (25_000, ('aspect_of_the_end',
                      'ender_pearl_to_absolute')),
            (50_000, 'saving_grace'),
        ],
    ),
    Collection(
        'ghast_tear', 'combat',
        [
            (20, 'ghast_minion'),
            (100, 'ghast_head'),
            (250, 'giant_killer_book'),
            (1_000, 'ghast_tear_to_enchanted'),
            (2_500, 'vampirism_book'),
            (5_000, 'silver_fang'),
            (10_000, 1_000),
            (25_000, 2_500),
            (50_000, 5_000),
        ],
    ),
    Collection(
        'slime_ball', 'combat',
        [
            (50, 'slime_minion'),
            (100, 'slime_hat'),
            (250, 'knockback_book'),
            (1_000, 100),
            (2_500, 'slime_ball_to_enchanted'),
            (5_000, 'punch_book'),
            (10_000, 1_000),
            (25_000, 'slime_ball_to_enchanted_block'),
            (50_000, 'slime_bow'),
        ],
    ),
    Collection(
        'blaze_rod', 'combat',
        [
            (50, 'blaze_minion'),
            (100, 'blaze_hat'),
            (250, 'fire_aspect_book'),
            (1_000, 'blaze_rod_to_enchanted_powder'),
            (2_500, 250),
            (5_000, 'flame_book'),
            (10_000, 'blaze_rod_to_enchanted'),
            (25_000, 'blaze_armor'),
            (50_000, 'blaze_pet'),
        ],
    ),
    Collection(
        'magma_cream', 'combat',
        [
            (50, 'magma_cube_minion'),
            (100, 'magma_cube_head'),
            (250, 'fire_protection_book'),
            (1_000, 100),
            (2_500, 'magma_cream_to_enchanted'),
            (5_000, 500),
            (10_000, 1_000),
            (25_000, 'armor_of_magma'),
            (50_000, 'magma_bow'),
        ],
    ),
]
