from ..object import *
from ..recipe import get_recipe


COMBAT_COLLECTIONS = [
    Collection(
        'rotten_flesh', 'combat',
        [
            (50, 5),
            (100, get_recipe('zombie_pickaxe')),
            (250, get_recipe('smite_book')),
            (1_000, get_recipe('rotten_flesh_to_enchanted')),
            (2_500, get_recipe('zombie_hat')),
            (5_000, get_recipe('zombies_heart')),
            (10_000, get_recipe('zombie_sword')),
            (25_000, get_recipe('zombie_armor')),
            (50_000, get_recipe('zombie_pet')),
        ],
    ),
    Collection(
        'bone', 'combat',
        [
            (50, 5),
            (100, 10),
            (250, get_recipe('power_book')),
            (1_000, get_recipe('skeleton_hat')),
            (2_500, get_recipe('bone_to_enchanted')),
            (5_000, get_recipe('skeleton_pet')),
            (10_000, get_recipe('hurricane_bow')),
            (25_000, get_recipe('skeletons_helmet')),
            (50_000, get_recipe('runaans_bow')),
            (150_000, get_recipe('bone_to_enchanted_block')),
        ],
    ),
    Collection(
        'string', 'combat',
        [
            (60, 6),
            (100, 10),
            (250, 25),
            (1_000, get_recipe('string_to_enchanted')),
            (2_500, 250),
            (5_000, get_recipe('infinite_quiver_book')),
            (10_000, 1_000),
            (25_000, get_recipe('spiders_boots')),
            (50_000, get_recipe('spider_pet')),
        ],
    ),
    Collection(
        'spider_eye', 'combat',
        [
            (50, 5),
            (100, get_recipe('spider_sword')),
            (250, get_recipe('spider_hat')),
            (1_000, get_recipe('spider_eye_to_enchanted')),
            (2_500, get_recipe('bane_of_arthropods_book')),
            (5_000, 500),
            (10_000, get_recipe('spider_eye_to_enchanted_fermented')),
            (25_000, 2_500),
            (50_000, get_recipe('leaping_sword')),
        ],
    ),
    Collection(
        'gunpowder', 'combat',
        [
            (50, 5),
            (100, get_recipe('creeper_hat')),
            (250, get_recipe('blast_protection_book')),
            (1_000, get_recipe('gunpowder_to_enchanted')),
            (2_500, get_recipe('thunderlord_book')),
            (5_000, get_recipe('gunpowder_to_enchanted_firework')),
            (10_000, 1_000),
            (25_000, get_recipe('creeper_pants')),
            (50_000, get_recipe('explosive_bow')),
        ],
    ),
    Collection(
        'ender_pearl', 'combat',
        [
            (50, 5),
            (250, get_recipe('ender_pearl_to_enchanted')),
            (1_000, get_recipe('ender_slayer_book')),
            (2_500, 250),
            (5_000, get_recipe('ender_bow')),
            (10_000, get_recipe('ender_pearl_to_enchanted_eye')),
            (15_000, 1_500),
            (25_000, (get_recipe('aspect_of_the_end'),
                      get_recipe('ender_pearl_to_absolute'))),
            (50_000, get_recipe('saving_grace')),
        ],
    ),
    Collection(
        'ghast_tear', 'combat',
        [
            (20, 2),
            (100, get_recipe('ghast_head')),
            (250, get_recipe('giant_killer_book')),
            (1_000, get_recipe('ghast_tear_to_enchanted')),
            (2_500, get_recipe('vampirism_book')),
            (5_000, get_recipe('silver_fang')),
            (10_000, 1_000),
            (25_000, 2_500),
            (50_000, 5_000),
        ],
    ),
    Collection(
        'slime_ball', 'combat',
        [
            (50, 5),
            (100, get_recipe('slime_hat')),
            (250, get_recipe('knockback_book')),
            (1_000, 100),
            (2_500, get_recipe('slime_ball_to_enchanted')),
            (5_000, get_recipe('punch_book')),
            (10_000, 1_000),
            (25_000, get_recipe('slime_ball_to_enchanted_block')),
            (50_000, get_recipe('slime_bow')),
        ],
    ),
    Collection(
        'blaze_rod', 'combat',
        [
            (50, 5),
            (100, get_recipe('blaze_hat')),
            (250, get_recipe('fire_aspect_book')),
            (1_000, get_recipe('blaze_rod_to_enchanted_powder')),
            (2_500, 250),
            (5_000, get_recipe('flame_book')),
            (10_000, get_recipe('blaze_rod_to_enchanted')),
            (25_000, get_recipe('blaze_armor')),
            (50_000, get_recipe('blaze_pet')),
        ],
    ),
    Collection(
        'magma_cream', 'combat',
        [
            (50, 5),
            (100, get_recipe('magma_cube_head')),
            (250, get_recipe('fire_protection_book')),
            (1_000, 100),
            (2_500, get_recipe('magma_cream_to_enchanted')),
            (5_000, 500),
            (10_000, 1_000),
            (25_000, get_recipe('armor_of_magma')),
            (50_000, get_recipe('magma_bow')),
        ],
    ),
]
