from ..object import *


FISHING_COLLECTIONS = [
    Collection(
        'fish', 'fishing',
        [
            (20, 'fish_hat'),
            (50, 'fishing_minion'),
            (100, 10),
            (250, 25),
            (500, 'angler_armor'),
            (1_000, 'fish_to_enchanted'),
            (2_500, 250),
            (15_000, 'fish_to_enchanted_cooked'),
            (30_000, 3_000),
            (45_000, 4_500),
            (60_000, 6_000),
        ],
    ),
    Collection(
        'salmon', 'fishing',
        [
            (20, 'minnow_bait'),
            (50, 5),
            (100, 'lure_book'),
            (250, 'salmon_to_enchanted'),
            (500, 'speedster_rod'),
            (1_000, 'fish_bait'),
            (2_500, 250),
            (5_000, 'salmon_to_enchanted_cooked'),
            (10_000, 'salmon_armor'),
        ],
    ),
    Collection(
        'clownfish', 'fishing',
        [
            (10, 'clownfish_hat'),
            (25, 2.5),
            (50, 'magnet_book'),
            (100, 10),
            (200, 20),
            (400, 40),
            (800, 80),
        ],
    ),
    Collection(
        'pufferfish', 'fishing',
        [
            (20, 'pufferfish_hat'),
            (50, 'pufferfish_to_enchanted'),
            (100, 'cleave_book'),
            (150, 15),
            (400, 'spiked_bait'),
            (800, 'spiked_hook_book'),
            (2_400, 240),
            (4_800, 480),
            (9_000, 900),
        ],
    ),
    Collection(
        'prismarine_shard', 'fishing',
        [
            (10, 'impaling_book'),
            (25, 'prismarine_blade'),
            (50, 'prismarine_shard_to_enchanted'),
            (100, 'prismarine_rod'),
            (200, 'prismarine_bow'),
        ],
    ),
    Collection(
        'prismarine_crystals', 'fishing',
        [
            (10, 1),
            (25, 'light_bait'),
            (50, 'prismarine_crystals_to_enchanted'),
            (100, 10),
            (200, 'guardian_chestplate'),
            (400, 'blessed_bait'),
            (800, 'blessing_book'),
        ],
    ),
    Collection(
        'clay', 'fishing',
        [
            (50, 'clay_minion'),
            (100, 'clay_to_enchanted'),
            (250, 25),
            (1_000, 'frail_book'),
            (2_500, 250),
        ],
    ),
    Collection(
        'lily_pad', 'fishing',
        [
            (10, 'spooky_bait'),
            (50, 'blobfish_hat'),
            (100, 'healing_talisman'),
            (200, 'lily_pad_to_enchanted'),
            (500, 'challenging_rod'),
            (1_500, 'whale_bait'),
            (3_000, 'rod_of_champions'),
            (6_000, 'healing_ring'),
            (10_000, 'rod_of_legends'),
        ],
    ),
    Collection(
        'ink_sack', 'fishing',
        [
            (20, 'squid_hat'),
            (40, 'dark_bait'),
            (100, 'ink_sack_to_enchanted'),
            (200, 20),
            (400, 'caster_book'),
            (800, 80),
            (1_500, 'angler_book'),
            (2_500, 250),
            (4_000, 'ink_wand'),
        ],
    ),
    Collection(
        'sponge', 'fishing',
        [
            (20, 'sponge_rod'),
            (40, 4),
            (100, 'sponge_to_enchanted'),
            (200, 'sea_creature_talisman'),
            (400, 'stereo_pants'),
            (800, 'sea_creature_ring'),
            (1_500, 'sponge_to_enchanted_wet'),
            (2_500, 'sea_creature_artifact'),
            (4_000, 'sponge_armor'),
        ],
    ),
]
