from typing import Optional

from ..function.io import *
from ..function.util import get, includes

from .object import *


__all__ = ['MOBS', 'get_mob']

MOBS = [
    Mob('zombie', level=1, health=100, damage=20,
        coins=1, exp=1, combat_exp=6,
        drops=[
            ({'name': 'rotten_flesh'}, 1, 'common', 1),
            ({'name': 'poisonous_potato'}, 1, 'uncommon', 0.02),
            ({'name': 'potato'}, 1, 'rare', 0.01),
            ({'name': 'carrot'}, 1, 'rare', 0.01),
        ]),
    Mob('zombie_villager', level=1, health=120, damage=24,
        coins=1, exp=2, combat_exp=7,
        drops=[
            ({'name': 'rotten_flesh'}, 1, 'common', 1),
            ({'name': 'poisonous_potato'}, 1, 'uncommon', 0.02),
            ({'name': 'potato'}, 1, 'rare', 0.01),
            ({'name': 'carrot'}, 1, 'rare', 0.01),
        ]),
    Mob('skeleton', level=6, health=200, damage=47,
        coins=2, exp=4, combat_exp=6,
        drops=[
            ({'name': 'bone'}, 2, 'common', 1),
        ]),
    Mob('crypt_ghoul', level=30, health=2000, damage=200,
        coins=13, exp=30, combat_exp=32,
        drops=[
            ({'name': 'rotten_flesh'}, (1, 2), 'common', 1),
            ({'name': 'ghoul_pet', 'rarity': 'epic'},
             1, 'pray_rngesus', 0.00003),
            ({'name': 'ghoul_pet', 'rarity': 'legendary'},
             1, 'pray_rngesus', 0.00001),
        ]),
    Mob('golden_ghoul', level=60, health=45000, damage=500,
        coins=100, exp=30, combat_exp=50,
        drops=[
            ({'name': 'rotten_flesh'}, 2, 'common', 1),
            ({'name': 'gold'}, (1, 10), 'common', 1),
            ({'name': 'golden_powder'}, 1, 'legendary', 0.0005),
        ]),
    Mob('wolf', level=15, health=250, damage=80,
        coins=1, exp=4, combat_exp=10,
        drops=[
            ({'name': 'bone'}, 1, 'common', 1),
            ({'name': 'hound_pet', 'rarity': 'epic'},
             1, 'pray_rngesus', 0.00001),
            ({'name': 'hound_pet', 'rarity': 'legendary'},
             1, 'pray_rngesus', 0.000003),
        ]),
    Mob('old_wolf', level=50, health=15000, damage=720,
        coins=40, exp=4, combat_exp=40,
        drops=[
            ({'name': 'bone'}, 1, 'common', 1),
            ({'name': 'hound_pet', 'rarity': 'epic'},
             1, 'pray_rngesus', 0.00001),
            ({'name': 'hound_pet', 'rarity': 'legendary'},
             1, 'pray_rngesus', 0.000003),
        ]),

    Mob('chicken', level=1, health=4, damage=0,
        coins=0, exp=2, farming_exp=2,
        drops=[
            ({'name': 'chicken'}, 1, 'common', 1),
            ({'name': 'feather'}, (1, 2), 'common', 2 / 3),
            ({'name': 'egg'}, 1, 'common', 1 / 4),
        ]),
    Mob('cow', level=1, health=10, damage=0,
        coins=0, exp=2, farming_exp=2,
        drops=[
            ({'name': 'beef'}, (1, 3), 'common', 1),
            ({'name': 'leather'}, (1, 2), 'common', 2 / 3),
        ]),
    Mob('mooshroom', level=1, health=10, damage=0,
        coins=0, exp=2, farming_exp=2,
        drops=[
            ({'name': 'beef'}, (1, 3), 'common', 1),
            ({'name': 'leather'}, (1, 2), 'common', 2 / 3),
            ({'name': 'mushroom'}, (1, 3), 'common', 1),
        ]),
    Mob('pig', level=1, health=10, damage=0,
        coins=0, exp=2, farming_exp=2,
        drops=[
            ({'name': 'pork'}, (1, 3), 'common', 1),
        ]),
    Mob('sheep', level=1, health=8, damage=0,
        coins=0, exp=2, farming_exp=2,
        drops=[
            ({'name': 'mutton'}, (1, 2), 'common', 1),
            ({'name': 'wool'}, 1, 'common', 1),
        ]),
    Mob('rabbit', level=10, health=125, damage=0,
        coins=0, exp=2, farming_exp=2,
        drops=[
            ({'name': 'rabbit'}, 1, 'common', 0.6),
            ({'name': 'rabbit_hide'}, 1, 'common', 0.3),
            ({'name': 'rabbit_foot'}, 1, 'uncommon', 0.1),
        ]),

    Mob('dasher_spider', level=4, health=160, damage=55,
        coins=2, exp=8, combat_exp=10,
        drops=[
            ({'name': 'string'}, 1, 'common', 1),
            ({'name': 'spider_eye'}, 1, 'common', 0.5),
            ({'name': 'travel_scroll_to_nest'}, 1, 'legendary', 0.0002),
            ({'name': 'tarantula_pet', 'rarity': 'epic'},
             1, 'pray_rngesus', 0.0001),
            ({'name': 'tarantula_pet', 'rarity': 'legendary'},
             1, 'pray_rngesus', 0.0001),
        ]),
    Mob('dasher_spider', level=42, health=5000, damage=240,
        coins=10, exp=10, combat_exp=28,
        drops=[
            ({'name': 'string'}, 1, 'common', 1),
            ({'name': 'spider_eye'}, 1, 'common', 0.5),
            ({'name': 'travel_scroll_to_nest'}, 1, 'legendary', 0.0002),
            ({'name': 'tarantula_pet', 'rarity': 'epic'},
             1, 'pray_rngesus', 0.0001),
            ({'name': 'tarantula_pet', 'rarity': 'legendary'},
             1, 'pray_rngesus', 0.0001),
        ]),
    Mob('dasher_spider', level=45, health=6000, damage=580,
        coins=12, exp=10, combat_exp=30,
        drops=[
            ({'name': 'string'}, 1, 'common', 1),
            ({'name': 'spider_eye'}, 1, 'common', 0.5),
            ({'name': 'travel_scroll_to_nest'}, 1, 'legendary', 0.0002),
            ({'name': 'tarantula_pet', 'rarity': 'epic'},
             1, 'pray_rngesus', 0.0001),
            ({'name': 'tarantula_pet', 'rarity': 'legendary'},
             1, 'pray_rngesus', 0.0001),
        ]),
    Mob('dasher_spider', level=50, health=7000, damage=720,
        coins=15, exp=10, combat_exp=36,
        drops=[
            ({'name': 'string'}, 1, 'common', 1),
            ({'name': 'spider_eye'}, 1, 'common', 0.5),
            ({'name': 'travel_scroll_to_nest'}, 1, 'legendary', 0.0002),
            ({'name': 'tarantula_pet', 'rarity': 'epic'},
             1, 'pray_rngesus', 0.0001),
            ({'name': 'tarantula_pet', 'rarity': 'legendary'},
             1, 'pray_rngesus', 0.0001),
        ]),
    Mob('spider_jockey', level=5, health=530, damage=93,
        coins=7, exp=10, combat_exp=14,
        drops=[
            ({'name': 'string'}, (1, 2), 'common', 1),
            ({'name': 'bone'}, 2, 'common', 1),
            ({'name': 'spider_eye'}, 1, 'uncommon', 0.1),
            ({'name': 'bow'}, 1, 'rare', 0.02),
        ]),
    Mob('weaver_spider', level=3, health=160, damage=35,
        coins=2, exp=2, combat_exp=9,
        drops=[
            ({'name': 'string'}, 1, 'common', 1),
            ({'name': 'spider_eye'}, 1, 'uncommon', 0.1),
        ]),
    Mob('weaver_spider', level=5, health=200, damage=45,
        coins=2, exp=2, combat_exp=8,
        drops=[
            ({'name': 'string'}, 1, 'common', 1),
            ({'name': 'spider_eye'}, 1, 'uncommon', 0.1),
        ]),
    Mob('voracious_spider', level=10, health=1000, damage=100,
        coins=2, exp=3, combat_exp=10,
        drops=[
            ({'name': 'string'}, 1, 'common', 1),
            ({'name': 'spider_eye'}, 1, 'uncommon', 0.1),
        ]),
    Mob('voracious_spider', level=42, health=5000, damage=244,
        coins=8, exp=8, combat_exp=28,
        drops=[
            ({'name': 'string'}, 1, 'common', 1),
            ({'name': 'spider_eye'}, 1, 'uncommon', 0.1),
        ]),
    Mob('voracious_spider', level=45, health=7000, damage=648,
        coins=12, exp=9, combat_exp=30,
        drops=[
            ({'name': 'string'}, 1, 'common', 1),
            ({'name': 'spider_eye'}, 1, 'uncommon', 0.1),
        ]),
    Mob('voracious_spider', level=50, health=7000, damage=648,
        coins=15, exp=10, combat_exp=36,
        drops=[
            ({'name': 'string'}, 1, 'common', 1),
            ({'name': 'spider_eye'}, 1, 'uncommon', 0.1),
        ]),
    Mob('splitter_spider', level=2, health=180, damage=25,
        coins=2, exp=2, combat_exp=8,
        drops=[
            ({'name': 'string'}, (1, 2), 'common', 1),
            ({'name': 'spider_eye'}, 1, 'uncommon', 0.1),
        ]),
    Mob('gravel_skeleton', level=2, health=100, damage=33,
        coins=1, exp=4, combat_exp=6,
        drops=[
            ({'name': 'bone'}, (3, 6), 'common', 1),
        ]),
    Mob('rain_slime', level=8, health=200, damage=100,
        coins=5, exp=3, combat_exp=4,
        drops=[
            ({'name': 'slime_ball'}, 1, 'common', 1),
        ]),

    Mob('small_magma_cube', level=3, health=200, damage=70,
        coins=3, exp=7, combat_exp=4,
        drops=[
            ({'name': 'magma_cream'}, 1, 'common', 1),
        ]),
    Mob('medium_magma_cube', level=6, health=250, damage=120,
        coins=4, exp=9, combat_exp=4,
        drops=[
            ({'name': 'magma_cream'}, 1, 'common', 1),
        ]),
    Mob('large_magma_cube', level=9, health=300, damage=150,
        coins=4, exp=20, combat_exp=4,
        drops=[
            ({'name': 'magma_cream'}, (1, 3), 'common', 1),
            ({'name': 'magma_cube_pet', 'rarity': 'common'},
             1, 'rare', 0.01),
            ({'name': 'magma_cube_pet', 'rarity': 'uncommon'},
             1, 'legendary', 0.0005),
            ({'name': 'magma_cube_pet', 'rarity': 'rare'},
             1, 'pray_rngesus', 0.0001),
        ]),
    Mob('mini_blaze', level=12, health=500, damage=120,
        coins=5, exp=30, combat_exp=10,
        drops=[
            ({'name': 'blaze_rod'}, 1, 'common', 1),
        ]),
    Mob('blaze', level=15, health=600, damage=150,
        coins=10, exp=35, combat_exp=10,
        drops=[
            ({'name': 'blaze_rod'}, 2, 'common', 1),
            ({'name': 'blaze_hat'}, 1, 'uncommon', 0.05),
        ]),
    Mob('wither_skeleton', level=10, health=250, damage=152,
        coins=4, exp=15, combat_exp=13,
        drops=[
            ({'name': 'bone'}, 3, 'common', 1),
            ({'name': 'coal'}, 1, 'common', 0.5),
            ({'name': 'enchanted_coal'}, 1, 'rare', 0.01),
        ]),
    Mob('zombie_pigman', level=12, health=240, damage=125,
        coins=4, exp=25, combat_exp=15,
        drops=[
            ({'name': 'gold_nugget'}, 2, 'common', 1),
            ({'name': 'flaming_sword'}, 1, 'uncommon', 0.03),
        ]),
    Mob('ghast', level=17, health=330, damage=150,
        coins=30, exp=32, combat_exp=50,
        drops=[
            ({'name': 'ghast_tear'}, 1, 'common', 1),
        ]),

    Mob('enderman', level=42, health=4500, damage=500,
        coins=10, exp=8, combat_exp=40.8,
        drops=[
            ({'name': 'ender_pearl'}, (1, 3), 'common', 1),
            ({'name': 'enchanted_ender_pearl'}, 1, 'rare', 0.01),
            ({'name': 'enderman_pet', 'rarity': 'common'},
             1, 'legendary', 0.0005),
            ({'name': 'enderman_pet', 'rarity': 'uncommon'},
             1, 'legendary', 0.0002),
            ({'name': 'enderman_pet', 'rarity': 'rare'},
             1, 'pray_rngesus', 0.0001),
            ({'name': 'ender_helmet'}, 1, 'legendary', 0.00025),
            ({'name': 'ender_chestplate'}, 1, 'legendary', 0.00025),
            ({'name': 'ender_leggings'}, 1, 'legendary', 0.00025),
            ({'name': 'ender_helmet'}, 1, 'legendary', 0.00025),
        ]),
    Mob('enderman', level=45, health=6000, damage=600,
        coins=12, exp=9, combat_exp=40.8,
        drops=[
            ({'name': 'ender_pearl'}, (1, 3), 'common', 1),
            ({'name': 'enchanted_ender_pearl'}, 1, 'rare', 0.01),
            ({'name': 'enderman_pet', 'rarity': 'uncommon'},
             1, 'legendary', 0.0005),
            ({'name': 'enderman_pet', 'rarity': 'rare'},
             1, 'legendary', 0.0002),
            ({'name': 'enderman_pet', 'rarity': 'epic'},
             1, 'pray_rngesus', 0.0001),
            ({'name': 'ender_helmet'}, 1, 'legendary', 0.00025 / 3),
            ({'name': 'ender_chestplate'}, 1, 'legendary', 0.00025 / 3),
            ({'name': 'ender_leggings'}, 1, 'legendary', 0.00025 / 3),
            ({'name': 'ender_helmet'}, 1, 'legendary', 0.00025 / 3),
        ]),
    Mob('enderman', level=50, health=9000, damage=700,
        coins=15, exp=10, combat_exp=40.8,
        drops=[
            ({'name': 'ender_pearl'}, (1, 2), 'common', 1),
            ({'name': 'enchanted_ender_pearl'}, 1, 'rare', 0.01),
            ({'name': 'enderman_pet', 'rarity': 'rare'},
             1, 'legendary', 0.001),
            ({'name': 'enderman_pet', 'rarity': 'epic'},
             1, 'pray_rngesus', 0.0001),
            ({'name': 'enderman_pet', 'rarity': 'legendary'},
             1, 'pray_rngesus', 0.000006),
            ({'name': 'ender_helmet'}, 1, 'legendary', 0.00005),
            ({'name': 'ender_chestplate'}, 1, 'legendary', 0.00005),
            ({'name': 'ender_leggings'}, 1, 'legendary', 0.00005),
            ({'name': 'ender_helmet'}, 1, 'legendary', 0.00005),
        ]),
    Mob('obsidian_defender', level=55, health=10000, damage=200,
        coins=15, exp=10, combat_exp=40,
        drops=[
            ({'name': 'obsidian'}, (2, 3), 'common', 1),
            ({'name': 'enchanted_obsidian'}, 1, 'rare', 0.01),
            ({'name': 'obsidian_chestplate'}, 1, 'legendary', 0.001),
        ]),
    Mob('watcher', level=55, health=9500, damage=475,
        coins=15, exp=10, combat_exp=40,
        drops=[
            ({'name': 'arrow'}, (1, 4), 'common', 1),
            ({'name': 'ender_pearl'}, (1, 2), 'common', 1),
            ({'name': 'enchanted_bone'}, 1, 'rare', 0.01),
            ({'name': 'end_stone_bow'}, 1, 'legendary', 0.001),
        ]),
    Mob('zealot', level=55, health=13000, damage=1250,
        coins=15, exp=10, combat_exp=40,
        drops=[
            ({'name': 'ender_pearl'}, (2, 4), 'common', 1),
            ({'name': 'enchanted_ender_pearl'}, 1, 'rare', 0.02),
            ({'name': 'summoning_eye'}, 1, 'legendary', 1 / 420),
        ]),
    Mob('endermite', level=37, health=2000, damage=400,
        coins=10, exp=8, combat_exp=25,
        drops=[
            ({'name': 'end_stone'}, (1, 2), 'common', 1),
        ]),
    Mob('endermite', level=40, health=2300, damage=475,
        coins=11, exp=8, combat_exp=28,
        drops=[
            ({'name': 'end_stone'}, (2, 4), 'common', 1),
        ]),

    Mob('voidling_fanatic', level=85, health=750000, damage=3500,
        coins=20, exp=30, combat_exp=110,
        drops=[
            ({'name': 'ender_pearl'}, (4, 5), 'common', 1),
            ({'name': 'enchanted_ender_pearl'}, 1, 'rare', 0.01),
        ]),
    Mob('voidling_extremist', level=100, health=8000000, damage=13500,
        coins=100, exp=70, combat_exp=500,
        drops=[
            ({'name': 'ender_pearl'}, (32, 64), 'common', 1),
            ({'name': 'enchanted_ender_pearl'}, 1, 'rare', 0.02),
        ]),

    Mob('sneaky_creeper', level=3, health=120, damage=80,
        coins=3, exp=3, combat_exp=8,
        drops=[
            ({'name': 'gunpowder'}, 1, 'common', 1),
            ({'name': 'exp_share_core'}, 1, 'pray_rngesus', 0.0001),
        ]),
    Mob('lapis_zombie', level=7, health=200, damage=50,
        coins=5, exp=10, combat_exp=12,
        drops=[
            ({'name': 'rotten_flesh'}, (1, 2), 'common', 1),
            ({'name': 'lapis_helmet'}, 1, 'rare', 0.0025),
            ({'name': 'lapis_chestplate'}, 1, 'rare', 0.0025),
            ({'name': 'lapis_leggings'}, 1, 'rare', 0.0025),
            ({'name': 'lapis_boots'}, 1, 'rare', 0.0025),
            ({'name': 'lapis_crystal'}, 1, 'rare', 0.0025),
            ({'name': 'exp_share_core'}, 1, 'pray_rngesus', 0.0001),
        ]),
    Mob('redstone_pigman', level=12, health=240, damage=125,
        coins=4, exp=25, combat_exp=20,
        drops=[
            ({'name': 'gold_nugget'}, 2, 'common', 1),
            ({'name': 'exp_share_core'}, 1, 'pray_rngesus', 0.0001),
        ]),
    Mob('small_emerald_slime', level=5, health=80, damage=70,
        coins=5, exp=20, combat_exp=12,
        drops=[
            ({'name': 'slime_ball'}, 1, 'common', 1),
            ({'name': 'exp_share_core'}, 1, 'pray_rngesus', 0.0001),
        ]),
    Mob('medium_emerald_slime', level=10, health=150, damage=100,
        coins=8, exp=30, combat_exp=15,
        drops=[
            ({'name': 'slime_ball'}, (1, 2), 'common', 1),
            ({'name': 'exp_share_core'}, 1, 'pray_rngesus', 0.0001),
        ]),
    Mob('large_emerald_slime', level=15, health=250, damage=150,
        coins=12, exp=50, combat_exp=20,
        drops=[
            ({'name': 'slime_ball'}, 2, 'common', 1),
            ({'name': 'exp_share_core'}, 1, 'pray_rngesus', 0.0001),
        ]),
    Mob('diamond_zombie', level=15, health=250, damage=150,
        coins=12, exp=30, combat_exp=20,
        drops=[
            ({'name': 'rotten_flesh'}, 4, 'common', 1),
            ({'name': 'miner_helmet'}, 1, 'pray_rngesus', 0.00125),
            ({'name': 'miner_chestplate'}, 1, 'pray_rngesus', 0.00125),
            ({'name': 'miner_leggings'}, 1, 'pray_rngesus', 0.00125),
            ({'name': 'miner_boots'}, 1, 'pray_rngesus', 0.00125),
            ({'name': 'exp_share_core'}, 1, 'pray_rngesus', 0.0001),
        ]),
    Mob('diamond_skeleton', level=15, health=250, damage=150,
        coins=12, exp=30, combat_exp=20,
        drops=[
            ({'name': 'bone'}, 4, 'common', 1),
            ({'name': 'miner_helmet'}, 1, 'pray_rngesus', 0.00125),
            ({'name': 'miner_chestplate'}, 1, 'pray_rngesus', 0.00125),
            ({'name': 'miner_leggings'}, 1, 'pray_rngesus', 0.00125),
            ({'name': 'miner_boots'}, 1, 'pray_rngesus', 0.00125),
            ({'name': 'exp_share_core'}, 1, 'pray_rngesus', 0.0001),
        ]),
    Mob('diamond_zombie', level=20, health=300, damage=190,
        coins=15, exp=40, combat_exp=24,
        drops=[
            ({'name': 'rotten_flesh'}, 4, 'common', 1),
            ({'name': 'miner_helmet', 'enchantments': {'protection': 5}},
             1, 'pray_rngesus', 0.00125),
            ({'name': 'miner_chestplate', 'enchantments': {'protection': 5}},
             1, 'pray_rngesus', 0.00125),
            ({'name': 'miner_leggings', 'enchantments': {'protection': 5}},
             1, 'pray_rngesus', 0.00125),
            ({'name': 'miner_boots', 'enchantments': {'protection': 5}},
             1, 'pray_rngesus', 0.00125),
            ({'name': 'exp_share_core'}, 1, 'pray_rngesus', 0.0001),
        ]),
    Mob('diamond_skeleton', level=20, health=300, damage=190,
        coins=15, exp=40, combat_exp=24,
        drops=[
            ({'name': 'bone'}, 4, 'common', 1),
            ({'name': 'miner_helmet', 'enchantments': {'protection': 5}},
             1, 'pray_rngesus', 0.00125),
            ({'name': 'miner_chestplate', 'enchantments': {'protection': 5}},
             1, 'pray_rngesus', 0.00125),
            ({'name': 'miner_leggings', 'enchantments': {'protection': 5}},
             1, 'pray_rngesus', 0.00125),
            ({'name': 'miner_boots', 'enchantments': {'protection': 5}},
             1, 'pray_rngesus', 0.00125),
            ({'name': 'exp_share_core'}, 1, 'pray_rngesus', 0.0001),
        ]),

    Mob('ghost', level=250, health=1000000, damage=1000, true_damage=100,
        coins=100, exp=30, combat_exp=100,
        drops=[
            ({'name': 'sorrow'}, 1, 'rare', 0.0012),
            ({'name': 'plasma'}, 1, 'legendary', 0.001),
            ({'name': 'bag_of_cash'}, 1, 'pray_rngesus', 0.0001),
        ]),
    Mob('goblin', level=25, health=800, damage=300,
        coins=10, exp=20, combat_exp=50,
        drops=[
            ({'name': 'goblin_helmet'},
             1, 'pray_rngesus', 0.00075),
            ({'name': 'goblin_chestplate'},
             1, 'pray_rngesus', 0.00075),
            ({'name': 'goblin_leggings'},
             1, 'pray_rngesus', 0.00075),
            ({'name': 'goblin_boots'},
             1, 'pray_rngesus', 0.00075),
        ]),
    Mob('treasure_hoarder', level=70, health=22000, damage=750,
        coins=50, exp=60, combat_exp=70,
        drops=[
            ({'name': 'starfall'}, (1, 2), 'common', 1),
            ({'name': 'salmon_opal'}, 1, 'rare', 0.01),
            ({'name': 'treasurite'}, 1, 'rare', 0.005),
        ]),
    Mob('ice_walker', level=45, health=888, defense=800, damage=500,
        coins=40, exp=35, combat_exp=40,
        drops=[
            ({'name': 'glacite_helmet'},
             1, 'pray_rngesus', 0.0025),
            ({'name': 'glacite_chestplate'},
             1, 'pray_rngesus', 0.0025),
            ({'name': 'glacite_leggings'},
             1, 'pray_rngesus', 0.0025),
            ({'name': 'glacite_boots'},
             1, 'pray_rngesus', 0.0025),
        ]),

    Mob('pack_spirit', level=35, health=7000, damage=450,
        coins=11, exp=10, combat_exp=15,
        drops=[
            ({'name': 'spruce'}, 1, 'uncommon', 0.15),
            ({'name': 'dark'}, 1, 'uncommon', 0.15),
            ({'name': 'acacia'}, 1, 'uncommon', 0.15),
            ({'name': 'travel_scroll_to_howl'}, 1, 'legendary', 0.0002),
            ({'name': 'hound_pet', 'rarity': 'epic'},
             1, 'pray_rngesus', 0.0002 / 3),
            ({'name': 'hound_pet', 'rarity': 'legendary'},
             1, 'pray_rngesus', 0.0001 / 6),
        ]),
    Mob('howling_spirit', level=35, health=7000, damage=450,
        coins=11, exp=10, combat_exp=15,
        drops=[
            ({'name': 'spruce'}, 1, 'uncommon', 0.15),
            ({'name': 'dark'}, 1, 'uncommon', 0.15),
            ({'name': 'acacia'}, 1, 'uncommon', 0.15),
            ({'name': 'travel_scroll_to_howl'}, 1, 'legendary', 0.0002),
            ({'name': 'hound_pet', 'rarity': 'epic'},
             1, 'pray_rngesus', 0.0002 / 3),
            ({'name': 'hound_pet', 'rarity': 'legendary'},
             1, 'pray_rngesus', 0.0001 / 6),
        ]),
    Mob('soul_of_the_alpha', level=55, health=31150, damage=1150,
        coins=50, exp=15, combat_exp=50,
        drops=[
            ({'name': 'jungle'}, 1, 'common', 1),
            ({'name': 'travel_scroll_to_howl'}, 1, 'legendary', 0.00035),
            ({'name': 'hound_pet', 'rarity': 'epic'},
             1, 'pray_rngesus', 0.0002 / 3),
            ({'name': 'hound_pet', 'rarity': 'legendary'},
             1, 'pray_rngesus', 0.0001 / 6),
        ]),

    # sea creatures
    Mob('squid', level=1, health=2000,
        coins=0, exp=15, fishing_exp=41,
        drops=[
            ({'name': 'lily_pad'}, (1, 2), 'common', 1),
            ({'name': 'ink_sack'}, (2, 5), 'common', 1),
        ]),
    Mob('sea_walker', level=4, health=1500, damage=60,
        coins=0, exp=30, fishing_exp=68,
        drops=[
            ({'name': 'rotten_flesh'}, (1, 4), 'common', 1),
            ({'name': 'lily_pad'}, (1, 6), 'common', 1),
            ({'name': 'fish'}, (1, 4), 'common', 1),
        ]),
    Mob('night_squid', level=6, health=4000,
        coins=0, exp=28, fishing_exp=270,
        drops=[
            ({'name': 'ink_sack'}, (12, 27), 'common', 1),
            ({'name': 'lily_pad'}, (1, 4), 'common', 1),
            ({'name': 'squid_boots'}, 1, 'rare', 0.05),
        ]),
    Mob('sea_guardian', level=10, health=5000, damage=150,
        coins=0, exp=32, fishing_exp=75,
        drops=[
            ({'name': 'lily_pad'}, (1, 2), 'common', 1),
            ({'name': 'prismarine_shard'}, (1, 3), 'common', 1),
            ({'name': 'prismarine_crystals'}, (1, 3), 'common', 1),
        ]),
    Mob('sea_witch', level=15, health=6000, damage=160,
        coins=0, exp=35, fishing_exp=338,
        drops=[
            ({'name': 'fish'}, (1, 5), 'common', 1),
            ({'name': 'salmon'}, (2, 4), 'common', 1),
            ({'name': 'clownfish'}, 1, 'common', 0.5),
            ({'name': 'lily_pad'}, (2, 3), 'common', 1),
            ({'name': 'fairys_fedora'}, 1, 'rare', 0.01),
            ({'name': 'fairys_polo'}, 1, 'rare', 0.01),
            ({'name': 'fairys_trousers'}, 1, 'rare', 0.01),
            ({'name': 'fairys_galoshes'}, 1, 'rare', 0.01),
        ]),
    Mob('sea_archer', level=15, health=7000, damage=130,
        coins=0, exp=41, fishing_exp=169,
        drops=[
            ({'name': 'bone'}, (1, 6), 'common', 1 / 7),
            ({'name': 'enchanted_bone'}, 1, 'common', 6 / 7),
            ({'name': 'fish'}, (2, 3), 'common', 1),
            ({'name': 'lily_pad'}, (2, 4), 'common', 1),
        ]),
    Mob('monster_of_the_deep', level=20, health=20000, damage=200,
        coins=0, exp=41, fishing_exp=270,
        drops=[
            ({'name': 'lily_pad'}, (2, 4), 'common', 1),
            ({'name': 'sponge'}, 1, 'common', 1),
            ({'name': 'rotten_flesh'}, (1, 6), 'common', 1 / 7),
            ({'name': 'enchanted_rotten_flesh'}, 1, 'common', 6 / 7),
            ({'name': 'enchanted_feather'}, 1, 'common', 6 / 7),
            ({'name': 'enchanted_book', 'enchantments': {'magnet': 6}},
             1, 'rare', 0.02),
        ]),
    Mob('catfish', level=23, health=26000, damage=220,
        coins=0, exp=50, fishing_exp=405,
        drops=[
            ({'name': 'clownfish'}, (1, 2), 'common', 1),
            ({'name': 'lily_pad'}, (2, 5), 'common', 1),
            ({'name': 'pufferfish'}, 1, 'common', 1),
            ({'name': 'fish'}, (1, 3), 'common', 1),
            ({'name': 'salmon'}, (1, 3), 'common', 1),
            ({'name': 'sponge'}, 1, 'common', 1),
            ({'name': 'enchanted_book', 'enchantments': {'frail': 6}},
             1, 'rare', 0.02),
        ]),
    Mob('sea_leech', level=30, health=60000, damage=300,
        coins=0, exp=65, fishing_exp=675,
        drops=[
            ({'name': 'fish'}, (10, 20), 'common', 1),
            ({'name': 'clownfish'}, 2, 'common', 1),
            ({'name': 'lily_pad'}, 3, 'common', 1),
            ({'name': 'sponge'}, 1, 'common', 1),
            ({'name': 'enchanted_book', 'enchantments': {'spiked_hook': 6}},
             1, 'rare', 0.02),
        ]),
    Mob('guardian_defender', level=45, health=70000, damage=212,
        coins=0, exp=72, fishing_exp=1150,
        drops=[
            ({'name': 'fish'}, (15, 30), 'common', 1),
            ({'name': 'enchanted_prismarine_shard'}, 1, 'common', 1),
            ({'name': 'enchanted_prismarine_crystals'}, 1, 'common', 3 / 4),
            ({'name': 'sponge'}, (1, 2), 'common', 1),
            ({'name': 'lily_pad'}, (5, 11), 'common', 1),
            ({'name': 'enchanted_book', 'enchantments': {'lure': 6}},
             1, 'rare', 0.02),
        ]),
    Mob('deep_sea_protector', level=60, health=150000, damage=400,
        coins=0, exp=100, fishing_exp=1350,
        drops=[
            ({'name': 'clownfish'}, (10, 25), 'common', 1),
            ({'name': 'lily_pad'}, (30, 40), 'common', 1),
            ({'name': 'enchanted_iron'}, (2, 4), 'common', 1),
            ({'name': 'sponge'}, (1, 3), 'common', 1),
            ({'name': 'enchanted_book', 'enchantments': {'angler': 4}},
             1, 'rare', 0.02),
        ]),
    Mob('water_hydra', level=100, health=500000, damage=500,
        coins=0, exp=175, fishing_exp=3000,
        drops=[
            ({'name': 'water_hydra_head'}, (1, 2), 'rare', 0.05),
            ({'name': 'enchanted_book', 'enchantments': {'luck_of_the_sea': 6}},
             1, 'rare', 0.02),
        ]),
    Mob('sea_emperor', level=150, health=750000, damage=600,
        coins=0, exp=250, fishing_exp=3375,
        drops=[
            ({'name': 'enchanted_lily_pad'}, (1, 3), 'common', 1),
            ({'name': 'emperors_skull'}, 1, 'common', 1),
            ({'name': 'shredder'}, 1, 'rare', 0.2),
            ({'name': 'flying_fish_pet', 'rarity': 'rare'}, 1, 'rare', 0.1),
            ({'name': 'flying_fish_pet', 'rarity': 'epic'}, 1, 'rare', 0.04),
            ({'name': 'flying_fish_pet', 'rarity': 'legendary'}, 1, 'rare', 0.01),
        ]),
]

def get_mob(name: str, /, *, warn=True, **kwargs) -> Optional[ItemType]:
    if not includes(MOBS, name):
        if warn:
            red(f'Mob not found: {name!r}')
        return
    return get(MOBS, name, **kwargs)
