from typing import Optional

from ..function.io import red
from ..function.util import includes, get

from .item import get_item, get_scroll
from .object import Item, Recipe


__all__ = ['RECIPES', 'get_recipe']


RECIPES = [
    Recipe('wooden_hoe', 'farming',
           [(Item('planks'), 2),
            (Item('stick'), 2)],
           (get_item('wooden_hoe'), 1)),
    Recipe('gold_hoe', 'farming',
           [(Item('gold'), 2),
            (Item('stick'), 2)],
           (get_item('golden_hoe'), 1)),
    Recipe('stone_hoe', 'farming',
           [(Item('cobblestone'), 2),
            (Item('stick'), 2)],
           (get_item('stone_hoe'), 1)),
    Recipe('iron_hoe', 'farming',
           [(Item('iron'), 2),
            (Item('stick'), 2)],
           (get_item('iron_hoe'), 1)),
    Recipe('diamond_hoe', 'farming',
           [(Item('diamond'), 2),
            (Item('stick'), 2)],
           (get_item('diamond_hoe'), 1)),

    Recipe('wheat_to_bread', 'farming',
           [(Item('wheat'), 3)],
           (Item('bread'), 1)),
    Recipe('wheat_to_hay', 'farming',
           [(Item('wheat'), 9)],
           (Item('hay_bale'), 1)),
    Recipe('hay_to_wheat', 'farming',
           [(Item('hay_bale'), 1)],
           (Item('wheat'), 9)),
    Recipe('carrot_to_golden', 'farming',
           [(Item('carrot'), 1),
            (Item('gold_nugget'), 8)],
           (Item('golden_carrot'), 1)),
    Recipe('glistering_melon', 'farming',
           [(Item('melon'), 1),
            (Item('gold_nugget'), 8)],
           (Item('glistering_melon'), 1)),
    Recipe('cane_to_sugar', 'farming',
           [(Item('sugar_cane'), 1)],
           (Item('sugar'), 1)),
    Recipe('cane_to_paper', 'farming',
           [(Item('sugar_cane'), 3)],
           (Item('paper'), 3)),
    Recipe('paper_to_book', 'farming',
           [(Item('paper'), 3),
            (Item('leather'), 1)],
           (Item('book'), 1)),
    Recipe('string_to_wool', 'farming',
           [(Item('string'), 4)],
           (Item('wool'), 1)),
    Recipe('hide_to_leather', 'farming',
           [(Item('rabbit_hide'), 4)],
           (Item('leather'), 1)),

    Recipe('bread_to_enchanted', 'farming',
           [(Item('wheat'), 144)],
           (Item('enchanted_bread'), 1),
           collection_req=('wheat', 5)),
    Recipe('hay_to_enchanted', 'farming',
           [(Item('hay_bale'), 144)],
           (Item('enchanted_hay_bale'), 1),
           collection_req=('wheat', 7)),
    Recipe('hay_to_tighted', 'farming',
           [(Item('enchanted_hay_bale'), 144)],
           (Item('tightly_tied_hay_bale'), 1),
           collection_req=('wheat', 11)),

    Recipe('farm_suit_helmet', 'farming',
           [(Item('hay_bale'), 5)],
           (get_item('farm_suit_helmet'), 1),
           collection_req=('wheat', 3)),
    Recipe('farm_suit_chestplate', 'farming',
           [(Item('hay_bale'), 8)],
           (get_item('farm_suit_chestplate'), 1),
           collection_req=('wheat', 3)),
    Recipe('farm_suit_leggings', 'farming',
           [(Item('hay_bale'), 7)],
           (get_item('farm_suit_leggings'), 1),
           collection_req=('wheat', 3)),
    Recipe('farm_suit_boots', 'farming',
           [(Item('hay_bale'), 4)],
           (get_item('farm_suit_boots'), 1),
           collection_req=('wheat', 3)),

    Recipe('farm_helmet', 'farming',
           [(Item('enchanted_hay_bale'), 5)],
           (get_item('farm_helmet'), 1),
           collection_req=('wheat', 9)),
    Recipe('farm_chestplate', 'farming',
           [(Item('enchanted_hay_bale'), 8)],
           (get_item('farm_chestplate'), 1),
           collection_req=('wheat', 9)),
    Recipe('farm_leggings', 'farming',
           [(Item('enchanted_hay_bale'), 7)],
           (get_item('farm_leggings'), 1),
           collection_req=('wheat', 9)),
    Recipe('farm_boots', 'farming',
           [(Item('enchanted_hay_bale'), 4)],
           (get_item('farm_boots'), 1),
           collection_req=('wheat', 9)),

    Recipe('carrot_to_enchanted', 'farming',
           [(Item('carrot'), 160)],
           (Item('enchanted_carrot'), 1),
           collection_req=('carrot', 4)),
    Recipe('carrot_to_enchanted_golden', 'farming',
           [(Item('golden_carrot'), 32),
            (Item('enchanted_carrot'), 128)],
           (Item('enchanted_golden_carrot'), 1),
           collection_req=('carrot', 7)),

    Recipe('potato_to_enchanted', 'farming',
           [(Item('potato'), 160)],
           (Item('enchanted_potato'), 1),
           collection_req=('potato', 4)),
    Recipe('scroll_to_barn', 'farming',
           [(Item('enchanted_ender_pearl'), 16),
            (Item('enchanted_carrot'), 48),
            (Item('enchanted_potato'), 80)],
           (get_scroll('barn'), 1),
           collection_req=('potato', 6)),
    Recipe('potato_to_enchanted_baked', 'farming',
           [(Item('enchanted_potato'), 160)],
           (Item('enchanted_baked_potato'), 1),
           collection_req=('potato', 7)),

    Recipe('pumpkin_helmet', 'farming',
           [(Item('pumpkin'), 5)],
           (get_item('pumpkin_helmet'), 1),
           collection_req=('pumpkin', 2)),
    Recipe('pumpkin_chestplate', 'farming',
           [(Item('pumpkin'), 8)],
           (get_item('pumpkin_chestplate'), 1),
           collection_req=('pumpkin', 2)),
    Recipe('pumpkin_leggings', 'farming',
           [(Item('pumpkin'), 7)],
           (get_item('pumpkin_leggings'), 1),
           collection_req=('pumpkin', 2)),
    Recipe('pumpkin_boots', 'farming',
           [(Item('pumpkin'), 4)],
           (get_item('pumpkin_boots'), 1),
           collection_req=('pumpkin', 2)),

    Recipe('pumpkin_to_enchanted', 'farming',
           [(Item('pumpkin'), 160)],
           (Item('enchanted_pumpkin'), 1),
           collection_req=('pumpkin', 3)),
    Recipe('pumpkin_to_polished', 'farming',
           [(Item('enchanted_pumpkin'), 160)],
           (Item('polished_pumpkin'), 1),
           collection_req=('pumpkin', 10)),

    Recipe('farmer_boots', 'farming',
           [(Item('enchanted_pumpkin'), 256)],
           (get_item('farmer_boots'), 1),
           collection_req=('pumpkin', 9)),
    Recipe('ranchers_boots', 'farming',
           [(get_item('farmer_boots'), 1),
            (Item('polished_pumpkin'), 16)],
           (get_item('ranchers_boots'), 1),
           collection_req=('pumpkin', 11)),

    Recipe('melon_to_enchanted', 'farming',
           [(Item('melon'), 160)],
           (Item('enchanted_melon'), 1),
           collection_req=('melon', 4)),
    Recipe('melon_to_enchanted_glistering', 'farming',
           [(Item('glistering_melon'), 256)],
           (Item('enchanted_glistering_melon'), 1),
           collection_req=('melon', 5)),
    Recipe('melon_to_enchanted_block', 'farming',
           [(Item('enchanted_melon'), 160)],
           (Item('enchanted_melon_block'), 1),
           collection_req=('melon', 6)),

    Recipe('mushroom_helmet', 'farming',
           [(Item('mushroom'), 5)],
           (get_item('mushroom_helmet'), 1),
           collection_req=('mushroom', 3)),
    Recipe('mushroom_chestplate', 'farming',
           [(Item('mushroom'), 8)],
           (get_item('mushroom_chestplate'), 1),
           collection_req=('mushroom', 3)),
    Recipe('mushroom_leggings', 'farming',
           [(Item('mushroom'), 7)],
           (get_item('mushroom_leggings'), 1),
           collection_req=('mushroom', 3)),
    Recipe('mushroom_boots', 'farming',
           [(Item('mushroom'), 4)],
           (get_item('mushroom_boots'), 1),
           collection_req=('mushroom', 3)),

    Recipe('mushroom_block', 'farming',
           [(Item('mushroom'), 9)],
           (Item('mushroom_block'), 1),
           collection_req=('mushroom', 5)),
    Recipe('mushroom_to_enchanted', 'farming',
           [(Item('mushroom'), 160)],
           (Item('enchanted_mushroom'), 1),
           collection_req=('mushroom', 6)),
    Recipe('mushroom_to_enchanted_block', 'farming',
           [(Item('mushroom_block'), 576)],
           (Item('enchanted_mushroom_block'), 1),
           collection_req=('mushroom', 8)),

    Recipe('cocoa_to_enchanted', 'farming',
           [(Item('cocoa'), 160)],
           (Item('enchanted_cocoa'), 1),
           collection_req=('cocoa', 4)),
    Recipe('scroll_to_desert', 'farming',
           [(Item('enchanted_ender_pearl'), 16),
            (Item('enchanted_cactus_green'), 48),
            (Item('enchanted_cocoa'), 80)],
           (get_scroll('desert'), 1),
           collection_req=('cocoa', 5)),
    Recipe('cocoa_to_enchanted_cookie', 'farming',
           [(Item('enchanted_cocoa'), 128),
            (Item('wheat'), 32)],
           (Item('enchanted_cookie'), 1),
           collection_req=('cocoa', 6)),

    Recipe('cactus_helmet', 'farming',
           [(Item('cactus'), 5)],
           (get_item('cactus_helmet'), 1),
           collection_req=('cactus', 2)),
    Recipe('cactus_chestplate', 'farming',
           [(Item('cactus'), 8)],
           (get_item('cactus_chestplate'), 1),
           collection_req=('cactus', 2)),
    Recipe('cactus_leggings', 'farming',
           [(Item('cactus'), 7)],
           (get_item('cactus_leggings'), 1),
           collection_req=('cactus', 2)),
    Recipe('cactus_boots', 'farming',
           [(Item('cactus'), 4)],
           (get_item('cactus_boots'), 1),
           collection_req=('cactus', 2)),

    Recipe('cactus_to_enchanted_green', 'farming',
           [(Item('cactus'), 160)],
           (Item('enchanted_cactus_green'), 1),
           collection_req=('cactus', 4)),
    Recipe('cactus_to_enchanted', 'farming',
           [(Item('enchanted_cactus_green'), 160)],
           (Item('enchanted_cactus'), 1),
           collection_req=('cactus', 8)),

    Recipe('cane_to_enchanted_sugar', 'farming',
           [(Item('sugar_cane'), 160)],
           (Item('enchanted_sugar'), 1),
           collection_req=('sugar_cane', 4)),
    Recipe('cane_to_enchanted_paper', 'farming',
           [(Item('sugar_cane'), 192)],
           (Item('enchanted_paper'), 1),
           collection_req=('sugar_cane', 5)),
    Recipe('cane_to_enchanted_bookshelf', 'farming',
           [(Item('enchanted_paper'), 6),
            (Item('enchanted_oak'), 6)],
           (Item('enchanted_bookshelf'), 1),
           collection_req=('sugar_cane', 6)),
    Recipe('cane_to_enchanted', 'farming',
           [(Item('enchanted_sugar'), 160)],
           (Item('enchanted_sugar_cane'), 1),
           collection_req=('sugar_cane', 8)),

    Recipe('speedster_helmet', 'farming',
           [(Item('enchanted_sugar_cane'), 5)],
           (get_item('speedster_helmet'), 1),
           collection_req=('sugar_cane', 9)),
    Recipe('speedster_chestplate', 'farming',
           [(Item('enchanted_sugar_cane'), 8)],
           (get_item('speedster_chestplate'), 1),
           collection_req=('sugar_cane', 9)),
    Recipe('speedster_leggings', 'farming',
           [(Item('enchanted_sugar_cane'), 7)],
           (get_item('speedster_leggings'), 1),
           collection_req=('sugar_cane', 9)),
    Recipe('speedster_boots', 'farming',
           [(Item('enchanted_sugar_cane'), 4)],
           (get_item('speedster_boots'), 1),
           collection_req=('sugar_cane', 9)),

    Recipe('feather_to_enchanted', 'farming',
           [(Item('feather'), 160)],
           (Item('enchanted_feather'), 1),
           collection_req=('feather', 5)),

    Recipe('cow_head', 'farming',
           [(Item('beef'), 8)],
           (get_item('cow_head'), 1),
           collection_req=('leather', 2)),
    Recipe('beef_to_enchanted', 'farming',
           [(Item('beef'), 160)],
           (Item('enchanted_beef'), 1),
           collection_req=('leather', 4)),
    Recipe('leather_to_enchanted', 'farming',
           [(Item('leather'), 576)],
           (Item('enchanted_leather'), 1),
           collection_req=('leather', 6)),

    Recipe('pork_to_enchanted', 'farming',
           [(Item('porkchop'), 160)],
           (Item('enchanted_pork'), 1),
           collection_req=('porkchop', 4)),
    Recipe('pork_to_enchanted_grilled', 'farming',
           [(Item('enchanted_pork'), 160)],
           (Item('enchanted_grilled_pork'), 1),
           collection_req=('porkchop', 7)),
    Recipe('pigman_sword', 'farming',
           [(Item('enchanted_grilled_pork'), 48),
            (Item('stick'), 1)],
           (get_item('pigman_sword'), 1),
           collection_req=('porkchop', 9)),

    Recipe('chicken_to_enchanted', 'farming',
           [(Item('chicken'), 160)],
           (Item('enchanted_chicken'), 1),
           collection_req=('chicken', 4)),
    Recipe('egg_to_enchanted', 'farming',
           [(Item('egg'), 144)],
           (Item('enchanted_egg'), 1),
           collection_req=('chicken', 5)),
    Recipe('enchanted_cake', 'farming',
           [(Item('enchanted_egg'), 1),
            (Item('enchanted_sugar'), 1),
            (Item('wheat'), 1)],
           (Item('enchanted_cake'), 1),
           collection_req=('chicken', 7)),
    Recipe('egg_to_super_enchanted', 'farming',
           [(Item('enchanted_egg'), 144)],
           (Item('super_enchanted_egg'), 1),
           collection_req=('chicken', 9)),

    Recipe('mutton_to_enchanted', 'farming',
           [(Item('mutton'), 160)],
           (Item('enchanted_mutton'), 1),
           collection_req=('mutton', 5)),
    Recipe('mutton_to_enchanted_cooked', 'farming',
           [(Item('enchanted_mutton'), 160)],
           (Item('enchanted_mutton_cooked'), 1),
           collection_req=('mutton', 8)),

    Recipe('rabbit_to_enchanted', 'farming',
           [(Item('rabbit'), 160)],
           (Item('enchanted_rabbit'), 1)),
    Recipe('rabbit_foot_to_enchanted', 'farming',
           [(Item('rabbit_foot'), 160)],
           (Item('enchanted_rabbit_foot'), 1),
           collection_req=('rabbit', 4)),
    Recipe('rabbit_hide_to_enchanted', 'farming',
           [(Item('rabbit_hide'), 576)],
           (Item('enchanted_rabbit_hide'), 1),
           collection_req=('rabbit', 6)),

    Recipe('nether_wart_to_enchanted', 'farming',
           [(Item('nether_wart'), 160)],
           (Item('enchanted_nether_wart'), 1),
           collection_req=('nether_wart', 4)),
    Recipe('nether_wart_to_mutant', 'farming',
           [(Item('enchanted_nether_wart'), 160)],
           (Item('mutant_nether_wart'), 1),
           collection_req=('nether_wart', 12)),

    Recipe('wooden_pickaxe', 'mining',
           [(Item('planks'), 3),
            (Item('stick'), 2)],
           (get_item('wooden_pickaxe'), 1)),
    Recipe('gold_pickaxe', 'mining',
           [(Item('gold'), 3),
            (Item('stick'), 2)],
           (get_item('golden_pickaxe'), 1)),
    Recipe('stone_pickaxe', 'mining',
           [(Item('cobblestone'), 3),
            (Item('stick'), 2)],
           (get_item('stone_pickaxe'), 1)),
    Recipe('iron_pickaxe', 'mining',
           [(Item('iron'), 3),
            (Item('stick'), 2)],
           (get_item('iron_pickaxe'), 1)),
    Recipe('diamond_pickaxe', 'mining',
           [(Item('diamond'), 3),
            (Item('stick'), 2)],
           (get_item('diamond_pickaxe'), 1)),

    Recipe('coal_to_block', 'mining',
           [(Item('coal'), 9)],
           (Item('coal_block'), 1)),
    Recipe('block_to_coal', 'mining',
           [(Item('coal_block'), 1)],
           (Item('coal'), 9)),

    Recipe('iron_to_block', 'mining',
           [(Item('iron'), 9)],
           (Item('iron_block'), 1)),
    Recipe('block_to_iron', 'mining',
           [(Item('iron_block'), 1)],
           (Item('iron'), 9)),
    Recipe('nugget_to_iron', 'mining',
           [(Item('iron_nugget'), 9)],
           (Item('iron'), 1)),
    Recipe('iron_to_nugget', 'mining',
           [(Item('iron'), 1)],
           (Item('iron_nugget'), 9)),

    Recipe('gold_to_block', 'mining',
           [(Item('gold'), 9)],
           (Item('gold_block'), 1)),
    Recipe('block_to_gold', 'mining',
           [(Item('gold_block'), 1)],
           (Item('gold'), 9)),
    Recipe('nugget_to_gold', 'mining',
           [(Item('gold_nugget'), 9)],
           (Item('gold'), 1)),
    Recipe('gold_to_nugget', 'mining',
           [(Item('gold'), 1)],
           (Item('gold_nugget'), 9)),

    Recipe('diamond_to_block', 'mining',
           [(Item('diamond'), 9)],
           (Item('diamond_block'), 1)),
    Recipe('block_to_diamond', 'mining',
           [(Item('diamond_block'), 1)],
           (Item('diamond'), 9)),

    Recipe('lapis_to_block', 'mining',
           [(Item('lapis'), 9)],
           (Item('lapis_block'), 1)),
    Recipe('block_to_lapis', 'mining',
           [(Item('lapis_block'), 1)],
           (Item('lapis'), 9)),

    Recipe('emerald_to_block', 'mining',
           [(Item('emerald'), 9)],
           (Item('emerald_block'), 1)),
    Recipe('block_to_emerald', 'mining',
           [(Item('emerald_block'), 1)],
           (Item('emerald'), 9)),

    Recipe('redstone_to_block', 'mining',
           [(Item('redstone'), 9)],
           (Item('redstone_block'), 1)),
    Recipe('block_to_redstone', 'mining',
           [(Item('redstone_block'), 1)],
           (Item('redstone'), 9)),

    Recipe('ice_to_packed', 'mining',
           [(Item('ice'), 9)],
           (Item('packed_ice'), 1)),

    Recipe('leather_helmet', 'combat',
           [(Item('leather'), 5)],
           (get_item('leather_helmet'), 1)),
    Recipe('leather_chestplate', 'combat',
           [(Item('leather'), 8)],
           (get_item('leather_chestplate'), 1)),
    Recipe('leather_leggings', 'combat',
           [(Item('leather'), 7)],
           (get_item('leather_leggings'), 1)),
    Recipe('leather_boots', 'combat',
           [(Item('leather'), 4)],
           (get_item('leather_boots'), 1)),

    Recipe('golden_helmet', 'combat',
           [(Item('gold'), 5)],
           (get_item('golden_helmet'), 1)),
    Recipe('golden_chestplate', 'combat',
           [(Item('gold'), 8)],
           (get_item('golden_chestplate'), 1)),
    Recipe('golden_leggings', 'combat',
           [(Item('gold'), 7)],
           (get_item('golden_leggings'), 1)),
    Recipe('golden_boots', 'combat',
           [(Item('gold'), 4)],
           (get_item('golden_boots'), 1)),

    Recipe('iron_helmet', 'combat',
           [(Item('iron'), 5)],
           (get_item('iron_helmet'), 1)),
    Recipe('iron_chestplate', 'combat',
           [(Item('iron'), 8)],
           (get_item('iron_chestplate'), 1)),
    Recipe('iron_leggings', 'combat',
           [(Item('iron'), 7)],
           (get_item('iron_leggings'), 1)),
    Recipe('iron_boots', 'combat',
           [(Item('iron'), 4)],
           (get_item('iron_boots'), 1)),

    Recipe('diamond_helmet', 'combat',
           [(Item('diamond'), 5)],
           (get_item('diamond_helmet'), 1)),
    Recipe('diamond_chestplate', 'combat',
           [(Item('diamond'), 8)],
           (get_item('diamond_chestplate'), 1)),
    Recipe('diamond_leggings', 'combat',
           [(Item('diamond'), 7)],
           (get_item('diamond_leggings'), 1)),
    Recipe('diamond_boots', 'combat',
           [(Item('diamond'), 4)],
           (get_item('diamond_boots'), 1)),

    Recipe('arrow', 'combat',
           [(Item('flint'), 1),
            (Item('stick'), 1),
            (Item('feather'), 1)],
           (Item('arrow'), 4)),

    Recipe('wooden_sword', 'combat',
           [(Item('planks'), 2),
            (Item('stick'), 1)],
           (get_item('wooden_sword'), 1)),
    Recipe('gold_sword', 'combat',
           [(Item('gold'), 2),
            (Item('stick'), 1)],
           (get_item('golden_sword'), 1)),
    Recipe('stone_sword', 'combat',
           [(Item('cobblestone'), 2),
            (Item('stick'), 1)],
           (get_item('stone_sword'), 1)),
    Recipe('iron_sword', 'combat',
           [(Item('iron'), 2),
            (Item('stick'), 1)],
           (get_item('iron_sword'), 1)),
    Recipe('diamond_sword', 'combat',
           [(Item('diamond'), 2),
            (Item('stick'), 1)],
           (get_item('diamond_sword'), 1)),
    Recipe('bow', 'combat',
           [(Item('stick'), 3),
            (Item('string'), 3)],
           (get_item('bow'), 1)),

    Recipe('blaze_rod_to_powder', 'combat',
           [(Item('blaze_rod'), 1)],
           (Item('blaze_powder'), 2)),

    Recipe('wooden_axe', 'foraging',
           [(Item('planks'), 3),
            (Item('stick'), 2)],
           (get_item('wooden_axe'), 1)),
    Recipe('gold_axe', 'foraging',
           [(Item('gold'), 3),
            (Item('stick'), 2)],
           (get_item('golden_axe'), 1)),
    Recipe('stone_axe', 'foraging',
           [(Item('cobblestone'), 3),
            (Item('stick'), 2)],
           (get_item('stone_axe'), 1)),
    Recipe('iron_axe', 'foraging',
           [(Item('iron'), 3),
            (Item('stick'), 2)],
           (get_item('iron_axe'), 1)),
    Recipe('diamond_axe', 'foraging',
           [(Item('diamond'), 3),
            (Item('stick'), 2)],
           (get_item('diamond_axe'), 1)),

    Recipe('oak_to_planks', 'foraging',
           [(Item('oak_wood'), 1)],
           (Item('planks'), 4)),
    Recipe('birch_to_planks', 'foraging',
           [(Item('birch_wood'), 1)],
           (Item('planks'), 4)),
    Recipe('spruce_to_planks', 'foraging',
           [(Item('spruce_wood'), 1)],
           (Item('planks'), 4)),
    Recipe('dark_to_planks', 'foraging',
           [(Item('dark_oak_wood'), 1)],
           (Item('planks'), 4)),
    Recipe('acacia_to_planks', 'foraging',
           [(Item('acacia_wood'), 1)],
           (Item('planks'), 4)),
    Recipe('jungle_to_planks', 'foraging',
           [(Item('jungle_wood'), 1)],
           (Item('planks'), 4)),
    Recipe('planks_to_stick', 'foraging',
           [(Item('planks'), 2)],
           (Item('stick'), 4)),
]


def get_recipe(name: str, **kwargs) -> Optional[Recipe]:
    if not includes(RECIPES, name):
        red(f'Invalid recipe: {name!r}')
        return
    return get(RECIPES, name, **kwargs)
